/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\Users\Alterna\Documents\nim-0.18.0\lib -o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\nimgame2_draw.o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\nimgame2_draw.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_wpFMp8IwxV6MlaM4GANJ0Q tyTuple_wpFMp8IwxV6MlaM4GANJ0Q;
typedef struct tyObject_Color_YizDHyEvJtgQk2fn8KdZUA tyObject_Color_YizDHyEvJtgQk2fn8KdZUA;
typedef struct tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A;
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q;
typedef struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ tyObject_Rect_qiXweduDJk1iLE5aHysNdQ;
typedef struct tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg;
struct tyTuple_wpFMp8IwxV6MlaM4GANJ0Q {
NF Field0;
NF Field1;
};
struct tyObject_Color_YizDHyEvJtgQk2fn8KdZUA {
NU8 r;
NU8 g;
NU8 b;
NU8 a;
};
typedef N_CDECL_PTR(int, tyProc_SSqw9cNo8Mf6MmIJEdLFGSQ) (void* renderer, NI16 x, NI16 y, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_rQIZx4wC6REw9aHmOegjvHg) (void* renderer, NI16 x1, NI16 x2, NI16 y, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_XKGgUlQDoYOavZdP09bvlvg) (void* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_TvDqUpQevFbLv23LGWgPvQ) (void* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 rad, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_qAUKUGou1ENFEIQWwibH1w) (void* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU8 width, NU8 r, NU8 g, NU8 b, NU8 a);
typedef NU8 tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA;
typedef N_CDECL_PTR(int, tyProc_qPqBS49ckVYghHaRhDe9bhzA) (void* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 x3, NI16 y3, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_sCoe4tIqEGTlfV3L9coWeoQ) (void* renderer, NI16* vx, NI16* vy, int n, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_iWZxubK6MtZbJP55ce9c9cZQ) (void* renderer, NI16* vx, NI16* vy, int n, tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A* texture, int texture_dx, int texture_dy);
typedef N_CDECL_PTR(int, tyProc_bG9aqvmV8xt5SjWK9cQ9aZM5g) (void* renderer, NI16* vx, NI16* vy, int n, int s, NU8 r, NU8 g, NU8 b, NU8 a);
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
typedef N_CDECL_PTR(void, tyProc_rpU67nzC5WaSfXPDEajeiA) (void* fontdata, NU32 cw, NU32 ch);
typedef N_CDECL_PTR(int, tyProc_ElHqXU4YrZEvKm7wPSDkYA) (void* renderer, NI16 x, NI16 y, NIM_CHAR c, NU8 r, NU8 g, NU8 b, NU8 a);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(int, tyProc_qtym4k1a9bIJYHCEaSHkiyg) (void* renderer, NI16 x, NI16 y, NCSTRING s, NU8 r, NU8 g, NU8 b, NU8 a);
struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ {
int x;
int y;
int w;
int h;
};
struct tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A {
NU32 flags;
tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q* format;
int w;
int h;
int pitch;
void* pixels;
void* userdata;
int locked;
void* lock_data;
tyObject_Rect_qiXweduDJk1iLE5aHysNdQ clip_rect;
void* map;
int refcount;
};
typedef NU8 tyArray_bN9bddWn8oiNSHn2MqEJSZQ[2];
struct tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q {
NU32 format;
tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette;
NU8 BitsPerPixel;
NU8 BytesPerPixel;
tyArray_bN9bddWn8oiNSHn2MqEJSZQ padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int refcount;
tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q* next;
};
struct tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg {
int ncolors;
tyObject_Color_YizDHyEvJtgQk2fn8KdZUA* colors;
NU32 version;
int refcount;
};
static N_INLINE(NIM_BOOL, pixel_oUAZrfApYLBuaGkNvNkr3Adraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, hline_UVeh9bMba9aQpeEO9cYczPLYQdraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NF length, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, vline_WyglBzhby9bXg9cmZbl9cUi5gdraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NF height, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color);
static N_INLINE(NIM_BOOL, rect_7YKUf5miCoqazm84W2XlBQdraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos2, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color);
static N_INLINE(NIM_BOOL, roundedRect_G2vR9b4hksE4NpWYKjqn9agAdraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos2, NF rad, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color);
static N_INLINE(NIM_BOOL, box_7YKUf5miCoqazm84W2XlBQ_2draw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos2, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color);
static N_INLINE(NIM_BOOL, roundedBox_G2vR9b4hksE4NpWYKjqn9agA_2draw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos2, NF rad, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color);
static N_INLINE(NIM_BOOL, line_7YKUf5miCoqazm84W2XlBQ_3draw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos2, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color);
static N_INLINE(NIM_BOOL, aaLine_7YKUf5miCoqazm84W2XlBQ_4draw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos2, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color);
static N_INLINE(NIM_BOOL, thickLine_PW6wqmAoqP640koPFbnEBAdraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos2, NF width, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, circle_Zt11YTcolz7sTfGESzrkNw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NF rad, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color, tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA mode);
static N_INLINE(NIM_BOOL, arc_WBipqCD5au9atLsNOL9aey7wdraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NF rad, NF start, NF finish, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, ellipse_JeHeic9cfCpIhj9bJPnPwAvw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q rad, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color, tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA mode);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, pie_ju6WYk9bshMewJwhxpXgxZw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NF rad, NF start, NF finish, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color, tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA mode);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, trigon_bxGs4Bgi8mKqxaJFQuSfmQ)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos2, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos3, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color, tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA mode);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, polygon_iR4TSuGoCc8usNFFb5ICXQ)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* pos, NI posLen_0, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color, tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA mode, tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A* surface, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q surfaceD);
N_LIB_PRIVATE N_NOCONV(void*, alloc_sVm4rDImKK2ZDdylByayiA_2)(NI size);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(int, toCint_yAPwf7d9aO5za0vgIa7yl8g)(NI x);
N_LIB_PRIVATE N_NOCONV(void, dealloc_RCjNtRnHdRYntrcE7YtwWw)(void* p);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, bezier_uKCNoVC8uO9b9bROYHZ9c45VQ)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* pos, NI posLen_0, NF s, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color);
N_LIB_PRIVATE N_NIMCALL(void, setFont_IB0xOoAheJR9bfLBOSGe5hQ)(void* fontdata, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ dim);
static N_INLINE(NIM_BOOL, character_NKHKZ5g2xM00QHYn288rxwdraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NIM_CHAR c, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color);
static N_INLINE(NIM_BOOL, string_0r9a1IrwaFDF5DIjL4Jm0Kwdraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NimStringDesc* s, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color);
extern tyProc_SSqw9cNo8Mf6MmIJEdLFGSQ Dl_177012_;
extern void* renderer_M5l6pK6T79aB5LqtC0dmeOg;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyProc_rQIZx4wC6REw9aHmOegjvHg Dl_177028_;
extern tyProc_rQIZx4wC6REw9aHmOegjvHg Dl_177045_;
extern tyProc_XKGgUlQDoYOavZdP09bvlvg Dl_177063_;
extern tyProc_TvDqUpQevFbLv23LGWgPvQ Dl_177083_;
extern tyProc_XKGgUlQDoYOavZdP09bvlvg Dl_177103_;
extern tyProc_TvDqUpQevFbLv23LGWgPvQ Dl_177123_;
extern tyProc_XKGgUlQDoYOavZdP09bvlvg Dl_177143_;
extern tyProc_XKGgUlQDoYOavZdP09bvlvg Dl_177162_;
extern tyProc_qAUKUGou1ENFEIQWwibH1w Dl_177182_;
extern tyProc_rQIZx4wC6REw9aHmOegjvHg Dl_177201_;
extern tyProc_rQIZx4wC6REw9aHmOegjvHg Dl_177239_;
extern tyProc_rQIZx4wC6REw9aHmOegjvHg Dl_177256_;
extern tyProc_TvDqUpQevFbLv23LGWgPvQ Dl_177220_;
extern tyProc_XKGgUlQDoYOavZdP09bvlvg Dl_177274_;
extern tyProc_XKGgUlQDoYOavZdP09bvlvg Dl_177293_;
extern tyProc_XKGgUlQDoYOavZdP09bvlvg Dl_177312_;
extern tyProc_TvDqUpQevFbLv23LGWgPvQ Dl_177332_;
extern tyProc_TvDqUpQevFbLv23LGWgPvQ Dl_177353_;
extern tyProc_qPqBS49ckVYghHaRhDe9bhzA Dl_177375_;
extern tyProc_qPqBS49ckVYghHaRhDe9bhzA Dl_177398_;
extern tyProc_qPqBS49ckVYghHaRhDe9bhzA Dl_177421_;
extern tyProc_sCoe4tIqEGTlfV3L9coWeoQ Dl_177443_;
extern tyProc_sCoe4tIqEGTlfV3L9coWeoQ Dl_177464_;
extern tyProc_sCoe4tIqEGTlfV3L9coWeoQ Dl_177485_;
extern tyProc_iWZxubK6MtZbJP55ce9c9cZQ Dl_177497_;
extern tyProc_bG9aqvmV8xt5SjWK9cQ9aZM5g Dl_177518_;
extern tyProc_rpU67nzC5WaSfXPDEajeiA Dl_177531_;
extern tyProc_ElHqXU4YrZEvKm7wPSDkYA Dl_177546_;
extern tyProc_qtym4k1a9bIJYHCEaSHkiyg Dl_177563_;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NIM_BOOL, pixel_oUAZrfApYLBuaGkNvNkr3Adraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color) {
	NIM_BOOL result;
	int T1_;
	nimfr_("pixel", "draw.nim");
	result = (NIM_BOOL)0;
	nimln_(38, "draw.nim");
	nimln_(40, "draw.nim");
	T1_ = (int)0;
	T1_ = Dl_177012_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos.Field0)), ((NI16) (pos.Field1)), color.r, color.g, color.b, color.a);
	result = (T1_ == ((NI32) 0));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, hline_UVeh9bMba9aQpeEO9cYczPLYQdraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NF length, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color) {
	NIM_BOOL result;
	NI TM_YyY4OsVNZhi24MT69bAVs8A_2;
	int T1_;
	nimfr_("hline", "draw.nim");
	result = (NIM_BOOL)0;
	nimln_(46, "draw.nim");
	nimln_(48, "draw.nim");
	nimln_(49, "draw.nim");
	TM_YyY4OsVNZhi24MT69bAVs8A_2 = addInt(((NI16) (pos.Field0)), ((NI16) (length)));
	if (TM_YyY4OsVNZhi24MT69bAVs8A_2 < -32768 || TM_YyY4OsVNZhi24MT69bAVs8A_2 > 32767) raiseOverflow();
	T1_ = (int)0;
	T1_ = Dl_177028_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos.Field0)), (NI16)(TM_YyY4OsVNZhi24MT69bAVs8A_2), ((NI16) (pos.Field1)), color.r, color.g, color.b, color.a);
	result = (T1_ == ((NI32) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, vline_WyglBzhby9bXg9cmZbl9cUi5gdraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NF height, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color) {
	NIM_BOOL result;
	NI TM_YyY4OsVNZhi24MT69bAVs8A_3;
	int T1_;
	nimfr_("vline", "draw.nim");
	result = (NIM_BOOL)0;
	nimln_(54, "draw.nim");
	nimln_(56, "draw.nim");
	nimln_(57, "draw.nim");
	TM_YyY4OsVNZhi24MT69bAVs8A_3 = addInt(((NI16) (pos.Field1)), ((NI16) (height)));
	if (TM_YyY4OsVNZhi24MT69bAVs8A_3 < -32768 || TM_YyY4OsVNZhi24MT69bAVs8A_3 > 32767) raiseOverflow();
	T1_ = (int)0;
	T1_ = Dl_177045_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos.Field0)), ((NI16) (pos.Field1)), (NI16)(TM_YyY4OsVNZhi24MT69bAVs8A_3), color.r, color.g, color.b, color.a);
	result = (T1_ == ((NI32) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, rect_7YKUf5miCoqazm84W2XlBQdraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos2, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color) {
	NIM_BOOL result;
	int T1_;
	nimfr_("rect", "draw.nim");
	result = (NIM_BOOL)0;
	nimln_(62, "draw.nim");
	nimln_(64, "draw.nim");
	T1_ = (int)0;
	T1_ = Dl_177063_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos1.Field0)), ((NI16) (pos1.Field1)), ((NI16) (pos2.Field0)), ((NI16) (pos2.Field1)), color.r, color.g, color.b, color.a);
	result = (T1_ == ((NI32) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, roundedRect_G2vR9b4hksE4NpWYKjqn9agAdraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos2, NF rad, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color) {
	NIM_BOOL result;
	int T1_;
	nimfr_("roundedRect", "draw.nim");
	result = (NIM_BOOL)0;
	nimln_(71, "draw.nim");
	nimln_(73, "draw.nim");
	T1_ = (int)0;
	T1_ = Dl_177083_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos1.Field0)), ((NI16) (pos1.Field1)), ((NI16) (pos2.Field0)), ((NI16) (pos2.Field1)), ((NI16) (rad)), color.r, color.g, color.b, color.a);
	result = (T1_ == ((NI32) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, box_7YKUf5miCoqazm84W2XlBQ_2draw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos2, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color) {
	NIM_BOOL result;
	int T1_;
	nimfr_("box", "draw.nim");
	result = (NIM_BOOL)0;
	nimln_(79, "draw.nim");
	nimln_(81, "draw.nim");
	T1_ = (int)0;
	T1_ = Dl_177103_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos1.Field0)), ((NI16) (pos1.Field1)), ((NI16) (pos2.Field0)), ((NI16) (pos2.Field1)), color.r, color.g, color.b, color.a);
	result = (T1_ == ((NI32) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, roundedBox_G2vR9b4hksE4NpWYKjqn9agA_2draw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos2, NF rad, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color) {
	NIM_BOOL result;
	int T1_;
	nimfr_("roundedBox", "draw.nim");
	result = (NIM_BOOL)0;
	nimln_(88, "draw.nim");
	nimln_(90, "draw.nim");
	T1_ = (int)0;
	T1_ = Dl_177123_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos1.Field0)), ((NI16) (pos1.Field1)), ((NI16) (pos2.Field0)), ((NI16) (pos2.Field1)), ((NI16) (rad)), color.r, color.g, color.b, color.a);
	result = (T1_ == ((NI32) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, line_7YKUf5miCoqazm84W2XlBQ_3draw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos2, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color) {
	NIM_BOOL result;
	int T1_;
	nimfr_("line", "draw.nim");
	result = (NIM_BOOL)0;
	nimln_(96, "draw.nim");
	nimln_(98, "draw.nim");
	T1_ = (int)0;
	T1_ = Dl_177143_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos1.Field0)), ((NI16) (pos1.Field1)), ((NI16) (pos2.Field0)), ((NI16) (pos2.Field1)), color.r, color.g, color.b, color.a);
	result = (T1_ == ((NI32) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, aaLine_7YKUf5miCoqazm84W2XlBQ_4draw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos2, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color) {
	NIM_BOOL result;
	int T1_;
	nimfr_("aaLine", "draw.nim");
	result = (NIM_BOOL)0;
	nimln_(104, "draw.nim");
	nimln_(106, "draw.nim");
	T1_ = (int)0;
	T1_ = Dl_177162_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos1.Field0)), ((NI16) (pos1.Field1)), ((NI16) (pos2.Field0)), ((NI16) (pos2.Field1)), color.r, color.g, color.b, color.a);
	result = (T1_ == ((NI32) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, thickLine_PW6wqmAoqP640koPFbnEBAdraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos2, NF width, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color) {
	NIM_BOOL result;
	int T1_;
	nimfr_("thickLine", "draw.nim");
	result = (NIM_BOOL)0;
	nimln_(113, "draw.nim");
	nimln_(115, "draw.nim");
	T1_ = (int)0;
	T1_ = Dl_177182_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos1.Field0)), ((NI16) (pos1.Field1)), ((NI16) (pos2.Field0)), ((NI16) (pos2.Field1)), ((NU8) (width)), color.r, color.g, color.b, color.a);
	result = (T1_ == ((NI32) 0));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, circle_Zt11YTcolz7sTfGESzrkNw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NF rad, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color, tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA mode) {
	NIM_BOOL result;
	nimfr_("circle", "draw.nim");
	result = (NIM_BOOL)0;
	nimln_(122, "draw.nim");
	nimln_(124, "draw.nim");
	switch (mode) {
	case ((tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA) 0):
	{
		int T2_;
		nimln_(126, "draw.nim");
		T2_ = (int)0;
		T2_ = Dl_177201_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos.Field0)), ((NI16) (pos.Field1)), ((NI16) (rad)), color.r, color.g, color.b, color.a);
		result = (T2_ == ((NI32) 0));
	}
	break;
	case ((tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA) 1):
	{
		int T4_;
		nimln_(130, "draw.nim");
		T4_ = (int)0;
		T4_ = Dl_177239_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos.Field0)), ((NI16) (pos.Field1)), ((NI16) (rad)), color.r, color.g, color.b, color.a);
		result = (T4_ == ((NI32) 0));
	}
	break;
	case ((tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA) 2):
	{
		int T6_;
		nimln_(134, "draw.nim");
		T6_ = (int)0;
		T6_ = Dl_177256_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos.Field0)), ((NI16) (pos.Field1)), ((NI16) (rad)), color.r, color.g, color.b, color.a);
		result = (T6_ == ((NI32) 0));
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, arc_WBipqCD5au9atLsNOL9aey7wdraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NF rad, NF start, NF finish, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color) {
	NIM_BOOL result;
	int T1_;
	nimfr_("arc", "draw.nim");
	result = (NIM_BOOL)0;
	nimln_(141, "draw.nim");
	nimln_(143, "draw.nim");
	T1_ = (int)0;
	T1_ = Dl_177220_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos.Field0)), ((NI16) (pos.Field1)), ((NI16) (rad)), ((NI16) (start)), ((NI16) (finish)), color.r, color.g, color.b, color.a);
	result = (T1_ == ((NI32) 0));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, ellipse_JeHeic9cfCpIhj9bJPnPwAvw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q rad, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color, tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA mode) {
	NIM_BOOL result;
	nimfr_("ellipse", "draw.nim");
	result = (NIM_BOOL)0;
	nimln_(150, "draw.nim");
	nimln_(152, "draw.nim");
	switch (mode) {
	case ((tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA) 0):
	{
		int T2_;
		nimln_(154, "draw.nim");
		T2_ = (int)0;
		T2_ = Dl_177274_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos.Field0)), ((NI16) (pos.Field1)), ((NI16) (rad.Field0)), ((NI16) (rad.Field1)), color.r, color.g, color.b, color.a);
		result = (T2_ == ((NI32) 0));
	}
	break;
	case ((tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA) 1):
	{
		int T4_;
		nimln_(158, "draw.nim");
		T4_ = (int)0;
		T4_ = Dl_177293_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos.Field0)), ((NI16) (pos.Field1)), ((NI16) (rad.Field0)), ((NI16) (rad.Field1)), color.r, color.g, color.b, color.a);
		result = (T4_ == ((NI32) 0));
	}
	break;
	case ((tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA) 2):
	{
		int T6_;
		nimln_(162, "draw.nim");
		T6_ = (int)0;
		T6_ = Dl_177312_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos.Field0)), ((NI16) (pos.Field1)), ((NI16) (rad.Field0)), ((NI16) (rad.Field1)), color.r, color.g, color.b, color.a);
		result = (T6_ == ((NI32) 0));
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, pie_ju6WYk9bshMewJwhxpXgxZw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NF rad, NF start, NF finish, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color, tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA mode) {
	NIM_BOOL result;
	nimfr_("pie", "draw.nim");
	result = (NIM_BOOL)0;
	nimln_(169, "draw.nim");
	nimln_(171, "draw.nim");
	switch (mode) {
	case ((tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA) 0):
	case ((tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA) 1):
	{
		int T2_;
		nimln_(173, "draw.nim");
		T2_ = (int)0;
		T2_ = Dl_177332_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos.Field0)), ((NI16) (pos.Field1)), ((NI16) (rad)), ((NI16) (start)), ((NI16) (finish)), color.r, color.g, color.b, color.a);
		result = (T2_ == ((NI32) 0));
	}
	break;
	case ((tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA) 2):
	{
		int T4_;
		nimln_(178, "draw.nim");
		T4_ = (int)0;
		T4_ = Dl_177353_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos.Field0)), ((NI16) (pos.Field1)), ((NI16) (rad)), ((NI16) (start)), ((NI16) (finish)), color.r, color.g, color.b, color.a);
		result = (T4_ == ((NI32) 0));
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, trigon_bxGs4Bgi8mKqxaJFQuSfmQ)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos2, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos3, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color, tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA mode) {
	NIM_BOOL result;
	nimfr_("trigon", "draw.nim");
	result = (NIM_BOOL)0;
	nimln_(186, "draw.nim");
	nimln_(188, "draw.nim");
	switch (mode) {
	case ((tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA) 0):
	{
		int T2_;
		nimln_(190, "draw.nim");
		T2_ = (int)0;
		T2_ = Dl_177375_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos1.Field0)), ((NI16) (pos1.Field1)), ((NI16) (pos2.Field0)), ((NI16) (pos2.Field1)), ((NI16) (pos3.Field0)), ((NI16) (pos3.Field1)), color.r, color.g, color.b, color.a);
		result = (T2_ == ((NI32) 0));
	}
	break;
	case ((tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA) 1):
	{
		int T4_;
		nimln_(196, "draw.nim");
		T4_ = (int)0;
		T4_ = Dl_177398_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos1.Field0)), ((NI16) (pos1.Field1)), ((NI16) (pos2.Field0)), ((NI16) (pos2.Field1)), ((NI16) (pos3.Field0)), ((NI16) (pos3.Field1)), color.r, color.g, color.b, color.a);
		result = (T4_ == ((NI32) 0));
	}
	break;
	case ((tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA) 2):
	{
		int T6_;
		nimln_(202, "draw.nim");
		T6_ = (int)0;
		T6_ = Dl_177421_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos1.Field0)), ((NI16) (pos1.Field1)), ((NI16) (pos2.Field0)), ((NI16) (pos2.Field1)), ((NI16) (pos3.Field0)), ((NI16) (pos3.Field1)), color.r, color.g, color.b, color.a);
		result = (T6_ == ((NI32) 0));
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, polygon_iR4TSuGoCc8usNFFb5ICXQ)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* pos, NI posLen_0, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color, tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA mode, tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A* surface, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q surfaceD) {
	NIM_BOOL result;
	NI16* vx;
	NI16* vy;
	NI TM_YyY4OsVNZhi24MT69bAVs8A_4;
	void* T1_;
	NI TM_YyY4OsVNZhi24MT69bAVs8A_5;
	void* T2_;
	nimfr_("polygon", "draw.nim");
	result = (NIM_BOOL)0;
	vx = (NI16*)0;
	vy = (NI16*)0;
	nimln_(223, "draw.nim");
	TM_YyY4OsVNZhi24MT69bAVs8A_4 = mulInt(posLen_0, ((NI) 2));
	T1_ = (void*)0;
	T1_ = alloc_sVm4rDImKK2ZDdylByayiA_2(((NI)chckRange((NI)(TM_YyY4OsVNZhi24MT69bAVs8A_4), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	vx = ((NI16*) (T1_));
	nimln_(224, "draw.nim");
	TM_YyY4OsVNZhi24MT69bAVs8A_5 = mulInt(posLen_0, ((NI) 2));
	T2_ = (void*)0;
	T2_ = alloc_sVm4rDImKK2ZDdylByayiA_2(((NI)chckRange((NI)(TM_YyY4OsVNZhi24MT69bAVs8A_5), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	vy = ((NI16*) (T2_));
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(225, "draw.nim");
		colontmp_ = (posLen_0-1);
		nimln_(2045, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_YyY4OsVNZhi24MT69bAVs8A_6;
				NI TM_YyY4OsVNZhi24MT69bAVs8A_7;
				NI TM_YyY4OsVNZhi24MT69bAVs8A_8;
				if (!(res <= colontmp_)) goto LA5;
				nimln_(2047, "system.nim");
				i = res;
				nimln_(210, "draw.nim");
				nimln_(226, "draw.nim");
				TM_YyY4OsVNZhi24MT69bAVs8A_6 = mulInt(i, ((NI) 2));
				if ((NU)(i) >= (NU)(posLen_0)) raiseIndexError();
				(*((NI16*) ((NI)((NU64)(((NI) (ptrdiff_t) (vx))) + (NU64)((NI)(TM_YyY4OsVNZhi24MT69bAVs8A_6)))))) = ((NI16) (pos[i].Field0));
				nimln_(210, "draw.nim");
				nimln_(227, "draw.nim");
				TM_YyY4OsVNZhi24MT69bAVs8A_7 = mulInt(i, ((NI) 2));
				if ((NU)(i) >= (NU)(posLen_0)) raiseIndexError();
				(*((NI16*) ((NI)((NU64)(((NI) (ptrdiff_t) (vy))) + (NU64)((NI)(TM_YyY4OsVNZhi24MT69bAVs8A_7)))))) = ((NI16) (pos[i].Field1));
				nimln_(2048, "system.nim");
				TM_YyY4OsVNZhi24MT69bAVs8A_8 = addInt(res, ((NI) 1));
				res = (NI)(TM_YyY4OsVNZhi24MT69bAVs8A_8);
			} LA5: ;
		}
	}
	nimln_(228, "draw.nim");
	{
		if (!(surface == NIM_NIL)) goto LA8_;
		nimln_(229, "draw.nim");
		switch (mode) {
		case ((tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA) 0):
		{
			int T11_;
			int T12_;
			nimln_(231, "draw.nim");
			nimln_(232, "draw.nim");
			T11_ = (int)0;
			T11_ = toCint_yAPwf7d9aO5za0vgIa7yl8g(posLen_0);
			T12_ = (int)0;
			T12_ = Dl_177443_(renderer_M5l6pK6T79aB5LqtC0dmeOg, vx, vy, T11_, color.r, color.g, color.b, color.a);
			result = (T12_ == ((NI32) 0));
		}
		break;
		case ((tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA) 1):
		{
			int T14_;
			int T15_;
			nimln_(235, "draw.nim");
			nimln_(236, "draw.nim");
			T14_ = (int)0;
			T14_ = toCint_yAPwf7d9aO5za0vgIa7yl8g(posLen_0);
			T15_ = (int)0;
			T15_ = Dl_177464_(renderer_M5l6pK6T79aB5LqtC0dmeOg, vx, vy, T14_, color.r, color.g, color.b, color.a);
			result = (T15_ == ((NI32) 0));
		}
		break;
		case ((tyEnum_DrawMode_4cn2SVdrTSIhT8C9boAm9awA) 2):
		{
			int T17_;
			int T18_;
			nimln_(239, "draw.nim");
			nimln_(240, "draw.nim");
			T17_ = (int)0;
			T17_ = toCint_yAPwf7d9aO5za0vgIa7yl8g(posLen_0);
			T18_ = (int)0;
			T18_ = Dl_177485_(renderer_M5l6pK6T79aB5LqtC0dmeOg, vx, vy, T17_, color.r, color.g, color.b, color.a);
			result = (T18_ == ((NI32) 0));
		}
		break;
		}
	}
	goto LA6_;
	LA8_: ;
	{
		int T20_;
		int T21_;
		int T22_;
		int T23_;
		nimln_(243, "draw.nim");
		nimln_(244, "draw.nim");
		T20_ = (int)0;
		T20_ = toCint_yAPwf7d9aO5za0vgIa7yl8g(posLen_0);
		nimln_(245, "draw.nim");
		T21_ = (int)0;
		T21_ = toCint_yAPwf7d9aO5za0vgIa7yl8g(((NI) (surfaceD.Field0)));
		T22_ = (int)0;
		T22_ = toCint_yAPwf7d9aO5za0vgIa7yl8g(((NI) (surfaceD.Field1)));
		T23_ = (int)0;
		T23_ = Dl_177497_(renderer_M5l6pK6T79aB5LqtC0dmeOg, vx, vy, T20_, surface, T21_, T22_);
		result = (T23_ == ((NI32) 0));
	}
	LA6_: ;
	nimln_(247, "draw.nim");
	dealloc_RCjNtRnHdRYntrcE7YtwWw(((void*) (vx)));
	nimln_(248, "draw.nim");
	dealloc_RCjNtRnHdRYntrcE7YtwWw(((void*) (vy)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, bezier_uKCNoVC8uO9b9bROYHZ9c45VQ)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* pos, NI posLen_0, NF s, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color) {
	NIM_BOOL result;
	NI16* vx;
	NI16* vy;
	NI TM_YyY4OsVNZhi24MT69bAVs8A_9;
	void* T1_;
	NI TM_YyY4OsVNZhi24MT69bAVs8A_10;
	void* T2_;
	int T6_;
	int T7_;
	int T8_;
	nimfr_("bezier", "draw.nim");
	result = (NIM_BOOL)0;
	vx = (NI16*)0;
	vy = (NI16*)0;
	nimln_(255, "draw.nim");
	TM_YyY4OsVNZhi24MT69bAVs8A_9 = mulInt(posLen_0, ((NI) 2));
	T1_ = (void*)0;
	T1_ = alloc_sVm4rDImKK2ZDdylByayiA_2(((NI)chckRange((NI)(TM_YyY4OsVNZhi24MT69bAVs8A_9), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	vx = ((NI16*) (T1_));
	nimln_(256, "draw.nim");
	TM_YyY4OsVNZhi24MT69bAVs8A_10 = mulInt(posLen_0, ((NI) 2));
	T2_ = (void*)0;
	T2_ = alloc_sVm4rDImKK2ZDdylByayiA_2(((NI)chckRange((NI)(TM_YyY4OsVNZhi24MT69bAVs8A_10), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	vy = ((NI16*) (T2_));
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(257, "draw.nim");
		colontmp_ = (posLen_0-1);
		nimln_(2045, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_YyY4OsVNZhi24MT69bAVs8A_11;
				NI TM_YyY4OsVNZhi24MT69bAVs8A_12;
				NI TM_YyY4OsVNZhi24MT69bAVs8A_13;
				if (!(res <= colontmp_)) goto LA5;
				nimln_(2047, "system.nim");
				i = res;
				nimln_(210, "draw.nim");
				nimln_(258, "draw.nim");
				TM_YyY4OsVNZhi24MT69bAVs8A_11 = mulInt(i, ((NI) 2));
				if ((NU)(i) >= (NU)(posLen_0)) raiseIndexError();
				(*((NI16*) ((NI)((NU64)(((NI) (ptrdiff_t) (vx))) + (NU64)((NI)(TM_YyY4OsVNZhi24MT69bAVs8A_11)))))) = ((NI16) (pos[i].Field0));
				nimln_(210, "draw.nim");
				nimln_(259, "draw.nim");
				TM_YyY4OsVNZhi24MT69bAVs8A_12 = mulInt(i, ((NI) 2));
				if ((NU)(i) >= (NU)(posLen_0)) raiseIndexError();
				(*((NI16*) ((NI)((NU64)(((NI) (ptrdiff_t) (vy))) + (NU64)((NI)(TM_YyY4OsVNZhi24MT69bAVs8A_12)))))) = ((NI16) (pos[i].Field1));
				nimln_(2048, "system.nim");
				TM_YyY4OsVNZhi24MT69bAVs8A_13 = addInt(res, ((NI) 1));
				res = (NI)(TM_YyY4OsVNZhi24MT69bAVs8A_13);
			} LA5: ;
		}
	}
	nimln_(260, "draw.nim");
	nimln_(261, "draw.nim");
	T6_ = (int)0;
	T6_ = toCint_yAPwf7d9aO5za0vgIa7yl8g(posLen_0);
	T7_ = (int)0;
	T7_ = toCint_yAPwf7d9aO5za0vgIa7yl8g(((NI) (s)));
	T8_ = (int)0;
	T8_ = Dl_177518_(renderer_M5l6pK6T79aB5LqtC0dmeOg, vx, vy, T6_, T7_, color.r, color.g, color.b, color.a);
	result = (T8_ == ((NI32) 0));
	nimln_(264, "draw.nim");
	dealloc_RCjNtRnHdRYntrcE7YtwWw(((void*) (vx)));
	nimln_(265, "draw.nim");
	dealloc_RCjNtRnHdRYntrcE7YtwWw(((void*) (vy)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, setFont_IB0xOoAheJR9bfLBOSGe5hQ)(void* fontdata, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ dim) {
	nimfr_("setFont", "draw.nim");
	nimln_(271, "draw.nim");
	Dl_177531_(fontdata, ((NU32) (dim.Field0)), ((NU32) (dim.Field1)));
	popFrame();
}

static N_INLINE(NIM_BOOL, character_NKHKZ5g2xM00QHYn288rxwdraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NIM_CHAR c, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color) {
	NIM_BOOL result;
	int T1_;
	nimfr_("character", "draw.nim");
	result = (NIM_BOOL)0;
	nimln_(287, "draw.nim");
	nimln_(289, "draw.nim");
	T1_ = (int)0;
	T1_ = Dl_177546_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos.Field0)), ((NI16) (pos.Field1)), c, color.r, color.g, color.b, color.a);
	result = (T1_ == ((NI32) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, string_0r9a1IrwaFDF5DIjL4Jm0Kwdraw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NimStringDesc* s, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color) {
	NIM_BOOL result;
	int T1_;
	nimfr_("string", "draw.nim");
	result = (NIM_BOOL)0;
	nimln_(295, "draw.nim");
	nimln_(297, "draw.nim");
	T1_ = (int)0;
	T1_ = Dl_177563_(renderer_M5l6pK6T79aB5LqtC0dmeOg, ((NI16) (pos.Field0)), ((NI16) (pos.Field1)), s->data, color.r, color.g, color.b, color.a);
	result = (T1_ == ((NI32) 0));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, nimgame2_drawInit000)(void) {
	nimfr_("draw", "draw.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimgame2_drawDatInit000)(void) {
}

