/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\Users\Alterna\Documents\nim-0.18.0\lib -o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\nimgame2_graphic.o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\nimgame2_graphic.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg;
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyTuple_wpFMp8IwxV6MlaM4GANJ0Q tyTuple_wpFMp8IwxV6MlaM4GANJ0Q;
typedef struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ tyObject_Rect_qiXweduDJk1iLE5aHysNdQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct RootObj RootObj;
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
struct tyTuple_wpFMp8IwxV6MlaM4GANJ0Q {
NF Field0;
NF Field1;
};
typedef NI32 tyEnum_Flip_qWHX0qRQS3EMdrguXFZZdA;
struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ {
int x;
int y;
int w;
int h;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg {
  RootObj Sup;
};
N_LIB_PRIVATE N_NIMCALL(NI, w_Q9a44aS7ONTzyl9ckqZQ9a8wQ)(tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* graphic);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NI, h_Q9a44aS7ONTzyl9ckqZQ9a8wQ_2)(tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* graphic);
N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, dim_xGlw53joA2RCl4ghqNZ6wQ)(tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* graphic);
N_LIB_PRIVATE N_NIMCALL(void, draw_c4IUiRdZx9b5WuFGjuN2gPg)(tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* graphic, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NF angle, NF scale, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q center, tyEnum_Flip_qWHX0qRQS3EMdrguXFZZdA flip, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ region);
static N_NIMCALL(void, Marker_tyRef_16PqNEivy9aM4gBlAQxLQhw)(void* p, NI op);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_W9c5ORj7z7QIE1MjKJgJgFg_;
TNimType NTI_16PqNEivy9aM4gBlAQxLQhw_;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NI, w_Q9a44aS7ONTzyl9ckqZQ9a8wQ)(tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* graphic) {
	NI result;
	nimfr_("w", "graphic.nim");
	result = (NI)0;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, h_Q9a44aS7ONTzyl9ckqZQ9a8wQ_2)(tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* graphic) {
	NI result;
	nimfr_("h", "graphic.nim");
	result = (NI)0;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, dim_xGlw53joA2RCl4ghqNZ6wQ)(tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* graphic) {
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ result;
	nimfr_("dim", "graphic.nim");
	memset((void*)(&result), 0, sizeof(result));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, draw_c4IUiRdZx9b5WuFGjuN2gPg)(tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* graphic, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NF angle, NF scale, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q center, tyEnum_Flip_qWHX0qRQS3EMdrguXFZZdA flip, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ region) {
	nimfr_("draw", "graphic.nim");
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_16PqNEivy9aM4gBlAQxLQhw)(void* p, NI op) {
	tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* a;
	a = (tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg*)p;
}
NIM_EXTERNC N_NOINLINE(void, nimgame2_graphicInit000)(void) {
	nimfr_("graphic", "graphic.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimgame2_graphicDatInit000)(void) {
static TNimNode TM_qgA8QoQrOaj3YWfqqYiDZg_0[1];
NTI_W9c5ORj7z7QIE1MjKJgJgFg_.size = sizeof(tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg);
NTI_W9c5ORj7z7QIE1MjKJgJgFg_.kind = 17;
NTI_W9c5ORj7z7QIE1MjKJgJgFg_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_W9c5ORj7z7QIE1MjKJgJgFg_.flags = 1;
TM_qgA8QoQrOaj3YWfqqYiDZg_0[0].len = 0; TM_qgA8QoQrOaj3YWfqqYiDZg_0[0].kind = 2;
NTI_W9c5ORj7z7QIE1MjKJgJgFg_.node = &TM_qgA8QoQrOaj3YWfqqYiDZg_0[0];
NTI_16PqNEivy9aM4gBlAQxLQhw_.size = sizeof(tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg*);
NTI_16PqNEivy9aM4gBlAQxLQhw_.kind = 22;
NTI_16PqNEivy9aM4gBlAQxLQhw_.base = (&NTI_W9c5ORj7z7QIE1MjKJgJgFg_);
NTI_16PqNEivy9aM4gBlAQxLQhw_.marker = Marker_tyRef_16PqNEivy9aM4gBlAQxLQhw;
}

