/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\Users\Alterna\Documents\nim-0.18.0\lib -o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\nimgame2_utils.o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\nimgame2_utils.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <math.h>
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_wpFMp8IwxV6MlaM4GANJ0Q tyTuple_wpFMp8IwxV6MlaM4GANJ0Q;
typedef struct tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA;
typedef struct tyTuple_HogsYWYa09czwuSNmOLhWVw tyTuple_HogsYWYa09czwuSNmOLhWVw;
typedef struct tyObject_RendererInfo_I9c5YLPHRMZZPky07Ra19asQ tyObject_RendererInfo_I9c5YLPHRMZZPky07Ra19asQ;
typedef union tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ;
typedef struct tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ;
typedef struct tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA;
typedef struct tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ;
typedef struct tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg;
typedef struct tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q;
typedef struct tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA;
typedef struct tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg;
typedef struct tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ;
typedef struct tySequence_acepldouQeokxA9cg6MkDnA tySequence_acepldouQeokxA9cg6MkDnA;
typedef struct tyObject_Color_YizDHyEvJtgQk2fn8KdZUA tyObject_Color_YizDHyEvJtgQk2fn8KdZUA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw;
typedef struct RootObj RootObj;
typedef struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_StringStreamObj_lGsM0FdhfyxyplfYoMsgFQ tyObject_StringStreamObj_lGsM0FdhfyxyplfYoMsgFQ;
typedef struct tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q;
typedef struct tyTuple_Fu1oVqpZ40A7cjazVlOmBA tyTuple_Fu1oVqpZ40A7cjazVlOmBA;
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence_phjbYJtsbOIAYa9be34hhZg tySequence_phjbYJtsbOIAYa9be34hhZg;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q;
typedef struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ tyObject_Rect_qiXweduDJk1iLE5aHysNdQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct tyTuple_wpFMp8IwxV6MlaM4GANJ0Q {
NF Field0;
NF Field1;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A*, tyProc_oTI7Gk9b9bgxQuZMQRpglP1w) (NCSTRING file);
typedef NI32 tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw;
typedef N_CDECL_PTR(void, tyProc_DusjKySyJW30WdV9bsteVxw) (tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw category, NCSTRING fmt, ...);
typedef N_CDECL_PTR(NCSTRING, tyProc_09bvyvHFtWbkzL5AHgf0bKw) (void);
typedef N_CDECL_PTR(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A*, tyProc_ov47cSW7te2Rk6vJnziJZA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, int freesrc);
typedef NU32 tyArray_U0SiHM0pVagA9c71oWelQMA[16];
struct tyTuple_HogsYWYa09czwuSNmOLhWVw {
NU32 Field0;
tyArray_U0SiHM0pVagA9c71oWelQMA Field1;
};
struct tyObject_RendererInfo_I9c5YLPHRMZZPky07Ra19asQ {
NCSTRING name;
NU32 flags;
NU32 num_texture_formats;
tyArray_U0SiHM0pVagA9c71oWelQMA texture_formats;
int max_texture_width;
int max_texture_height;
};
typedef N_CDECL_PTR(int, tyProc_eacO1b28DxmNZ4wkv7Xz1A) (void* renderer, tyObject_RendererInfo_I9c5YLPHRMZZPky07Ra19asQ* info);
typedef N_CDECL_PTR(NI64, tyProc_p9adtE9afP6ObPoIZKMFxiAA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context);
typedef N_CDECL_PTR(NI64, tyProc_tpgoL9bwK9bkzBn2qq83QKag) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context, NI64 offset, int whence);
typedef N_CDECL_PTR(size_t, tyProc_vPnfrHDX45Ib7P40WFtTvg) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context, void* p, size_t size, size_t maxnum);
typedef N_CDECL_PTR(int, tyProc_pcLKO4pFPDvuTZj9c0HX5oA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context);
struct tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ {
void* fileNameRef;
void* inputStreamRef;
void* readableByteChannelRef;
void* readMethod;
void* assetFileDescriptorRef;
long position;
long size;
long offset;
int fd;
};
struct tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ {
void* data;
size_t size;
size_t left;
};
struct tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA {
NIM_BOOL append;
void* h;
tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ buffer;
};
struct tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg {
NIM_BOOL autoclose;
FILE* fp;
};
struct tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q {
NU8* base;
NU8* here;
NU8* stop;
};
struct tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA {
void* data1;
void* data2;
};
union tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ {
tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ androidio;
tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA windowsio;
tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg stdio;
tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q mem;
tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA unknown;
};
struct tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA {
tyProc_p9adtE9afP6ObPoIZKMFxiAA size;
tyProc_tpgoL9bwK9bkzBn2qq83QKag seek;
tyProc_vPnfrHDX45Ib7P40WFtTvg read;
tyProc_vPnfrHDX45Ib7P40WFtTvg write;
tyProc_pcLKO4pFPDvuTZj9c0HX5oA close;
NU32 kind;
tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ mem;
};
struct tyObject_Color_YizDHyEvJtgQk2fn8KdZUA {
NU8 r;
NU8 g;
NU8 b;
NU8 a;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw {
  RootObj Sup;
NI bufpos;
NCSTRING buf;
NI bufLen;
tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input;
NI lineNumber;
NI sentinel;
NI lineStart;
NI offsetBase;
tySet_tyChar_nmiMWKVIe46vacnhAFrQvw refillChars;
};
struct tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ {
  tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw Sup;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* row;
NimStringDesc* filename;
NIM_CHAR sep;
NIM_CHAR quote;
NIM_CHAR esc;
NIM_BOOL skipWhite;
NI currRow;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* headers;
};
typedef N_CDECL_PTR(void, tyProc_OMfTrA6Dqf9cACW3aIhhxEA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* area);
struct tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q {
NI counter;
NI current;
NI interval;
NU64 time;
};
typedef N_CDECL_PTR(NU64, tyProc_F2KC9bitLsP5b9bCBN9b81hEg) (void);
struct tyTuple_Fu1oVqpZ40A7cjazVlOmBA {
tyTuple_wpFMp8IwxV6MlaM4GANJ0Q Field0;
NF Field1;
NF Field2;
};
typedef struct {
N_NIMCALL_PTR(NimStringDesc*, ClP_0) (NimStringDesc* input, void* ClE_0);
void* ClE_0;
} tyProc_lRW9cfxqfm1ql4gkxfLReYg;
typedef N_CLOSURE_PTR(NimStringDesc*, TM_WSc01Aef5CMpWdOBujpuWQ_11) (NimStringDesc* input);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef N_CLOSURE_PTR(NimStringDesc*, TM_WSc01Aef5CMpWdOBujpuWQ_14) (NimStringDesc* input);
struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ {
int x;
int y;
int w;
int h;
};
struct tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A {
NU32 flags;
tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q* format;
int w;
int h;
int pitch;
void* pixels;
void* userdata;
int locked;
void* lock_data;
tyObject_Rect_qiXweduDJk1iLE5aHysNdQ clip_rect;
void* map;
int refcount;
};
struct tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg {
int ncolors;
tyObject_Color_YizDHyEvJtgQk2fn8KdZUA* colors;
NU32 version;
int refcount;
};
typedef N_NIMCALL_PTR(void, tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_KjFcmLOhf4VQvVcyLJWXZw) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(void, tyProc_jlOYFw9cHausuCbPoWx2iiA) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NI, tyProc_tjaJtoUzLe1BMUbItlcGhQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc_b9bsIuILxTLVZHPvJBW187A) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ {
  RootObj Sup;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q closeImpl;
tyProc_KjFcmLOhf4VQvVcyLJWXZw atEndImpl;
tyProc_jlOYFw9cHausuCbPoWx2iiA setPositionImpl;
tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ getPositionImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ readDataImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ peekDataImpl;
tyProc_b9bsIuILxTLVZHPvJBW187A writeDataImpl;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q flushImpl;
};
struct tyObject_StringStreamObj_lGsM0FdhfyxyplfYoMsgFQ {
  tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ Sup;
NimStringDesc* data;
NI pos;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef NU8 tyArray_bN9bddWn8oiNSHn2MqEJSZQ[2];
struct tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q {
NU32 format;
tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette;
NU8 BitsPerPixel;
NU8 BytesPerPixel;
tyArray_bN9bddWn8oiNSHn2MqEJSZQ padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int refcount;
tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q* next;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_acepldouQeokxA9cg6MkDnA {
  TGenericSeq Sup;
  tyObject_Color_YizDHyEvJtgQk2fn8KdZUA data[SEQ_DECL_SIZE];
};
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_phjbYJtsbOIAYa9be34hhZg {
  TGenericSeq Sup;
  tySequence_sM4lkSb7zS6F7OVMvW9cffQ* data[SEQ_DECL_SIZE];
};
static N_INLINE(NF, distance_n3XFirBkiC8vVJ6RcnI3LAutils)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q a, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NF, distanceToLine_7bdMeaya4Rx19bFRZ8D0AHQ)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q a, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q d1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q d2);
static N_INLINE(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, minus__j2pnXFSCXLnkC9a3JwzEgTw_2types)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c2);
N_LIB_PRIVATE N_NIMCALL(NF, direction_tPnITEUbWU2FqRTbBpk9cEw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q a, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q b);
N_LIB_PRIVATE N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, rotate_movj9bCQBNw2qFx9bykK5X9bw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q a, NF angle);
N_LIB_PRIVATE N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, rotate_ei2HXYH1uVu4d1z432QNLw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q point, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q offset, NF angle);
static N_INLINE(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, plus__j2pnXFSCXLnkC9a3JwzEgTwtypes)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c2);
N_LIB_PRIVATE N_NIMCALL(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A*, loadSurface_nYdhujP6pdi6JN4kFcLD9aw)(NimStringDesc* file);
N_LIB_PRIVATE N_NIMCALL(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A*, loadSurface_fe9atOmS3LLEmcMVW7SoEbw)(tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NIM_BOOL freeSrc);
N_LIB_PRIVATE N_NIMCALL(tyTuple_HogsYWYa09czwuSNmOLhWVw, textureFormats_FHZG4pWypjsUIfeOMWc0WA)(void* renderer);
N_LIB_PRIVATE N_NIMCALL(NU32, textureFormat_TfMLpZoUN8qi5KmaGtdIWg)(void* renderer, NU32 n);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readAll_F7m4d1s9ce15AymiFiYv8ew)(tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, loadPalette_TokvM2rcMK3fjDTH4UDGfA)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg** palette, tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* parser);
static N_NIMCALL(void, Marker_tySequence_acepldouQeokxA9cg6MkDnA)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readRow_9bHdhFE0qEvOrDqjuQBz8Pw)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NI columns);
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, free_XPSpdGrbzFLrRNrh4eaJuA)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette);
N_LIB_PRIVATE N_NIMCALL(void, init_NWdB9au5KthgJE4agI9amyAA)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg** palette, NI ncolors);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__syZw77tfvlbUcAM2X9aa9aaA)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette, NI i, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA* colors, NI colorsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, loadPalette_zmXTqFCKc6HB1J9bDsaP3EA)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg** palette, NimStringDesc* file, NIM_CHAR separator, NIM_CHAR quote, NIM_CHAR escape, NIM_BOOL skipInitialSpace);
N_LIB_PRIVATE N_NIMCALL(void, open_grmoJIpX15R5Xfx6m2M1UA)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, NimStringDesc* filename, NIM_CHAR separator, NIM_CHAR quote, NIM_CHAR escape, NIM_BOOL skipInitialSpace);
static N_INLINE(void, close_A55CxARYHkQe359a6AS5GRQparsecsv)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my);
N_LIB_PRIVATE N_NIMCALL(void, close_QbedUCk2XwI9c7bbRzXBY0g)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L);
N_LIB_PRIVATE N_NIMCALL(void, loadPalette_1CtzKxkUfkpzEKz9alpH9bqQ)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg** palette, tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NimStringDesc* file, NIM_CHAR separator, NIM_CHAR quote, NIM_CHAR escape, NIM_BOOL skipInitialSpace, NIM_BOOL freeSrc);
N_LIB_PRIVATE N_NIMCALL(tyObject_StringStreamObj_lGsM0FdhfyxyplfYoMsgFQ*, newStringStream_0dQ0A0pna0dG9cMxo4TbLKQ)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, open_dmBuwTCvdiT9cdjydWhbTTg)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my, tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input, NimStringDesc* filename, NIM_CHAR separator, NIM_CHAR quote, NIM_CHAR escape, NIM_BOOL skipInitialSpace);
N_LIB_PRIVATE N_NIMCALL(void, close_4ed7IXme7lqtClFI7s2sTQ_2)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, randomBool_R3rTyvvmThxxKUf4W6tpqQ)(NF chance);
N_LIB_PRIVATE N_NIMCALL(NF, random_ysAjdvfIGCDnzC8BoWsOAw)(NF max);
N_LIB_PRIVATE N_NIMCALL(NF, clamp_BGhQiHv5LFkg9aDgeidEq0g)(NF x, NF a, NF b);
static N_INLINE(NIM_BOOL, randBool_xwNyTFCoEbHFYNHdUfF4OAutils)(NF chance);
N_LIB_PRIVATE N_NIMCALL(NI, randomSign_UJ8proCyAoKiHeYltnU8tA)(NF chance);
static N_INLINE(NI, randSign_DZSArtZoMyaKku4qgJ8V1gutils)(NF chance);
N_LIB_PRIVATE N_NIMCALL(tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q*, newCounter_NrzaLdJXb3T0qcpTsT9c9cdw)(NI interval);
static N_NIMCALL(void, Marker_tyRef_NfV7YMRLkJnJfP6TGsbPDA)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(void, update_pJzkC1Hjtqv9bJ3RWlcS1wA)(tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q* counter);
static N_INLINE(NI, value_k3IDuofZgKrTXDbo9alw2cgutils)(tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q* counter);
N_LIB_PRIVATE N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, point_VxjuNbYTDh6zu8OpfTFxYw)(tyTuple_Fu1oVqpZ40A7cjazVlOmBA* self, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q point);
static N_INLINE(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, star__P3evVH8XmA9cYiwl3XfSW4Q_3types)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c, NF v);
N_LIB_PRIVATE N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, inverse_point_VxjuNbYTDh6zu8OpfTFxYw_2)(tyTuple_Fu1oVqpZ40A7cjazVlOmBA* self, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q point);
N_LIB_PRIVATE N_NIMCALL(tyTuple_Fu1oVqpZ40A7cjazVlOmBA, translated_bcWSNVzEunN9b3tnWBTENbQ)(tyTuple_Fu1oVqpZ40A7cjazVlOmBA* self, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q delta);
N_LIB_PRIVATE N_NIMCALL(tyTuple_Fu1oVqpZ40A7cjazVlOmBA, copy_BX8qKci9av4hVcEqiqVHs9cA)(tyTuple_Fu1oVqpZ40A7cjazVlOmBA* self);
static N_INLINE(void, pluseq__PCl7gsYLasB10y8xsRW9afgtypes)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* c1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c2);
static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x, NF y);
N_LIB_PRIVATE N_NIMCALL(tyTuple_Fu1oVqpZ40A7cjazVlOmBA, rotated_ONlKdR0uXo814AKNf5PsUg)(tyTuple_Fu1oVqpZ40A7cjazVlOmBA* self, NF angle);
N_LIB_PRIVATE N_NIMCALL(tyTuple_Fu1oVqpZ40A7cjazVlOmBA, scaled_ZbuYcr36xox69bLb4wEZoGw)(tyTuple_Fu1oVqpZ40A7cjazVlOmBA* self, NF scale);
static N_INLINE(void, stareq__7kHiltrvRlcg6wSYR3CxAwstrutils)(NF* x, NF y);
N_LIB_PRIVATE N_NIMCALL(NI, rand_F1qFFP53BvbP4L65Kn9bG1w_2)(NI max);
static N_INLINE(NIM_BOOL, contains_P6sCVNQ9cdTFh3rtVXMEtxgutils)(NI* a, NI aLen_0, NI item);
static N_INLINE(NI, find_b2asjP2y9cPDPwOLa1pD5PAutils)(NI* a, NI aLen_0, NI item);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_phjbYJtsbOIAYa9be34hhZg)(void* p, NI op);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(tySequence_sM4lkSb7zS6F7OVMvW9cffQ**, X5BX5D__HTndH1gVLM7rZgP9a9bH1iZgutils)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ** s, NI sLen_0, NI i);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyProc_oTI7Gk9b9bgxQuZMQRpglP1w Dl_157041_;
extern tyProc_DusjKySyJW30WdV9bsteVxw Dl_154881_;
extern tyProc_09bvyvHFtWbkzL5AHgf0bKw Dl_147926_;
extern tyProc_ov47cSW7te2Rk6vJnziJZA Dl_157044_;
extern tyProc_eacO1b28DxmNZ4wkv7Xz1A Dl_155126_;
extern TNimType NTI_YizDHyEvJtgQk2fn8KdZUA_;
TNimType NTI_acepldouQeokxA9cg6MkDnA_;
extern TNimType NTI_e0KmhL4ItditGQKnCUZMoQ_;
extern tyProc_OMfTrA6Dqf9cACW3aIhhxEA Dl_147327_;
TNimType NTI_xch5drbeIU4SamGPZzsp8Q_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_wMtfD88jmrPZwfzTH9c8e9cA_;
TNimType NTI_NfV7YMRLkJnJfP6TGsbPDA_;
extern tyProc_F2KC9bitLsP5b9bCBN9b81hEg Dl_156042_;
extern tyProc_F2KC9bitLsP5b9bCBN9b81hEg Dl_156044_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
TNimType NTI_phjbYJtsbOIAYa9be34hhZg_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_WSc01Aef5CMpWdOBujpuWQ_13, "len(a) == L seq modified while iterating over it", 48);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NF, distance_n3XFirBkiC8vVJ6RcnI3LAutils)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q a, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q b) {
	NF result;
	NF T1_;
	NF T2_;
	nimfr_("distance", "utils.nim");
{	result = (NF)0;
	nimln_(50, "utils.nim");
	T1_ = (NF)0;
	T1_ = pow(((NF)(b.Field0) - (NF)(a.Field0)), 2.0000000000000000e+000);
	T2_ = (NF)0;
	T2_ = pow(((NF)(b.Field1) - (NF)(a.Field1)), 2.0000000000000000e+000);
	result = sqrt(((NF)(T1_) + (NF)(T2_)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, minus__j2pnXFSCXLnkC9a3JwzEgTw_2types)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c2) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	nimfr_("-", "types.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(271, "types.nim");
	result.Field0 = ((NF)(c1.Field0) - (NF)(c2.Field0));
	nimln_(272, "types.nim");
	result.Field1 = ((NF)(c1.Field1) - (NF)(c2.Field1));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NF, distanceToLine_7bdMeaya4Rx19bFRZ8D0AHQ)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q a, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q d1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q d2) {
	NF result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q d;
	NF T1_;
	NF T2_;
	NF T3_;
	nimfr_("distanceToLine", "utils.nim");
{	result = (NF)0;
	nimln_(56, "utils.nim");
	d = minus__j2pnXFSCXLnkC9a3JwzEgTw_2types(d2, d1);
	nimln_(57, "utils.nim");
	nimln_(58, "utils.nim");
	T1_ = (NF)0;
	T1_ = pow(d.Field1, 2.0000000000000000e+000);
	T2_ = (NF)0;
	T2_ = pow(d.Field0, 2.0000000000000000e+000);
	T3_ = (NF)0;
	T3_ = sqrt(((NF)(T1_) + (NF)(T2_)));
	result = ((NF)((((NF)(((NF)(((NF)(((NF)(d.Field1) * (NF)(a.Field0))) - (NF)(((NF)(d.Field0) * (NF)(a.Field1))))) + (NF)(((NF)(d2.Field0) * (NF)(d1.Field1))))) - (NF)(((NF)(d2.Field1) * (NF)(d1.Field0)))) < 0? -(((NF)(((NF)(((NF)(((NF)(d.Field1) * (NF)(a.Field0))) - (NF)(((NF)(d.Field0) * (NF)(a.Field1))))) + (NF)(((NF)(d2.Field0) * (NF)(d1.Field1))))) - (NF)(((NF)(d2.Field1) * (NF)(d1.Field0))))) : (((NF)(((NF)(((NF)(((NF)(d.Field1) * (NF)(a.Field0))) - (NF)(((NF)(d.Field0) * (NF)(a.Field1))))) + (NF)(((NF)(d2.Field0) * (NF)(d1.Field1))))) - (NF)(((NF)(d2.Field1) * (NF)(d1.Field0))))))) / (NF)(T3_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NF, direction_tPnITEUbWU2FqRTbBpk9cEw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q a, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q b) {
	NF result;
	NF dx;
	NF dy;
	NF T1_;
	nimfr_("direction", "utils.nim");
{	result = (NF)0;
	nimln_(65, "utils.nim");
	dx = ((NF)(b.Field0) - (NF)(a.Field0));
	nimln_(66, "utils.nim");
	dy = ((NF)(a.Field1) - (NF)(b.Field1));
	nimln_(67, "utils.nim");
	T1_ = (NF)0;
	T1_ = atan2(dy, dx);
	result = ((NF)(((NF)(-(((NF)(T1_) / (NF)(3.1415926535897931e+000)))) * (NF)(1.8000000000000000e+002))) + (NF)(9.0000000000000000e+001));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, rotate_movj9bCQBNw2qFx9bykK5X9bw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q a, NF angle) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	NF rot;
	NF c;
	NF s;
	nimfr_("rotate", "utils.nim");
{	memset((void*)(&result), 0, sizeof(result));
	nimln_(73, "utils.nim");
	{
		if (!(angle == 0.0)) goto LA3_;
		nimln_(74, "utils.nim");
		result = a;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(76, "utils.nim");
	nimln_(38, "utils.nim");
	nimln_(76, "utils.nim");
	rot = ((NF)(((NF)(angle) * (NF)(3.1415926535897931e+000))) / (NF)(1.8000000000000000e+002));
	nimln_(77, "utils.nim");
	c = cos(rot);
	nimln_(78, "utils.nim");
	s = sin(rot);
	nimln_(79, "utils.nim");
	result.Field0 = ((NF)(((NF)(a.Field0) * (NF)(c))) - (NF)(((NF)(a.Field1) * (NF)(s))));
	nimln_(80, "utils.nim");
	result.Field1 = ((NF)(((NF)(a.Field0) * (NF)(s))) + (NF)(((NF)(a.Field1) * (NF)(c))));
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, plus__j2pnXFSCXLnkC9a3JwzEgTwtypes)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c2) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	nimfr_("+", "types.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(261, "types.nim");
	result.Field0 = ((NF)(c1.Field0) + (NF)(c2.Field0));
	nimln_(262, "types.nim");
	result.Field1 = ((NF)(c1.Field1) + (NF)(c2.Field1));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, rotate_ei2HXYH1uVu4d1z432QNLw)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q point, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q offset, NF angle) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	nimfr_("rotate", "utils.nim");
{	memset((void*)(&result), 0, sizeof(result));
	nimln_(90, "utils.nim");
	nimln_(91, "utils.nim");
	{
		tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T5_;
		nimln_(398, "system.nim");
		nimln_(91, "utils.nim");
		if (!!((angle == 0.0))) goto LA3_;
		nimln_(92, "utils.nim");
		T5_ = rotate_movj9bCQBNw2qFx9bykK5X9bw(point, angle);
		result = plus__j2pnXFSCXLnkC9a3JwzEgTwtypes(T5_, offset);
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(94, "utils.nim");
		result = plus__j2pnXFSCXLnkC9a3JwzEgTwtypes(offset, point);
	}
	LA1_: ;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A*, loadSurface_nYdhujP6pdi6JN4kFcLD9aw)(NimStringDesc* file) {
	tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A* result;
	nimfr_("loadSurface", "utils.nim");
{	result = (tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A*)0;
	nimln_(109, "utils.nim");
	result = Dl_157041_(file->data);
	nimln_(110, "utils.nim");
	{
		NCSTRING T5_;
		if (!(result == NIM_NIL)) goto LA3_;
		nimln_(111, "utils.nim");
		nimln_(113, "utils.nim");
		T5_ = (NCSTRING)0;
		T5_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t load image %s: %s", file->data, T5_);
		nimln_(114, "utils.nim");
		result = NIM_NIL;
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A*, loadSurface_fe9atOmS3LLEmcMVW7SoEbw)(tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NIM_BOOL freeSrc) {
	tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A* result;
	nimfr_("loadSurface", "utils.nim");
{	result = (tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A*)0;
	nimln_(122, "utils.nim");
	result = Dl_157044_(src, ((int) (freeSrc)));
	nimln_(123, "utils.nim");
	{
		NCSTRING T5_;
		if (!(result == NIM_NIL)) goto LA3_;
		nimln_(124, "utils.nim");
		nimln_(126, "utils.nim");
		T5_ = (NCSTRING)0;
		T5_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t load image RW: %s", T5_);
		nimln_(127, "utils.nim");
		result = NIM_NIL;
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_HogsYWYa09czwuSNmOLhWVw, textureFormats_FHZG4pWypjsUIfeOMWc0WA)(void* renderer) {
	tyTuple_HogsYWYa09czwuSNmOLhWVw result;
	tyObject_RendererInfo_I9c5YLPHRMZZPky07Ra19asQ info;
	nimfr_("textureFormats", "utils.nim");
{	memset((void*)(&result), 0, sizeof(result));
	memset((void*)(&info), 0, sizeof(info));
	nimln_(136, "utils.nim");
	{
		int T3_;
		T3_ = (int)0;
		T3_ = Dl_155126_(renderer, (&info));
		if (!(T3_ == ((NI32) 0))) goto LA4_;
		nimln_(137, "utils.nim");
		result.Field0 = info.num_texture_formats;
		memcpy((void*)result.Field1, (NIM_CONST void*)info.texture_formats, sizeof(tyArray_U0SiHM0pVagA9c71oWelQMA));
		goto BeforeRet_;
	}
	goto LA1_;
	LA4_: ;
	{
		NCSTRING T7_;
		nimln_(139, "utils.nim");
		nimln_(141, "utils.nim");
		T7_ = (NCSTRING)0;
		T7_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t get renderer texture format: %s", T7_);
		nimln_(142, "utils.nim");
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NU32, textureFormat_TfMLpZoUN8qi5KmaGtdIWg)(void* renderer, NU32 n) {
	NU32 result;
	tyTuple_HogsYWYa09czwuSNmOLhWVw T1_;
	NU32 num;
	tyArray_U0SiHM0pVagA9c71oWelQMA formats;
	nimfr_("textureFormat", "utils.nim");
{	result = (NU32)0;
	nimln_(148, "utils.nim");
	T1_ = textureFormats_FHZG4pWypjsUIfeOMWc0WA(renderer);
	num = T1_.Field0;
	memcpy((void*)formats, (NIM_CONST void*)T1_.Field1, sizeof(tyArray_U0SiHM0pVagA9c71oWelQMA));
	nimln_(149, "utils.nim");
	{
		if (!((NU32)(n) < (NU32)(num))) goto LA4_;
		nimln_(150, "utils.nim");
		if ((NU)(n) > (NU)(15)) raiseIndexError();
		result = formats[(n)- 0];
		goto BeforeRet_;
	}
	goto LA2_;
	LA4_: ;
	{
		nimln_(152, "utils.nim");
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "No such texture format (%d) in current renderer.", n);
		nimln_(154, "utils.nim");
		goto BeforeRet_;
	}
	LA2_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readAll_F7m4d1s9ce15AymiFiYv8ew)(tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src) {
	NimStringDesc* result;
	NI r;
	nimfr_("readAll", "utils.nim");
	result = (NimStringDesc*)0;
	nimln_(166, "utils.nim");
	result = mnewString(((NI) 1000));
	nimln_(167, "utils.nim");
	r = ((NI) 0);
	{
		nimln_(168, "utils.nim");
		while (1) {
			size_t readBytes;
			NI TM_WSc01Aef5CMpWdOBujpuWQ_3;
			NI TM_WSc01Aef5CMpWdOBujpuWQ_4;
			nimln_(169, "utils.nim");
			if ((NU)(r) > (NU)(result->Sup.len)) raiseIndexError();
			readBytes = (*src).read(src, ((void*) ((&result->data[r]))), ((NI) 1), ((NI) 1000));
			nimln_(170, "utils.nim");
			{
				NI TM_WSc01Aef5CMpWdOBujpuWQ_2;
				if (!(readBytes < ((NI) 1000))) goto LA5_;
				nimln_(171, "utils.nim");
				TM_WSc01Aef5CMpWdOBujpuWQ_2 = addInt(r, readBytes);
				result = setLengthStr(result, ((NI)chckRange((NI)(TM_WSc01Aef5CMpWdOBujpuWQ_2), ((NI) 0), ((NI) IL64(9223372036854775807)))));
				nimln_(172, "utils.nim");
				goto LA1;
			}
			LA5_: ;
			nimln_(173, "utils.nim");
			TM_WSc01Aef5CMpWdOBujpuWQ_3 = addInt(r, ((NI) 1000));
			r = (NI)(TM_WSc01Aef5CMpWdOBujpuWQ_3);
			nimln_(174, "utils.nim");
			TM_WSc01Aef5CMpWdOBujpuWQ_4 = addInt(r, ((NI) 1000));
			result = setLengthStr(result, ((NI)chckRange((NI)(TM_WSc01Aef5CMpWdOBujpuWQ_4), ((NI) 0), ((NI) IL64(9223372036854775807)))));
		}
	} LA1: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_acepldouQeokxA9cg6MkDnA)(void* p, NI op) {
	tySequence_acepldouQeokxA9cg6MkDnA* a;
	NI T1_;
	a = (tySequence_acepldouQeokxA9cg6MkDnA*)p;
	T1_ = (NI)0;
}

N_LIB_PRIVATE N_NIMCALL(void, loadPalette_TokvM2rcMK3fjDTH4UDGfA)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg** palette, tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* parser) {
	NI ncolors;
	tySequence_acepldouQeokxA9cg6MkDnA* colors;
	NI r;
	NI g;
	NI b;
	NI a;
	nimfr_("loadPalette", "utils.nim");
	nimln_(235, "utils.nim");
	ncolors = ((NI) 0);
	nimln_(236, "utils.nim");
	colors = (tySequence_acepldouQeokxA9cg6MkDnA*) newSeq((&NTI_acepldouQeokxA9cg6MkDnA_), 0);
	r = (NI)0;
	g = (NI)0;
	b = (NI)0;
	a = (NI)0;
	{
		nimln_(238, "utils.nim");
		while (1) {
			NIM_BOOL T3_;
			T3_ = (NIM_BOOL)0;
			T3_ = readRow_9bHdhFE0qEvOrDqjuQBz8Pw(parser, ((NI) 0));
			if (!T3_) goto LA2;
			{
				NI cols;
				NI T5_;
				nimln_(239, "utils.nim");
				T5_ = ((*parser).row ? (*parser).row->Sup.len : 0);
				cols = T5_;
				nimln_(240, "utils.nim");
				{
					NI TM_WSc01Aef5CMpWdOBujpuWQ_5;
					if (!(cols == ((NI) 3) || cols == ((NI) 4))) goto LA8_;
					nimln_(241, "utils.nim");
					if ((NU)(((NI) 0)) >= (NU)((*parser).row->Sup.len)) raiseIndexError();
					r = nsuParseInt((*parser).row->data[((NI) 0)]);
					nimln_(242, "utils.nim");
					if ((NU)(((NI) 1)) >= (NU)((*parser).row->Sup.len)) raiseIndexError();
					g = nsuParseInt((*parser).row->data[((NI) 1)]);
					nimln_(243, "utils.nim");
					if ((NU)(((NI) 2)) >= (NU)((*parser).row->Sup.len)) raiseIndexError();
					b = nsuParseInt((*parser).row->data[((NI) 2)]);
					nimln_(244, "utils.nim");
					{
						if (!(cols == ((NI) 4))) goto LA12_;
						if ((NU)(((NI) 3)) >= (NU)((*parser).row->Sup.len)) raiseIndexError();
						a = nsuParseInt((*parser).row->data[((NI) 3)]);
					}
					goto LA10_;
					LA12_: ;
					{
						a = ((NI) 255);
					}
					LA10_: ;
					nimln_(246, "utils.nim");
					TM_WSc01Aef5CMpWdOBujpuWQ_5 = addInt(ncolors, ((NI) 1));
					ncolors = (NI)(TM_WSc01Aef5CMpWdOBujpuWQ_5);
				}
				goto LA6_;
				LA8_: ;
				{
					nimln_(248, "utils.nim");
					goto LA4;
				}
				LA6_: ;
			} LA4: ;
		} LA2: ;
	}
	nimln_(249, "utils.nim");
	{
		if (!(((NI) 0) < ncolors)) goto LA18_;
		nimln_(250, "utils.nim");
		{
			if (!!(((*palette) == NIM_NIL))) goto LA22_;
			nimln_(251, "utils.nim");
			free_XPSpdGrbzFLrRNrh4eaJuA((*palette));
		}
		LA22_: ;
		nimln_(252, "utils.nim");
		init_NWdB9au5KthgJE4agI9amyAA(palette, ncolors);
		nimln_(253, "utils.nim");
		X5BX5Deq__syZw77tfvlbUcAM2X9aa9aaA((*palette), ((NI) 0), colors->data, colors->Sup.len);
	}
	LA18_: ;
	popFrame();
}

static N_INLINE(void, close_A55CxARYHkQe359a6AS5GRQparsecsv)(tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ* my) {
	tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T1_;
	nimfr_("close", "parsecsv.nim");
	nimln_(206, "parsecsv.nim");
	T1_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
	T1_ = &my->Sup;
	close_QbedUCk2XwI9c7bbRzXBY0g(T1_);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, loadPalette_zmXTqFCKc6HB1J9bDsaP3EA)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg** palette, NimStringDesc* file, NIM_CHAR separator, NIM_CHAR quote, NIM_CHAR escape, NIM_BOOL skipInitialSpace) {
	tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ parser;
	nimfr_("loadPalette", "utils.nim");
	memset((void*)(&parser), 0, sizeof(parser));
	parser.Sup.Sup.m_type = (&NTI_e0KmhL4ItditGQKnCUZMoQ_);
	nimln_(283, "utils.nim");
	open_grmoJIpX15R5Xfx6m2M1UA((&parser), file, separator, quote, escape, skipInitialSpace);
	nimln_(284, "utils.nim");
	loadPalette_TokvM2rcMK3fjDTH4UDGfA(palette, (&parser));
	nimln_(285, "utils.nim");
	close_A55CxARYHkQe359a6AS5GRQparsecsv((&parser));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, loadPalette_1CtzKxkUfkpzEKz9alpH9bqQ)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg** palette, tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NimStringDesc* file, NIM_CHAR separator, NIM_CHAR quote, NIM_CHAR escape, NIM_BOOL skipInitialSpace, NIM_BOOL freeSrc) {
	tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ parser;
	tyObject_StringStreamObj_lGsM0FdhfyxyplfYoMsgFQ* stream;
	NimStringDesc* T1_;
	tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T2_;
	tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T3_;
	nimfr_("loadPalette", "utils.nim");
	memset((void*)(&parser), 0, sizeof(parser));
	parser.Sup.Sup.m_type = (&NTI_e0KmhL4ItditGQKnCUZMoQ_);
	nimln_(298, "utils.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = readAll_F7m4d1s9ce15AymiFiYv8ew(src);
	stream = newStringStream_0dQ0A0pna0dG9cMxo4TbLKQ(T1_);
	nimln_(299, "utils.nim");
	T2_ = (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
	T2_ = &stream->Sup;
	open_dmBuwTCvdiT9cdjydWhbTTg((&parser), T2_, file, separator, quote, escape, skipInitialSpace);
	nimln_(300, "utils.nim");
	loadPalette_TokvM2rcMK3fjDTH4UDGfA(palette, (&parser));
	nimln_(301, "utils.nim");
	close_A55CxARYHkQe359a6AS5GRQparsecsv((&parser));
	nimln_(302, "utils.nim");
	T3_ = (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
	T3_ = &stream->Sup;
	close_4ed7IXme7lqtClFI7s2sTQ_2(T3_);
	nimln_(303, "utils.nim");
	{
		if (!freeSrc) goto LA6_;
		nimln_(304, "utils.nim");
		Dl_147327_(src);
	}
	LA6_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, randomBool_R3rTyvvmThxxKUf4W6tpqQ)(NF chance) {
	NIM_BOOL result;
	NF T1_;
	NF T2_;
	nimfr_("randomBool", "utils.nim");
{	result = (NIM_BOOL)0;
	nimln_(471, "utils.nim");
	T1_ = (NF)0;
	T1_ = random_ysAjdvfIGCDnzC8BoWsOAw(1.0000000000000000e+000);
	T2_ = (NF)0;
	T2_ = clamp_BGhQiHv5LFkg9aDgeidEq0g(chance, 0.0, 1.0000000000000000e+000);
	result = (T1_ < T2_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, randBool_xwNyTFCoEbHFYNHdUfF4OAutils)(NF chance) {
	NIM_BOOL result;
	nimfr_("randBool", "utils.nim");
	result = (NIM_BOOL)0;
	nimln_(474, "utils.nim");
	result = randomBool_R3rTyvvmThxxKUf4W6tpqQ(chance);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, randomSign_UJ8proCyAoKiHeYltnU8tA)(NF chance) {
	NI result;
	nimfr_("randomSign", "utils.nim");
{	result = (NI)0;
	nimln_(481, "utils.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = randomBool_R3rTyvvmThxxKUf4W6tpqQ(chance);
		if (!T3_) goto LA4_;
		result = ((NI) 1);
	}
	goto LA1_;
	LA4_: ;
	{
		result = ((NI) -1);
	}
	LA1_: ;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, randSign_DZSArtZoMyaKku4qgJ8V1gutils)(NF chance) {
	NI result;
	nimfr_("randSign", "utils.nim");
	result = (NI)0;
	nimln_(484, "utils.nim");
	result = randomSign_UJ8proCyAoKiHeYltnU8tA(chance);
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_NfV7YMRLkJnJfP6TGsbPDA)(void* p, NI op) {
	tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q* a;
	a = (tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q*)p;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q*, newCounter_NrzaLdJXb3T0qcpTsT9c9cdw)(NI interval) {
	tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q* result;
	nimfr_("newCounter", "utils.nim");
	result = (tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q*)0;
	nimln_(535, "utils.nim");
	result = (tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q*) newObj((&NTI_NfV7YMRLkJnJfP6TGsbPDA_), sizeof(tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q));
	nimln_(536, "utils.nim");
	(*result).counter = ((NI) 0);
	nimln_(537, "utils.nim");
	(*result).current = ((NI) 0);
	nimln_(538, "utils.nim");
	(*result).interval = interval;
	nimln_(539, "utils.nim");
	(*result).time = Dl_156042_();
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, update_pJzkC1Hjtqv9bJ3RWlcS1wA)(tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q* counter) {
	NI TM_WSc01Aef5CMpWdOBujpuWQ_7;
	NU64 time_1;
	nimfr_("update", "utils.nim");
	nimln_(543, "utils.nim");
	TM_WSc01Aef5CMpWdOBujpuWQ_7 = addInt((*counter).counter, ((NI) 1));
	(*counter).counter = (NI)(TM_WSc01Aef5CMpWdOBujpuWQ_7);
	nimln_(544, "utils.nim");
	time_1 = Dl_156042_();
	nimln_(545, "utils.nim");
	{
		NU64 T3_;
		nimln_(519, "utils.nim");
		nimln_(545, "utils.nim");
		nimln_(519, "utils.nim");
		T3_ = (NU64)0;
		T3_ = Dl_156044_();
		if (!((*counter).interval < ((NI) ((NU64)((NU64)((NU64)((NU64)((NU64)((NU64)(time_1) - (NU64)((*counter).time))) * (NU64)(((NI) 1000)))) / (NU64)(T3_)))))) goto LA4_;
		nimln_(546, "utils.nim");
		(*counter).current = (*counter).counter;
		nimln_(547, "utils.nim");
		(*counter).counter = ((NI) 0);
		nimln_(548, "utils.nim");
		(*counter).time = time_1;
	}
	LA4_: ;
	popFrame();
}

static N_INLINE(NI, value_k3IDuofZgKrTXDbo9alw2cgutils)(tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q* counter) {
	NI result;
	nimfr_("value", "utils.nim");
	result = (NI)0;
	nimln_(552, "utils.nim");
	result = (*counter).current;
	popFrame();
	return result;
}

static N_INLINE(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, star__P3evVH8XmA9cYiwl3XfSW4Q_3types)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c, NF v) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	nimfr_("*", "types.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(329, "types.nim");
	result.Field0 = ((NF)(c.Field0) * (NF)(v));
	nimln_(330, "types.nim");
	result.Field1 = ((NF)(c.Field1) * (NF)(v));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, point_VxjuNbYTDh6zu8OpfTFxYw)(tyTuple_Fu1oVqpZ40A7cjazVlOmBA* self, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q point) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T2_;
	nimfr_("point", "utils.nim");
{	memset((void*)(&result), 0, sizeof(result));
	nimln_(560, "utils.nim");
	T1_ = rotate_movj9bCQBNw2qFx9bykK5X9bw(point, (*self).Field1);
	T2_ = star__P3evVH8XmA9cYiwl3XfSW4Q_3types(T1_, (*self).Field2);
	result = plus__j2pnXFSCXLnkC9a3JwzEgTwtypes((*self).Field0, T2_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, inverse_point_VxjuNbYTDh6zu8OpfTFxYw_2)(tyTuple_Fu1oVqpZ40A7cjazVlOmBA* self, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q point) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q relpoint;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	nimfr_("inverse_point", "utils.nim");
{	memset((void*)(&result), 0, sizeof(result));
	nimln_(564, "utils.nim");
	relpoint = minus__j2pnXFSCXLnkC9a3JwzEgTw_2types((*self).Field0, point);
	nimln_(565, "utils.nim");
	T1_ = rotate_ei2HXYH1uVu4d1z432QNLw(relpoint, (*self).Field0, -((*self).Field1));
	result = minus__j2pnXFSCXLnkC9a3JwzEgTw_2types((*self).Field0, T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x, NF y) {
	nimfr_("+=", "system.nim");
	nimln_(3700, "system.nim");
	(*x) = ((NF)((*x)) + (NF)(y));
	popFrame();
}

static N_INLINE(void, pluseq__PCl7gsYLasB10y8xsRW9afgtypes)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* c1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c2) {
	nimfr_("+=", "types.nim");
	nimln_(266, "types.nim");
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*c1).Field0), c2.Field0);
	nimln_(267, "types.nim");
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&(*c1).Field1), c2.Field1);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_Fu1oVqpZ40A7cjazVlOmBA, translated_bcWSNVzEunN9b3tnWBTENbQ)(tyTuple_Fu1oVqpZ40A7cjazVlOmBA* self, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q delta) {
	tyTuple_Fu1oVqpZ40A7cjazVlOmBA result;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T1_;
	nimfr_("translated", "utils.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(568, "utils.nim");
	result = copy_BX8qKci9av4hVcEqiqVHs9cA(self);
	nimln_(569, "utils.nim");
	T1_ = point_VxjuNbYTDh6zu8OpfTFxYw((&result), delta);
	pluseq__PCl7gsYLasB10y8xsRW9afgtypes((&result.Field0), T1_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_Fu1oVqpZ40A7cjazVlOmBA, rotated_ONlKdR0uXo814AKNf5PsUg)(tyTuple_Fu1oVqpZ40A7cjazVlOmBA* self, NF angle) {
	tyTuple_Fu1oVqpZ40A7cjazVlOmBA result;
	nimfr_("rotated", "utils.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(572, "utils.nim");
	result = copy_BX8qKci9av4hVcEqiqVHs9cA(self);
	nimln_(573, "utils.nim");
	pluseq__7kHiltrvRlcg6wSYR3CxAw_2strutils((&result.Field1), angle);
	popFrame();
	return result;
}

static N_INLINE(void, stareq__7kHiltrvRlcg6wSYR3CxAwstrutils)(NF* x, NF y) {
	nimfr_("*=", "system.nim");
	nimln_(3710, "system.nim");
	(*x) = ((NF)((*x)) * (NF)(y));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_Fu1oVqpZ40A7cjazVlOmBA, scaled_ZbuYcr36xox69bLb4wEZoGw)(tyTuple_Fu1oVqpZ40A7cjazVlOmBA* self, NF scale) {
	tyTuple_Fu1oVqpZ40A7cjazVlOmBA result;
	nimfr_("scaled", "utils.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(576, "utils.nim");
	result = copy_BX8qKci9av4hVcEqiqVHs9cA(self);
	nimln_(577, "utils.nim");
	stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&result.Field2), scale);
	popFrame();
	return result;
}

static N_INLINE(NI, find_b2asjP2y9cPDPwOLa1pD5PAutils)(NI* a, NI aLen_0, NI item) {
	NI result;
	nimfr_("find", "system.nim");
{	result = (NI)0;
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(2185, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI TM_WSc01Aef5CMpWdOBujpuWQ_8;
				NI TM_WSc01Aef5CMpWdOBujpuWQ_9;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				if ((NU)(i_2) >= (NU)(aLen_0)) raiseIndexError();
				i = a[i_2];
				nimln_(2419, "system.nim");
				{
					if (!(i == item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(2420, "system.nim");
				TM_WSc01Aef5CMpWdOBujpuWQ_8 = addInt(result, ((NI) 1));
				result = (NI)(TM_WSc01Aef5CMpWdOBujpuWQ_8);
				nimln_(2188, "system.nim");
				TM_WSc01Aef5CMpWdOBujpuWQ_9 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_WSc01Aef5CMpWdOBujpuWQ_9);
			} LA3: ;
		}
	}
	nimln_(2421, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_P6sCVNQ9cdTFh3rtVXMEtxgutils)(NI* a, NI aLen_0, NI item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "system.nim");
{	result = (NIM_BOOL)0;
	nimln_(2426, "system.nim");
	T1_ = (NI)0;
	T1_ = find_b2asjP2y9cPDPwOLa1pD5PAutils(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, rand_bXFhlVh7ZFz3I1g4MkLBnw)(NI max, tySequence_qwqHTkRvwhrRyENtudHQ7g* exclude) {
	NI result;
	nimfr_("rand", "utils.nim");
	result = (NI)0;
	nimln_(382, "utils.nim");
	result = rand_F1qFFP53BvbP4L65Kn9bG1w_2(max);
	{
		nimln_(383, "utils.nim");
		while (1) {
			NIM_BOOL T3_;
			T3_ = (NIM_BOOL)0;
			T3_ = contains_P6sCVNQ9cdTFh3rtVXMEtxgutils(exclude->data, exclude->Sup.len, result);
			if (!T3_) goto LA2;
			nimln_(384, "utils.nim");
			result = rand_F1qFFP53BvbP4L65Kn9bG1w_2(max);
		} LA2: ;
	}
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_phjbYJtsbOIAYa9be34hhZg)(void* p, NI op) {
	tySequence_phjbYJtsbOIAYa9be34hhZg* a;
	NI T1_;
	a = (tySequence_phjbYJtsbOIAYa9be34hhZg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(tySequence_sM4lkSb7zS6F7OVMvW9cffQ**, X5BX5D__HTndH1gVLM7rZgP9a9bH1iZgutils)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ** s, NI sLen_0, NI i) {
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ** result;
	NI TM_WSc01Aef5CMpWdOBujpuWQ_10;
	nimfr_("[]", "system.nim");
	result = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ**)0;
	nimln_(3629, "system.nim");
	TM_WSc01Aef5CMpWdOBujpuWQ_10 = subInt(sLen_0, i);
	if ((NU)((NI)(TM_WSc01Aef5CMpWdOBujpuWQ_10)) >= (NU)(sLen_0)) raiseIndexError();
	result = (&s[(NI)(TM_WSc01Aef5CMpWdOBujpuWQ_10)]);
	popFrame();
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tySequence_phjbYJtsbOIAYa9be34hhZg*, loadCSV_qawRPbC1I69cg4CQ9a6J5Sbg)(NimStringDesc* file, tyProc_lRW9cfxqfm1ql4gkxfLReYg parse, NIM_CHAR separator, NIM_CHAR quote, NIM_CHAR escape, NIM_BOOL skipInitialSpace) {
	tySequence_phjbYJtsbOIAYa9be34hhZg* result;
	tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ parser;
	nimfr_("loadCSV", "utils.nim");
	result = (tySequence_phjbYJtsbOIAYa9be34hhZg*)0;
	nimln_(188, "utils.nim");
	result = (tySequence_phjbYJtsbOIAYa9be34hhZg*) newSeq((&NTI_phjbYJtsbOIAYa9be34hhZg_), 0);
	memset((void*)(&parser), 0, sizeof(parser));
	parser.Sup.Sup.m_type = (&NTI_e0KmhL4ItditGQKnCUZMoQ_);
	nimln_(190, "utils.nim");
	open_grmoJIpX15R5Xfx6m2M1UA((&parser), file, separator, quote, escape, skipInitialSpace);
	{
		nimln_(191, "utils.nim");
		while (1) {
			NIM_BOOL T3_;
			tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T4_;
			NI T5_;
			T3_ = (NIM_BOOL)0;
			T3_ = readRow_9bHdhFE0qEvOrDqjuQBz8Pw((&parser), ((NI) 0));
			if (!T3_) goto LA2;
			nimln_(192, "utils.nim");
			T4_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
			T4_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
			result = (tySequence_phjbYJtsbOIAYa9be34hhZg*) incrSeqV2(&(result)->Sup, sizeof(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*));
			T5_ = result->Sup.len++;
			genericSeqAssign((&result->data[T5_]), T4_, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
			{
				NimStringDesc* item;
				tySequence_sM4lkSb7zS6F7OVMvW9cffQ* colontmp_;
				NI i;
				NI L;
				NI T7_;
				item = (NimStringDesc*)0;
				colontmp_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
				nimln_(193, "utils.nim");
				colontmp_ = parser.row;
				nimln_(3805, "system.nim");
				i = ((NI) 0);
				nimln_(3806, "system.nim");
				T7_ = (colontmp_ ? colontmp_->Sup.len : 0);
				L = T7_;
				{
					nimln_(3807, "system.nim");
					while (1) {
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ** T10_;
						NimStringDesc* T11_;
						NI T12_;
						NimStringDesc* T13_;
						NI TM_WSc01Aef5CMpWdOBujpuWQ_12;
						if (!(i < L)) goto LA9;
						nimln_(3808, "system.nim");
						if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
						item = colontmp_->data[i];
						nimln_(194, "utils.nim");
						T10_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ**)0;
						T10_ = X5BX5D__HTndH1gVLM7rZgP9a9bH1iZgutils(result->data, result->Sup.len, ((NI) 1));
						T11_ = (NimStringDesc*)0;
						T11_ = parse.ClE_0? parse.ClP_0(item, parse.ClE_0):((TM_WSc01Aef5CMpWdOBujpuWQ_11)(parse.ClP_0))(item);
						(*T10_) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*T10_))->Sup, sizeof(NimStringDesc*));
						T12_ = (*T10_)->Sup.len++;
						T13_ = (NimStringDesc*)0;
						T13_ = (*T10_)->data[T12_]; (*T10_)->data[T12_] = copyStringRC1(T11_);
						if (T13_) nimGCunrefNoCycle(T13_);
						nimln_(3809, "system.nim");
						TM_WSc01Aef5CMpWdOBujpuWQ_12 = addInt(i, ((NI) 1));
						i = (NI)(TM_WSc01Aef5CMpWdOBujpuWQ_12);
						nimln_(3810, "system.nim");
						{
							NI T16_;
							T16_ = (colontmp_ ? colontmp_->Sup.len : 0);
							if (!!((T16_ == L))) goto LA17_;
							failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_WSc01Aef5CMpWdOBujpuWQ_13));
						}
						LA17_: ;
					} LA9: ;
				}
			}
		} LA2: ;
	}
	nimln_(195, "utils.nim");
	close_A55CxARYHkQe359a6AS5GRQparsecsv((&parser));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_phjbYJtsbOIAYa9be34hhZg*, loadCSV_9afXmpQyieHVjeHUD9cf61cQ)(tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NimStringDesc* file, tyProc_lRW9cfxqfm1ql4gkxfLReYg parse, NIM_CHAR separator, NIM_CHAR quote, NIM_CHAR escape, NIM_BOOL skipInitialSpace, NIM_BOOL freeSrc) {
	tySequence_phjbYJtsbOIAYa9be34hhZg* result;
	tyObject_CsvParser_e0KmhL4ItditGQKnCUZMoQ parser;
	tyObject_StringStreamObj_lGsM0FdhfyxyplfYoMsgFQ* stream;
	NimStringDesc* T1_;
	tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T2_;
	tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T21_;
	nimfr_("loadCSV", "utils.nim");
	result = (tySequence_phjbYJtsbOIAYa9be34hhZg*)0;
	nimln_(213, "utils.nim");
	result = (tySequence_phjbYJtsbOIAYa9be34hhZg*) newSeq((&NTI_phjbYJtsbOIAYa9be34hhZg_), 0);
	memset((void*)(&parser), 0, sizeof(parser));
	parser.Sup.Sup.m_type = (&NTI_e0KmhL4ItditGQKnCUZMoQ_);
	nimln_(216, "utils.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = readAll_F7m4d1s9ce15AymiFiYv8ew(src);
	stream = newStringStream_0dQ0A0pna0dG9cMxo4TbLKQ(T1_);
	nimln_(217, "utils.nim");
	T2_ = (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
	T2_ = &stream->Sup;
	open_dmBuwTCvdiT9cdjydWhbTTg((&parser), T2_, file, separator, quote, escape, skipInitialSpace);
	{
		nimln_(218, "utils.nim");
		while (1) {
			NIM_BOOL T5_;
			tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T6_;
			NI T7_;
			T5_ = (NIM_BOOL)0;
			T5_ = readRow_9bHdhFE0qEvOrDqjuQBz8Pw((&parser), ((NI) 0));
			if (!T5_) goto LA4;
			nimln_(219, "utils.nim");
			T6_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
			T6_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
			result = (tySequence_phjbYJtsbOIAYa9be34hhZg*) incrSeqV2(&(result)->Sup, sizeof(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*));
			T7_ = result->Sup.len++;
			genericSeqAssign((&result->data[T7_]), T6_, (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_));
			{
				NimStringDesc* item;
				tySequence_sM4lkSb7zS6F7OVMvW9cffQ* colontmp_;
				NI i;
				NI L;
				NI T9_;
				item = (NimStringDesc*)0;
				colontmp_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
				nimln_(220, "utils.nim");
				colontmp_ = parser.row;
				nimln_(3805, "system.nim");
				i = ((NI) 0);
				nimln_(3806, "system.nim");
				T9_ = (colontmp_ ? colontmp_->Sup.len : 0);
				L = T9_;
				{
					nimln_(3807, "system.nim");
					while (1) {
						tySequence_sM4lkSb7zS6F7OVMvW9cffQ** T12_;
						NimStringDesc* T13_;
						NI T14_;
						NimStringDesc* T15_;
						NI TM_WSc01Aef5CMpWdOBujpuWQ_15;
						if (!(i < L)) goto LA11;
						nimln_(3808, "system.nim");
						if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
						item = colontmp_->data[i];
						nimln_(221, "utils.nim");
						T12_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ**)0;
						T12_ = X5BX5D__HTndH1gVLM7rZgP9a9bH1iZgutils(result->data, result->Sup.len, ((NI) 1));
						T13_ = (NimStringDesc*)0;
						T13_ = parse.ClE_0? parse.ClP_0(item, parse.ClE_0):((TM_WSc01Aef5CMpWdOBujpuWQ_14)(parse.ClP_0))(item);
						(*T12_) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&((*T12_))->Sup, sizeof(NimStringDesc*));
						T14_ = (*T12_)->Sup.len++;
						T15_ = (NimStringDesc*)0;
						T15_ = (*T12_)->data[T14_]; (*T12_)->data[T14_] = copyStringRC1(T13_);
						if (T15_) nimGCunrefNoCycle(T15_);
						nimln_(3809, "system.nim");
						TM_WSc01Aef5CMpWdOBujpuWQ_15 = addInt(i, ((NI) 1));
						i = (NI)(TM_WSc01Aef5CMpWdOBujpuWQ_15);
						nimln_(3810, "system.nim");
						{
							NI T18_;
							T18_ = (colontmp_ ? colontmp_->Sup.len : 0);
							if (!!((T18_ == L))) goto LA19_;
							failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_WSc01Aef5CMpWdOBujpuWQ_13));
						}
						LA19_: ;
					} LA11: ;
				}
			}
		} LA4: ;
	}
	nimln_(222, "utils.nim");
	close_A55CxARYHkQe359a6AS5GRQparsecsv((&parser));
	nimln_(223, "utils.nim");
	T21_ = (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
	T21_ = &stream->Sup;
	close_4ed7IXme7lqtClFI7s2sTQ_2(T21_);
	nimln_(224, "utils.nim");
	{
		if (!freeSrc) goto LA24_;
		nimln_(225, "utils.nim");
		Dl_147327_(src);
	}
	LA24_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, nimgame2_utilsInit000)(void) {
	nimfr_("utils", "utils.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimgame2_utilsDatInit000)(void) {
static TNimNode* TM_WSc01Aef5CMpWdOBujpuWQ_6[4];
static TNimNode TM_WSc01Aef5CMpWdOBujpuWQ_0[5];
NTI_acepldouQeokxA9cg6MkDnA_.size = sizeof(tySequence_acepldouQeokxA9cg6MkDnA*);
NTI_acepldouQeokxA9cg6MkDnA_.kind = 24;
NTI_acepldouQeokxA9cg6MkDnA_.base = (&NTI_YizDHyEvJtgQk2fn8KdZUA_);
NTI_acepldouQeokxA9cg6MkDnA_.flags = 2;
NTI_acepldouQeokxA9cg6MkDnA_.marker = Marker_tySequence_acepldouQeokxA9cg6MkDnA;
NTI_xch5drbeIU4SamGPZzsp8Q_.size = sizeof(tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q);
NTI_xch5drbeIU4SamGPZzsp8Q_.kind = 18;
NTI_xch5drbeIU4SamGPZzsp8Q_.base = 0;
NTI_xch5drbeIU4SamGPZzsp8Q_.flags = 3;
TM_WSc01Aef5CMpWdOBujpuWQ_6[0] = &TM_WSc01Aef5CMpWdOBujpuWQ_0[1];
TM_WSc01Aef5CMpWdOBujpuWQ_0[1].kind = 1;
TM_WSc01Aef5CMpWdOBujpuWQ_0[1].offset = offsetof(tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q, counter);
TM_WSc01Aef5CMpWdOBujpuWQ_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_WSc01Aef5CMpWdOBujpuWQ_0[1].name = "counter";
TM_WSc01Aef5CMpWdOBujpuWQ_6[1] = &TM_WSc01Aef5CMpWdOBujpuWQ_0[2];
TM_WSc01Aef5CMpWdOBujpuWQ_0[2].kind = 1;
TM_WSc01Aef5CMpWdOBujpuWQ_0[2].offset = offsetof(tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q, current);
TM_WSc01Aef5CMpWdOBujpuWQ_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_WSc01Aef5CMpWdOBujpuWQ_0[2].name = "current";
TM_WSc01Aef5CMpWdOBujpuWQ_6[2] = &TM_WSc01Aef5CMpWdOBujpuWQ_0[3];
TM_WSc01Aef5CMpWdOBujpuWQ_0[3].kind = 1;
TM_WSc01Aef5CMpWdOBujpuWQ_0[3].offset = offsetof(tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q, interval);
TM_WSc01Aef5CMpWdOBujpuWQ_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_WSc01Aef5CMpWdOBujpuWQ_0[3].name = "interval";
TM_WSc01Aef5CMpWdOBujpuWQ_6[3] = &TM_WSc01Aef5CMpWdOBujpuWQ_0[4];
TM_WSc01Aef5CMpWdOBujpuWQ_0[4].kind = 1;
TM_WSc01Aef5CMpWdOBujpuWQ_0[4].offset = offsetof(tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q, time);
TM_WSc01Aef5CMpWdOBujpuWQ_0[4].typ = (&NTI_wMtfD88jmrPZwfzTH9c8e9cA_);
TM_WSc01Aef5CMpWdOBujpuWQ_0[4].name = "time";
TM_WSc01Aef5CMpWdOBujpuWQ_0[0].len = 4; TM_WSc01Aef5CMpWdOBujpuWQ_0[0].kind = 2; TM_WSc01Aef5CMpWdOBujpuWQ_0[0].sons = &TM_WSc01Aef5CMpWdOBujpuWQ_6[0];
NTI_xch5drbeIU4SamGPZzsp8Q_.node = &TM_WSc01Aef5CMpWdOBujpuWQ_0[0];
NTI_NfV7YMRLkJnJfP6TGsbPDA_.size = sizeof(tyObject_CountercolonObjectType__xch5drbeIU4SamGPZzsp8Q*);
NTI_NfV7YMRLkJnJfP6TGsbPDA_.kind = 22;
NTI_NfV7YMRLkJnJfP6TGsbPDA_.base = (&NTI_xch5drbeIU4SamGPZzsp8Q_);
NTI_NfV7YMRLkJnJfP6TGsbPDA_.flags = 2;
NTI_NfV7YMRLkJnJfP6TGsbPDA_.marker = Marker_tyRef_NfV7YMRLkJnJfP6TGsbPDA;
NTI_phjbYJtsbOIAYa9be34hhZg_.size = sizeof(tySequence_phjbYJtsbOIAYa9be34hhZg*);
NTI_phjbYJtsbOIAYa9be34hhZg_.kind = 24;
NTI_phjbYJtsbOIAYa9be34hhZg_.base = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
NTI_phjbYJtsbOIAYa9be34hhZg_.flags = 2;
NTI_phjbYJtsbOIAYa9be34hhZg_.marker = Marker_tySequence_phjbYJtsbOIAYa9be34hhZg;
}

