/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\Users\Alterna\Documents\nim-0.18.0\lib -o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\nimgame2_indexedimage.o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\nimgame2_indexedimage.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg;
typedef struct tyObject_Color_YizDHyEvJtgQk2fn8KdZUA tyObject_Color_YizDHyEvJtgQk2fn8KdZUA;
typedef struct tyObject_IndexError_b0IIwghFQBADkB2c86kXQA tyObject_IndexError_b0IIwghFQBADkB2c86kXQA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA;
typedef struct tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A;
typedef struct tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q;
typedef struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ tyObject_Rect_qiXweduDJk1iLE5aHysNdQ;
typedef struct tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef union tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ;
typedef struct tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ;
typedef struct tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA;
typedef struct tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ;
typedef struct tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg;
typedef struct tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q;
typedef struct tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA;
typedef N_CDECL_PTR(void, tyProc_3d8ZGFdX9cH9cDT9a42QwE9cvg) (tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette);
typedef N_CDECL_PTR(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg*, tyProc_Anj9as7d5YZdqOLVOsW9cq9bQ) (int ncolors);
struct tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg {
int ncolors;
tyObject_Color_YizDHyEvJtgQk2fn8KdZUA* colors;
NU32 version;
int refcount;
};
struct tyObject_Color_YizDHyEvJtgQk2fn8KdZUA {
NU8 r;
NU8 g;
NU8 b;
NU8 a;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_IndexError_b0IIwghFQBADkB2c86kXQA {
  Exception Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef N_CDECL_PTR(int, tyProc_wotRTUnRZK0xNH5VjeE8Ng) (tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA* colors, int firstcolor, int ncolors);
typedef NI32 tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw;
typedef N_CDECL_PTR(void, tyProc_DusjKySyJW30WdV9bsteVxw) (tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw category, NCSTRING fmt, ...);
typedef N_CDECL_PTR(NCSTRING, tyProc_09bvyvHFtWbkzL5AHgf0bKw) (void);
typedef tyObject_Color_YizDHyEvJtgQk2fn8KdZUA tyArray_cXelO9ahiHJ8br39bNGtKXJw[1];
struct tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA {
  RootObj Sup;
tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A* fSurface;
};
typedef N_CDECL_PTR(void, tyProc_fj5zQw9asqT9cpDX9bwFTdIYQ) (tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A* surface);
typedef N_CDECL_PTR(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A*, tyProc_oTI7Gk9b9bgxQuZMQRpglP1w) (NCSTRING file);
struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ {
int x;
int y;
int w;
int h;
};
struct tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A {
NU32 flags;
tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q* format;
int w;
int h;
int pitch;
void* pixels;
void* userdata;
int locked;
void* lock_data;
tyObject_Rect_qiXweduDJk1iLE5aHysNdQ clip_rect;
void* map;
int refcount;
};
typedef NU8 tyArray_bN9bddWn8oiNSHn2MqEJSZQ[2];
struct tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q {
NU32 format;
tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette;
NU8 BitsPerPixel;
NU8 BytesPerPixel;
tyArray_bN9bddWn8oiNSHn2MqEJSZQ padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int refcount;
tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q* next;
};
typedef N_CDECL_PTR(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A*, tyProc_ov47cSW7te2Rk6vJnziJZA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, int freesrc);
typedef N_CDECL_PTR(int, tyProc_D19cH77xVwhL04Bkj8wjreA) (tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A* surface, tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette);
typedef N_CDECL_PTR(void*, tyProc_WCSbnyfpsjNzpCETKXisyQ) (void* renderer, tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A* surface);
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef N_CDECL_PTR(NI64, tyProc_p9adtE9afP6ObPoIZKMFxiAA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context);
typedef N_CDECL_PTR(NI64, tyProc_tpgoL9bwK9bkzBn2qq83QKag) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context, NI64 offset, int whence);
typedef N_CDECL_PTR(size_t, tyProc_vPnfrHDX45Ib7P40WFtTvg) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context, void* p, size_t size, size_t maxnum);
typedef N_CDECL_PTR(int, tyProc_pcLKO4pFPDvuTZj9c0HX5oA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context);
struct tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ {
void* fileNameRef;
void* inputStreamRef;
void* readableByteChannelRef;
void* readMethod;
void* assetFileDescriptorRef;
long position;
long size;
long offset;
int fd;
};
struct tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ {
void* data;
size_t size;
size_t left;
};
struct tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA {
NIM_BOOL append;
void* h;
tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ buffer;
};
struct tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg {
NIM_BOOL autoclose;
FILE* fp;
};
struct tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q {
NU8* base;
NU8* here;
NU8* stop;
};
struct tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA {
void* data1;
void* data2;
};
union tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ {
tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ androidio;
tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA windowsio;
tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg stdio;
tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q mem;
tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA unknown;
};
struct tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA {
tyProc_p9adtE9afP6ObPoIZKMFxiAA size;
tyProc_tpgoL9bwK9bkzBn2qq83QKag seek;
tyProc_vPnfrHDX45Ib7P40WFtTvg read;
tyProc_vPnfrHDX45Ib7P40WFtTvg write;
tyProc_pcLKO4pFPDvuTZj9c0HX5oA close;
NU32 kind;
tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ mem;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, free_XPSpdGrbzFLrRNrh4eaJuA)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, init_NWdB9au5KthgJE4agI9amyAA)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg** palette, NI ncolors);
N_LIB_PRIVATE N_NIMCALL(int, toCint_yAPwf7d9aO5za0vgIa7yl8g)(NI x);
N_LIB_PRIVATE N_NIMCALL(NI, ncolors_2IKulTeKaOuGcJ7Dc3pJTQ)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette);
N_LIB_PRIVATE N_NIMCALL(tyObject_Color_YizDHyEvJtgQk2fn8KdZUA, X5BX5D__UNdfFgEYbNrVfxD9aY5UoVg)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette, NI i);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__syZw77tfvlbUcAM2X9aa9aaA)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette, NI i, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA* colors, NI colorsLen_0);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__Lk179bE9c6s9axBaKp9aDuaJ8w)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette, NI i, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color);
N_LIB_PRIVATE N_NIMCALL(void, free_M1hGt9aeNFb7o9cj9aZ54ctxA)(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* image);
N_LIB_PRIVATE N_NIMCALL(void, init_M1hGt9aeNFb7o9cj9aZ54ctxA_2)(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* image);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_RNOc9cgPL5BS9cfU3Lb6agqw)(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* image, NimStringDesc* file);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_vMPLrEwYOLpw16tBPOEN4g)(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* image, tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NIM_BOOL freeSrc);
N_LIB_PRIVATE N_NIMCALL(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA*, newIndexedImage_nqJW9cdSjrjwFWhWNW9akysQ)(void);
static N_NIMCALL(void, Marker_tyRef_u12PFMspomW7u9c3dd0pjrw)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA*, newIndexedImage_VoJlItJuDxcPSPXof39cDXA)(NimStringDesc* file);
N_LIB_PRIVATE N_NIMCALL(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA*, newIndexedImage_EU812G0X4NGBL0gmdQLviQ)(tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NIM_BOOL freeSrc);
static N_INLINE(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg*, palette_4flvG9cyxolGL89caH106Dcwindexedimage)(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* image);
static N_INLINE(void, paletteeq__dQem5wSC4dTtitn41zVDBwindexedimage)(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* image, tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette);
static N_INLINE(void*, render_NgIqiLav9cgGTJS8wkEaHuQindexedimage)(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* image);
extern tyProc_3d8ZGFdX9cH9cDT9a42QwE9cvg Dl_150911_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyProc_Anj9as7d5YZdqOLVOsW9cq9bQ Dl_150893_;
extern TNimType NTI_z58cIdR0vOibqJ0QwYvB3Q_;
extern TNimType NTI_b0IIwghFQBADkB2c86kXQA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyProc_wotRTUnRZK0xNH5VjeE8Ng Dl_150903_;
extern tyProc_DusjKySyJW30WdV9bsteVxw Dl_154881_;
extern tyProc_09bvyvHFtWbkzL5AHgf0bKw Dl_147926_;
extern tyProc_fj5zQw9asqT9cpDX9bwFTdIYQ Dl_151078_;
extern tyProc_oTI7Gk9b9bgxQuZMQRpglP1w Dl_157041_;
extern tyProc_ov47cSW7te2Rk6vJnziJZA Dl_157044_;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_QxsZ9aTjc9cSTAnl6eM3FppA_;
extern TNimType NTI_upQLnkUdjbWZ8w9ag9btZFYw_;
TNimType NTI_u12PFMspomW7u9c3dd0pjrw_;
extern tyProc_D19cH77xVwhL04Bkj8wjreA Dl_151081_;
extern tyProc_WCSbnyfpsjNzpCETKXisyQ Dl_155145_;
extern void* renderer_M5l6pK6T79aB5LqtC0dmeOg;
STRING_LITERAL(TM_mqFKzWI89bYN3imy5BYLrZw_2, "Palette color index ", 20);
STRING_LITERAL(TM_mqFKzWI89bYN3imy5BYLrZw_3, " is out of bounds.", 18);
STRING_LITERAL(TM_mqFKzWI89bYN3imy5BYLrZw_6, "Palette color index range ", 26);
STRING_LITERAL(TM_mqFKzWI89bYN3imy5BYLrZw_7, "..", 2);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, free_XPSpdGrbzFLrRNrh4eaJuA)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette) {
	nimfr_("free", "indexedimage.nim");
	nimln_(44, "indexedimage.nim");
	{
		if (!!((palette == NIM_NIL))) goto LA3_;
		nimln_(45, "indexedimage.nim");
		Dl_150911_(palette);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, init_NWdB9au5KthgJE4agI9amyAA)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg** palette, NI ncolors) {
	int T1_;
	nimfr_("init", "indexedimage.nim");
	nimln_(49, "indexedimage.nim");
	free_XPSpdGrbzFLrRNrh4eaJuA((*palette));
	nimln_(50, "indexedimage.nim");
	T1_ = (int)0;
	T1_ = toCint_yAPwf7d9aO5za0vgIa7yl8g(ncolors);
	(*palette) = Dl_150893_(T1_);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, ncolors_2IKulTeKaOuGcJ7Dc3pJTQ)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette) {
	NI result;
	nimfr_("ncolors", "indexedimage.nim");
	result = (NI)0;
	nimln_(54, "indexedimage.nim");
	nimln_(56, "indexedimage.nim");
	{
		if (!(palette == NIM_NIL)) goto LA3_;
		result = ((NI) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		result = ((NI) ((*palette).ncolors));
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Color_YizDHyEvJtgQk2fn8KdZUA, X5BX5D__UNdfFgEYbNrVfxD9aY5UoVg)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette, NI i) {
	tyObject_Color_YizDHyEvJtgQk2fn8KdZUA result;
	NI TM_mqFKzWI89bYN3imy5BYLrZw_4;
	nimfr_("[]", "indexedimage.nim");
{	memset((void*)(&result), 0, sizeof(result));
	nimln_(65, "indexedimage.nim");
	{
		NIM_BOOL T3_;
		tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
		NimStringDesc* T7_;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = (i < ((NI) 0));
		if (T3_) goto LA4_;
		T3_ = (((NI) ((*palette).ncolors)) <= i);
		LA4_: ;
		if (!T3_) goto LA5_;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
		(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
		nimln_(67, "indexedimage.nim");
		T7_ = (NimStringDesc*)0;
		T8_ = (NimStringDesc*)0;
		T8_ = nimIntToStr(i);
		T7_ = rawNewString(T8_->Sup.len + 38);
appendString(T7_, ((NimStringDesc*) &TM_mqFKzWI89bYN3imy5BYLrZw_2));
appendString(T7_, T8_);
appendString(T7_, ((NimStringDesc*) &TM_mqFKzWI89bYN3imy5BYLrZw_3));
		asgnRefNoCycle((void**) (&(*e).Sup.message), T7_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(66, "indexedimage.nim");
		raiseException((Exception*)e, "IndexError");
	}
	LA5_: ;
	nimln_(69, "indexedimage.nim");
	nimln_(59, "stdinc.nim");
	nimln_(69, "indexedimage.nim");
	nimln_(59, "stdinc.nim");
	TM_mqFKzWI89bYN3imy5BYLrZw_4 = mulInt(i, ((NI)sizeof(tyObject_Color_YizDHyEvJtgQk2fn8KdZUA)));
	result = (*((tyObject_Color_YizDHyEvJtgQk2fn8KdZUA*) ((NI)((NU64)(((NI) (ptrdiff_t) ((*palette).colors))) + (NU64)((NI)(TM_mqFKzWI89bYN3imy5BYLrZw_4))))));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__syZw77tfvlbUcAM2X9aa9aaA)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette, NI i, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA* colors, NI colorsLen_0) {
	nimfr_("[]=", "indexedimage.nim");
	nimln_(75, "indexedimage.nim");
	{
		NIM_BOOL T3_;
		NI TM_mqFKzWI89bYN3imy5BYLrZw_5;
		tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
		NimStringDesc* T7_;
		NimStringDesc* T8_;
		NI TM_mqFKzWI89bYN3imy5BYLrZw_8;
		NI TM_mqFKzWI89bYN3imy5BYLrZw_9;
		NimStringDesc* T9_;
		T3_ = (NIM_BOOL)0;
		T3_ = (i < ((NI) 0));
		if (T3_) goto LA4_;
		TM_mqFKzWI89bYN3imy5BYLrZw_5 = addInt(i, colorsLen_0);
		T3_ = (((NI) ((*palette).ncolors)) < (NI)(TM_mqFKzWI89bYN3imy5BYLrZw_5));
		LA4_: ;
		if (!T3_) goto LA5_;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
		(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
		nimln_(77, "indexedimage.nim");
		T7_ = (NimStringDesc*)0;
		T8_ = (NimStringDesc*)0;
		T8_ = nimIntToStr(i);
		TM_mqFKzWI89bYN3imy5BYLrZw_8 = addInt(i, colorsLen_0);
		TM_mqFKzWI89bYN3imy5BYLrZw_9 = subInt((NI)(TM_mqFKzWI89bYN3imy5BYLrZw_8), ((NI) 1));
		T9_ = (NimStringDesc*)0;
		T9_ = nimIntToStr((NI)(TM_mqFKzWI89bYN3imy5BYLrZw_9));
		T7_ = rawNewString(T8_->Sup.len + T9_->Sup.len + 46);
appendString(T7_, ((NimStringDesc*) &TM_mqFKzWI89bYN3imy5BYLrZw_6));
appendString(T7_, T8_);
appendString(T7_, ((NimStringDesc*) &TM_mqFKzWI89bYN3imy5BYLrZw_7));
appendString(T7_, T9_);
appendString(T7_, ((NimStringDesc*) &TM_mqFKzWI89bYN3imy5BYLrZw_3));
		asgnRefNoCycle((void**) (&(*e).Sup.message), T7_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(76, "indexedimage.nim");
		raiseException((Exception*)e, "IndexError");
	}
	LA5_: ;
	nimln_(79, "indexedimage.nim");
	{
		int T12_;
		int T13_;
		int T14_;
		NCSTRING T17_;
		nimln_(398, "system.nim");
		nimln_(79, "indexedimage.nim");
		if ((NU)(((NI) 0)) >= (NU)(colorsLen_0)) raiseIndexError();
		nimln_(80, "indexedimage.nim");
		T12_ = (int)0;
		T12_ = toCint_yAPwf7d9aO5za0vgIa7yl8g(i);
		T13_ = (int)0;
		T13_ = toCint_yAPwf7d9aO5za0vgIa7yl8g(colorsLen_0);
		T14_ = (int)0;
		T14_ = Dl_150903_(palette, ((tyObject_Color_YizDHyEvJtgQk2fn8KdZUA*) ((&colors[((NI) 0)]))), T12_, T13_);
		if (!!((T14_ == ((NI32) 0)))) goto LA15_;
		nimln_(81, "indexedimage.nim");
		nimln_(83, "indexedimage.nim");
		T17_ = (NCSTRING)0;
		T17_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Error on setting palette colors: %s", T17_);
	}
	LA15_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__Lk179bE9c6s9axBaKp9aDuaJ8w)(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette, NI i, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color) {
	tyArray_cXelO9ahiHJ8br39bNGtKXJw T9_;
	nimfr_("[]=", "indexedimage.nim");
	nimln_(89, "indexedimage.nim");
	{
		NIM_BOOL T3_;
		tyObject_IndexError_b0IIwghFQBADkB2c86kXQA* e;
		NimStringDesc* T7_;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = (i < ((NI) 0));
		if (T3_) goto LA4_;
		T3_ = (((NI) ((*palette).ncolors)) <= i);
		LA4_: ;
		if (!T3_) goto LA5_;
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_IndexError_b0IIwghFQBADkB2c86kXQA*) newObj((&NTI_z58cIdR0vOibqJ0QwYvB3Q_), sizeof(tyObject_IndexError_b0IIwghFQBADkB2c86kXQA));
		(*e).Sup.Sup.m_type = (&NTI_b0IIwghFQBADkB2c86kXQA_);
		nimln_(91, "indexedimage.nim");
		T7_ = (NimStringDesc*)0;
		T8_ = (NimStringDesc*)0;
		T8_ = nimIntToStr(i);
		T7_ = rawNewString(T8_->Sup.len + 38);
appendString(T7_, ((NimStringDesc*) &TM_mqFKzWI89bYN3imy5BYLrZw_2));
appendString(T7_, T8_);
appendString(T7_, ((NimStringDesc*) &TM_mqFKzWI89bYN3imy5BYLrZw_3));
		asgnRefNoCycle((void**) (&(*e).Sup.message), T7_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(90, "indexedimage.nim");
		raiseException((Exception*)e, "IndexError");
	}
	LA5_: ;
	nimln_(92, "indexedimage.nim");
	T9_[0] = color;
	X5BX5Deq__syZw77tfvlbUcAM2X9aa9aaA(palette, i, T9_, 1);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, free_M1hGt9aeNFb7o9cj9aZ54ctxA)(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* image) {
	nimfr_("free", "indexedimage.nim");
	nimln_(100, "indexedimage.nim");
	{
		if (!!(((*image).fSurface == NIM_NIL))) goto LA3_;
		nimln_(101, "indexedimage.nim");
		Dl_151078_((*image).fSurface);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, init_M1hGt9aeNFb7o9cj9aZ54ctxA_2)(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* image) {
	nimfr_("init", "indexedimage.nim");
	nimln_(105, "indexedimage.nim");
	free_M1hGt9aeNFb7o9cj9aZ54ctxA(image);
	nimln_(106, "indexedimage.nim");
	(*image).fSurface = NIM_NIL;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_RNOc9cgPL5BS9cfU3Lb6agqw)(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* image, NimStringDesc* file) {
	NIM_BOOL result;
	nimfr_("load", "indexedimage.nim");
{	result = (NIM_BOOL)0;
	nimln_(113, "indexedimage.nim");
	result = NIM_TRUE;
	nimln_(114, "indexedimage.nim");
	free_M1hGt9aeNFb7o9cj9aZ54ctxA(image);
	nimln_(116, "indexedimage.nim");
	(*image).fSurface = Dl_157041_(file->data);
	nimln_(117, "indexedimage.nim");
	{
		NCSTRING T5_;
		if (!((*image).fSurface == NIM_NIL)) goto LA3_;
		nimln_(118, "indexedimage.nim");
		nimln_(120, "indexedimage.nim");
		T5_ = (NCSTRING)0;
		T5_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t load indexed image %s: %s", file->data, T5_);
		nimln_(121, "indexedimage.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(123, "indexedimage.nim");
	{
		if (!((*(*(*image).fSurface).format).palette == NIM_NIL)) goto LA8_;
		nimln_(124, "indexedimage.nim");
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "No palette found in image %s", file->data);
		nimln_(127, "indexedimage.nim");
		Dl_151078_((*image).fSurface);
		nimln_(128, "indexedimage.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA8_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_vMPLrEwYOLpw16tBPOEN4g)(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* image, tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NIM_BOOL freeSrc) {
	NIM_BOOL result;
	nimfr_("load", "indexedimage.nim");
{	result = (NIM_BOOL)0;
	nimln_(135, "indexedimage.nim");
	result = NIM_TRUE;
	nimln_(136, "indexedimage.nim");
	free_M1hGt9aeNFb7o9cj9aZ54ctxA(image);
	nimln_(138, "indexedimage.nim");
	(*image).fSurface = Dl_157044_(src, ((int) (freeSrc)));
	nimln_(139, "indexedimage.nim");
	{
		NCSTRING T5_;
		if (!((*image).fSurface == NIM_NIL)) goto LA3_;
		nimln_(140, "indexedimage.nim");
		nimln_(142, "indexedimage.nim");
		T5_ = (NCSTRING)0;
		T5_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t load indexed image RW: %s", T5_);
		nimln_(143, "indexedimage.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(145, "indexedimage.nim");
	{
		if (!((*(*(*image).fSurface).format).palette == NIM_NIL)) goto LA8_;
		nimln_(146, "indexedimage.nim");
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "No palette found in image RW");
		nimln_(148, "indexedimage.nim");
		Dl_151078_((*image).fSurface);
		nimln_(149, "indexedimage.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA8_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_u12PFMspomW7u9c3dd0pjrw)(void* p, NI op) {
	tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* a;
	a = (tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA*)p;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA*, newIndexedImage_nqJW9cdSjrjwFWhWNW9akysQ)(void) {
	tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* result;
	nimfr_("newIndexedImage", "indexedimage.nim");
	result = (tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA*)0;
	nimln_(153, "indexedimage.nim");
	result = (tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA*) newObj((&NTI_u12PFMspomW7u9c3dd0pjrw_), sizeof(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA));
	(*result).Sup.m_type = (&NTI_QxsZ9aTjc9cSTAnl6eM3FppA_);
	nimln_(154, "indexedimage.nim");
	init_M1hGt9aeNFb7o9cj9aZ54ctxA_2(result);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA*, newIndexedImage_VoJlItJuDxcPSPXof39cDXA)(NimStringDesc* file) {
	tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* result;
	NIM_BOOL T1_;
	nimfr_("newIndexedImage", "indexedimage.nim");
	result = (tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA*)0;
	nimln_(160, "indexedimage.nim");
	result = newIndexedImage_nqJW9cdSjrjwFWhWNW9akysQ();
	nimln_(161, "indexedimage.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = load_RNOc9cgPL5BS9cfU3Lb6agqw(result, file);
	T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA*, newIndexedImage_EU812G0X4NGBL0gmdQLviQ)(tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NIM_BOOL freeSrc) {
	tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* result;
	NIM_BOOL T1_;
	nimfr_("newIndexedImage", "indexedimage.nim");
	result = (tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA*)0;
	nimln_(167, "indexedimage.nim");
	result = newIndexedImage_nqJW9cdSjrjwFWhWNW9akysQ();
	nimln_(168, "indexedimage.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = load_vMPLrEwYOLpw16tBPOEN4g(result, src, freeSrc);
	T1_;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg*, palette_4flvG9cyxolGL89caH106Dcwindexedimage)(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* image) {
	tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* result;
	nimfr_("palette", "indexedimage.nim");
	result = (tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg*)0;
	nimln_(172, "indexedimage.nim");
	result = (*(*(*image).fSurface).format).palette;
	popFrame();
	return result;
}

static N_INLINE(void, paletteeq__dQem5wSC4dTtitn41zVDBwindexedimage)(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* image, tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette) {
	nimfr_("palette=", "indexedimage.nim");
	nimln_(180, "indexedimage.nim");
	{
		int T3_;
		NCSTRING T6_;
		nimln_(398, "system.nim");
		nimln_(180, "indexedimage.nim");
		T3_ = (int)0;
		T3_ = Dl_151081_((*image).fSurface, palette);
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		nimln_(181, "indexedimage.nim");
		nimln_(183, "indexedimage.nim");
		T6_ = (NCSTRING)0;
		T6_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t set the new palette: %s", T6_);
	}
	LA4_: ;
	popFrame();
}

static N_INLINE(void*, render_NgIqiLav9cgGTJS8wkEaHuQindexedimage)(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA* image) {
	void* result;
	nimfr_("render", "indexedimage.nim");
	result = (void*)0;
	nimln_(187, "indexedimage.nim");
	nimln_(189, "indexedimage.nim");
	result = Dl_155145_(renderer_M5l6pK6T79aB5LqtC0dmeOg, (*image).fSurface);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, nimgame2_indexedimageInit000)(void) {
	nimfr_("indexedimage", "indexedimage.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimgame2_indexedimageDatInit000)(void) {
static TNimNode TM_mqFKzWI89bYN3imy5BYLrZw_0[1];
NTI_QxsZ9aTjc9cSTAnl6eM3FppA_.size = sizeof(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA);
NTI_QxsZ9aTjc9cSTAnl6eM3FppA_.kind = 17;
NTI_QxsZ9aTjc9cSTAnl6eM3FppA_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_QxsZ9aTjc9cSTAnl6eM3FppA_.flags = 1;
TM_mqFKzWI89bYN3imy5BYLrZw_0[0].kind = 1;
TM_mqFKzWI89bYN3imy5BYLrZw_0[0].offset = offsetof(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA, fSurface);
TM_mqFKzWI89bYN3imy5BYLrZw_0[0].typ = (&NTI_upQLnkUdjbWZ8w9ag9btZFYw_);
TM_mqFKzWI89bYN3imy5BYLrZw_0[0].name = "fSurface";
NTI_QxsZ9aTjc9cSTAnl6eM3FppA_.node = &TM_mqFKzWI89bYN3imy5BYLrZw_0[0];
NTI_u12PFMspomW7u9c3dd0pjrw_.size = sizeof(tyObject_IndexedImagecolonObjectType__QxsZ9aTjc9cSTAnl6eM3FppA*);
NTI_u12PFMspomW7u9c3dd0pjrw_.kind = 22;
NTI_u12PFMspomW7u9c3dd0pjrw_.base = (&NTI_QxsZ9aTjc9cSTAnl6eM3FppA_);
NTI_u12PFMspomW7u9c3dd0pjrw_.marker = Marker_tyRef_u12PFMspomW7u9c3dd0pjrw;
(&NTI_u12PFMspomW7u9c3dd0pjrw_)->finalizer = (void*)free_M1hGt9aeNFb7o9cj9aZ54ctxA;
}

