/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\Users\Alterna\Documents\nim-0.18.0\lib -o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\nimgame2_audio.o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\nimgame2_audio.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA;
typedef struct tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ;
typedef struct tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA;
typedef struct tySequence_cIlT2tiEqOuMg0NQ1IqASw tySequence_cIlT2tiEqOuMg0NQ1IqASw;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef union tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ;
typedef struct tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ;
typedef struct tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA;
typedef struct tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ;
typedef struct tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg;
typedef struct tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q;
typedef struct tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA {
  RootObj Sup;
tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA* fChunk;
NI fChannel;
};
typedef N_CDECL_PTR(int, tyProc_4hSZquf3VZZvlELaYshEWg) (int channel);
typedef N_CDECL_PTR(void, tyProc_br1oh11YVvfM9avejTxxNpQ) (tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA* chunk);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA*, tyProc_aBWCOlwWWonQvhPQizx8Ug) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, int freesrc);
typedef N_CDECL_PTR(tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA*, tyProc_Q4hOU9as18Fp2AN1WS9af3lw) (NCSTRING file, NCSTRING mode);
typedef NI32 tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw;
typedef N_CDECL_PTR(void, tyProc_DusjKySyJW30WdV9bsteVxw) (tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw category, NCSTRING fmt, ...);
typedef N_CDECL_PTR(NCSTRING, tyProc_09bvyvHFtWbkzL5AHgf0bKw) (void);
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(int, tyProc_yyBtDTXzQO2Lna7JemGx2g) (int channel, tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA* chunk, int loops, int ticks);
typedef N_CDECL_PTR(void, tyProc_NuisSWKwsQg36a0Egqo6Qw) (int channel);
typedef N_CDECL_PTR(int, tyProc_MGiOj2b5S2DqV5jgE4sbMw) (tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA* chunk, int volume);
typedef N_CDECL_PTR(int, tyProc_7VGp0OOrDVpzpiikBAb50A) (int channel, NU8 distance);
typedef N_CDECL_PTR(int, tyProc_IQYjW9c4S3CibO23lDxXOxw) (int channel, NU8 left, NU8 right);
typedef N_CDECL_PTR(int, tyProc_7p9b9aTX47z9coV9cdAsiN46aQ) (int channel, NI16 angle, NU8 distance);
typedef N_CDECL_PTR(int, tyProc_6DzmQdLg31OmeFUXpotB2g) (int channel, int volume);
struct tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ {
  RootObj Sup;
void* fMusic;
};
typedef N_CDECL_PTR(void, tyProc_32w2ZypAyMWuajvi2Jt79cg) (void* music);
typedef N_CDECL_PTR(void*, tyProc_YDKrw1adv61oVQkQhbYyaA) (NCSTRING file);
typedef N_CDECL_PTR(void*, tyProc_TH669aE9aoWAsrXM41jGg5rw) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, int freesrc);
typedef N_CDECL_PTR(int, tyProc_AbsnR49cK1X9a2Wblez5VQWQ) (void* music, int loops);
typedef N_CDECL_PTR(int, tyProc_cez8YhJI0vaCUcjGg6z4zA) (void);
typedef N_CDECL_PTR(void, tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(int, tyProc_zHmgYCIVwMsNhQMzkHVoMQ) (double position);
struct tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA {
  RootObj Sup;
tySequence_cIlT2tiEqOuMg0NQ1IqASw* list;
NI fIndex;
NIM_BOOL fFinished;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NI tyArray_GAcaPw08Gj9cXYhAaMMr9cfw[1];
typedef N_CDECL_PTR(void, tyProc_DB9cnq6SiUb8XjfAfm1BAtA) (tyProc_ln4kdL5W9bbX4a1xl8nnVXQ music_finished);
struct tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA {
int allocated;
NU8* abuf;
NU32 alen;
NU8 volume;
};
typedef N_CDECL_PTR(NI64, tyProc_p9adtE9afP6ObPoIZKMFxiAA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context);
typedef N_CDECL_PTR(NI64, tyProc_tpgoL9bwK9bkzBn2qq83QKag) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context, NI64 offset, int whence);
typedef N_CDECL_PTR(size_t, tyProc_vPnfrHDX45Ib7P40WFtTvg) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context, void* p, size_t size, size_t maxnum);
typedef N_CDECL_PTR(int, tyProc_pcLKO4pFPDvuTZj9c0HX5oA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context);
struct tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ {
void* fileNameRef;
void* inputStreamRef;
void* readableByteChannelRef;
void* readMethod;
void* assetFileDescriptorRef;
long position;
long size;
long offset;
int fd;
};
struct tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ {
void* data;
size_t size;
size_t left;
};
struct tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA {
NIM_BOOL append;
void* h;
tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ buffer;
};
struct tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg {
NIM_BOOL autoclose;
FILE* fp;
};
struct tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q {
NU8* base;
NU8* here;
NU8* stop;
};
struct tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA {
void* data1;
void* data2;
};
union tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ {
tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ androidio;
tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA windowsio;
tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg stdio;
tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q mem;
tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA unknown;
};
struct tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA {
tyProc_p9adtE9afP6ObPoIZKMFxiAA size;
tyProc_tpgoL9bwK9bkzBn2qq83QKag seek;
tyProc_vPnfrHDX45Ib7P40WFtTvg read;
tyProc_vPnfrHDX45Ib7P40WFtTvg write;
tyProc_pcLKO4pFPDvuTZj9c0HX5oA close;
NU32 kind;
tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ mem;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_cIlT2tiEqOuMg0NQ1IqASw {
  TGenericSeq Sup;
  tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ* data[SEQ_DECL_SIZE];
};
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, free_hD9a9ai9bEuxjtkfYz0Pe9bBsg)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound);
N_LIB_PRIVATE N_NIMCALL(int, toCint_yAPwf7d9aO5za0vgIa7yl8g)(NI x);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_Yq6S7Ut1q0TYAwJihuPA8A)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound, NimStringDesc* file);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_6TuWZC8Y6fluekWEEKGskg)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound, tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NIM_BOOL freeSrc);
N_LIB_PRIVATE N_NIMCALL(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA*, newSound_Lr4q09b9amAu7mQfsOmsUltg)(NimStringDesc* file);
static N_NIMCALL(void, Marker_tyRef_e9apj1prYTCFEje3gK1rjQw)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA*, newSound_ZzXvzn3ZfCTu6QBDW7NJTA)(tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NIM_BOOL freeSrc);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, available_tdsri5IsxRTTtaBV4PL03g)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, playing_tdsri5IsxRTTtaBV4PL03g_2)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound);
N_LIB_PRIVATE N_NIMCALL(void, stop_hD9a9ai9bEuxjtkfYz0Pe9bBsg_2)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound);
N_LIB_PRIVATE N_NIMCALL(NI, play_xcMNPMPQQBqFvemqYGQCog)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound, NI loops);
N_LIB_PRIVATE N_NIMCALL(NI, channel_1jzAIJxnneZvWqVPG8O4hg)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, paused_tdsri5IsxRTTtaBV4PL03g_3)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound);
N_LIB_PRIVATE N_NIMCALL(void, pause_hD9a9ai9bEuxjtkfYz0Pe9bBsg_3)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound);
N_LIB_PRIVATE N_NIMCALL(void, resume_hD9a9ai9bEuxjtkfYz0Pe9bBsg_4)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound);
static N_INLINE(NI, volume_rPYENh3usOjojQmWP3iO0Aaudio)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_LIB_PRIVATE N_NIMCALL(NI, normalizeVolume_s6LQNTS0LUGhO9bHRZqRQFg)(NI val);
static N_INLINE(void, volumeeq__CaYICGSMf5Ly0PXHh1k4DAaudio)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound, NI val);
static N_INLINE(void, setDistance_WLA6pHUyKvaO9bLPfcAJaEwaudio)(NI channel, NI distance);
static N_INLINE(void, setPanning_YvFkIOUrQT7J3HvBdt069cAaudio)(NI channel, NI left, NI right);
static N_INLINE(void, setPosition_VocJGfjEh3Qsoev5MPNovAaudio)(NI channel, NF angle, NI distance);
static N_INLINE(void, soundStop_YyzWTSr9cdBKzXtCIewcHtQaudio)(void);
static N_INLINE(NI, soundPlayingNum_JTJHmTUXGVkIEk2pCkNXoQaudio)(void);
static N_INLINE(NI, soundPausedNum_JTJHmTUXGVkIEk2pCkNXoQ_2audio)(void);
static N_INLINE(void, soundPause_YyzWTSr9cdBKzXtCIewcHtQ_2audio)(void);
static N_INLINE(void, soundResume_YyzWTSr9cdBKzXtCIewcHtQ_3audio)(void);
static N_INLINE(NI, getSoundVolume_yyCpSdZK59ct104bsA7VIFQaudio)(void);
static N_INLINE(void, setSoundVolume_jDnW5lEBdhvoSrw9chZVAeQaudio)(NI val);
N_LIB_PRIVATE N_NIMCALL(void, free_q1GOEG8ePj0WoPsvq2U89aQ)(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ* music);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_MSdpeaBk3Sp6QWo9bGOZl3g)(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ* music, NimStringDesc* file);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_e8kbOdzLDRQnldo65KXc8Q)(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ* music, tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NIM_BOOL freeSrc);
N_LIB_PRIVATE N_NIMCALL(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ*, newMusic_kkaB9cxEgsD31GhzLyVeFEQ)(NimStringDesc* file);
static N_NIMCALL(void, Marker_tyRef_dUpvtO9besQUIGBspvDW48w)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ*, newMusic_gwZRzVNW7ut9bua7F4u1Rsw)(tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NIM_BOOL freeSrc);
static N_INLINE(NIM_BOOL, available_GEM9a3Di0GEW9cex1YsgMzggaudio)(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ* music);
N_LIB_PRIVATE N_NIMCALL(void, play_su9aQq1H6WaNmgajnNdZxgw)(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ* music, NI loops);
static N_INLINE(NIM_BOOL, musicPaused_kmKHfshD3RNnIaIVdbPmmwaudio)(void);
static N_INLINE(void, musicPause_YyzWTSr9cdBKzXtCIewcHtQ_4audio)(void);
static N_INLINE(void, musicResume_YyzWTSr9cdBKzXtCIewcHtQ_5audio)(void);
static N_INLINE(void, musicRewind_YyzWTSr9cdBKzXtCIewcHtQ_6audio)(void);
static N_INLINE(NIM_BOOL, musicPlaying_kmKHfshD3RNnIaIVdbPmmw_2audio)(void);
static N_INLINE(void, musicStop_YyzWTSr9cdBKzXtCIewcHtQ_7audio)(void);
static N_INLINE(void, musicPosition_7C5pzenTcF0E57TbZQjefgaudio)(NF val);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_cIlT2tiEqOuMg0NQ1IqASw)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_cVxn2iwI9aZh5MPcCZPNprQ)(void* p, NI op);
static N_NIMCALL(void, TM_39bXrYa3vA9aMKLBuvGNJgUA_4)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_CDECL(void, finished_GPWLpLUP82js9a8c55dxNwg)(void);
N_LIB_PRIVATE N_NIMCALL(void, init_gVEFyHMJP4jNWhC2yoGrrw)(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA* pl);
static N_INLINE(void, nimGCunrefRC1)(void* p);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA*, newPlaylist_fkV4CBjqZi0z1evlOiJbkA)(void);
static N_INLINE(NI, index_aS3bkUl9aO89b1v0vk5ZuNVgaudio)(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA* pl);
N_LIB_PRIVATE N_NIMCALL(NI, play_g2yFfzwnTz7Ev5OKztuJxw)(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA* pl, NI index);
static N_INLINE(NI, rand_3MNNZB2vD1hQTqPc9bVQ9b4gaudio)(NI max, NI* exclude, NI excludeLen_0);
N_LIB_PRIVATE N_NIMCALL(NI, rand_bXFhlVh7ZFz3I1g4MkLBnw)(NI max, tySequence_qwqHTkRvwhrRyENtudHQ7g* exclude);
N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, at__7KXK9aqsdE0ndrhB7KxewvA)(NI* a, NI aLen_0);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(void, stop_gVEFyHMJP4jNWhC2yoGrrw_2)(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA* pl);
N_LIB_PRIVATE N_NIMCALL(void, update_MlDddNjBpRGSlwmH4NptYg)(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA* pl);
static N_INLINE(NIM_BOOL, contains_P6sCVNQ9cdTFh3rtVXMEtxgutils)(NI* a, NI aLen_0, NI item);
static N_INLINE(NI, find_b2asjP2y9cPDPwOLa1pD5PAutils)(NI* a, NI aLen_0, NI item);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
extern tyProc_4hSZquf3VZZvlELaYshEWg Dl_159929_;
extern tyProc_4hSZquf3VZZvlELaYshEWg Dl_159881_;
extern tyProc_br1oh11YVvfM9avejTxxNpQ Dl_159511_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyProc_aBWCOlwWWonQvhPQizx8Ug Dl_159459_;
extern tyProc_Q4hOU9as18Fp2AN1WS9af3lw Dl_147304_;
extern tyProc_DusjKySyJW30WdV9bsteVxw Dl_154881_;
extern tyProc_09bvyvHFtWbkzL5AHgf0bKw Dl_147926_;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_JCPxIEGn03VSW9aKyV6FvQA_;
extern TNimType NTI_fk5c7FchYduFB24e7g9aUsA_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_e9apj1prYTCFEje3gK1rjQw_;
extern tyProc_yyBtDTXzQO2Lna7JemGx2g Dl_159829_;
extern tyProc_4hSZquf3VZZvlELaYshEWg Dl_159915_;
extern tyProc_NuisSWKwsQg36a0Egqo6Qw Dl_159909_;
extern tyProc_NuisSWKwsQg36a0Egqo6Qw Dl_159912_;
extern tyProc_MGiOj2b5S2DqV5jgE4sbMw Dl_159874_;
extern tyProc_7VGp0OOrDVpzpiikBAb50A Dl_159613_;
extern tyProc_IQYjW9c4S3CibO23lDxXOxw Dl_159603_;
extern tyProc_7p9b9aTX47z9coV9cdAsiN46aQ Dl_159608_;
extern tyProc_6DzmQdLg31OmeFUXpotB2g Dl_159870_;
extern tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_159514_;
extern tyProc_YDKrw1adv61oVQkQhbYyaA Dl_159475_;
extern tyProc_TH669aE9aoWAsrXM41jGg5rw Dl_159478_;
TNimType NTI_UDy9bnueEy9bjI49cgSUMhdzQ_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
TNimType NTI_dUpvtO9besQUIGBspvDW48w_;
extern tyProc_AbsnR49cK1X9a2Wblez5VQWQ Dl_159841_;
extern tyProc_cez8YhJI0vaCUcjGg6z4zA Dl_159924_;
extern tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_159918_;
extern tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_159920_;
extern tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_159922_;
extern tyProc_cez8YhJI0vaCUcjGg6z4zA Dl_159932_;
extern tyProc_cez8YhJI0vaCUcjGg6z4zA Dl_159887_;
extern tyProc_zHmgYCIVwMsNhQMzkHVoMQ Dl_159926_;
tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA* playlist_gna9cd1d772Ka9aPCqMpHOYQ;
TNimType NTI_hH9a3qlZLWG9bOTrtP9bUhWSA_;
TNimType NTI_cIlT2tiEqOuMg0NQ1IqASw_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_cVxn2iwI9aZh5MPcCZPNprQ_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyProc_DB9cnq6SiUb8XjfAfm1BAtA Dl_159553_;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, free_hD9a9ai9bEuxjtkfYz0Pe9bBsg)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound) {
	nimfr_("free", "audio.nim");
	nimln_(52, "audio.nim");
	{
		if (!!(((*sound).fChunk == NIM_NIL))) goto LA3_;
		nimln_(54, "audio.nim");
		{
			if (!(((NI) -1) < (*sound).fChannel)) goto LA7_;
			nimln_(55, "audio.nim");
			{
				int T11_;
				int T12_;
				int T15_;
				int T16_;
				T11_ = (int)0;
				T11_ = toCint_yAPwf7d9aO5za0vgIa7yl8g((*sound).fChannel);
				T12_ = (int)0;
				T12_ = Dl_159929_(T11_);
				if (!(((NI32) 0) < T12_)) goto LA13_;
				nimln_(57, "audio.nim");
				T15_ = (int)0;
				T15_ = toCint_yAPwf7d9aO5za0vgIa7yl8g((*sound).fChannel);
				T16_ = (int)0;
				T16_ = Dl_159881_(T15_);
				T16_;
			}
			LA13_: ;
		}
		LA7_: ;
		nimln_(59, "audio.nim");
		Dl_159511_((*sound).fChunk);
		nimln_(60, "audio.nim");
		(*sound).fChunk = NIM_NIL;
	}
	LA3_: ;
	nimln_(61, "audio.nim");
	(*sound).fChannel = ((NI) -1);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_Yq6S7Ut1q0TYAwJihuPA8A)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound, NimStringDesc* file) {
	NIM_BOOL result;
	tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* T1_;
	nimfr_("load", "audio.nim");
{	result = (NIM_BOOL)0;
	nimln_(65, "audio.nim");
	result = NIM_TRUE;
	nimln_(66, "audio.nim");
	free_hD9a9ai9bEuxjtkfYz0Pe9bBsg(sound);
	nimln_(350, "sdl_mixer.nim");
	nimln_(68, "audio.nim");
	T1_ = (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA*)0;
	T1_ = Dl_147304_(file->data, "rb");
	(*sound).fChunk = Dl_159459_(T1_, ((int) 1));
	nimln_(69, "audio.nim");
	{
		NCSTRING T6_;
		if (!((*sound).fChunk == NIM_NIL)) goto LA4_;
		nimln_(70, "audio.nim");
		nimln_(72, "audio.nim");
		T6_ = (NCSTRING)0;
		T6_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t load sound file %s: %s", file->data, T6_);
		nimln_(73, "audio.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(74, "audio.nim");
	(*sound).fChannel = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_6TuWZC8Y6fluekWEEKGskg)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound, tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NIM_BOOL freeSrc) {
	NIM_BOOL result;
	nimfr_("load", "audio.nim");
{	result = (NIM_BOOL)0;
	nimln_(78, "audio.nim");
	result = NIM_TRUE;
	nimln_(79, "audio.nim");
	free_hD9a9ai9bEuxjtkfYz0Pe9bBsg(sound);
	nimln_(81, "audio.nim");
	(*sound).fChunk = Dl_159459_(src, ((int) (freeSrc)));
	nimln_(82, "audio.nim");
	{
		NCSTRING T5_;
		if (!((*sound).fChunk == NIM_NIL)) goto LA3_;
		nimln_(83, "audio.nim");
		nimln_(85, "audio.nim");
		T5_ = (NCSTRING)0;
		T5_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t load sound file RW: %s", T5_);
		nimln_(86, "audio.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(87, "audio.nim");
	(*sound).fChannel = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_e9apj1prYTCFEje3gK1rjQw)(void* p, NI op) {
	tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* a;
	a = (tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA*)p;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA*, newSound_Lr4q09b9amAu7mQfsOmsUltg)(NimStringDesc* file) {
	tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* result;
	NIM_BOOL T1_;
	nimfr_("newSound", "audio.nim");
	result = (tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA*)0;
	nimln_(91, "audio.nim");
	result = (tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA*) newObj((&NTI_e9apj1prYTCFEje3gK1rjQw_), sizeof(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA));
	(*result).Sup.m_type = (&NTI_JCPxIEGn03VSW9aKyV6FvQA_);
	nimln_(92, "audio.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = load_Yq6S7Ut1q0TYAwJihuPA8A(result, file);
	T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA*, newSound_ZzXvzn3ZfCTu6QBDW7NJTA)(tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NIM_BOOL freeSrc) {
	tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* result;
	NIM_BOOL T1_;
	nimfr_("newSound", "audio.nim");
	result = (tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA*)0;
	nimln_(96, "audio.nim");
	result = (tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA*) newObj((&NTI_e9apj1prYTCFEje3gK1rjQw_), sizeof(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA));
	(*result).Sup.m_type = (&NTI_JCPxIEGn03VSW9aKyV6FvQA_);
	nimln_(97, "audio.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = load_6TuWZC8Y6fluekWEEKGskg(result, src, freeSrc);
	T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, available_tdsri5IsxRTTtaBV4PL03g)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound) {
	NIM_BOOL result;
	nimfr_("available", "audio.nim");
{	result = (NIM_BOOL)0;
	nimln_(103, "audio.nim");
	{
		if (!((*sound).fChunk == NIM_NIL)) goto LA3_;
		nimln_(104, "audio.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(105, "audio.nim");
	result = !(((*sound).fChannel < ((NI) 0)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, playing_tdsri5IsxRTTtaBV4PL03g_2)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound) {
	NIM_BOOL result;
	int T6_;
	int T7_;
	nimfr_("playing", "audio.nim");
{	result = (NIM_BOOL)0;
	nimln_(111, "audio.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = available_tdsri5IsxRTTtaBV4PL03g(sound);
		if (!!(T3_)) goto LA4_;
		nimln_(112, "audio.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(113, "audio.nim");
	T6_ = (int)0;
	T6_ = toCint_yAPwf7d9aO5za0vgIa7yl8g((*sound).fChannel);
	T7_ = (int)0;
	T7_ = Dl_159929_(T6_);
	result = (((NI32) 0) < T7_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, stop_hD9a9ai9bEuxjtkfYz0Pe9bBsg_2)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound) {
	nimfr_("stop", "audio.nim");
	nimln_(119, "audio.nim");
	{
		NIM_BOOL T3_;
		int T6_;
		int T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = playing_tdsri5IsxRTTtaBV4PL03g_2(sound);
		if (!T3_) goto LA4_;
		nimln_(120, "audio.nim");
		T6_ = (int)0;
		T6_ = toCint_yAPwf7d9aO5za0vgIa7yl8g((*sound).fChannel);
		T7_ = (int)0;
		T7_ = Dl_159881_(T6_);
		T7_;
	}
	LA4_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, play_xcMNPMPQQBqFvemqYGQCog)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound, NI loops) {
	NI result;
	int T6_;
	int T7_;
	nimfr_("play", "audio.nim");
{	result = (NI)0;
	nimln_(128, "audio.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = playing_tdsri5IsxRTTtaBV4PL03g_2(sound);
		if (!T3_) goto LA4_;
		nimln_(129, "audio.nim");
		stop_hD9a9ai9bEuxjtkfYz0Pe9bBsg_2(sound);
	}
	LA4_: ;
	nimln_(130, "audio.nim");
	T6_ = (int)0;
	T6_ = toCint_yAPwf7d9aO5za0vgIa7yl8g(loops);
	T7_ = (int)0;
	T7_ = Dl_159829_(((int) -1), (*sound).fChunk, T6_, ((int) -1));
	(*sound).fChannel = ((NI) (T7_));
	nimln_(131, "audio.nim");
	{
		NCSTRING T12_;
		if (!((*sound).fChannel < ((NI) 0))) goto LA10_;
		nimln_(132, "audio.nim");
		nimln_(134, "audio.nim");
		T12_ = (NCSTRING)0;
		T12_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t play sound chunk: %s", T12_);
	}
	LA10_: ;
	nimln_(135, "audio.nim");
	result = (*sound).fChannel;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, channel_1jzAIJxnneZvWqVPG8O4hg)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound) {
	NI result;
	nimfr_("channel", "audio.nim");
{	result = (NI)0;
	nimln_(141, "audio.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = playing_tdsri5IsxRTTtaBV4PL03g_2(sound);
		if (!T3_) goto LA4_;
		nimln_(142, "audio.nim");
		result = (*sound).fChannel;
		goto BeforeRet_;
	}
	goto LA1_;
	LA4_: ;
	{
		nimln_(144, "audio.nim");
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, paused_tdsri5IsxRTTtaBV4PL03g_3)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound) {
	NIM_BOOL result;
	int T6_;
	int T7_;
	nimfr_("paused", "audio.nim");
{	result = (NIM_BOOL)0;
	nimln_(150, "audio.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = available_tdsri5IsxRTTtaBV4PL03g(sound);
		if (!!(T3_)) goto LA4_;
		nimln_(151, "audio.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(152, "audio.nim");
	T6_ = (int)0;
	T6_ = toCint_yAPwf7d9aO5za0vgIa7yl8g((*sound).fChannel);
	T7_ = (int)0;
	T7_ = Dl_159915_(T6_);
	result = (((NI32) 0) < T7_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, pause_hD9a9ai9bEuxjtkfYz0Pe9bBsg_3)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound) {
	nimfr_("pause", "audio.nim");
{	nimln_(158, "audio.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = available_tdsri5IsxRTTtaBV4PL03g(sound);
		if (!!(T3_)) goto LA4_;
		nimln_(159, "audio.nim");
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(160, "audio.nim");
	{
		NIM_BOOL T8_;
		int T11_;
		T8_ = (NIM_BOOL)0;
		T8_ = paused_tdsri5IsxRTTtaBV4PL03g_3(sound);
		if (!!(T8_)) goto LA9_;
		nimln_(161, "audio.nim");
		T11_ = (int)0;
		T11_ = toCint_yAPwf7d9aO5za0vgIa7yl8g((*sound).fChannel);
		Dl_159909_(T11_);
	}
	LA9_: ;
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, resume_hD9a9ai9bEuxjtkfYz0Pe9bBsg_4)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound) {
	nimfr_("resume", "audio.nim");
{	nimln_(167, "audio.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = available_tdsri5IsxRTTtaBV4PL03g(sound);
		if (!!(T3_)) goto LA4_;
		nimln_(168, "audio.nim");
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(169, "audio.nim");
	{
		NIM_BOOL T8_;
		int T11_;
		T8_ = (NIM_BOOL)0;
		T8_ = paused_tdsri5IsxRTTtaBV4PL03g_3(sound);
		if (!T8_) goto LA9_;
		nimln_(170, "audio.nim");
		T11_ = (int)0;
		T11_ = toCint_yAPwf7d9aO5za0vgIa7yl8g((*sound).fChannel);
		Dl_159912_(T11_);
	}
	LA9_: ;
	}BeforeRet_: ;
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, volume_rPYENh3usOjojQmWP3iO0Aaudio)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound) {
	NI result;
	int T1_;
	nimfr_("volume", "audio.nim");
{	result = (NI)0;
	nimln_(176, "audio.nim");
	T1_ = (int)0;
	T1_ = Dl_159874_((*sound).fChunk, ((int) -1));
	result = ((NI)chckRange(T1_, ((NI) 0), ((NI) 128)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, normalizeVolume_s6LQNTS0LUGhO9bHRZqRQFg)(NI val) {
	NI result;
	nimfr_("normalizeVolume", "audio.nim");
{	result = (NI)0;
	nimln_(180, "audio.nim");
	{
		if (!(val < ((NI) 0))) goto LA3_;
		result = ((NI) 0);
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(181, "audio.nim");
	{
		if (!(((NI) 128) < val)) goto LA7_;
		result = ((NI) 128);
		goto BeforeRet_;
	}
	LA7_: ;
	nimln_(182, "audio.nim");
	result = ((NI)chckRange(val, ((NI) 0), ((NI) 128)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, volumeeq__CaYICGSMf5Ly0PXHh1k4DAaudio)(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA* sound, NI val) {
	int T1_;
	nimfr_("volume=", "audio.nim");
	nimln_(188, "audio.nim");
	T1_ = (int)0;
	T1_ = Dl_159874_((*sound).fChunk, ((int) (val)));
	T1_;
	popFrame();
}

static N_INLINE(void, setDistance_WLA6pHUyKvaO9bLPfcAJaEwaudio)(NI channel, NI distance) {
	nimfr_("setDistance", "audio.nim");
	nimln_(221, "audio.nim");
	{
		int T3_;
		int T4_;
		NCSTRING T7_;
		T3_ = (int)0;
		T3_ = toCint_yAPwf7d9aO5za0vgIa7yl8g(channel);
		T4_ = (int)0;
		T4_ = Dl_159613_(T3_, ((NU8) (distance)));
		if (!(T4_ == ((NI32) 0))) goto LA5_;
		nimln_(222, "audio.nim");
		nimln_(224, "audio.nim");
		T7_ = (NCSTRING)0;
		T7_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t set the distance on the channel %s: %s", channel, T7_);
	}
	LA5_: ;
	popFrame();
}

static N_INLINE(void, setPanning_YvFkIOUrQT7J3HvBdt069cAaudio)(NI channel, NI left, NI right) {
	nimfr_("setPanning", "audio.nim");
	nimln_(235, "audio.nim");
	{
		int T3_;
		int T4_;
		NCSTRING T7_;
		T3_ = (int)0;
		T3_ = toCint_yAPwf7d9aO5za0vgIa7yl8g(channel);
		T4_ = (int)0;
		T4_ = Dl_159603_(T3_, ((NU8) (left)), ((NU8) (right)));
		if (!(T4_ == ((NI32) 0))) goto LA5_;
		nimln_(236, "audio.nim");
		nimln_(238, "audio.nim");
		T7_ = (NCSTRING)0;
		T7_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t set the panning on the channel %s: %s", channel, T7_);
	}
	LA5_: ;
	popFrame();
}

static N_INLINE(void, setPosition_VocJGfjEh3Qsoev5MPNovAaudio)(NI channel, NF angle, NI distance) {
	nimfr_("setPosition", "audio.nim");
	nimln_(255, "audio.nim");
	{
		int T3_;
		int T4_;
		NCSTRING T7_;
		T3_ = (int)0;
		T3_ = toCint_yAPwf7d9aO5za0vgIa7yl8g(channel);
		T4_ = (int)0;
		T4_ = Dl_159608_(T3_, ((NI16) (angle)), ((NU8) (distance)));
		if (!(T4_ == ((NI32) 0))) goto LA5_;
		nimln_(256, "audio.nim");
		nimln_(258, "audio.nim");
		T7_ = (NCSTRING)0;
		T7_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t set the position on the channel %s: %s", channel, T7_);
	}
	LA5_: ;
	popFrame();
}

static N_INLINE(void, soundStop_YyzWTSr9cdBKzXtCIewcHtQaudio)(void) {
	int T1_;
	nimfr_("soundStop", "audio.nim");
	nimln_(268, "audio.nim");
	T1_ = (int)0;
	T1_ = Dl_159881_(((int) -1));
	T1_;
	popFrame();
}

static N_INLINE(NI, soundPlayingNum_JTJHmTUXGVkIEk2pCkNXoQaudio)(void) {
	NI result;
	int T1_;
	nimfr_("soundPlayingNum", "audio.nim");
{	result = (NI)0;
	nimln_(274, "audio.nim");
	T1_ = (int)0;
	T1_ = Dl_159929_(((int) -1));
	result = ((NI) (T1_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, soundPausedNum_JTJHmTUXGVkIEk2pCkNXoQ_2audio)(void) {
	NI result;
	int T1_;
	nimfr_("soundPausedNum", "audio.nim");
{	result = (NI)0;
	nimln_(280, "audio.nim");
	T1_ = (int)0;
	T1_ = Dl_159915_(((int) -1));
	result = ((NI) (T1_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, soundPause_YyzWTSr9cdBKzXtCIewcHtQ_2audio)(void) {
	nimfr_("soundPause", "audio.nim");
	nimln_(286, "audio.nim");
	Dl_159909_(((int) -1));
	popFrame();
}

static N_INLINE(void, soundResume_YyzWTSr9cdBKzXtCIewcHtQ_3audio)(void) {
	nimfr_("soundResume", "audio.nim");
	nimln_(292, "audio.nim");
	Dl_159912_(((int) -1));
	popFrame();
}

static N_INLINE(NI, getSoundVolume_yyCpSdZK59ct104bsA7VIFQaudio)(void) {
	NI result;
	int T1_;
	nimfr_("getSoundVolume", "audio.nim");
{	result = (NI)0;
	nimln_(298, "audio.nim");
	T1_ = (int)0;
	T1_ = Dl_159870_(((int) -1), ((int) -1));
	result = ((NI)chckRange(T1_, ((NI) 0), ((NI) 128)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, setSoundVolume_jDnW5lEBdhvoSrw9chZVAeQaudio)(NI val) {
	int T1_;
	nimfr_("setSoundVolume", "audio.nim");
	nimln_(304, "audio.nim");
	T1_ = (int)0;
	T1_ = Dl_159870_(((int) -1), ((int) (val)));
	T1_;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, free_q1GOEG8ePj0WoPsvq2U89aQ)(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ* music) {
	nimfr_("free", "audio.nim");
	nimln_(324, "audio.nim");
	{
		if (!!(((*music).fMusic == NIM_NIL))) goto LA3_;
		nimln_(325, "audio.nim");
		Dl_159514_((*music).fMusic);
		nimln_(326, "audio.nim");
		(*music).fMusic = NIM_NIL;
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_MSdpeaBk3Sp6QWo9bGOZl3g)(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ* music, NimStringDesc* file) {
	NIM_BOOL result;
	nimfr_("load", "audio.nim");
{	result = (NIM_BOOL)0;
	nimln_(330, "audio.nim");
	result = NIM_TRUE;
	nimln_(331, "audio.nim");
	free_q1GOEG8ePj0WoPsvq2U89aQ(music);
	nimln_(333, "audio.nim");
	(*music).fMusic = Dl_159475_(file->data);
	nimln_(334, "audio.nim");
	{
		NCSTRING T5_;
		if (!((*music).fMusic == NIM_NIL)) goto LA3_;
		nimln_(335, "audio.nim");
		nimln_(337, "audio.nim");
		T5_ = (NCSTRING)0;
		T5_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t load music file %s: %s", file->data, T5_);
		nimln_(338, "audio.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_e8kbOdzLDRQnldo65KXc8Q)(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ* music, tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NIM_BOOL freeSrc) {
	NIM_BOOL result;
	nimfr_("load", "audio.nim");
{	result = (NIM_BOOL)0;
	nimln_(342, "audio.nim");
	result = NIM_TRUE;
	nimln_(343, "audio.nim");
	free_q1GOEG8ePj0WoPsvq2U89aQ(music);
	nimln_(345, "audio.nim");
	(*music).fMusic = Dl_159478_(src, ((int) (freeSrc)));
	nimln_(346, "audio.nim");
	{
		NCSTRING T5_;
		if (!((*music).fMusic == NIM_NIL)) goto LA3_;
		nimln_(347, "audio.nim");
		nimln_(349, "audio.nim");
		T5_ = (NCSTRING)0;
		T5_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t load music file RW: %s", T5_);
		nimln_(350, "audio.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_dUpvtO9besQUIGBspvDW48w)(void* p, NI op) {
	tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ* a;
	a = (tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ*)p;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ*, newMusic_kkaB9cxEgsD31GhzLyVeFEQ)(NimStringDesc* file) {
	tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ* result;
	NIM_BOOL T1_;
	nimfr_("newMusic", "audio.nim");
	result = (tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ*)0;
	nimln_(354, "audio.nim");
	result = (tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ*) newObj((&NTI_dUpvtO9besQUIGBspvDW48w_), sizeof(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ));
	(*result).Sup.m_type = (&NTI_UDy9bnueEy9bjI49cgSUMhdzQ_);
	nimln_(355, "audio.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = load_MSdpeaBk3Sp6QWo9bGOZl3g(result, file);
	T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ*, newMusic_gwZRzVNW7ut9bua7F4u1Rsw)(tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NIM_BOOL freeSrc) {
	tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ* result;
	NIM_BOOL T1_;
	nimfr_("newMusic", "audio.nim");
	result = (tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ*)0;
	nimln_(359, "audio.nim");
	result = (tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ*) newObj((&NTI_dUpvtO9besQUIGBspvDW48w_), sizeof(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ));
	(*result).Sup.m_type = (&NTI_UDy9bnueEy9bjI49cgSUMhdzQ_);
	nimln_(360, "audio.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = load_e8kbOdzLDRQnldo65KXc8Q(result, src, freeSrc);
	T1_;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, available_GEM9a3Di0GEW9cex1YsgMzggaudio)(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ* music) {
	NIM_BOOL result;
	nimfr_("available", "audio.nim");
{	result = (NIM_BOOL)0;
	nimln_(366, "audio.nim");
	result = !(((*music).fMusic == NIM_NIL));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, play_su9aQq1H6WaNmgajnNdZxgw)(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ* music, NI loops) {
	nimfr_("play", "audio.nim");
	nimln_(372, "audio.nim");
	{
		int T3_;
		int T4_;
		NCSTRING T7_;
		T3_ = (int)0;
		T3_ = toCint_yAPwf7d9aO5za0vgIa7yl8g(loops);
		T4_ = (int)0;
		T4_ = Dl_159841_((*music).fMusic, T3_);
		if (!(T4_ < ((NI32) 0))) goto LA5_;
		nimln_(373, "audio.nim");
		nimln_(375, "audio.nim");
		T7_ = (NCSTRING)0;
		T7_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t play music: %s", T7_);
	}
	LA5_: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, musicPaused_kmKHfshD3RNnIaIVdbPmmwaudio)(void) {
	NIM_BOOL result;
	int T1_;
	nimfr_("musicPaused", "audio.nim");
{	result = (NIM_BOOL)0;
	nimln_(385, "audio.nim");
	nimln_(398, "system.nim");
	nimln_(385, "audio.nim");
	T1_ = (int)0;
	T1_ = Dl_159924_();
	result = !((T1_ == ((NI32) 0)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, musicPause_YyzWTSr9cdBKzXtCIewcHtQ_4audio)(void) {
	nimfr_("musicPause", "audio.nim");
	nimln_(391, "audio.nim");
	Dl_159918_();
	popFrame();
}

static N_INLINE(void, musicResume_YyzWTSr9cdBKzXtCIewcHtQ_5audio)(void) {
	nimfr_("musicResume", "audio.nim");
	nimln_(397, "audio.nim");
	Dl_159920_();
	popFrame();
}

static N_INLINE(void, musicRewind_YyzWTSr9cdBKzXtCIewcHtQ_6audio)(void) {
	nimfr_("musicRewind", "audio.nim");
	nimln_(403, "audio.nim");
	Dl_159922_();
	popFrame();
}

static N_INLINE(NIM_BOOL, musicPlaying_kmKHfshD3RNnIaIVdbPmmw_2audio)(void) {
	NIM_BOOL result;
	int T1_;
	nimfr_("musicPlaying", "audio.nim");
{	result = (NIM_BOOL)0;
	nimln_(409, "audio.nim");
	nimln_(398, "system.nim");
	nimln_(409, "audio.nim");
	T1_ = (int)0;
	T1_ = Dl_159932_();
	result = !((T1_ == ((NI32) 0)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, musicStop_YyzWTSr9cdBKzXtCIewcHtQ_7audio)(void) {
	int T1_;
	nimfr_("musicStop", "audio.nim");
	nimln_(415, "audio.nim");
	T1_ = (int)0;
	T1_ = Dl_159887_();
	T1_;
	popFrame();
}

static N_INLINE(void, musicPosition_7C5pzenTcF0E57TbZQjefgaudio)(NF val) {
	int T1_;
	nimfr_("musicPosition", "audio.nim");
	nimln_(429, "audio.nim");
	T1_ = (int)0;
	T1_ = Dl_159926_(val);
	T1_;
	popFrame();
}
static N_NIMCALL(void, Marker_tySequence_cIlT2tiEqOuMg0NQ1IqASw)(void* p, NI op) {
	tySequence_cIlT2tiEqOuMg0NQ1IqASw* a;
	NI T1_;
	a = (tySequence_cIlT2tiEqOuMg0NQ1IqASw*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, Marker_tyRef_cVxn2iwI9aZh5MPcCZPNprQ)(void* p, NI op) {
	tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA* a;
	a = (tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA*)p;
	nimGCvisit((void*)(*a).list, op);
}
static N_NIMCALL(void, TM_39bXrYa3vA9aMKLBuvGNJgUA_4)(void) {
	nimGCvisit((void*)playlist_gna9cd1d772Ka9aPCqMpHOYQ, 0);
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_CDECL(void, finished_GPWLpLUP82js9a8c55dxNwg)(void) {
	nimfr_("finished", "audio.nim");
{	nimln_(472, "audio.nim");
	{
		if (!(playlist_gna9cd1d772Ka9aPCqMpHOYQ == NIM_NIL)) goto LA3_;
		nimln_(473, "audio.nim");
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(474, "audio.nim");
	(*playlist_gna9cd1d772Ka9aPCqMpHOYQ).fFinished = NIM_TRUE;
	}BeforeRet_: ;
	popFrame();
}

static N_INLINE(void, nimGCunrefRC1)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefRC1", "gc.nim");
	nimln_(258, "gc.nim");
	T1_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T1_);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, init_gVEFyHMJP4jNWhC2yoGrrw)(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA* pl) {
	nimfr_("init", "audio.nim");
	nimln_(478, "audio.nim");
	if ((*pl).list) { nimGCunrefRC1((*pl).list); (*pl).list = NIM_NIL; }
	(*pl).list = (tySequence_cIlT2tiEqOuMg0NQ1IqASw*) newSeqRC1((&NTI_cIlT2tiEqOuMg0NQ1IqASw_), 0);
	nimln_(479, "audio.nim");
	(*pl).fIndex = ((NI) -1);
	nimln_(480, "audio.nim");
	(*pl).fFinished = NIM_FALSE;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA*, newPlaylist_fkV4CBjqZi0z1evlOiJbkA)(void) {
	tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA* result;
	nimfr_("newPlaylist", "audio.nim");
	result = (tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA*)0;
	nimln_(484, "audio.nim");
	result = (tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA*) newObj((&NTI_cVxn2iwI9aZh5MPcCZPNprQ_), sizeof(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA));
	(*result).Sup.m_type = (&NTI_hH9a3qlZLWG9bOTrtP9bUhWSA_);
	nimln_(485, "audio.nim");
	init_gVEFyHMJP4jNWhC2yoGrrw(result);
	popFrame();
	return result;
}

static N_INLINE(NI, index_aS3bkUl9aO89b1v0vk5ZuNVgaudio)(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA* pl) {
	NI result;
	nimfr_("index", "audio.nim");
	result = (NI)0;
	nimln_(489, "audio.nim");
	result = (*pl).fIndex;
	popFrame();
	return result;
}

static N_INLINE(NI, rand_3MNNZB2vD1hQTqPc9bVQ9b4gaudio)(NI max, NI* exclude, NI excludeLen_0) {
	NI result;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* T1_;
	nimfr_("rand", "utils.nim");
	result = (NI)0;
	nimln_(388, "utils.nim");
	T1_ = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)0;
	T1_ = at__7KXK9aqsdE0ndrhB7KxewvA(exclude, excludeLen_0);
	result = rand_bXFhlVh7ZFz3I1g4MkLBnw(max, T1_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, play_g2yFfzwnTz7Ev5OKztuJxw)(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA* pl, NI index) {
	NI result;
	nimfr_("play", "audio.nim");
{	result = (NI)0;
	nimln_(501, "audio.nim");
	{
		NI T5_;
		tyArray_GAcaPw08Gj9cXYhAaMMr9cfw T6_;
		if (!(index < ((NI) 0))) goto LA3_;
		T5_ = ((*pl).list ? ((*pl).list->Sup.len-1) : -1);
		T6_[0] = (*pl).fIndex;
		(*pl).fIndex = rand_3MNNZB2vD1hQTqPc9bVQ9b4gaudio(T5_, T6_, 1);
	}
	goto LA1_;
	LA3_: ;
	{
		(*pl).fIndex = index;
	}
	LA1_: ;
	nimln_(503, "audio.nim");
	if ((NU)((*pl).fIndex) >= (NU)((*pl).list->Sup.len)) raiseIndexError();
	play_su9aQq1H6WaNmgajnNdZxgw((*pl).list->data[(*pl).fIndex], ((NI) 0));
	nimln_(504, "audio.nim");
	Dl_159553_(finished_GPWLpLUP82js9a8c55dxNwg);
	nimln_(505, "audio.nim");
	result = (*pl).fIndex;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, stop_gVEFyHMJP4jNWhC2yoGrrw_2)(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA* pl) {
	nimfr_("stop", "audio.nim");
	nimln_(509, "audio.nim");
	musicStop_YyzWTSr9cdBKzXtCIewcHtQ_7audio();
	nimln_(510, "audio.nim");
	(*pl).fIndex = ((NI) -1);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, update_MlDddNjBpRGSlwmH4NptYg)(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA* pl) {
	nimfr_("update", "audio.nim");
	nimln_(514, "audio.nim");
	{
		NI T5_;
		if (!(*pl).fFinished) goto LA3_;
		nimln_(515, "audio.nim");
		(*pl).fFinished = NIM_FALSE;
		nimln_(516, "audio.nim");
		T5_ = (NI)0;
		T5_ = play_g2yFfzwnTz7Ev5OKztuJxw(pl, ((NI) -1));
		T5_;
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, find_b2asjP2y9cPDPwOLa1pD5PAutils)(NI* a, NI aLen_0, NI item) {
	NI result;
	nimfr_("find", "system.nim");
{	result = (NI)0;
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(2185, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI TM_39bXrYa3vA9aMKLBuvGNJgUA_5;
				NI TM_39bXrYa3vA9aMKLBuvGNJgUA_6;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				if ((NU)(i_2) >= (NU)(aLen_0)) raiseIndexError();
				i = a[i_2];
				nimln_(2419, "system.nim");
				{
					if (!(i == item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(2420, "system.nim");
				TM_39bXrYa3vA9aMKLBuvGNJgUA_5 = addInt(result, ((NI) 1));
				result = (NI)(TM_39bXrYa3vA9aMKLBuvGNJgUA_5);
				nimln_(2188, "system.nim");
				TM_39bXrYa3vA9aMKLBuvGNJgUA_6 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_39bXrYa3vA9aMKLBuvGNJgUA_6);
			} LA3: ;
		}
	}
	nimln_(2421, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_P6sCVNQ9cdTFh3rtVXMEtxgutils)(NI* a, NI aLen_0, NI item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "system.nim");
{	result = (NIM_BOOL)0;
	nimln_(2426, "system.nim");
	T1_ = (NI)0;
	T1_ = find_b2asjP2y9cPDPwOLa1pD5PAutils(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, nimgame2_audioInit000)(void) {
	nimfr_("audio", "audio.nim");
nimRegisterGlobalMarker(TM_39bXrYa3vA9aMKLBuvGNJgUA_4);
	nimln_(466, "audio.nim");
	asgnRef((void**) (&playlist_gna9cd1d772Ka9aPCqMpHOYQ), NIM_NIL);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimgame2_audioDatInit000)(void) {
static TNimNode* TM_39bXrYa3vA9aMKLBuvGNJgUA_2[2];
static TNimNode* TM_39bXrYa3vA9aMKLBuvGNJgUA_3[3];
static TNimNode TM_39bXrYa3vA9aMKLBuvGNJgUA_0[8];
NTI_JCPxIEGn03VSW9aKyV6FvQA_.size = sizeof(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA);
NTI_JCPxIEGn03VSW9aKyV6FvQA_.kind = 17;
NTI_JCPxIEGn03VSW9aKyV6FvQA_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_JCPxIEGn03VSW9aKyV6FvQA_.flags = 1;
TM_39bXrYa3vA9aMKLBuvGNJgUA_2[0] = &TM_39bXrYa3vA9aMKLBuvGNJgUA_0[1];
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[1].kind = 1;
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[1].offset = offsetof(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA, fChunk);
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[1].typ = (&NTI_fk5c7FchYduFB24e7g9aUsA_);
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[1].name = "fChunk";
TM_39bXrYa3vA9aMKLBuvGNJgUA_2[1] = &TM_39bXrYa3vA9aMKLBuvGNJgUA_0[2];
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[2].kind = 1;
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[2].offset = offsetof(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA, fChannel);
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[2].name = "fChannel";
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[0].len = 2; TM_39bXrYa3vA9aMKLBuvGNJgUA_0[0].kind = 2; TM_39bXrYa3vA9aMKLBuvGNJgUA_0[0].sons = &TM_39bXrYa3vA9aMKLBuvGNJgUA_2[0];
NTI_JCPxIEGn03VSW9aKyV6FvQA_.node = &TM_39bXrYa3vA9aMKLBuvGNJgUA_0[0];
NTI_e9apj1prYTCFEje3gK1rjQw_.size = sizeof(tyObject_SoundcolonObjectType__JCPxIEGn03VSW9aKyV6FvQA*);
NTI_e9apj1prYTCFEje3gK1rjQw_.kind = 22;
NTI_e9apj1prYTCFEje3gK1rjQw_.base = (&NTI_JCPxIEGn03VSW9aKyV6FvQA_);
NTI_e9apj1prYTCFEje3gK1rjQw_.marker = Marker_tyRef_e9apj1prYTCFEje3gK1rjQw;
(&NTI_e9apj1prYTCFEje3gK1rjQw_)->finalizer = (void*)free_hD9a9ai9bEuxjtkfYz0Pe9bBsg;
(&NTI_e9apj1prYTCFEje3gK1rjQw_)->finalizer = (void*)free_hD9a9ai9bEuxjtkfYz0Pe9bBsg;
NTI_UDy9bnueEy9bjI49cgSUMhdzQ_.size = sizeof(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ);
NTI_UDy9bnueEy9bjI49cgSUMhdzQ_.kind = 17;
NTI_UDy9bnueEy9bjI49cgSUMhdzQ_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_UDy9bnueEy9bjI49cgSUMhdzQ_.flags = 1;
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[3].kind = 1;
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[3].offset = offsetof(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ, fMusic);
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[3].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[3].name = "fMusic";
NTI_UDy9bnueEy9bjI49cgSUMhdzQ_.node = &TM_39bXrYa3vA9aMKLBuvGNJgUA_0[3];
NTI_dUpvtO9besQUIGBspvDW48w_.size = sizeof(tyObject_MusiccolonObjectType__UDy9bnueEy9bjI49cgSUMhdzQ*);
NTI_dUpvtO9besQUIGBspvDW48w_.kind = 22;
NTI_dUpvtO9besQUIGBspvDW48w_.base = (&NTI_UDy9bnueEy9bjI49cgSUMhdzQ_);
NTI_dUpvtO9besQUIGBspvDW48w_.marker = Marker_tyRef_dUpvtO9besQUIGBspvDW48w;
(&NTI_dUpvtO9besQUIGBspvDW48w_)->finalizer = (void*)free_q1GOEG8ePj0WoPsvq2U89aQ;
(&NTI_dUpvtO9besQUIGBspvDW48w_)->finalizer = (void*)free_q1GOEG8ePj0WoPsvq2U89aQ;
NTI_hH9a3qlZLWG9bOTrtP9bUhWSA_.size = sizeof(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA);
NTI_hH9a3qlZLWG9bOTrtP9bUhWSA_.kind = 17;
NTI_hH9a3qlZLWG9bOTrtP9bUhWSA_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_39bXrYa3vA9aMKLBuvGNJgUA_3[0] = &TM_39bXrYa3vA9aMKLBuvGNJgUA_0[5];
NTI_cIlT2tiEqOuMg0NQ1IqASw_.size = sizeof(tySequence_cIlT2tiEqOuMg0NQ1IqASw*);
NTI_cIlT2tiEqOuMg0NQ1IqASw_.kind = 24;
NTI_cIlT2tiEqOuMg0NQ1IqASw_.base = (&NTI_dUpvtO9besQUIGBspvDW48w_);
NTI_cIlT2tiEqOuMg0NQ1IqASw_.marker = Marker_tySequence_cIlT2tiEqOuMg0NQ1IqASw;
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[5].kind = 1;
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[5].offset = offsetof(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA, list);
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[5].typ = (&NTI_cIlT2tiEqOuMg0NQ1IqASw_);
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[5].name = "list";
TM_39bXrYa3vA9aMKLBuvGNJgUA_3[1] = &TM_39bXrYa3vA9aMKLBuvGNJgUA_0[6];
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[6].kind = 1;
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[6].offset = offsetof(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA, fIndex);
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[6].name = "fIndex";
TM_39bXrYa3vA9aMKLBuvGNJgUA_3[2] = &TM_39bXrYa3vA9aMKLBuvGNJgUA_0[7];
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[7].kind = 1;
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[7].offset = offsetof(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA, fFinished);
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[7].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[7].name = "fFinished";
TM_39bXrYa3vA9aMKLBuvGNJgUA_0[4].len = 3; TM_39bXrYa3vA9aMKLBuvGNJgUA_0[4].kind = 2; TM_39bXrYa3vA9aMKLBuvGNJgUA_0[4].sons = &TM_39bXrYa3vA9aMKLBuvGNJgUA_3[0];
NTI_hH9a3qlZLWG9bOTrtP9bUhWSA_.node = &TM_39bXrYa3vA9aMKLBuvGNJgUA_0[4];
NTI_cVxn2iwI9aZh5MPcCZPNprQ_.size = sizeof(tyObject_PlaylistcolonObjectType__hH9a3qlZLWG9bOTrtP9bUhWSA*);
NTI_cVxn2iwI9aZh5MPcCZPNprQ_.kind = 22;
NTI_cVxn2iwI9aZh5MPcCZPNprQ_.base = (&NTI_hH9a3qlZLWG9bOTrtP9bUhWSA_);
NTI_cVxn2iwI9aZh5MPcCZPNprQ_.marker = Marker_tyRef_cVxn2iwI9aZh5MPcCZPNprQ;
}

