/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\Users\Alterna\Documents\nim-0.18.0\lib -o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\nimgame2_texturegraphic.o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\nimgame2_texturegraphic.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ;
typedef struct tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA;
typedef struct tyTuple_wpFMp8IwxV6MlaM4GANJ0Q tyTuple_wpFMp8IwxV6MlaM4GANJ0Q;
typedef struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ tyObject_Rect_qiXweduDJk1iLE5aHysNdQ;
typedef struct tyObject_Point_O882QUBegNwSZhlvLsYQRw tyObject_Point_O882QUBegNwSZhlvLsYQRw;
typedef struct tyObject_Env_texturegraphicdotnim__uFub4jMdWk7Mc5m2Y9bkWdA tyObject_Env_texturegraphicdotnim__uFub4jMdWk7Mc5m2Y9bkWdA;
typedef struct tyObject_Color_YizDHyEvJtgQk2fn8KdZUA tyObject_Color_YizDHyEvJtgQk2fn8KdZUA;
typedef union tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ;
typedef struct tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ;
typedef struct tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA;
typedef struct tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ;
typedef struct tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg;
typedef struct tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q;
typedef struct tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg {
  RootObj Sup;
};
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
struct tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ {
  tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg Sup;
void* fTexture;
NU32 fFormat;
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ fSize;
};
typedef N_CDECL_PTR(void, tyProc_32w2ZypAyMWuajvi2Jt79cg) (void* texture);
typedef NI32 tyEnum_TextureAccess_poCqMuWAVlQ9auy0EWhBQuA;
typedef N_CDECL_PTR(int, tyProc_Z3C0z9blaIY9abfEJhIF9b1WQ) (void* texture, NU32* format, tyEnum_TextureAccess_poCqMuWAVlQ9auy0EWhBQuA* access, int* w, int* h);
typedef NI32 tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw;
typedef N_CDECL_PTR(void, tyProc_DusjKySyJW30WdV9bsteVxw) (tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw category, NCSTRING fmt, ...);
typedef N_CDECL_PTR(NCSTRING, tyProc_09bvyvHFtWbkzL5AHgf0bKw) (void);
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(void**, tyProc_1LIoIPgxf1fnU6YXXXDfCA) (void* renderer, NCSTRING file);
typedef N_CDECL_PTR(void*, tyProc_VQBltFKZwH39aVWDIW09ctKw) (void* renderer, tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, int freesrc);
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyTuple_wpFMp8IwxV6MlaM4GANJ0Q {
NF Field0;
NF Field1;
};
typedef NI32 tyEnum_Flip_qWHX0qRQS3EMdrguXFZZdA;
struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ {
int x;
int y;
int w;
int h;
};
typedef N_CDECL_PTR(int, tyProc_QGX7uxPZtIoH9bzksYUj1mg) (void* renderer, void* texture, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* srcrect, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* dstrect);
struct tyObject_Point_O882QUBegNwSZhlvLsYQRw {
int x;
int y;
};
typedef NI32 tyEnum_RendererFlip_v7zeNYRvzJgcDDS9cEco6wg;
typedef N_CDECL_PTR(int, tyProc_oVfcvGczxlST8hWjhSa9aHA) (void* renderer, void* texture, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* srcrect, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* dstrect, double angle, tyObject_Point_O882QUBegNwSZhlvLsYQRw* center, tyEnum_RendererFlip_v7zeNYRvzJgcDDS9cEco6wg flip);
struct tyObject_Env_texturegraphicdotnim__uFub4jMdWk7Mc5m2Y9bkWdA {
  RootObj Sup;
NI colonstate_;
NIM_BOOL reverseX1;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* src, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* dst, NI deltaX, NI endX, void* ClE_0);
void* ClE_0;
} tyProc_a7iqrcvoMsV1TcEUWb7YRQ;
typedef N_CLOSURE_PTR(void, TM_iUjz9bRo1B8EXWVmzAlkVNA_16) (tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* src, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* dst, NI deltaX, NI endX);
typedef N_CLOSURE_PTR(void, TM_iUjz9bRo1B8EXWVmzAlkVNA_19) (tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* src, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* dst, NI deltaX, NI endX);
struct tyObject_Color_YizDHyEvJtgQk2fn8KdZUA {
NU8 r;
NU8 g;
NU8 b;
NU8 a;
};
typedef N_CDECL_PTR(int, tyProc_wPxvXWWgPCAYBuODEXklIQ) (void* texture, NU8* r, NU8* g, NU8* b);
typedef N_CDECL_PTR(int, tyProc_zhHzw47u9aiQa6dkiW0Xt6A) (void* texture, NU8 r, NU8 g, NU8 b);
typedef N_CDECL_PTR(int, tyProc_vQpo9bldiNjTNBM8HFLFDnA) (void* texture, NU8* alpha);
typedef N_CDECL_PTR(int, tyProc_FlP63hJrVpAOGAcB9aysLWg) (void* texture, NU8 alpha);
typedef NI32 tyEnum_Blend_j9a9czwucCcTZ69cftFUpcNJA;
typedef NI32 tyEnum_BlendMode_acuvsAfHtuIf9ats9aWCQoeQ;
typedef N_CDECL_PTR(int, tyProc_iHseqIAJGzwtK1AnPOzGxg) (void* texture, tyEnum_BlendMode_acuvsAfHtuIf9ats9aWCQoeQ* blendMode);
typedef N_CDECL_PTR(int, tyProc_drbIXv9cjqA4ZjQmLutUd0A) (void* texture, tyEnum_BlendMode_acuvsAfHtuIf9ats9aWCQoeQ blendMode);
typedef N_CDECL_PTR(NI64, tyProc_p9adtE9afP6ObPoIZKMFxiAA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context);
typedef N_CDECL_PTR(NI64, tyProc_tpgoL9bwK9bkzBn2qq83QKag) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context, NI64 offset, int whence);
typedef N_CDECL_PTR(size_t, tyProc_vPnfrHDX45Ib7P40WFtTvg) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context, void* p, size_t size, size_t maxnum);
typedef N_CDECL_PTR(int, tyProc_pcLKO4pFPDvuTZj9c0HX5oA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context);
struct tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ {
void* fileNameRef;
void* inputStreamRef;
void* readableByteChannelRef;
void* readMethod;
void* assetFileDescriptorRef;
long position;
long size;
long offset;
int fd;
};
struct tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ {
void* data;
size_t size;
size_t left;
};
struct tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA {
NIM_BOOL append;
void* h;
tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ buffer;
};
struct tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg {
NIM_BOOL autoclose;
FILE* fp;
};
struct tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q {
NU8* base;
NU8* here;
NU8* stop;
};
struct tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA {
void* data1;
void* data2;
};
union tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ {
tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ androidio;
tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA windowsio;
tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg stdio;
tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q mem;
tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA unknown;
};
struct tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA {
tyProc_p9adtE9afP6ObPoIZKMFxiAA size;
tyProc_tpgoL9bwK9bkzBn2qq83QKag seek;
tyProc_vPnfrHDX45Ib7P40WFtTvg read;
tyProc_vPnfrHDX45Ib7P40WFtTvg write;
tyProc_pcLKO4pFPDvuTZj9c0HX5oA close;
NU32 kind;
tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ mem;
};
N_LIB_PRIVATE N_NIMCALL(void, freeTexture_TVIPFgvKm23EZwbfT9bLtlw)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, free_TVIPFgvKm23EZwbfT9bLtlw_2)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic);
N_LIB_PRIVATE N_NIMCALL(void, init_TVIPFgvKm23EZwbfT9bLtlw_3)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, updateTexture_o5gIGNbuUX7M9aXENTS0MrQ)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic);
static N_INLINE(NU32, format_9bCoHJ5a8pZxJkrBY2PrxAwtexturegraphic)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_MVqmhd3eEvdvf8UDCyvQNg)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, NimStringDesc* file);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_bh9bbDkisoutTeH0q0Xg7QQ)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* rw, NIM_BOOL freeSrc);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, assignTexture_izBjDCMx0V6Mqi9afESEH9bw)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, void* texture, NIM_BOOL freeCurrent);
static N_INLINE(void*, texture_rmsBaP9cgI9cIMw2Ufl6cQSQtexturegraphic)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic);
N_LIB_PRIVATE N_NIMCALL(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ*, newTextureGraphic_FnSxV8ZkuJJUGeunVqnGuQ)(void);
static N_NIMCALL(void, Marker_tyRef_tdrwAKYExl1bGpmSl0OZSw)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ*, newTextureGraphic_0Ay11MhmFiBbDCfohNldJg)(NimStringDesc* file);
N_LIB_PRIVATE N_NIMCALL(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ*, newTextureGraphic_PywCtF7Yhabyne2iyrdefQ)(tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NIM_BOOL freeSrc);
N_LIB_PRIVATE N_NIMCALL(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ*, newTextureGraphic_0tHPchX6AKFowGHM3p9a7Dw)(void* texture);
static N_INLINE(NI, w_4pYVftVR7bGh3MkKzaR9cbgtexturegraphic)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic);
static N_INLINE(NI, h_4pYVftVR7bGh3MkKzaR9cbg_2texturegraphic)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic);
static N_INLINE(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, dim_bCktJef7meJbpcLqB39cfhAtexturegraphic)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic);
N_LIB_PRIVATE N_NIMCALL(void, drawTextureGraphic_iZaVEAoZEJ8MZ7GJqAyxBA)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NF angle, NF scale, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q center, tyEnum_Flip_qWHX0qRQS3EMdrguXFZZdA flip, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ region);
N_NOINLINE(void, chckNil)(void* p);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__a05Mt4S1qT9bYa0L8KYON6A)(tyObject_Rect_qiXweduDJk1iLE5aHysNdQ x, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ y);
N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, dim_EIe1nJUG9bPRe4lU9b6M4seQ)(tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* graphic);
static N_INLINE(void, stareq__JY1gD4DsDLYjLacuUnapNQ_3types)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* c, NF v);
static N_INLINE(void, stareq__7kHiltrvRlcg6wSYR3CxAwstrutils)(NF* x, NF y);
static N_INLINE(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, minus__j2pnXFSCXLnkC9a3JwzEgTw_2types)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c2);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_LIB_PRIVATE N_NIMCALL(void, draw_iZaVEAoZEJ8MZ7GJqAyxBA_2)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NF angle, NF scale, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q center, tyEnum_Flip_qWHX0qRQS3EMdrguXFZZdA flip, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ region);
N_LIB_PRIVATE N_NIMCALL(void, drawTiled_aqjcU09a423NxGj9ccLenIvA)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ rect, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ region, NIM_BOOL reverseX, NIM_BOOL reverseY);
static N_NIMCALL(void, Marker_tyRef_WP9as9aO1mXAo1uTvhN3g2LQ)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(int, toCint_yAPwf7d9aO5za0vgIa7yl8g)(NI x);
N_LIB_PRIVATE N_NIMCALL(NI, w_VokxRR2q72oBljkKbWBi9bg)(tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* graphic);
N_LIB_PRIVATE N_NIMCALL(NI, h_VokxRR2q72oBljkKbWBi9bg_2)(tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* graphic);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_CLOSURE(void, drawLine_ihJDU459bFX5661hgVbE0uA)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* src, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* dst, NI deltaX, NI endX, void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(void, drawTile_0JsNsTMlaBHN36igdj9aomQ)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* src, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* dst);
N_LIB_PRIVATE N_NIMCALL(tyObject_Color_YizDHyEvJtgQk2fn8KdZUA, colorMod_zm9akqyhW5blM0A21i08UkQ)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic);
N_LIB_PRIVATE N_NIMCALL(void, colorModeq__lf2VXq9cmoMc9bycgmqCnz1Q)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color);
N_LIB_PRIVATE N_NIMCALL(NU8, alphaMod_zPXx2AkXI59cBFY4IYzj3Sw)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic);
N_LIB_PRIVATE N_NIMCALL(void, alphaModeq__4RMJgcbaGjKTC7hn36z1Pg)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, NU8 alpha);
N_LIB_PRIVATE N_NIMCALL(tyEnum_Blend_j9a9czwucCcTZ69cftFUpcNJA, blendMod_GiLgryKZfy4KMjTfguCoCQ)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic);
N_LIB_PRIVATE N_NIMCALL(void, blendModeq__QDfuMY32f9c7H6lDqNvRoXw)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyEnum_Blend_j9a9czwucCcTZ69cftFUpcNJA blend);
extern tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_155413_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyProc_Z3C0z9blaIY9abfEJhIF9b1WQ Dl_155149_;
extern tyProc_DusjKySyJW30WdV9bsteVxw Dl_154881_;
extern tyProc_09bvyvHFtWbkzL5AHgf0bKw Dl_147926_;
extern tyProc_1LIoIPgxf1fnU6YXXXDfCA Dl_157060_;
extern void* renderer_M5l6pK6T79aB5LqtC0dmeOg;
extern tyProc_VQBltFKZwH39aVWDIW09ctKw Dl_157065_;
extern TNimType NTI_W9c5ORj7z7QIE1MjKJgJgFg_;
TNimType NTI_XO5Zgk1wZdddPxRev2t9aEQ_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_;
extern TNimType NTI_1v9bKyksXWMsm0vNwmZ4EuQ_;
TNimType NTI_tdrwAKYExl1bGpmSl0OZSw_;
extern tyProc_QGX7uxPZtIoH9bzksYUj1mg Dl_155382_;
extern tyProc_oVfcvGczxlST8hWjhSa9aHA Dl_155390_;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_uFub4jMdWk7Mc5m2Y9bkWdA_;
extern TNimType NTI_xHTZrq9aYs6boc9bCba0JbpQ_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
TNimType NTI_WP9as9aO1mXAo1uTvhN3g2LQ_;
extern tyProc_wPxvXWWgPCAYBuODEXklIQ Dl_155170_;
extern tyProc_zhHzw47u9aiQa6dkiW0Xt6A Dl_155160_;
extern tyProc_vQpo9bldiNjTNBM8HFLFDnA Dl_155187_;
extern tyProc_FlP63hJrVpAOGAcB9aysLWg Dl_155183_;
extern tyProc_iHseqIAJGzwtK1AnPOzGxg Dl_155196_;
extern tyProc_drbIXv9cjqA4ZjQmLutUd0A Dl_155192_;
NIM_CONST tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ TM_iUjz9bRo1B8EXWVmzAlkVNA_2 = {((NI) 0),
((NI) 0)}
;
NIM_CONST tyObject_Rect_qiXweduDJk1iLE5aHysNdQ TM_iUjz9bRo1B8EXWVmzAlkVNA_5 = {((int) 0), ((int) 0), ((int) 0), ((int) 0)};

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, freeTexture_TVIPFgvKm23EZwbfT9bLtlw)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic) {
	nimfr_("freeTexture", "texturegraphic.nim");
	nimln_(44, "texturegraphic.nim");
	{
		if (!!(((*graphic).fTexture == NIM_NIL))) goto LA3_;
		nimln_(45, "texturegraphic.nim");
		Dl_155413_((*graphic).fTexture);
		nimln_(46, "texturegraphic.nim");
		(*graphic).fTexture = NIM_NIL;
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, free_TVIPFgvKm23EZwbfT9bLtlw_2)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic) {
	nimfr_("free", "texturegraphic.nim");
	nimln_(50, "texturegraphic.nim");
	freeTexture_TVIPFgvKm23EZwbfT9bLtlw(graphic);
	nimln_(51, "texturegraphic.nim");
	(*graphic).fFormat = ((NU32) 0);
	nimln_(52, "texturegraphic.nim");
	(*graphic).fSize = TM_iUjz9bRo1B8EXWVmzAlkVNA_2;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, init_TVIPFgvKm23EZwbfT9bLtlw_3)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic) {
	nimfr_("init", "texturegraphic.nim");
	nimln_(56, "texturegraphic.nim");
	(*graphic).fTexture = NIM_NIL;
	nimln_(57, "texturegraphic.nim");
	(*graphic).fFormat = ((NU32) 0);
	nimln_(58, "texturegraphic.nim");
	(*graphic).fSize = TM_iUjz9bRo1B8EXWVmzAlkVNA_2;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, updateTexture_o5gIGNbuUX7M9aXENTS0MrQ)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic) {
	NIM_BOOL result;
	int w;
	int h;
	nimfr_("updateTexture", "texturegraphic.nim");
{	result = (NIM_BOOL)0;
	nimln_(62, "texturegraphic.nim");
	{
		if (!((*graphic).fTexture == NIM_NIL)) goto LA3_;
		nimln_(63, "texturegraphic.nim");
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(64, "texturegraphic.nim");
	result = NIM_TRUE;
	w = (int)0;
	h = (int)0;
	nimln_(66, "texturegraphic.nim");
	{
		int T7_;
		nimln_(398, "system.nim");
		nimln_(66, "texturegraphic.nim");
		T7_ = (int)0;
		T7_ = Dl_155149_((*graphic).fTexture, (&(*graphic).fFormat), NIM_NIL, (&w), (&h));
		if (!!((T7_ == ((NI32) 0)))) goto LA8_;
		nimln_(68, "texturegraphic.nim");
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t get texture attributes: %s", Dl_147926_);
		nimln_(71, "texturegraphic.nim");
		Dl_155413_((*graphic).fTexture);
		nimln_(72, "texturegraphic.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA8_: ;
	nimln_(73, "texturegraphic.nim");
	(*graphic).fSize.Field0 = ((NI) (w));
	nimln_(74, "texturegraphic.nim");
	(*graphic).fSize.Field1 = ((NI) (h));
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NU32, format_9bCoHJ5a8pZxJkrBY2PrxAwtexturegraphic)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic) {
	NU32 result;
	nimfr_("format", "texturegraphic.nim");
	result = (NU32)0;
	nimln_(78, "texturegraphic.nim");
	result = (*graphic).fFormat;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_MVqmhd3eEvdvf8UDCyvQNg)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, NimStringDesc* file) {
	NIM_BOOL result;
	void** T1_;
	nimfr_("load", "texturegraphic.nim");
{	result = (NIM_BOOL)0;
	nimln_(87, "texturegraphic.nim");
	result = NIM_TRUE;
	nimln_(88, "texturegraphic.nim");
	free_TVIPFgvKm23EZwbfT9bLtlw_2(graphic);
	nimln_(90, "texturegraphic.nim");
	T1_ = (void**)0;
	T1_ = Dl_157060_(renderer_M5l6pK6T79aB5LqtC0dmeOg, file->data);
	(*graphic).fTexture = ((void*) (T1_));
	nimln_(91, "texturegraphic.nim");
	{
		NCSTRING T6_;
		if (!((*graphic).fTexture == NIM_NIL)) goto LA4_;
		nimln_(92, "texturegraphic.nim");
		nimln_(94, "texturegraphic.nim");
		T6_ = (NCSTRING)0;
		T6_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t load image %s: %s", file->data, T6_);
		nimln_(95, "texturegraphic.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(96, "texturegraphic.nim");
	result = updateTexture_o5gIGNbuUX7M9aXENTS0MrQ(graphic);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, load_bh9bbDkisoutTeH0q0Xg7QQ)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* rw, NIM_BOOL freeSrc) {
	NIM_BOOL result;
	nimfr_("load", "texturegraphic.nim");
{	result = (NIM_BOOL)0;
	nimln_(105, "texturegraphic.nim");
	result = NIM_TRUE;
	nimln_(106, "texturegraphic.nim");
	free_TVIPFgvKm23EZwbfT9bLtlw_2(graphic);
	nimln_(108, "texturegraphic.nim");
	(*graphic).fTexture = Dl_157065_(renderer_M5l6pK6T79aB5LqtC0dmeOg, rw, ((int) (freeSrc)));
	nimln_(109, "texturegraphic.nim");
	{
		NCSTRING T5_;
		if (!((*graphic).fTexture == NIM_NIL)) goto LA3_;
		nimln_(110, "texturegraphic.nim");
		nimln_(112, "texturegraphic.nim");
		T5_ = (NCSTRING)0;
		T5_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t load image RW: %s", T5_);
		nimln_(113, "texturegraphic.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(114, "texturegraphic.nim");
	result = updateTexture_o5gIGNbuUX7M9aXENTS0MrQ(graphic);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, assignTexture_izBjDCMx0V6Mqi9afESEH9bw)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, void* texture, NIM_BOOL freeCurrent) {
	NIM_BOOL result;
	nimfr_("assignTexture", "texturegraphic.nim");
	result = (NIM_BOOL)0;
	nimln_(128, "texturegraphic.nim");
	{
		if (!freeCurrent) goto LA3_;
		nimln_(129, "texturegraphic.nim");
		freeTexture_TVIPFgvKm23EZwbfT9bLtlw(graphic);
	}
	LA3_: ;
	nimln_(130, "texturegraphic.nim");
	(*graphic).fTexture = texture;
	nimln_(131, "texturegraphic.nim");
	result = updateTexture_o5gIGNbuUX7M9aXENTS0MrQ(graphic);
	popFrame();
	return result;
}

static N_INLINE(void*, texture_rmsBaP9cgI9cIMw2Ufl6cQSQtexturegraphic)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic) {
	void* result;
	nimfr_("texture", "texturegraphic.nim");
	result = (void*)0;
	nimln_(135, "texturegraphic.nim");
	result = (*graphic).fTexture;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_tdrwAKYExl1bGpmSl0OZSw)(void* p, NI op) {
	tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* a;
	a = (tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ*)p;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ*, newTextureGraphic_FnSxV8ZkuJJUGeunVqnGuQ)(void) {
	tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* result;
	nimfr_("newTextureGraphic", "texturegraphic.nim");
	result = (tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ*)0;
	nimln_(141, "texturegraphic.nim");
	result = (tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ*) newObj((&NTI_tdrwAKYExl1bGpmSl0OZSw_), sizeof(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ));
	(*result).Sup.Sup.m_type = (&NTI_XO5Zgk1wZdddPxRev2t9aEQ_);
	nimln_(142, "texturegraphic.nim");
	init_TVIPFgvKm23EZwbfT9bLtlw_3(result);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ*, newTextureGraphic_0Ay11MhmFiBbDCfohNldJg)(NimStringDesc* file) {
	tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* result;
	NIM_BOOL T1_;
	nimfr_("newTextureGraphic", "texturegraphic.nim");
	result = (tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ*)0;
	nimln_(146, "texturegraphic.nim");
	result = newTextureGraphic_FnSxV8ZkuJJUGeunVqnGuQ();
	nimln_(147, "texturegraphic.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = load_MVqmhd3eEvdvf8UDCyvQNg(result, file);
	T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ*, newTextureGraphic_PywCtF7Yhabyne2iyrdefQ)(tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, NIM_BOOL freeSrc) {
	tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* result;
	NIM_BOOL T1_;
	nimfr_("newTextureGraphic", "texturegraphic.nim");
	result = (tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ*)0;
	nimln_(151, "texturegraphic.nim");
	result = newTextureGraphic_FnSxV8ZkuJJUGeunVqnGuQ();
	nimln_(152, "texturegraphic.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = load_bh9bbDkisoutTeH0q0Xg7QQ(result, src, freeSrc);
	T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ*, newTextureGraphic_0tHPchX6AKFowGHM3p9a7Dw)(void* texture) {
	tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* result;
	NIM_BOOL T1_;
	nimfr_("newTextureGraphic", "texturegraphic.nim");
	result = (tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ*)0;
	nimln_(156, "texturegraphic.nim");
	result = newTextureGraphic_FnSxV8ZkuJJUGeunVqnGuQ();
	nimln_(157, "texturegraphic.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = assignTexture_izBjDCMx0V6Mqi9afESEH9bw(result, texture, NIM_TRUE);
	T1_;
	popFrame();
	return result;
}

static N_INLINE(NI, w_4pYVftVR7bGh3MkKzaR9cbgtexturegraphic)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic) {
	NI result;
	nimfr_("w", "texturegraphic.nim");
	result = (NI)0;
	nimln_(161, "texturegraphic.nim");
	result = (*graphic).fSize.Field0;
	popFrame();
	return result;
}

static N_INLINE(NI, h_4pYVftVR7bGh3MkKzaR9cbg_2texturegraphic)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic) {
	NI result;
	nimfr_("h", "texturegraphic.nim");
	result = (NI)0;
	nimln_(165, "texturegraphic.nim");
	result = (*graphic).fSize.Field1;
	popFrame();
	return result;
}

static N_INLINE(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, dim_bCktJef7meJbpcLqB39cfhAtexturegraphic)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic) {
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ result;
	nimfr_("dim", "texturegraphic.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(169, "texturegraphic.nim");
	result = (*graphic).fSize;
	popFrame();
	return result;
}

static N_INLINE(void, stareq__7kHiltrvRlcg6wSYR3CxAwstrutils)(NF* x, NF y) {
	nimfr_("*=", "system.nim");
	nimln_(3710, "system.nim");
	(*x) = ((NF)((*x)) * (NF)(y));
	popFrame();
}

static N_INLINE(void, stareq__JY1gD4DsDLYjLacuUnapNQ_3types)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q* c, NF v) {
	nimfr_("*=", "types.nim");
	nimln_(338, "types.nim");
	stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*c).Field0), v);
	nimln_(339, "types.nim");
	stareq__7kHiltrvRlcg6wSYR3CxAwstrutils((&(*c).Field1), v);
	popFrame();
}

static N_INLINE(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, minus__j2pnXFSCXLnkC9a3JwzEgTw_2types)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c2) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	nimfr_("-", "types.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(271, "types.nim");
	result.Field0 = ((NF)(c1.Field0) - (NF)(c2.Field0));
	nimln_(272, "types.nim");
	result.Field1 = ((NF)(c1.Field1) - (NF)(c2.Field1));
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, drawTextureGraphic_iZaVEAoZEJ8MZ7GJqAyxBA)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NF angle, NF scale, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q center, tyEnum_Flip_qWHX0qRQS3EMdrguXFZZdA flip, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ region) {
	tyObject_Rect_qiXweduDJk1iLE5aHysNdQ empty;
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ size;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q cntr;
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q position;
	tyObject_Rect_qiXweduDJk1iLE5aHysNdQ dstRect;
	nimfr_("drawTextureGraphic", "texturegraphic.nim");
{	nimln_(194, "texturegraphic.nim");
	{
		if (!((*graphic).fTexture == NIM_NIL)) goto LA3_;
		nimln_(195, "texturegraphic.nim");
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(196, "texturegraphic.nim");
	{
		if (!(scale == 0.0)) goto LA7_;
		nimln_(197, "texturegraphic.nim");
		goto BeforeRet_;
	}
	LA7_: ;
	nimln_(200, "texturegraphic.nim");
	chckNil((void*)(&empty));
	memset((void*)(&empty), 0, sizeof(empty));
	empty.x = ((int) 0);
	empty.y = ((int) 0);
	empty.w = ((int) 0);
	empty.h = ((int) 0);
	nimln_(202, "texturegraphic.nim");
	{
		NIM_BOOL T11_;
		tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* T14_;
		T11_ = (NIM_BOOL)0;
		T11_ = eqeq__a05Mt4S1qT9bYa0L8KYON6A(region, empty);
		if (!T11_) goto LA12_;
		T14_ = (tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg*)0;
		T14_ = &graphic->Sup;
		size = dim_EIe1nJUG9bPRe4lU9b6M4seQ(T14_);
	}
	goto LA9_;
	LA12_: ;
	{
		size.Field0 = ((NI) (region.w));
		size.Field1 = ((NI) (region.h));
	}
	LA9_: ;
	nimln_(204, "texturegraphic.nim");
	cntr = center;
	nimln_(206, "texturegraphic.nim");
	{
		nimln_(398, "system.nim");
		nimln_(206, "texturegraphic.nim");
		if (!!((scale == 1.0000000000000000e+000))) goto LA18_;
		nimln_(207, "texturegraphic.nim");
		size.Field0 = ((NI) (((NF)(((NF) (size.Field0))) * (NF)(scale))));
		nimln_(208, "texturegraphic.nim");
		size.Field1 = ((NI) (((NF)(((NF) (size.Field1))) * (NF)(scale))));
		nimln_(209, "texturegraphic.nim");
		stareq__JY1gD4DsDLYjLacuUnapNQ_3types((&cntr), scale);
	}
	LA18_: ;
	nimln_(212, "texturegraphic.nim");
	position = minus__j2pnXFSCXLnkC9a3JwzEgTw_2types(pos, cntr);
	nimln_(213, "texturegraphic.nim");
	chckNil((void*)(&dstRect));
	memset((void*)(&dstRect), 0, sizeof(dstRect));
	dstRect.x = ((int) (position.Field0));
	dstRect.y = ((int) (position.Field1));
	dstRect.w = ((int)chckRange(size.Field0, ((int) (-2147483647 -1)), ((int) 2147483647)));
	dstRect.h = ((int)chckRange(size.Field1, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(216, "texturegraphic.nim");
	{
		NIM_BOOL T22_;
		T22_ = (NIM_BOOL)0;
		T22_ = (angle == 0.0);
		if (!(T22_)) goto LA23_;
		T22_ = (flip == ((tyEnum_Flip_qWHX0qRQS3EMdrguXFZZdA) 0));
		LA23_: ;
		if (!T22_) goto LA24_;
		nimln_(218, "texturegraphic.nim");
		{
			NIM_BOOL T28_;
			int T31_;
			T28_ = (NIM_BOOL)0;
			T28_ = eqeq__a05Mt4S1qT9bYa0L8KYON6A(region, empty);
			if (!T28_) goto LA29_;
			nimln_(219, "texturegraphic.nim");
			T31_ = (int)0;
			T31_ = Dl_155382_(renderer_M5l6pK6T79aB5LqtC0dmeOg, (*graphic).fTexture, NIM_NIL, (&dstRect));
			T31_;
		}
		goto LA26_;
		LA29_: ;
		{
			tyObject_Rect_qiXweduDJk1iLE5aHysNdQ srcRect;
			int T33_;
			nimln_(223, "texturegraphic.nim");
			srcRect = region;
			nimln_(224, "texturegraphic.nim");
			T33_ = (int)0;
			T33_ = Dl_155382_(renderer_M5l6pK6T79aB5LqtC0dmeOg, (*graphic).fTexture, (&srcRect), (&dstRect));
			T33_;
		}
		LA26_: ;
	}
	goto LA20_;
	LA24_: ;
	{
		tyObject_Point_O882QUBegNwSZhlvLsYQRw anchor;
		memset((void*)(&anchor), 0, sizeof(anchor));
		nimln_(232, "texturegraphic.nim");
		anchor.x = ((int) (cntr.Field0));
		nimln_(233, "texturegraphic.nim");
		anchor.y = ((int) (cntr.Field1));
		nimln_(235, "texturegraphic.nim");
		{
			NIM_BOOL T37_;
			int T40_;
			T37_ = (NIM_BOOL)0;
			T37_ = eqeq__a05Mt4S1qT9bYa0L8KYON6A(region, empty);
			if (!T37_) goto LA38_;
			nimln_(236, "texturegraphic.nim");
			T40_ = (int)0;
			T40_ = Dl_155390_(renderer_M5l6pK6T79aB5LqtC0dmeOg, (*graphic).fTexture, NIM_NIL, (&dstRect), angle, (&anchor), ((tyEnum_RendererFlip_v7zeNYRvzJgcDDS9cEco6wg) (flip)));
			T40_;
		}
		goto LA35_;
		LA38_: ;
		{
			tyObject_Rect_qiXweduDJk1iLE5aHysNdQ srcRect_2;
			int T42_;
			nimln_(243, "texturegraphic.nim");
			srcRect_2 = region;
			nimln_(244, "texturegraphic.nim");
			T42_ = (int)0;
			T42_ = Dl_155390_(renderer_M5l6pK6T79aB5LqtC0dmeOg, (*graphic).fTexture, (&srcRect_2), (&dstRect), angle, (&anchor), ((tyEnum_RendererFlip_v7zeNYRvzJgcDDS9cEco6wg) (flip)));
			T42_;
		}
		LA35_: ;
	}
	LA20_: ;
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, draw_iZaVEAoZEJ8MZ7GJqAyxBA_2)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos, NF angle, NF scale, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q center, tyEnum_Flip_qWHX0qRQS3EMdrguXFZZdA flip, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ region) {
	nimfr_("draw", "texturegraphic.nim");
	nimln_(259, "texturegraphic.nim");
	drawTextureGraphic_iZaVEAoZEJ8MZ7GJqAyxBA(graphic, pos, angle, scale, center, flip, region);
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_WP9as9aO1mXAo1uTvhN3g2LQ)(void* p, NI op) {
	tyObject_Env_texturegraphicdotnim__uFub4jMdWk7Mc5m2Y9bkWdA* a;
	a = (tyObject_Env_texturegraphicdotnim__uFub4jMdWk7Mc5m2Y9bkWdA*)p;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, drawTile_0JsNsTMlaBHN36igdj9aomQ)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* src, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* dst) {
	int T1_;
	nimfr_("drawTile", "texturegraphic.nim");
	nimln_(274, "texturegraphic.nim");
	T1_ = (int)0;
	T1_ = Dl_155382_(renderer_M5l6pK6T79aB5LqtC0dmeOg, (*graphic).fTexture, src, dst);
	T1_;
	popFrame();
}

N_LIB_PRIVATE N_CLOSURE(void, drawLine_ihJDU459bFX5661hgVbE0uA)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* src, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* dst, NI deltaX, NI endX, void* ClE_0) {
	tyObject_Env_texturegraphicdotnim__uFub4jMdWk7Mc5m2Y9bkWdA* colonenvP_;
	int startX;
	NI lastX;
	NI TM_iUjz9bRo1B8EXWVmzAlkVNA_12;
	nimfr_("drawLine", "texturegraphic.nim");
	colonenvP_ = (tyObject_Env_texturegraphicdotnim__uFub4jMdWk7Mc5m2Y9bkWdA*) ClE_0;
	nimln_(279, "texturegraphic.nim");
	startX = (*dst).x;
	nimln_(280, "texturegraphic.nim");
	TM_iUjz9bRo1B8EXWVmzAlkVNA_12 = subInt(endX, deltaX);
	lastX = (NI)(TM_iUjz9bRo1B8EXWVmzAlkVNA_12);
	nimln_(282, "texturegraphic.nim");
	{
		int T5_;
		NI TM_iUjz9bRo1B8EXWVmzAlkVNA_13;
		if (!(*colonenvP_).reverseX1) goto LA3_;
		T5_ = (int)0;
		T5_ = toCint_yAPwf7d9aO5za0vgIa7yl8g(deltaX);
		TM_iUjz9bRo1B8EXWVmzAlkVNA_13 = addInt((*dst).x, T5_);
		if (TM_iUjz9bRo1B8EXWVmzAlkVNA_13 < (-2147483647 -1) || TM_iUjz9bRo1B8EXWVmzAlkVNA_13 > 2147483647) raiseOverflow();
		(*dst).x = (int)(TM_iUjz9bRo1B8EXWVmzAlkVNA_13);
	}
	LA3_: ;
	{
		nimln_(283, "texturegraphic.nim");
		while (1) {
			NI TM_iUjz9bRo1B8EXWVmzAlkVNA_14;
			if (!(((NI) ((*dst).x)) < lastX)) goto LA7;
			nimln_(284, "texturegraphic.nim");
			drawTile_0JsNsTMlaBHN36igdj9aomQ(graphic, src, dst);
			nimln_(285, "texturegraphic.nim");
			TM_iUjz9bRo1B8EXWVmzAlkVNA_14 = addInt((*dst).x, (*dst).w);
			if (TM_iUjz9bRo1B8EXWVmzAlkVNA_14 < (-2147483647 -1) || TM_iUjz9bRo1B8EXWVmzAlkVNA_14 > 2147483647) raiseOverflow();
			(*dst).x = (int)(TM_iUjz9bRo1B8EXWVmzAlkVNA_14);
		} LA7: ;
	}
	nimln_(287, "texturegraphic.nim");
	{
		tyObject_Rect_qiXweduDJk1iLE5aHysNdQ partSrc;
		tyObject_Rect_qiXweduDJk1iLE5aHysNdQ T12_;
		tyObject_Rect_qiXweduDJk1iLE5aHysNdQ partDst;
		if (!(((NI) 0) < deltaX)) goto LA10_;
		nimln_(289, "texturegraphic.nim");
		memset((void*)(&T12_), 0, sizeof(T12_));
		T12_.x = (*src).x;
		T12_.y = (*src).y;
		T12_.w = toCint_yAPwf7d9aO5za0vgIa7yl8g(deltaX);
		T12_.h = (*src).h;
		partSrc = T12_;
		nimln_(290, "texturegraphic.nim");
		partDst = (*dst);
		nimln_(291, "texturegraphic.nim");
		{
			NI TM_iUjz9bRo1B8EXWVmzAlkVNA_15;
			if (!(*colonenvP_).reverseX1) goto LA15_;
			nimln_(292, "texturegraphic.nim");
			TM_iUjz9bRo1B8EXWVmzAlkVNA_15 = subInt(((NI) ((*src).w)), deltaX);
			partSrc.x = toCint_yAPwf7d9aO5za0vgIa7yl8g((NI)(TM_iUjz9bRo1B8EXWVmzAlkVNA_15));
			nimln_(293, "texturegraphic.nim");
			partSrc.y = (*src).y;
			nimln_(294, "texturegraphic.nim");
			partDst.x = startX;
		}
		LA15_: ;
		nimln_(295, "texturegraphic.nim");
		partDst.w = toCint_yAPwf7d9aO5za0vgIa7yl8g(deltaX);
		nimln_(296, "texturegraphic.nim");
		drawTile_0JsNsTMlaBHN36igdj9aomQ(graphic, (&partSrc), (&partDst));
	}
	LA10_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, drawTiled_aqjcU09a423NxGj9ccLenIvA)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ rect, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ region, NIM_BOOL reverseX, NIM_BOOL reverseY) {
	tyObject_Env_texturegraphicdotnim__uFub4jMdWk7Mc5m2Y9bkWdA* colonenv_;
	tyObject_Rect_qiXweduDJk1iLE5aHysNdQ srcRect;
	tyObject_Rect_qiXweduDJk1iLE5aHysNdQ dstRect;
	tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* T11_;
	NI T12_;
	tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* T13_;
	NI T14_;
	NI32 endX;
	NI TM_iUjz9bRo1B8EXWVmzAlkVNA_6;
	NI32 endY;
	NI TM_iUjz9bRo1B8EXWVmzAlkVNA_7;
	NI32 deltaX;
	NI TM_iUjz9bRo1B8EXWVmzAlkVNA_8;
	NI32 deltaY;
	NI TM_iUjz9bRo1B8EXWVmzAlkVNA_9;
	int startY;
	NI32 lastY;
	NI TM_iUjz9bRo1B8EXWVmzAlkVNA_10;
	nimfr_("drawTiled", "texturegraphic.nim");
	colonenv_ = (tyObject_Env_texturegraphicdotnim__uFub4jMdWk7Mc5m2Y9bkWdA*)0;
	nimln_(262, "texturegraphic.nim");
	colonenv_ = (tyObject_Env_texturegraphicdotnim__uFub4jMdWk7Mc5m2Y9bkWdA*) newObj((&NTI_WP9as9aO1mXAo1uTvhN3g2LQ_), sizeof(tyObject_Env_texturegraphicdotnim__uFub4jMdWk7Mc5m2Y9bkWdA));
	(*colonenv_).Sup.m_type = (&NTI_uFub4jMdWk7Mc5m2Y9bkWdA_);
	nimln_(265, "texturegraphic.nim");
	(*colonenv_).reverseX1 = reverseX;
	memset((void*)(&srcRect), 0, sizeof(srcRect));
	memset((void*)(&dstRect), 0, sizeof(dstRect));
	nimln_(300, "texturegraphic.nim");
	{
		NIM_BOOL T3_;
		tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* T6_;
		tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ T7_;
		tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* T8_;
		tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ T9_;
		T3_ = (NIM_BOOL)0;
		T3_ = eqeq__a05Mt4S1qT9bYa0L8KYON6A(region, TM_iUjz9bRo1B8EXWVmzAlkVNA_5);
		if (!T3_) goto LA4_;
		chckNil((void*)(&srcRect));
		memset((void*)(&srcRect), 0, sizeof(srcRect));
		srcRect.x = ((int) 0);
		srcRect.y = ((int) 0);
		nimln_(301, "texturegraphic.nim");
		T6_ = (tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg*)0;
		T6_ = &graphic->Sup;
		T7_ = dim_EIe1nJUG9bPRe4lU9b6M4seQ(T6_);
		srcRect.w = toCint_yAPwf7d9aO5za0vgIa7yl8g(T7_.Field0);
		T8_ = (tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg*)0;
		T8_ = &graphic->Sup;
		T9_ = dim_EIe1nJUG9bPRe4lU9b6M4seQ(T8_);
		srcRect.h = toCint_yAPwf7d9aO5za0vgIa7yl8g(T9_.Field1);
	}
	goto LA1_;
	LA4_: ;
	{
		srcRect = region;
	}
	LA1_: ;
	nimln_(304, "texturegraphic.nim");
	chckNil((void*)(&dstRect));
	memset((void*)(&dstRect), 0, sizeof(dstRect));
	dstRect.x = rect.x;
	dstRect.y = rect.y;
	T11_ = (tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg*)0;
	T11_ = &graphic->Sup;
	T12_ = (NI)0;
	T12_ = w_VokxRR2q72oBljkKbWBi9bg(T11_);
	dstRect.w = toCint_yAPwf7d9aO5za0vgIa7yl8g(T12_);
	T13_ = (tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg*)0;
	T13_ = &graphic->Sup;
	T14_ = (NI)0;
	T14_ = h_VokxRR2q72oBljkKbWBi9bg_2(T13_);
	dstRect.h = toCint_yAPwf7d9aO5za0vgIa7yl8g(T14_);
	nimln_(307, "texturegraphic.nim");
	TM_iUjz9bRo1B8EXWVmzAlkVNA_6 = addInt(rect.x, rect.w);
	if (TM_iUjz9bRo1B8EXWVmzAlkVNA_6 < (-2147483647 -1) || TM_iUjz9bRo1B8EXWVmzAlkVNA_6 > 2147483647) raiseOverflow();
	endX = (NI32)(TM_iUjz9bRo1B8EXWVmzAlkVNA_6);
	nimln_(308, "texturegraphic.nim");
	TM_iUjz9bRo1B8EXWVmzAlkVNA_7 = addInt(rect.y, rect.h);
	if (TM_iUjz9bRo1B8EXWVmzAlkVNA_7 < (-2147483647 -1) || TM_iUjz9bRo1B8EXWVmzAlkVNA_7 > 2147483647) raiseOverflow();
	endY = (NI32)(TM_iUjz9bRo1B8EXWVmzAlkVNA_7);
	nimln_(309, "texturegraphic.nim");
	TM_iUjz9bRo1B8EXWVmzAlkVNA_8 = modInt(rect.w, srcRect.w);
	if (TM_iUjz9bRo1B8EXWVmzAlkVNA_8 < (-2147483647 -1) || TM_iUjz9bRo1B8EXWVmzAlkVNA_8 > 2147483647) raiseOverflow();
	deltaX = (NI32)(TM_iUjz9bRo1B8EXWVmzAlkVNA_8);
	nimln_(310, "texturegraphic.nim");
	TM_iUjz9bRo1B8EXWVmzAlkVNA_9 = modInt(rect.h, srcRect.h);
	if (TM_iUjz9bRo1B8EXWVmzAlkVNA_9 < (-2147483647 -1) || TM_iUjz9bRo1B8EXWVmzAlkVNA_9 > 2147483647) raiseOverflow();
	deltaY = (NI32)(TM_iUjz9bRo1B8EXWVmzAlkVNA_9);
	nimln_(311, "texturegraphic.nim");
	startY = dstRect.y;
	nimln_(312, "texturegraphic.nim");
	TM_iUjz9bRo1B8EXWVmzAlkVNA_10 = subInt(endY, deltaY);
	if (TM_iUjz9bRo1B8EXWVmzAlkVNA_10 < (-2147483647 -1) || TM_iUjz9bRo1B8EXWVmzAlkVNA_10 > 2147483647) raiseOverflow();
	lastY = (NI32)(TM_iUjz9bRo1B8EXWVmzAlkVNA_10);
	nimln_(314, "texturegraphic.nim");
	{
		NI TM_iUjz9bRo1B8EXWVmzAlkVNA_11;
		if (!reverseY) goto LA17_;
		TM_iUjz9bRo1B8EXWVmzAlkVNA_11 = addInt(dstRect.y, deltaY);
		if (TM_iUjz9bRo1B8EXWVmzAlkVNA_11 < (-2147483647 -1) || TM_iUjz9bRo1B8EXWVmzAlkVNA_11 > 2147483647) raiseOverflow();
		dstRect.y = (int)(TM_iUjz9bRo1B8EXWVmzAlkVNA_11);
	}
	LA17_: ;
	{
		nimln_(315, "texturegraphic.nim");
		while (1) {
			tyProc_a7iqrcvoMsV1TcEUWb7YRQ T21_;
			NI TM_iUjz9bRo1B8EXWVmzAlkVNA_17;
			if (!(dstRect.y < lastY)) goto LA20;
			nimln_(316, "texturegraphic.nim");
			memset((void*)(&T21_), 0, sizeof(T21_));
			T21_.ClP_0 = drawLine_ihJDU459bFX5661hgVbE0uA; T21_.ClE_0 = colonenv_;
			T21_.ClE_0? T21_.ClP_0(graphic, (&srcRect), (&dstRect), ((NI) (deltaX)), ((NI) (endX)), T21_.ClE_0):((TM_iUjz9bRo1B8EXWVmzAlkVNA_16)(T21_.ClP_0))(graphic, (&srcRect), (&dstRect), ((NI) (deltaX)), ((NI) (endX)));
			nimln_(317, "texturegraphic.nim");
			dstRect.x = rect.x;
			nimln_(318, "texturegraphic.nim");
			TM_iUjz9bRo1B8EXWVmzAlkVNA_17 = addInt(dstRect.y, dstRect.h);
			if (TM_iUjz9bRo1B8EXWVmzAlkVNA_17 < (-2147483647 -1) || TM_iUjz9bRo1B8EXWVmzAlkVNA_17 > 2147483647) raiseOverflow();
			dstRect.y = (int)(TM_iUjz9bRo1B8EXWVmzAlkVNA_17);
		} LA20: ;
	}
	nimln_(320, "texturegraphic.nim");
	{
		tyProc_a7iqrcvoMsV1TcEUWb7YRQ T30_;
		if (!(((NI32) 0) < deltaY)) goto LA24_;
		nimln_(321, "texturegraphic.nim");
		srcRect.x = ((int) 0);
		nimln_(322, "texturegraphic.nim");
		srcRect.y = ((int) 0);
		nimln_(323, "texturegraphic.nim");
		{
			NI TM_iUjz9bRo1B8EXWVmzAlkVNA_18;
			if (!reverseY) goto LA28_;
			nimln_(324, "texturegraphic.nim");
			TM_iUjz9bRo1B8EXWVmzAlkVNA_18 = subInt(srcRect.h, deltaY);
			if (TM_iUjz9bRo1B8EXWVmzAlkVNA_18 < (-2147483647 -1) || TM_iUjz9bRo1B8EXWVmzAlkVNA_18 > 2147483647) raiseOverflow();
			srcRect.y = (NI32)(TM_iUjz9bRo1B8EXWVmzAlkVNA_18);
			nimln_(325, "texturegraphic.nim");
			dstRect.y = startY;
		}
		LA28_: ;
		nimln_(326, "texturegraphic.nim");
		srcRect.h = deltaY;
		nimln_(327, "texturegraphic.nim");
		dstRect.h = deltaY;
		nimln_(328, "texturegraphic.nim");
		memset((void*)(&T30_), 0, sizeof(T30_));
		T30_.ClP_0 = drawLine_ihJDU459bFX5661hgVbE0uA; T30_.ClE_0 = colonenv_;
		T30_.ClE_0? T30_.ClP_0(graphic, (&srcRect), (&dstRect), ((NI) (deltaX)), ((NI) (endX)), T30_.ClE_0):((TM_iUjz9bRo1B8EXWVmzAlkVNA_19)(T30_.ClP_0))(graphic, (&srcRect), (&dstRect), ((NI) (deltaX)), ((NI) (endX)));
	}
	LA24_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Color_YizDHyEvJtgQk2fn8KdZUA, colorMod_zm9akqyhW5blM0A21i08UkQ)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic) {
	tyObject_Color_YizDHyEvJtgQk2fn8KdZUA result;
	NU8 r;
	NU8 g;
	NU8 b;
	nimfr_("colorMod", "texturegraphic.nim");
{	memset((void*)(&result), 0, sizeof(result));
	r = (NU8)0;
	g = (NU8)0;
	b = (NU8)0;
	nimln_(335, "texturegraphic.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.r = ((NU8) 0);
	result.g = ((NU8) 0);
	result.b = ((NU8) 0);
	result.a = ((NU8) 0);
	nimln_(337, "texturegraphic.nim");
	{
		int T3_;
		NCSTRING T6_;
		nimln_(398, "system.nim");
		nimln_(337, "texturegraphic.nim");
		T3_ = (int)0;
		T3_ = Dl_155170_((*graphic).fTexture, (&r), (&g), (&b));
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		nimln_(338, "texturegraphic.nim");
		nimln_(340, "texturegraphic.nim");
		T6_ = (NCSTRING)0;
		T6_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t get texture color mod: %s", T6_);
		nimln_(341, "texturegraphic.nim");
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(343, "texturegraphic.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.r = r;
	result.g = g;
	result.b = b;
	result.a = ((NU8) 255);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, colorModeq__lf2VXq9cmoMc9bycgmqCnz1Q)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA color) {
	nimfr_("colorMod=", "texturegraphic.nim");
	nimln_(349, "texturegraphic.nim");
	{
		int T3_;
		NCSTRING T6_;
		nimln_(398, "system.nim");
		nimln_(349, "texturegraphic.nim");
		T3_ = (int)0;
		T3_ = Dl_155160_((*graphic).fTexture, color.r, color.g, color.b);
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		nimln_(350, "texturegraphic.nim");
		nimln_(352, "texturegraphic.nim");
		T6_ = (NCSTRING)0;
		T6_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t set texture color mod: %s", T6_);
	}
	LA4_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NU8, alphaMod_zPXx2AkXI59cBFY4IYzj3Sw)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic) {
	NU8 result;
	NU8 a;
	nimfr_("alphaMod", "texturegraphic.nim");
{	result = (NU8)0;
	a = (NU8)0;
	nimln_(359, "texturegraphic.nim");
	{
		int T3_;
		NCSTRING T6_;
		nimln_(398, "system.nim");
		nimln_(359, "texturegraphic.nim");
		T3_ = (int)0;
		T3_ = Dl_155187_((*graphic).fTexture, (&a));
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		nimln_(360, "texturegraphic.nim");
		nimln_(362, "texturegraphic.nim");
		T6_ = (NCSTRING)0;
		T6_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t get texture alpha mod: %s", T6_);
		nimln_(363, "texturegraphic.nim");
		result = ((NU8) 255);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(364, "texturegraphic.nim");
	result = a;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, alphaModeq__4RMJgcbaGjKTC7hn36z1Pg)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, NU8 alpha) {
	nimfr_("alphaMod=", "texturegraphic.nim");
	nimln_(370, "texturegraphic.nim");
	{
		int T3_;
		NCSTRING T6_;
		nimln_(398, "system.nim");
		nimln_(370, "texturegraphic.nim");
		T3_ = (int)0;
		T3_ = Dl_155183_((*graphic).fTexture, alpha);
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		nimln_(371, "texturegraphic.nim");
		nimln_(373, "texturegraphic.nim");
		T6_ = (NCSTRING)0;
		T6_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t set texture alpha mod: %s", T6_);
	}
	LA4_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_Blend_j9a9czwucCcTZ69cftFUpcNJA, blendMod_GiLgryKZfy4KMjTfguCoCQ)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic) {
	tyEnum_Blend_j9a9czwucCcTZ69cftFUpcNJA result;
	tyEnum_BlendMode_acuvsAfHtuIf9ats9aWCQoeQ blend;
	nimfr_("blendMod", "texturegraphic.nim");
{	result = (tyEnum_Blend_j9a9czwucCcTZ69cftFUpcNJA)0;
	blend = (tyEnum_BlendMode_acuvsAfHtuIf9ats9aWCQoeQ)0;
	nimln_(381, "texturegraphic.nim");
	{
		int T3_;
		NCSTRING T6_;
		nimln_(398, "system.nim");
		nimln_(381, "texturegraphic.nim");
		T3_ = (int)0;
		T3_ = Dl_155196_((*graphic).fTexture, (&blend));
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		nimln_(382, "texturegraphic.nim");
		nimln_(384, "texturegraphic.nim");
		T6_ = (NCSTRING)0;
		T6_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t get texture blend mode: %s", T6_);
		nimln_(385, "texturegraphic.nim");
		result = ((tyEnum_Blend_j9a9czwucCcTZ69cftFUpcNJA) 0);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(386, "texturegraphic.nim");
	result = ((tyEnum_Blend_j9a9czwucCcTZ69cftFUpcNJA)chckRange(blend, ((tyEnum_Blend_j9a9czwucCcTZ69cftFUpcNJA) 0), ((tyEnum_Blend_j9a9czwucCcTZ69cftFUpcNJA) 4)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, blendModeq__QDfuMY32f9c7H6lDqNvRoXw)(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ* graphic, tyEnum_Blend_j9a9czwucCcTZ69cftFUpcNJA blend) {
	nimfr_("blendMod=", "texturegraphic.nim");
	nimln_(392, "texturegraphic.nim");
	{
		int T3_;
		NCSTRING T6_;
		nimln_(398, "system.nim");
		nimln_(392, "texturegraphic.nim");
		T3_ = (int)0;
		T3_ = Dl_155192_((*graphic).fTexture, ((tyEnum_BlendMode_acuvsAfHtuIf9ats9aWCQoeQ) (blend)));
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		nimln_(393, "texturegraphic.nim");
		nimln_(395, "texturegraphic.nim");
		T6_ = (NCSTRING)0;
		T6_ = Dl_147926_();
		Dl_154881_(((tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw) 1), "Can\'t set texture blend mode: %s", T6_);
	}
	LA4_: ;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, nimgame2_texturegraphicInit000)(void) {
	nimfr_("texturegraphic", "texturegraphic.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimgame2_texturegraphicDatInit000)(void) {
static TNimNode* TM_iUjz9bRo1B8EXWVmzAlkVNA_3[3];
static TNimNode* TM_iUjz9bRo1B8EXWVmzAlkVNA_4[2];
static TNimNode TM_iUjz9bRo1B8EXWVmzAlkVNA_0[7];
NTI_XO5Zgk1wZdddPxRev2t9aEQ_.size = sizeof(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ);
NTI_XO5Zgk1wZdddPxRev2t9aEQ_.kind = 17;
NTI_XO5Zgk1wZdddPxRev2t9aEQ_.base = (&NTI_W9c5ORj7z7QIE1MjKJgJgFg_);
NTI_XO5Zgk1wZdddPxRev2t9aEQ_.flags = 1;
TM_iUjz9bRo1B8EXWVmzAlkVNA_3[0] = &TM_iUjz9bRo1B8EXWVmzAlkVNA_0[1];
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[1].kind = 1;
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[1].offset = offsetof(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ, fTexture);
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[1].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[1].name = "fTexture";
TM_iUjz9bRo1B8EXWVmzAlkVNA_3[1] = &TM_iUjz9bRo1B8EXWVmzAlkVNA_0[2];
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[2].kind = 1;
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[2].offset = offsetof(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ, fFormat);
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[2].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[2].name = "fFormat";
TM_iUjz9bRo1B8EXWVmzAlkVNA_3[2] = &TM_iUjz9bRo1B8EXWVmzAlkVNA_0[3];
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[3].kind = 1;
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[3].offset = offsetof(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ, fSize);
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[3].typ = (&NTI_1v9bKyksXWMsm0vNwmZ4EuQ_);
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[3].name = "fSize";
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[0].len = 3; TM_iUjz9bRo1B8EXWVmzAlkVNA_0[0].kind = 2; TM_iUjz9bRo1B8EXWVmzAlkVNA_0[0].sons = &TM_iUjz9bRo1B8EXWVmzAlkVNA_3[0];
NTI_XO5Zgk1wZdddPxRev2t9aEQ_.node = &TM_iUjz9bRo1B8EXWVmzAlkVNA_0[0];
NTI_tdrwAKYExl1bGpmSl0OZSw_.size = sizeof(tyObject_TextureGraphiccolonObjectType__XO5Zgk1wZdddPxRev2t9aEQ*);
NTI_tdrwAKYExl1bGpmSl0OZSw_.kind = 22;
NTI_tdrwAKYExl1bGpmSl0OZSw_.base = (&NTI_XO5Zgk1wZdddPxRev2t9aEQ_);
NTI_tdrwAKYExl1bGpmSl0OZSw_.marker = Marker_tyRef_tdrwAKYExl1bGpmSl0OZSw;
(&NTI_tdrwAKYExl1bGpmSl0OZSw_)->finalizer = (void*)free_TVIPFgvKm23EZwbfT9bLtlw_2;
NTI_uFub4jMdWk7Mc5m2Y9bkWdA_.size = sizeof(tyObject_Env_texturegraphicdotnim__uFub4jMdWk7Mc5m2Y9bkWdA);
NTI_uFub4jMdWk7Mc5m2Y9bkWdA_.kind = 17;
NTI_uFub4jMdWk7Mc5m2Y9bkWdA_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_uFub4jMdWk7Mc5m2Y9bkWdA_.flags = 1;
TM_iUjz9bRo1B8EXWVmzAlkVNA_4[0] = &TM_iUjz9bRo1B8EXWVmzAlkVNA_0[5];
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[5].kind = 1;
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[5].offset = offsetof(tyObject_Env_texturegraphicdotnim__uFub4jMdWk7Mc5m2Y9bkWdA, colonstate_);
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[5].typ = (&NTI_xHTZrq9aYs6boc9bCba0JbpQ_);
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[5].name = ":state";
TM_iUjz9bRo1B8EXWVmzAlkVNA_4[1] = &TM_iUjz9bRo1B8EXWVmzAlkVNA_0[6];
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[6].kind = 1;
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[6].offset = offsetof(tyObject_Env_texturegraphicdotnim__uFub4jMdWk7Mc5m2Y9bkWdA, reverseX1);
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[6].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[6].name = "reverseX1";
TM_iUjz9bRo1B8EXWVmzAlkVNA_0[4].len = 2; TM_iUjz9bRo1B8EXWVmzAlkVNA_0[4].kind = 2; TM_iUjz9bRo1B8EXWVmzAlkVNA_0[4].sons = &TM_iUjz9bRo1B8EXWVmzAlkVNA_4[0];
NTI_uFub4jMdWk7Mc5m2Y9bkWdA_.node = &TM_iUjz9bRo1B8EXWVmzAlkVNA_0[4];
NTI_WP9as9aO1mXAo1uTvhN3g2LQ_.size = sizeof(tyObject_Env_texturegraphicdotnim__uFub4jMdWk7Mc5m2Y9bkWdA*);
NTI_WP9as9aO1mXAo1uTvhN3g2LQ_.kind = 22;
NTI_WP9as9aO1mXAo1uTvhN3g2LQ_.base = (&NTI_uFub4jMdWk7Mc5m2Y9bkWdA_);
NTI_WP9as9aO1mXAo1uTvhN3g2LQ_.marker = Marker_tyRef_WP9as9aO1mXAo1uTvhN3g2LQ;
}

