/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\Users\Alterna\Documents\nim-0.18.0\lib -o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\nimgame2_scene.o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\nimgame2_scene.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_ABvfaE9beHzEcUOwofFJ5yg tySequence_ABvfaE9beHzEcUOwofFJ5yg;
typedef struct tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ;
typedef struct tyTuple_wpFMp8IwxV6MlaM4GANJ0Q tyTuple_wpFMp8IwxV6MlaM4GANJ0Q;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct TGenericSeq TGenericSeq;
typedef union tyObject_Event_QLORHniUO5yE9cFPjAVIQUQ tyObject_Event_QLORHniUO5yE9cFPjAVIQUQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg;
typedef struct tyObject_SpritecolonObjectType__I8eJwU4XNzQLr2ecdbCLaw tyObject_SpritecolonObjectType__I8eJwU4XNzQLr2ecdbCLaw;
typedef struct tyObject_CollidercolonObjectType__zBNkeiXjkkPoCkXQ9afyuhQ tyObject_CollidercolonObjectType__zBNkeiXjkkPoCkXQ9afyuhQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_CommonEventObj_U66FPCFgDSbmlcOHqT5Evg tyObject_CommonEventObj_U66FPCFgDSbmlcOHqT5Evg;
typedef struct tyObject_WindowEventObj_HBP9bGvXZ9cfsCLYB1W6CBWg tyObject_WindowEventObj_HBP9bGvXZ9cfsCLYB1W6CBWg;
typedef struct tyObject_KeyboardEventObj_Dgl9ajEnawue8OG9aYGwSYbA tyObject_KeyboardEventObj_Dgl9ajEnawue8OG9aYGwSYbA;
typedef struct tyObject_Keysym_F9bEEu9clWcmI0vvyozr9a4Tw tyObject_Keysym_F9bEEu9clWcmI0vvyozr9a4Tw;
typedef struct tyObject_TextEditingEventObj_4AU9cO5RL5ZL4hmpgH3Jyzg tyObject_TextEditingEventObj_4AU9cO5RL5ZL4hmpgH3Jyzg;
typedef struct tyObject_TextInputEventObj_S9cLtDyk9axj9aA9clgun09c5Ew tyObject_TextInputEventObj_S9cLtDyk9axj9aA9clgun09c5Ew;
typedef struct tyObject_MouseMotionEventObj_Y5AiWYph9bMQ3GmyLOmToig tyObject_MouseMotionEventObj_Y5AiWYph9bMQ3GmyLOmToig;
typedef struct tyObject_MouseButtonEventObj_oaAf9csV57uDbAJMQu9aLB4g tyObject_MouseButtonEventObj_oaAf9csV57uDbAJMQu9aLB4g;
typedef struct tyObject_MouseWheelEventObj_pHTMxw9akKBFiwZnl89aPqHA tyObject_MouseWheelEventObj_pHTMxw9akKBFiwZnl89aPqHA;
typedef struct tyObject_JoyAxisEventObj_9almo0Qaqu9aJI54QQBFQtxw tyObject_JoyAxisEventObj_9almo0Qaqu9aJI54QQBFQtxw;
typedef struct tyObject_JoyBallEventObj_RpVDnVNhcJe4TgE9b9cBTQyA tyObject_JoyBallEventObj_RpVDnVNhcJe4TgE9b9cBTQyA;
typedef struct tyObject_JoyHatEventObj_mT1NMwB9bgI2VnTkrYRUIfw tyObject_JoyHatEventObj_mT1NMwB9bgI2VnTkrYRUIfw;
typedef struct tyObject_JoyButtonEventObj_nyLCEn9bu9c9bD34sZSYrZKpA tyObject_JoyButtonEventObj_nyLCEn9bu9c9bD34sZSYrZKpA;
typedef struct tyObject_JoyDeviceEventObj_V7ZbnyDb6P6GWjH1BlzlWA tyObject_JoyDeviceEventObj_V7ZbnyDb6P6GWjH1BlzlWA;
typedef struct tyObject_ControllerAxisEventObj_HZEfvgUe1nwZN4Lfp9bSltg tyObject_ControllerAxisEventObj_HZEfvgUe1nwZN4Lfp9bSltg;
typedef struct tyObject_ControllerButtonEventObj_vFJG0ERJ9byeZvGy7hGG9cAA tyObject_ControllerButtonEventObj_vFJG0ERJ9byeZvGy7hGG9cAA;
typedef struct tyObject_ControllerDeviceEventObj_hNueoLSiKNHag4YYAV7iMw tyObject_ControllerDeviceEventObj_hNueoLSiKNHag4YYAV7iMw;
typedef struct tyObject_AudioDeviceEventObj_XI9bTqUH9cIPyHTibgkMxZrQ tyObject_AudioDeviceEventObj_XI9bTqUH9cIPyHTibgkMxZrQ;
typedef struct tyObject_QuitEventObj_b9aT3LGnCHReVoiRUmUOH6Q tyObject_QuitEventObj_b9aT3LGnCHReVoiRUmUOH6Q;
typedef struct tyObject_UserEventObj_Zjaeqi8Qb8tdMBVF5j19aBg tyObject_UserEventObj_Zjaeqi8Qb8tdMBVF5j19aBg;
typedef struct tyObject_SysWMEventObj_NVNWXaYFlMqYyeJw89cqUmw tyObject_SysWMEventObj_NVNWXaYFlMqYyeJw89cqUmw;
typedef struct tyObject_TouchFingerEventObj_a2BGLpKFgONBTuDEalsX9bg tyObject_TouchFingerEventObj_a2BGLpKFgONBTuDEalsX9bg;
typedef struct tyObject_MultiGestureEventObj_aD7Jwxj5RkeR6dZxbx4v9cQ tyObject_MultiGestureEventObj_aD7Jwxj5RkeR6dZxbx4v9cQ;
typedef struct tyObject_DollarGestureEventObj_9afGfbHjuc5BDKXR9aYAnpJg tyObject_DollarGestureEventObj_9afGfbHjuc5BDKXR9aYAnpJg;
typedef struct tyObject_DropEventObj_M4TEepExXfQepg9bRejOs1A tyObject_DropEventObj_M4TEepExXfQepg9bRejOs1A;
typedef struct tySequence_ur2pN1NPtVVZt5iFb87hig tySequence_ur2pN1NPtVVZt5iFb87hig;
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tySequence_42HkjPs5lPuA0zCz0ayouw tySequence_42HkjPs5lPuA0zCz0ayouw;
typedef struct tyObject_Animation_ZjJFzPlbPkEoLRYA69bG6Eg tyObject_Animation_ZjJFzPlbPkEoLRYA69bG6Eg;
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ tyObject_Rect_qiXweduDJk1iLE5aHysNdQ;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct tyTuple_wpFMp8IwxV6MlaM4GANJ0Q {
NF Field0;
NF Field1;
};
struct tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA {
  RootObj Sup;
tySequence_ABvfaE9beHzEcUOwofFJ5yg* fList;
tySequence_ABvfaE9beHzEcUOwofFJ5yg* fAddList;
tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* camera;
tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* cameraBond;
tyTuple_wpFMp8IwxV6MlaM4GANJ0Q cameraBondOffset;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity, NF elapsed, void* ClE_0);
void* ClE_0;
} tyProc_CrS6eUTvVPte7p19c4m57eQ;
typedef NI32 tyEnum_Flip_qWHX0qRQS3EMdrguXFZZdA;
struct tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ {
  RootObj Sup;
NI fLayer;
NF fBlinkTimer;
tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* parent;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* tags;
NIM_BOOL dead;
NIM_BOOL updLayer;
tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg* graphic;
tyObject_SpritecolonObjectType__I8eJwU4XNzQLr2ecdbCLaw* sprite;
tyProc_CrS6eUTvVPte7p19c4m57eQ logic;
tyProc_CrS6eUTvVPte7p19c4m57eQ physics;
NIM_BOOL fastPhysics;
tySequence_ABvfaE9beHzEcUOwofFJ5yg* collisionEnvironment;
tyObject_CollidercolonObjectType__zBNkeiXjkkPoCkXQ9afyuhQ* collider;
tySequence_ABvfaE9beHzEcUOwofFJ5yg* colliding;
tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos;
tyTuple_wpFMp8IwxV6MlaM4GANJ0Q vel;
tyTuple_wpFMp8IwxV6MlaM4GANJ0Q acc;
tyTuple_wpFMp8IwxV6MlaM4GANJ0Q drg;
NF rot;
NF rotVel;
NF rotAcc;
NF rotDrg;
NF parallax;
NF scale;
NF scaleVel;
NF scaleAcc;
NF scaleDrg;
tyTuple_wpFMp8IwxV6MlaM4GANJ0Q center;
tyEnum_Flip_qWHX0qRQS3EMdrguXFZZdA flip;
NIM_BOOL visible;
NIM_BOOL blinking;
NF blinkOn;
NF blinkOff;
};
typedef NU8 tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef NU8 tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ;
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef NI32 tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA;
struct tyObject_CommonEventObj_U66FPCFgDSbmlcOHqT5Evg {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
};
typedef NU8 tyEnum_WindowEventID_4pBj089cDcviznpP9amV8ALg;
struct tyObject_WindowEventObj_HBP9bGvXZ9cfsCLYB1W6CBWg {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 windowID;
tyEnum_WindowEventID_4pBj089cDcviznpP9amV8ALg event;
NU8 padding1;
NU8 padding2;
NU8 padding3;
NI32 data1;
NI32 data2;
};
typedef NI32 tyEnum_Scancode_GQzt28Vd9bjjGKwYsdVggVg;
typedef NI32 tyEnum_Keycode_gca09as4xPHN0YKkZ6i0fwg;
struct tyObject_Keysym_F9bEEu9clWcmI0vvyozr9a4Tw {
tyEnum_Scancode_GQzt28Vd9bjjGKwYsdVggVg scancode;
tyEnum_Keycode_gca09as4xPHN0YKkZ6i0fwg sym;
NU16 mods;
NU32 unused;
};
struct tyObject_KeyboardEventObj_Dgl9ajEnawue8OG9aYGwSYbA {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 windowID;
NU8 state;
NU8 repeat;
NU8 padding2;
NU8 padding3;
tyObject_Keysym_F9bEEu9clWcmI0vvyozr9a4Tw keysym;
};
typedef NIM_CHAR tyArray_x9aRkN8DVcTBDUl3hEPJutg[32];
struct tyObject_TextEditingEventObj_4AU9cO5RL5ZL4hmpgH3Jyzg {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 windowID;
tyArray_x9aRkN8DVcTBDUl3hEPJutg text;
NI32 start;
NI32 length;
};
struct tyObject_TextInputEventObj_S9cLtDyk9axj9aA9clgun09c5Ew {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 windowID;
tyArray_x9aRkN8DVcTBDUl3hEPJutg text;
};
struct tyObject_MouseMotionEventObj_Y5AiWYph9bMQ3GmyLOmToig {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 windowID;
NU32 which;
NU32 state;
NI32 x;
NI32 y;
NI32 xrel;
NI32 yrel;
};
struct tyObject_MouseButtonEventObj_oaAf9csV57uDbAJMQu9aLB4g {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 windowID;
NU32 which;
NU8 button;
NU8 state;
NU8 clicks;
NU8 padding1;
NI32 x;
NI32 y;
};
typedef NI32 tyEnum_MouseWheelDirection_ZdgUQMIRg26TpKLhSp2wQw;
struct tyObject_MouseWheelEventObj_pHTMxw9akKBFiwZnl89aPqHA {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 windowID;
NU32 which;
NI32 x;
NI32 y;
tyEnum_MouseWheelDirection_ZdgUQMIRg26TpKLhSp2wQw direction;
};
struct tyObject_JoyAxisEventObj_9almo0Qaqu9aJI54QQBFQtxw {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI32 which;
NU8 axis;
NU8 padding1;
NU8 padding2;
NU8 padding3;
NI16 value;
NU16 padding4;
};
struct tyObject_JoyBallEventObj_RpVDnVNhcJe4TgE9b9cBTQyA {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI32 which;
NU8 ball;
NU8 padding1;
NU8 padding2;
NU8 padding3;
NI16 xrel;
NI16 yrel;
};
typedef NU8 tyEnum_HatPosition_WXrdDcbfAWDwkLkWu9c0m2w;
struct tyObject_JoyHatEventObj_mT1NMwB9bgI2VnTkrYRUIfw {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI32 which;
NU8 hat;
tyEnum_HatPosition_WXrdDcbfAWDwkLkWu9c0m2w value;
NU8 padding1;
NU8 padding2;
};
struct tyObject_JoyButtonEventObj_nyLCEn9bu9c9bD34sZSYrZKpA {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI32 which;
NU8 button;
NU8 state;
NU8 padding1;
NU8 padding2;
};
struct tyObject_JoyDeviceEventObj_V7ZbnyDb6P6GWjH1BlzlWA {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI32 which;
};
typedef NU8 tyEnum_GameControllerAxis_SZ9c5QxUIAU7GwhI6uAzqsA;
struct tyObject_ControllerAxisEventObj_HZEfvgUe1nwZN4Lfp9bSltg {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI32 which;
tyEnum_GameControllerAxis_SZ9c5QxUIAU7GwhI6uAzqsA axis;
NU8 padding1;
NU8 padding2;
NU8 padding3;
NI16 value;
NU16 padding4;
};
typedef NU8 tyEnum_GameControllerButton_GCZhKAmuNz63NHEW2cMy6g;
struct tyObject_ControllerButtonEventObj_vFJG0ERJ9byeZvGy7hGG9cAA {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI32 which;
tyEnum_GameControllerButton_GCZhKAmuNz63NHEW2cMy6g button;
NU8 state;
NU8 padding1;
NU8 padding2;
};
struct tyObject_ControllerDeviceEventObj_hNueoLSiKNHag4YYAV7iMw {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI32 which;
};
struct tyObject_AudioDeviceEventObj_XI9bTqUH9cIPyHTibgkMxZrQ {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 which;
NU8 iscapture;
NU8 padding1;
NU8 padding2;
NU8 padding3;
};
struct tyObject_QuitEventObj_b9aT3LGnCHReVoiRUmUOH6Q {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
};
struct tyObject_UserEventObj_Zjaeqi8Qb8tdMBVF5j19aBg {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 windowID;
NI32 code;
void* data1;
void* data2;
};
struct tyObject_SysWMEventObj_NVNWXaYFlMqYyeJw89cqUmw {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
void* msg;
};
struct tyObject_TouchFingerEventObj_a2BGLpKFgONBTuDEalsX9bg {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI64 touchId;
NI64 fingerId;
float x;
float y;
float dx;
float dy;
float pressure;
};
struct tyObject_MultiGestureEventObj_aD7Jwxj5RkeR6dZxbx4v9cQ {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI64 touchId;
float dTheta;
float dDist;
float x;
float y;
NU16 numFingers;
NU16 padding;
};
struct tyObject_DollarGestureEventObj_9afGfbHjuc5BDKXR9aYAnpJg {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI64 touchId;
NI64 gestureId;
NU32 numFingers;
float error;
float x;
float y;
};
struct tyObject_DropEventObj_M4TEepExXfQepg9bRejOs1A {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NCSTRING file;
NU32 windowID;
};
typedef NU8 tyArray_sH9avbK619blGCGFZhgSDaWg[56];
union tyObject_Event_QLORHniUO5yE9cFPjAVIQUQ {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
tyObject_CommonEventObj_U66FPCFgDSbmlcOHqT5Evg common;
tyObject_WindowEventObj_HBP9bGvXZ9cfsCLYB1W6CBWg window;
tyObject_KeyboardEventObj_Dgl9ajEnawue8OG9aYGwSYbA key;
tyObject_TextEditingEventObj_4AU9cO5RL5ZL4hmpgH3Jyzg edit;
tyObject_TextInputEventObj_S9cLtDyk9axj9aA9clgun09c5Ew text;
tyObject_MouseMotionEventObj_Y5AiWYph9bMQ3GmyLOmToig motion;
tyObject_MouseButtonEventObj_oaAf9csV57uDbAJMQu9aLB4g button;
tyObject_MouseWheelEventObj_pHTMxw9akKBFiwZnl89aPqHA wheel;
tyObject_JoyAxisEventObj_9almo0Qaqu9aJI54QQBFQtxw jaxis;
tyObject_JoyBallEventObj_RpVDnVNhcJe4TgE9b9cBTQyA jball;
tyObject_JoyHatEventObj_mT1NMwB9bgI2VnTkrYRUIfw jhat;
tyObject_JoyButtonEventObj_nyLCEn9bu9c9bD34sZSYrZKpA jbutton;
tyObject_JoyDeviceEventObj_V7ZbnyDb6P6GWjH1BlzlWA jdevice;
tyObject_ControllerAxisEventObj_HZEfvgUe1nwZN4Lfp9bSltg caxis;
tyObject_ControllerButtonEventObj_vFJG0ERJ9byeZvGy7hGG9cAA cbutton;
tyObject_ControllerDeviceEventObj_hNueoLSiKNHag4YYAV7iMw cdevice;
tyObject_AudioDeviceEventObj_XI9bTqUH9cIPyHTibgkMxZrQ adevice;
tyObject_QuitEventObj_b9aT3LGnCHReVoiRUmUOH6Q quit;
tyObject_UserEventObj_Zjaeqi8Qb8tdMBVF5j19aBg user;
tyObject_SysWMEventObj_NVNWXaYFlMqYyeJw89cqUmw syswm;
tyObject_TouchFingerEventObj_a2BGLpKFgONBTuDEalsX9bg tfinger;
tyObject_MultiGestureEventObj_aD7Jwxj5RkeR6dZxbx4v9cQ mgesture;
tyObject_DollarGestureEventObj_9afGfbHjuc5BDKXR9aYAnpJg dgesture;
tyObject_DropEventObj_M4TEepExXfQepg9bRejOs1A drop;
tyArray_sH9avbK619blGCGFZhgSDaWg padding;
};
struct tyObject_GraphiccolonObjectType__W9c5ORj7z7QIE1MjKJgJgFg {
  RootObj Sup;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity, NI index, void* ClE_0);
void* ClE_0;
} tyProc_slvfuk36VyBonNLFcXbyMw;
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
struct tyObject_SpritecolonObjectType__I8eJwU4XNzQLr2ecdbCLaw {
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* animationKeys;
tySequence_ur2pN1NPtVVZt5iFb87hig* animations;
NI currentAnimationIndex;
NI currentFrame;
NI cycles;
NIM_BOOL kill;
tyProc_slvfuk36VyBonNLFcXbyMw callback;
NF time;
NIM_BOOL playing;
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ dim;
tySequence_42HkjPs5lPuA0zCz0ayouw* frames;
};
struct tyObject_CollidercolonObjectType__zBNkeiXjkkPoCkXQ9afyuhQ {
  RootObj Sup;
tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* parent;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* tags;
tyTuple_wpFMp8IwxV6MlaM4GANJ0Q pos;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tyObject_Animation_ZjJFzPlbPkEoLRYA69bG6Eg {
tySequence_qwqHTkRvwhrRyENtudHQ7g* frames;
NF frameRate;
tyEnum_Flip_qWHX0qRQS3EMdrguXFZZdA flip;
};
struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ {
int x;
int y;
int w;
int h;
};
struct tySequence_ABvfaE9beHzEcUOwofFJ5yg {
  TGenericSeq Sup;
  tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_ur2pN1NPtVVZt5iFb87hig {
  TGenericSeq Sup;
  tyObject_Animation_ZjJFzPlbPkEoLRYA69bG6Eg data[SEQ_DECL_SIZE];
};
struct tySequence_42HkjPs5lPuA0zCz0ayouw {
  TGenericSeq Sup;
  tyObject_Rect_qiXweduDJk1iLE5aHysNdQ data[SEQ_DECL_SIZE];
};
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, init_9bamm4yWZGWNL9cFIxsa1NiA)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, nimGCunrefRC1)(void* p);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(void, eventScene_ulGLb80QQwgsdUqwXLNysQ)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, tyObject_Event_QLORHniUO5yE9cFPjAVIQUQ* e);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(void, event_5cqlxnNzJHBh9aHNB9cFwrKQ)(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity, tyObject_Event_QLORHniUO5yE9cFPjAVIQUQ* e);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, event_ulGLb80QQwgsdUqwXLNysQ_2)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, tyObject_Event_QLORHniUO5yE9cFPjAVIQUQ* e);
N_LIB_PRIVATE N_NIMCALL(void, show_9bamm4yWZGWNL9cFIxsa1NiA_2)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene);
N_LIB_PRIVATE N_NIMCALL(void, hide_9bamm4yWZGWNL9cFIxsa1NiA_3)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene);
N_LIB_PRIVATE N_NIMCALL(void, renderScene_9bBdXs1cYU6xzkure7rMYnA)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene);
N_LIB_PRIVATE N_NIMCALL(void, render_cotbj5pWZpFNBJsTLdYj2Q)(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity);
N_LIB_PRIVATE N_NIMCALL(void, render_K9bA5D9aMLRDELTerBvTErcA)(tyObject_CollidercolonObjectType__zBNkeiXjkkPoCkXQ9afyuhQ* a);
N_LIB_PRIVATE N_NIMCALL(void, render_9bBdXs1cYU6xzkure7rMYnA_2)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene);
N_LIB_PRIVATE N_NIMCALL(void, addEntity_Cp4FOWvRImFR0m3pJkLJ4g)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
static N_INLINE(NI, layer_82xf47FwZMwe8BGc6te4Agentity)(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, insert_xomBgcm9b9b1YwpzMGlqqu8A)(tySequence_ABvfaE9beHzEcUOwofFJ5yg** x, tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* item, NI i);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_LIB_PRIVATE N_NIMCALL(void, delEntity_Vq0VQZglrlMtBCfSqTVWhg)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, NI index);
N_LIB_PRIVATE N_NIMCALL(void, delete_u0cB2dHLcbRs4TfbWVUz9ag)(tySequence_ABvfaE9beHzEcUOwofFJ5yg** x, NI i);
N_LIB_PRIVATE N_NIMCALL(void, add_Cp4FOWvRImFR0m3pJkLJ4g_2)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity);
N_LIB_PRIVATE N_NIMCALL(void, clear_9bamm4yWZGWNL9cFIxsa1NiA_4)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene);
static N_INLINE(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*, pop_SFMHK6VSghLf4k767qwYZwscene)(tySequence_ABvfaE9beHzEcUOwofFJ5yg** s);
static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old);
N_LIB_PRIVATE N_NIMCALL(void*, growObj_AVYny8c0GTk28gxjmat1MA)(void* old, NI newsize);
N_NIMCALL(TNimType*, extGetCellType)(void* c);
N_LIB_PRIVATE N_NIMCALL(void, forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA)(void* dest, TNimType* mt, tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ op);
static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size);
static N_INLINE(NIM_BOOL, contains_PfQQJQ1tNcyzaDw8yG6sSQscene)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity);
static N_INLINE(NIM_BOOL, contains_wD1DP29c9ayER3xPt65k12Xgentity)(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ** a, NI aLen_0, tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* item);
static N_INLINE(NI, find_quIcrUMPLkXyMTdUJDGaOQentity)(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ** a, NI aLen_0, tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* item);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_Tywx2nglwvRnNIuUx6Bqkg)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, NimStringDesc* tag);
static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwentity)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQentity)(NimStringDesc** a, NI aLen_0, NimStringDesc* item);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
static N_INLINE(NI, count_uyu55kJi1AIKU8xWX8mKhQscene)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene);
N_LIB_PRIVATE N_NIMCALL(NI, count_9a8i7Yo4B2zeii9czqh0HBWg)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, NimStringDesc* tag);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, del_zU9begrejTrfzTOoJIam3MQ)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity);
static N_INLINE(NI, find_z2erUaWDbBVqqSLomg4pTwscene)(tySequence_ABvfaE9beHzEcUOwofFJ5yg* a, tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* item);
N_LIB_PRIVATE N_NIMCALL(void, del_YUWZZUdqdcwCLbMPB6vA1A)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, NimStringDesc* tag);
N_LIB_PRIVATE N_NIMCALL(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*, find_zEjajiZOL18HtUtZGrrlTw)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, NimStringDesc* tag);
N_LIB_PRIVATE N_NIMCALL(tySequence_ABvfaE9beHzEcUOwofFJ5yg*, findAll_pIOVzxkYcih3Ffh02dhKQw)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, NimStringDesc* tag);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*, pop_Y6MZmmMWAR3B4FWYDkEw8wscene)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene);
N_LIB_PRIVATE N_NIMCALL(void, updateScene_GBnhpMP7riWhmVbv07iTXQ)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, NF elapsed);
static N_INLINE(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, plus__j2pnXFSCXLnkC9a3JwzEgTwtypes)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c2);
static N_INLINE(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, minus__OTjbpX9bsrQJ5TtNSBVUyQgtypes)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c);
N_LIB_PRIVATE N_NIMCALL(void, update_zhLW56ZENVpzTBjQIGPe5A)(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity, NF elapsed);
N_LIB_PRIVATE N_NIMCALL(void, checkCollisions_V089cTsA3atpv9ctdTnB2CiQ)(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity, tySequence_ABvfaE9beHzEcUOwofFJ5yg* list);
N_LIB_PRIVATE N_NIMCALL(void, update_GBnhpMP7riWhmVbv07iTXQ_2)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, NF elapsed);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_362BxmZEsdbfpPK9cPHeiRA)(void* p, NI op);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_ABvfaE9beHzEcUOwofFJ5yg_;
extern NIM_BOOL colliderOutline_9cwoxZ6MFoT65iPeSzcTajQ;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_HJoCklFKysxcwmn6eT8mUA_;
extern TNimType NTI_T7Veu570Ns0s8v8VllCJeQ_;
extern TNimType NTI_wpFMp8IwxV6MlaM4GANJ0Q_;
TNimType NTI_362BxmZEsdbfpPK9cPHeiRA_;
NIM_CONST tyTuple_wpFMp8IwxV6MlaM4GANJ0Q TM_W21qh9cNwdEes8mcgZon3lA_2 = {0.0,
0.0}
;
STRING_LITERAL(TM_W21qh9cNwdEes8mcgZon3lA_4, "len(a) == L seq modified while iterating over it", 48);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, nimGCunrefRC1)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefRC1", "gc.nim");
	nimln_(258, "gc.nim");
	T1_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T1_);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, init_9bamm4yWZGWNL9cFIxsa1NiA)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene) {
	nimfr_("init", "scene.nim");
	nimln_(44, "scene.nim");
	asgnRef((void**) (&(*scene).camera), NIM_NIL);
	nimln_(45, "scene.nim");
	asgnRef((void**) (&(*scene).cameraBond), NIM_NIL);
	nimln_(46, "scene.nim");
	(*scene).cameraBondOffset = TM_W21qh9cNwdEes8mcgZon3lA_2;
	nimln_(47, "scene.nim");
	if ((*scene).fList) { nimGCunrefRC1((*scene).fList); (*scene).fList = NIM_NIL; }
	(*scene).fList = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*) newSeqRC1((&NTI_ABvfaE9beHzEcUOwofFJ5yg_), 0);
	nimln_(48, "scene.nim");
	if ((*scene).fAddList) { nimGCunrefRC1((*scene).fAddList); (*scene).fAddList = NIM_NIL; }
	(*scene).fAddList = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*) newSeqRC1((&NTI_ABvfaE9beHzEcUOwofFJ5yg_), 0);
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, eventScene_ulGLb80QQwgsdUqwXLNysQ)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, tyObject_Event_QLORHniUO5yE9cFPjAVIQUQ* e) {
	nimfr_("eventScene", "scene.nim");
	{
		tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity;
		tySequence_ABvfaE9beHzEcUOwofFJ5yg* colontmp_;
		NI i;
		NI L;
		NI T2_;
		entity = (tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*)0;
		colontmp_ = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*)0;
		nimln_(52, "scene.nim");
		colontmp_ = (*scene).fList;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_W21qh9cNwdEes8mcgZon3lA_3;
				if (!(i < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				entity = colontmp_->data[i];
				nimln_(53, "scene.nim");
				event_5cqlxnNzJHBh9aHNB9cFwrKQ(entity, e);
				nimln_(3809, "system.nim");
				TM_W21qh9cNwdEes8mcgZon3lA_3 = addInt(i, ((NI) 1));
				i = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_3);
				nimln_(3810, "system.nim");
				{
					NI T7_;
					T7_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T7_ == L))) goto LA8_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_W21qh9cNwdEes8mcgZon3lA_4));
				}
				LA8_: ;
			} LA4: ;
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, event_ulGLb80QQwgsdUqwXLNysQ_2)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, tyObject_Event_QLORHniUO5yE9cFPjAVIQUQ* e) {
	nimfr_("event", "scene.nim");
	nimln_(57, "scene.nim");
	eventScene_ulGLb80QQwgsdUqwXLNysQ(scene, e);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, show_9bamm4yWZGWNL9cFIxsa1NiA_2)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene) {
	nimfr_("show", "scene.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, hide_9bamm4yWZGWNL9cFIxsa1NiA_3)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene) {
	nimfr_("hide", "scene.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, renderScene_9bBdXs1cYU6xzkure7rMYnA)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene) {
	nimfr_("renderScene", "scene.nim");
	{
		tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity;
		tySequence_ABvfaE9beHzEcUOwofFJ5yg* colontmp_;
		NI i;
		NI L;
		NI T2_;
		entity = (tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*)0;
		colontmp_ = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*)0;
		nimln_(77, "scene.nim");
		colontmp_ = (*scene).fList;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_W21qh9cNwdEes8mcgZon3lA_5;
				if (!(i < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				entity = colontmp_->data[i];
				nimln_(78, "scene.nim");
				render_cotbj5pWZpFNBJsTLdYj2Q(entity);
				nimln_(3809, "system.nim");
				TM_W21qh9cNwdEes8mcgZon3lA_5 = addInt(i, ((NI) 1));
				i = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_5);
				nimln_(3810, "system.nim");
				{
					NI T7_;
					T7_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T7_ == L))) goto LA8_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_W21qh9cNwdEes8mcgZon3lA_4));
				}
				LA8_: ;
			} LA4: ;
		}
	}
	nimln_(80, "scene.nim");
	{
		if (!colliderOutline_9cwoxZ6MFoT65iPeSzcTajQ) goto LA12_;
		{
			tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity_2;
			tySequence_ABvfaE9beHzEcUOwofFJ5yg* colontmp__2;
			NI i_2;
			NI L_2;
			NI T15_;
			entity_2 = (tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*)0;
			colontmp__2 = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*)0;
			nimln_(81, "scene.nim");
			colontmp__2 = (*scene).fList;
			nimln_(3805, "system.nim");
			i_2 = ((NI) 0);
			nimln_(3806, "system.nim");
			T15_ = (colontmp__2 ? colontmp__2->Sup.len : 0);
			L_2 = T15_;
			{
				nimln_(3807, "system.nim");
				while (1) {
					NI TM_W21qh9cNwdEes8mcgZon3lA_6;
					if (!(i_2 < L_2)) goto LA17;
					nimln_(3808, "system.nim");
					if ((NU)(i_2) >= (NU)(colontmp__2->Sup.len)) raiseIndexError();
					entity_2 = colontmp__2->data[i_2];
					nimln_(82, "scene.nim");
					{
						nimln_(398, "system.nim");
						nimln_(82, "scene.nim");
						if (!!(((*entity_2).collider == NIM_NIL))) goto LA20_;
						nimln_(83, "scene.nim");
						render_K9bA5D9aMLRDELTerBvTErcA((*entity_2).collider);
					}
					LA20_: ;
					nimln_(3809, "system.nim");
					TM_W21qh9cNwdEes8mcgZon3lA_6 = addInt(i_2, ((NI) 1));
					i_2 = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_6);
					nimln_(3810, "system.nim");
					{
						NI T24_;
						T24_ = (colontmp__2 ? colontmp__2->Sup.len : 0);
						if (!!((T24_ == L_2))) goto LA25_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_W21qh9cNwdEes8mcgZon3lA_4));
					}
					LA25_: ;
				} LA17: ;
			}
		}
	}
	LA12_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, render_9bBdXs1cYU6xzkure7rMYnA_2)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene) {
	nimfr_("render", "scene.nim");
	nimln_(87, "scene.nim");
	renderScene_9bBdXs1cYU6xzkure7rMYnA(scene);
	popFrame();
}

static N_INLINE(NI, layer_82xf47FwZMwe8BGc6te4Agentity)(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity) {
	NI result;
	nimfr_("layer", "entity.nim");
{	result = (NI)0;
	nimln_(613, "entity.nim");
	result = (*entity).fLayer;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, addEntity_Cp4FOWvRImFR0m3pJkLJ4g)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity) {
	NI i;
	NI T15_;
	NI TM_W21qh9cNwdEes8mcgZon3lA_7;
	nimfr_("addEntity", "scene.nim");
{	nimln_(91, "scene.nim");
	{
		NI T3_;
		NI T6_;
		T3_ = ((*scene).fList ? (*scene).fList->Sup.len : 0);
		if (!(T3_ < ((NI) 1))) goto LA4_;
		nimln_(92, "scene.nim");
		(*scene).fList = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*) incrSeqV2(&((*scene).fList)->Sup, sizeof(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*));
		T6_ = (*scene).fList->Sup.len++;
		asgnRef((void**) (&(*scene).fList->data[T6_]), entity);
		nimln_(93, "scene.nim");
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(95, "scene.nim");
	{
		NI T9_;
		NI T10_;
		NI T11_;
		NI T14_;
		T9_ = ((*scene).fList ? ((*scene).fList->Sup.len-1) : -1);
		if ((NU)(T9_) >= (NU)((*scene).fList->Sup.len)) raiseIndexError();
		T10_ = (NI)0;
		T10_ = layer_82xf47FwZMwe8BGc6te4Agentity((*scene).fList->data[T9_]);
		T11_ = (NI)0;
		T11_ = layer_82xf47FwZMwe8BGc6te4Agentity(entity);
		if (!(T10_ <= T11_)) goto LA12_;
		nimln_(96, "scene.nim");
		(*scene).fList = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*) incrSeqV2(&((*scene).fList)->Sup, sizeof(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*));
		T14_ = (*scene).fList->Sup.len++;
		asgnRef((void**) (&(*scene).fList->data[T14_]), entity);
		nimln_(97, "scene.nim");
		goto BeforeRet_;
	}
	LA12_: ;
	nimln_(99, "scene.nim");
	T15_ = ((*scene).fList ? ((*scene).fList->Sup.len-1) : -1);
	TM_W21qh9cNwdEes8mcgZon3lA_7 = subInt(T15_, ((NI) 1));
	i = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_7);
	{
		nimln_(100, "scene.nim");
		while (1) {
			NI TM_W21qh9cNwdEes8mcgZon3lA_9;
			if (!(((NI) 0) <= i)) goto LA17;
			nimln_(101, "scene.nim");
			{
				NI T20_;
				NI T21_;
				NI TM_W21qh9cNwdEes8mcgZon3lA_8;
				if ((NU)(i) >= (NU)((*scene).fList->Sup.len)) raiseIndexError();
				T20_ = (NI)0;
				T20_ = layer_82xf47FwZMwe8BGc6te4Agentity((*scene).fList->data[i]);
				T21_ = (NI)0;
				T21_ = layer_82xf47FwZMwe8BGc6te4Agentity(entity);
				if (!(T20_ <= T21_)) goto LA22_;
				nimln_(102, "scene.nim");
				TM_W21qh9cNwdEes8mcgZon3lA_8 = addInt(i, ((NI) 1));
				insert_xomBgcm9b9b1YwpzMGlqqu8A((&(*scene).fList), entity, ((NI)chckRange((NI)(TM_W21qh9cNwdEes8mcgZon3lA_8), ((NI) 0), ((NI) IL64(9223372036854775807)))));
				nimln_(103, "scene.nim");
				goto BeforeRet_;
			}
			LA22_: ;
			nimln_(104, "scene.nim");
			TM_W21qh9cNwdEes8mcgZon3lA_9 = subInt(i, ((NI) 1));
			i = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_9);
		} LA17: ;
	}
	nimln_(106, "scene.nim");
	insert_xomBgcm9b9b1YwpzMGlqqu8A((&(*scene).fList), entity, ((NI) 0));
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, delEntity_Vq0VQZglrlMtBCfSqTVWhg)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, NI index) {
	nimfr_("delEntity", "scene.nim");
	nimln_(110, "scene.nim");
	delete_u0cB2dHLcbRs4TfbWVUz9ag((&(*scene).fList), ((NI)chckRange(index, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, add_Cp4FOWvRImFR0m3pJkLJ4g_2)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity) {
	NI T1_;
	nimfr_("add", "scene.nim");
	nimln_(116, "scene.nim");
	(*scene).fAddList = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*) incrSeqV2(&((*scene).fAddList)->Sup, sizeof(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*));
	T1_ = (*scene).fAddList->Sup.len++;
	asgnRef((void**) (&(*scene).fAddList->data[T1_]), entity);
	popFrame();
}

static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old) {
	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(p, ((int) 0), ((size_t) (size)));
}

static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen) {
	TGenericSeq* result;
	result = (TGenericSeq*)0;
	result = seq;
	{
		NI r;
		NI T5_;
		void* T6_;
		if (!((NI)((*result).reserved & ((NI) IL64(4611686018427387903))) < newLen)) goto LA3_;
		T5_ = (NI)0;
		T5_ = resize_bzF9a0JivP3Z4njqaxuLc5wsystem((NI)((*result).reserved & ((NI) IL64(4611686018427387903))));
		r = ((T5_ >= newLen) ? T5_ : newLen);
		T6_ = (void*)0;
		T6_ = growObj_AVYny8c0GTk28gxjmat1MA(((void*) (result)), (NI)((NI)(elemSize * r) + ((NI) 16)));
		result = ((TGenericSeq*) (T6_));
		(*result).reserved = r;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(newLen < (*result).len)) goto LA8_;
		{
			TNimType* T12_;
			T12_ = (TNimType*)0;
			T12_ = extGetCellType(((void*) (result)));
			if (!!((((*(*T12_).base).flags &(1U<<((NU)(((tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ) 0))&7U)))!=0))) goto LA13_;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (NI)((*result).len - ((NI) 1));
				res = newLen;
				{
					while (1) {
						TNimType* T18_;
						if (!(res <= colontmp_)) goto LA17;
						i = res;
						T18_ = (TNimType*)0;
						T18_ = extGetCellType(((void*) (result)));
						forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(i) * (NU64)(elemSize)))))), (*T18_).base, ((tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ) 2));
						res += ((NI) 1);
					} LA17: ;
				}
			}
		}
		LA13_: ;
		zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(newLen) * (NU64)(elemSize)))))), ((NI) ((NI)((NU64)((NI)((NU64)((*result).len) - (NU64)(newLen))) * (NU64)(elemSize)))));
	}
	goto LA1_;
	LA8_: ;
	LA1_: ;
	(*result).len = newLen;
	return result;
}

static N_INLINE(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*, pop_SFMHK6VSghLf4k767qwYZwscene)(tySequence_ABvfaE9beHzEcUOwofFJ5yg** s) {
	tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* result;
	NI L;
	NI T1_;
	NI TM_W21qh9cNwdEes8mcgZon3lA_10;
	nimfr_("pop", "system.nim");
	result = (tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*)0;
	nimln_(2431, "system.nim");
	T1_ = ((*s) ? (*s)->Sup.len : 0);
	TM_W21qh9cNwdEes8mcgZon3lA_10 = subInt(T1_, ((NI) 1));
	L = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_10);
	nimln_(2432, "system.nim");
	if ((NU)(L) >= (NU)((*s)->Sup.len)) raiseIndexError();
	result = (*s)->data[L];
	nimln_(2433, "system.nim");
	(*s) = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*) setLengthSeq(&((*s))->Sup, sizeof(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*), ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, clear_9bamm4yWZGWNL9cFIxsa1NiA_4)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene) {
	nimfr_("clear", "scene.nim");
	{
		nimln_(129, "scene.nim");
		while (1) {
			NI T3_;
			tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* T4_;
			T3_ = ((*scene).fList ? (*scene).fList->Sup.len : 0);
			if (!(((NI) 0) < T3_)) goto LA2;
			nimln_(130, "scene.nim");
			T4_ = (tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*)0;
			T4_ = pop_SFMHK6VSghLf4k767qwYZwscene((&(*scene).fList));
			T4_;
		} LA2: ;
	}
	popFrame();
}

static N_INLINE(NI, find_quIcrUMPLkXyMTdUJDGaOQentity)(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ** a, NI aLen_0, tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* item) {
	NI result;
	nimfr_("find", "system.nim");
{	result = (NI)0;
	{
		tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* i;
		NI i_2;
		i = (tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*)0;
		nimln_(2185, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI TM_W21qh9cNwdEes8mcgZon3lA_11;
				NI TM_W21qh9cNwdEes8mcgZon3lA_12;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				if ((NU)(i_2) >= (NU)(aLen_0)) raiseIndexError();
				i = a[i_2];
				nimln_(2419, "system.nim");
				{
					if (!(i == item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(2420, "system.nim");
				TM_W21qh9cNwdEes8mcgZon3lA_11 = addInt(result, ((NI) 1));
				result = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_11);
				nimln_(2188, "system.nim");
				TM_W21qh9cNwdEes8mcgZon3lA_12 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_12);
			} LA3: ;
		}
	}
	nimln_(2421, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_wD1DP29c9ayER3xPt65k12Xgentity)(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ** a, NI aLen_0, tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "system.nim");
{	result = (NIM_BOOL)0;
	nimln_(2426, "system.nim");
	T1_ = (NI)0;
	T1_ = find_quIcrUMPLkXyMTdUJDGaOQentity(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_PfQQJQ1tNcyzaDw8yG6sSQscene)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity) {
	NIM_BOOL result;
	nimfr_("contains", "scene.nim");
{	result = (NIM_BOOL)0;
	nimln_(137, "scene.nim");
	result = contains_wD1DP29c9ayER3xPt65k12Xgentity((*scene).fList->data, (*scene).fList->Sup.len, entity);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, find_9basNl9bVqn7SOf9bgUeI8TEQentity)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NI result;
	nimfr_("find", "system.nim");
{	result = (NI)0;
	{
		NimStringDesc* i;
		NI i_2;
		i = (NimStringDesc*)0;
		nimln_(2185, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI TM_W21qh9cNwdEes8mcgZon3lA_13;
				NI TM_W21qh9cNwdEes8mcgZon3lA_14;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				if ((NU)(i_2) >= (NU)(aLen_0)) raiseIndexError();
				i = a[i_2];
				nimln_(2419, "system.nim");
				{
					if (!eqStrings(i, item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(2420, "system.nim");
				TM_W21qh9cNwdEes8mcgZon3lA_13 = addInt(result, ((NI) 1));
				result = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_13);
				nimln_(2188, "system.nim");
				TM_W21qh9cNwdEes8mcgZon3lA_14 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_14);
			} LA3: ;
		}
	}
	nimln_(2421, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, contains_jPdUhZfr9a8sH2V3ZBDljzwentity)(NimStringDesc** a, NI aLen_0, NimStringDesc* item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "system.nim");
{	result = (NIM_BOOL)0;
	nimln_(2426, "system.nim");
	T1_ = (NI)0;
	T1_ = find_9basNl9bVqn7SOf9bgUeI8TEQentity(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_Tywx2nglwvRnNIuUx6Bqkg)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, NimStringDesc* tag) {
	NIM_BOOL result;
	nimfr_("contains", "scene.nim");
{	result = (NIM_BOOL)0;
	{
		tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity;
		tySequence_ABvfaE9beHzEcUOwofFJ5yg* colontmp_;
		NI i;
		NI L;
		NI T2_;
		entity = (tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*)0;
		colontmp_ = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*)0;
		nimln_(144, "scene.nim");
		colontmp_ = (*scene).fList;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_W21qh9cNwdEes8mcgZon3lA_15;
				if (!(i < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				entity = colontmp_->data[i];
				nimln_(145, "scene.nim");
				{
					NIM_BOOL T7_;
					T7_ = (NIM_BOOL)0;
					T7_ = contains_jPdUhZfr9a8sH2V3ZBDljzwentity((*entity).tags->data, (*entity).tags->Sup.len, tag);
					if (!T7_) goto LA8_;
					nimln_(146, "scene.nim");
					result = NIM_TRUE;
					goto BeforeRet_;
				}
				LA8_: ;
				nimln_(3809, "system.nim");
				TM_W21qh9cNwdEes8mcgZon3lA_15 = addInt(i, ((NI) 1));
				i = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_15);
				nimln_(3810, "system.nim");
				{
					NI T12_;
					T12_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T12_ == L))) goto LA13_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_W21qh9cNwdEes8mcgZon3lA_4));
				}
				LA13_: ;
			} LA4: ;
		}
	}
	nimln_(147, "scene.nim");
	result = NIM_FALSE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, count_uyu55kJi1AIKU8xWX8mKhQscene)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene) {
	NI result;
	NI T1_;
	nimfr_("count", "scene.nim");
{	result = (NI)0;
	nimln_(153, "scene.nim");
	T1_ = ((*scene).fList ? (*scene).fList->Sup.len : 0);
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, count_9a8i7Yo4B2zeii9czqh0HBWg)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, NimStringDesc* tag) {
	NI result;
	nimfr_("count", "scene.nim");
	result = (NI)0;
	nimln_(159, "scene.nim");
	result = ((NI) 0);
	{
		tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity;
		tySequence_ABvfaE9beHzEcUOwofFJ5yg* colontmp_;
		NI i;
		NI L;
		NI T2_;
		entity = (tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*)0;
		colontmp_ = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*)0;
		nimln_(160, "scene.nim");
		colontmp_ = (*scene).fList;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_W21qh9cNwdEes8mcgZon3lA_17;
				if (!(i < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				entity = colontmp_->data[i];
				nimln_(161, "scene.nim");
				{
					NIM_BOOL T7_;
					NI TM_W21qh9cNwdEes8mcgZon3lA_16;
					T7_ = (NIM_BOOL)0;
					T7_ = contains_jPdUhZfr9a8sH2V3ZBDljzwentity((*entity).tags->data, (*entity).tags->Sup.len, tag);
					if (!T7_) goto LA8_;
					nimln_(162, "scene.nim");
					TM_W21qh9cNwdEes8mcgZon3lA_16 = addInt(result, ((NI) 1));
					result = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_16);
				}
				LA8_: ;
				nimln_(3809, "system.nim");
				TM_W21qh9cNwdEes8mcgZon3lA_17 = addInt(i, ((NI) 1));
				i = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_17);
				nimln_(3810, "system.nim");
				{
					NI T12_;
					T12_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T12_ == L))) goto LA13_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_W21qh9cNwdEes8mcgZon3lA_4));
				}
				LA13_: ;
			} LA4: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(NI, find_z2erUaWDbBVqqSLomg4pTwscene)(tySequence_ABvfaE9beHzEcUOwofFJ5yg* a, tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* item) {
	NI result;
	nimfr_("find", "system.nim");
{	result = (NI)0;
	{
		tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* i;
		NI i_2;
		NI L;
		NI T2_;
		i = (tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*)0;
		nimln_(3805, "system.nim");
		i_2 = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (a ? a->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_W21qh9cNwdEes8mcgZon3lA_18;
				NI TM_W21qh9cNwdEes8mcgZon3lA_19;
				if (!(i_2 < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i_2) >= (NU)(a->Sup.len)) raiseIndexError();
				i = a->data[i_2];
				nimln_(2419, "system.nim");
				{
					if (!(i == item)) goto LA7_;
					goto BeforeRet_;
				}
				LA7_: ;
				nimln_(2420, "system.nim");
				TM_W21qh9cNwdEes8mcgZon3lA_18 = addInt(result, ((NI) 1));
				result = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_18);
				nimln_(3809, "system.nim");
				TM_W21qh9cNwdEes8mcgZon3lA_19 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_19);
				nimln_(3810, "system.nim");
				{
					NI T11_;
					T11_ = (a ? a->Sup.len : 0);
					if (!!((T11_ == L))) goto LA12_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_W21qh9cNwdEes8mcgZon3lA_4));
				}
				LA12_: ;
			} LA4: ;
		}
	}
	nimln_(2421, "system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, del_zU9begrejTrfzTOoJIam3MQ)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity) {
	NIM_BOOL result;
	NI idx;
	nimfr_("del", "scene.nim");
{	result = (NIM_BOOL)0;
	nimln_(171, "scene.nim");
	idx = find_z2erUaWDbBVqqSLomg4pTwscene((*scene).fList, entity);
	nimln_(172, "scene.nim");
	{
		if (!(idx < ((NI) 0))) goto LA3_;
		nimln_(173, "scene.nim");
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(174, "scene.nim");
	delEntity_Vq0VQZglrlMtBCfSqTVWhg(scene, idx);
	nimln_(175, "scene.nim");
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, del_YUWZZUdqdcwCLbMPB6vA1A)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, NimStringDesc* tag) {
	NI idx;
	nimfr_("del", "scene.nim");
	nimln_(181, "scene.nim");
	idx = ((NI) 0);
	{
		nimln_(182, "scene.nim");
		while (1) {
			NI T3_;
			T3_ = ((*scene).fList ? (*scene).fList->Sup.len : 0);
			if (!(idx < T3_)) goto LA2;
			{
				NI TM_W21qh9cNwdEes8mcgZon3lA_20;
				nimln_(183, "scene.nim");
				{
					NIM_BOOL T7_;
					if ((NU)(idx) >= (NU)((*scene).fList->Sup.len)) raiseIndexError();
					T7_ = (NIM_BOOL)0;
					T7_ = contains_jPdUhZfr9a8sH2V3ZBDljzwentity((*(*scene).fList->data[idx]).tags->data, (*(*scene).fList->data[idx]).tags->Sup.len, tag);
					if (!T7_) goto LA8_;
					nimln_(184, "scene.nim");
					delEntity_Vq0VQZglrlMtBCfSqTVWhg(scene, idx);
					nimln_(185, "scene.nim");
					goto LA4;
				}
				LA8_: ;
				nimln_(186, "scene.nim");
				TM_W21qh9cNwdEes8mcgZon3lA_20 = addInt(idx, ((NI) 1));
				idx = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_20);
			} LA4: ;
		} LA2: ;
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*, find_zEjajiZOL18HtUtZGrrlTw)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, NimStringDesc* tag) {
	tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* result;
	nimfr_("find", "scene.nim");
{	result = (tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*)0;
	{
		tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity;
		tySequence_ABvfaE9beHzEcUOwofFJ5yg* colontmp_;
		NI i;
		NI L;
		NI T2_;
		entity = (tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*)0;
		colontmp_ = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*)0;
		nimln_(193, "scene.nim");
		colontmp_ = (*scene).fList;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_W21qh9cNwdEes8mcgZon3lA_21;
				if (!(i < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				entity = colontmp_->data[i];
				nimln_(194, "scene.nim");
				{
					NIM_BOOL T7_;
					T7_ = (NIM_BOOL)0;
					T7_ = contains_jPdUhZfr9a8sH2V3ZBDljzwentity((*entity).tags->data, (*entity).tags->Sup.len, tag);
					if (!T7_) goto LA8_;
					nimln_(195, "scene.nim");
					result = entity;
					goto BeforeRet_;
				}
				LA8_: ;
				nimln_(3809, "system.nim");
				TM_W21qh9cNwdEes8mcgZon3lA_21 = addInt(i, ((NI) 1));
				i = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_21);
				nimln_(3810, "system.nim");
				{
					NI T12_;
					T12_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T12_ == L))) goto LA13_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_W21qh9cNwdEes8mcgZon3lA_4));
				}
				LA13_: ;
			} LA4: ;
		}
	}
	nimln_(196, "scene.nim");
	result = NIM_NIL;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_ABvfaE9beHzEcUOwofFJ5yg*, findAll_pIOVzxkYcih3Ffh02dhKQw)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, NimStringDesc* tag) {
	tySequence_ABvfaE9beHzEcUOwofFJ5yg* result;
	nimfr_("findAll", "scene.nim");
	result = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*)0;
	nimln_(203, "scene.nim");
	result = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*) newSeq((&NTI_ABvfaE9beHzEcUOwofFJ5yg_), 0);
	{
		tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity;
		tySequence_ABvfaE9beHzEcUOwofFJ5yg* colontmp_;
		NI i;
		NI L;
		NI T2_;
		entity = (tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*)0;
		colontmp_ = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*)0;
		nimln_(204, "scene.nim");
		colontmp_ = (*scene).fList;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_W21qh9cNwdEes8mcgZon3lA_22;
				if (!(i < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				entity = colontmp_->data[i];
				nimln_(205, "scene.nim");
				{
					NIM_BOOL T7_;
					NI T10_;
					T7_ = (NIM_BOOL)0;
					T7_ = contains_jPdUhZfr9a8sH2V3ZBDljzwentity((*entity).tags->data, (*entity).tags->Sup.len, tag);
					if (!T7_) goto LA8_;
					nimln_(206, "scene.nim");
					result = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*) incrSeqV2(&(result)->Sup, sizeof(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*));
					T10_ = result->Sup.len++;
					asgnRef((void**) (&result->data[T10_]), entity);
				}
				LA8_: ;
				nimln_(3809, "system.nim");
				TM_W21qh9cNwdEes8mcgZon3lA_22 = addInt(i, ((NI) 1));
				i = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_22);
				nimln_(3810, "system.nim");
				{
					NI T13_;
					T13_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T13_ == L))) goto LA14_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_W21qh9cNwdEes8mcgZon3lA_4));
				}
				LA14_: ;
			} LA4: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*, pop_Y6MZmmMWAR3B4FWYDkEw8wscene)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene) {
	tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* result;
	nimfr_("pop", "scene.nim");
{	result = (tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*)0;
	nimln_(212, "scene.nim");
	result = pop_SFMHK6VSghLf4k767qwYZwscene((&(*scene).fList));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, plus__j2pnXFSCXLnkC9a3JwzEgTwtypes)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c1, tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c2) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	nimfr_("+", "types.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(261, "types.nim");
	result.Field0 = ((NF)(c1.Field0) + (NF)(c2.Field0));
	nimln_(262, "types.nim");
	result.Field1 = ((NF)(c1.Field1) + (NF)(c2.Field1));
	popFrame();
	return result;
}

static N_INLINE(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q, minus__OTjbpX9bsrQJ5TtNSBVUyQgtypes)(tyTuple_wpFMp8IwxV6MlaM4GANJ0Q c) {
	tyTuple_wpFMp8IwxV6MlaM4GANJ0Q result;
	nimfr_("-", "types.nim");
{	memset((void*)(&result), 0, sizeof(result));
	nimln_(257, "types.nim");
	result.Field0 = -(c.Field0);
	result.Field1 = -(c.Field1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, updateScene_GBnhpMP7riWhmVbv07iTXQ)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, NF elapsed) {
	NI i;
	NI len;
	NI T1_;
	nimfr_("updateScene", "scene.nim");
	nimln_(238, "scene.nim");
	i = ((NI) 0);
	nimln_(239, "scene.nim");
	T1_ = ((*scene).fList ? (*scene).fList->Sup.len : 0);
	len = T1_;
	{
		nimln_(240, "scene.nim");
		while (1) {
			if (!(i < len)) goto LA3;
			{
				NI TM_W21qh9cNwdEes8mcgZon3lA_25;
				nimln_(242, "scene.nim");
				{
					NI TM_W21qh9cNwdEes8mcgZon3lA_23;
					if ((NU)(i) >= (NU)((*scene).fList->Sup.len)) raiseIndexError();
					if (!(*(*scene).fList->data[i]).dead) goto LA7_;
					nimln_(243, "scene.nim");
					delEntity_Vq0VQZglrlMtBCfSqTVWhg(scene, i);
					nimln_(244, "scene.nim");
					TM_W21qh9cNwdEes8mcgZon3lA_23 = subInt(len, ((NI) 1));
					len = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_23);
					nimln_(245, "scene.nim");
					goto LA4;
				}
				LA7_: ;
				nimln_(247, "scene.nim");
				{
					NI T13_;
					NI TM_W21qh9cNwdEes8mcgZon3lA_24;
					if ((NU)(i) >= (NU)((*scene).fList->Sup.len)) raiseIndexError();
					if (!(*(*scene).fList->data[i]).updLayer) goto LA11_;
					if ((NU)(i) >= (NU)((*scene).fList->Sup.len)) raiseIndexError();
					nimln_(248, "scene.nim");
					(*(*scene).fList->data[i]).updLayer = NIM_FALSE;
					nimln_(249, "scene.nim");
					if ((NU)(i) >= (NU)((*scene).fList->Sup.len)) raiseIndexError();
					(*scene).fAddList = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*) incrSeqV2(&((*scene).fAddList)->Sup, sizeof(tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*));
					T13_ = (*scene).fAddList->Sup.len++;
					asgnRef((void**) (&(*scene).fAddList->data[T13_]), (*scene).fList->data[i]);
					nimln_(250, "scene.nim");
					delEntity_Vq0VQZglrlMtBCfSqTVWhg(scene, i);
					nimln_(251, "scene.nim");
					TM_W21qh9cNwdEes8mcgZon3lA_24 = subInt(len, ((NI) 1));
					len = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_24);
					nimln_(252, "scene.nim");
					goto LA4;
				}
				LA11_: ;
				nimln_(253, "scene.nim");
				TM_W21qh9cNwdEes8mcgZon3lA_25 = addInt(i, ((NI) 1));
				i = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_25);
			} LA4: ;
		} LA3: ;
	}
	{
		nimln_(256, "scene.nim");
		while (1) {
			NI T16_;
			tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity;
			T16_ = ((*scene).fAddList ? (*scene).fAddList->Sup.len : 0);
			if (!(((NI) 0) < T16_)) goto LA15;
			nimln_(257, "scene.nim");
			entity = pop_SFMHK6VSghLf4k767qwYZwscene((&(*scene).fAddList));
			nimln_(258, "scene.nim");
			(*entity).updLayer = NIM_FALSE;
			nimln_(259, "scene.nim");
			addEntity_Cp4FOWvRImFR0m3pJkLJ4g(scene, entity);
		} LA15: ;
	}
	nimln_(262, "scene.nim");
	{
		tyTuple_wpFMp8IwxV6MlaM4GANJ0Q T21_;
		if (!!(((*scene).cameraBond == NIM_NIL))) goto LA19_;
		nimln_(263, "scene.nim");
		T21_ = minus__OTjbpX9bsrQJ5TtNSBVUyQgtypes((*(*scene).cameraBond).pos);
		(*(*scene).camera).pos = plus__j2pnXFSCXLnkC9a3JwzEgTwtypes(T21_, (*scene).cameraBondOffset);
	}
	LA19_: ;
	{
		tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity_2;
		tySequence_ABvfaE9beHzEcUOwofFJ5yg* colontmp_;
		NI i_2;
		NI L;
		NI T23_;
		entity_2 = (tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*)0;
		colontmp_ = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*)0;
		nimln_(266, "scene.nim");
		colontmp_ = (*scene).fList;
		nimln_(3805, "system.nim");
		i_2 = ((NI) 0);
		nimln_(3806, "system.nim");
		T23_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T23_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_W21qh9cNwdEes8mcgZon3lA_26;
				if (!(i_2 < L)) goto LA25;
				nimln_(3808, "system.nim");
				if ((NU)(i_2) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				entity_2 = colontmp_->data[i_2];
				nimln_(267, "scene.nim");
				update_zhLW56ZENVpzTBjQIGPe5A(entity_2, elapsed);
				nimln_(268, "scene.nim");
				{
					nimln_(398, "system.nim");
					nimln_(268, "scene.nim");
					if (!!(((*entity_2).collider == NIM_NIL))) goto LA28_;
					nimln_(269, "scene.nim");
					if ((*entity_2).colliding) { nimGCunrefRC1((*entity_2).colliding); (*entity_2).colliding = NIM_NIL; }
					(*entity_2).colliding = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*) newSeqRC1((&NTI_ABvfaE9beHzEcUOwofFJ5yg_), 0);
				}
				LA28_: ;
				nimln_(3809, "system.nim");
				TM_W21qh9cNwdEes8mcgZon3lA_26 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_26);
				nimln_(3810, "system.nim");
				{
					NI T32_;
					T32_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T32_ == L))) goto LA33_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_W21qh9cNwdEes8mcgZon3lA_4));
				}
				LA33_: ;
			} LA25: ;
		}
	}
	{
		tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ* entity_3;
		tySequence_ABvfaE9beHzEcUOwofFJ5yg* colontmp__2;
		NI i_3;
		NI L_2;
		NI T36_;
		entity_3 = (tyObject_EntitycolonObjectType__5R75E4zPEMQkVQJZ7MNZwQ*)0;
		colontmp__2 = (tySequence_ABvfaE9beHzEcUOwofFJ5yg*)0;
		nimln_(272, "scene.nim");
		colontmp__2 = (*scene).fList;
		nimln_(3805, "system.nim");
		i_3 = ((NI) 0);
		nimln_(3806, "system.nim");
		T36_ = (colontmp__2 ? colontmp__2->Sup.len : 0);
		L_2 = T36_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_W21qh9cNwdEes8mcgZon3lA_27;
				if (!(i_3 < L_2)) goto LA38;
				nimln_(3808, "system.nim");
				if ((NU)(i_3) >= (NU)(colontmp__2->Sup.len)) raiseIndexError();
				entity_3 = colontmp__2->data[i_3];
				nimln_(273, "scene.nim");
				{
					nimln_(398, "system.nim");
					nimln_(273, "scene.nim");
					if (!!(((*entity_3).collider == NIM_NIL))) goto LA41_;
					nimln_(274, "scene.nim");
					checkCollisions_V089cTsA3atpv9ctdTnB2CiQ(entity_3, (*scene).fList);
				}
				LA41_: ;
				nimln_(3809, "system.nim");
				TM_W21qh9cNwdEes8mcgZon3lA_27 = addInt(i_3, ((NI) 1));
				i_3 = (NI)(TM_W21qh9cNwdEes8mcgZon3lA_27);
				nimln_(3810, "system.nim");
				{
					NI T45_;
					T45_ = (colontmp__2 ? colontmp__2->Sup.len : 0);
					if (!!((T45_ == L_2))) goto LA46_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_W21qh9cNwdEes8mcgZon3lA_4));
				}
				LA46_: ;
			} LA38: ;
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, update_GBnhpMP7riWhmVbv07iTXQ_2)(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* scene, NF elapsed) {
	nimfr_("update", "scene.nim");
	nimln_(278, "scene.nim");
	updateScene_GBnhpMP7riWhmVbv07iTXQ(scene, elapsed);
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_362BxmZEsdbfpPK9cPHeiRA)(void* p, NI op) {
	tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA* a;
	a = (tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA*)p;
	nimGCvisit((void*)(*a).fList, op);
	nimGCvisit((void*)(*a).fAddList, op);
	nimGCvisit((void*)(*a).camera, op);
	nimGCvisit((void*)(*a).cameraBond, op);
}
NIM_EXTERNC N_NOINLINE(void, nimgame2_sceneInit000)(void) {
	nimfr_("scene", "scene.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimgame2_sceneDatInit000)(void) {
static TNimNode* TM_W21qh9cNwdEes8mcgZon3lA_28[5];
static TNimNode TM_W21qh9cNwdEes8mcgZon3lA_0[6];
NTI_HJoCklFKysxcwmn6eT8mUA_.size = sizeof(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA);
NTI_HJoCklFKysxcwmn6eT8mUA_.kind = 17;
NTI_HJoCklFKysxcwmn6eT8mUA_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_W21qh9cNwdEes8mcgZon3lA_28[0] = &TM_W21qh9cNwdEes8mcgZon3lA_0[1];
TM_W21qh9cNwdEes8mcgZon3lA_0[1].kind = 1;
TM_W21qh9cNwdEes8mcgZon3lA_0[1].offset = offsetof(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA, fList);
TM_W21qh9cNwdEes8mcgZon3lA_0[1].typ = (&NTI_ABvfaE9beHzEcUOwofFJ5yg_);
TM_W21qh9cNwdEes8mcgZon3lA_0[1].name = "fList";
TM_W21qh9cNwdEes8mcgZon3lA_28[1] = &TM_W21qh9cNwdEes8mcgZon3lA_0[2];
TM_W21qh9cNwdEes8mcgZon3lA_0[2].kind = 1;
TM_W21qh9cNwdEes8mcgZon3lA_0[2].offset = offsetof(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA, fAddList);
TM_W21qh9cNwdEes8mcgZon3lA_0[2].typ = (&NTI_ABvfaE9beHzEcUOwofFJ5yg_);
TM_W21qh9cNwdEes8mcgZon3lA_0[2].name = "fAddList";
TM_W21qh9cNwdEes8mcgZon3lA_28[2] = &TM_W21qh9cNwdEes8mcgZon3lA_0[3];
TM_W21qh9cNwdEes8mcgZon3lA_0[3].kind = 1;
TM_W21qh9cNwdEes8mcgZon3lA_0[3].offset = offsetof(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA, camera);
TM_W21qh9cNwdEes8mcgZon3lA_0[3].typ = (&NTI_T7Veu570Ns0s8v8VllCJeQ_);
TM_W21qh9cNwdEes8mcgZon3lA_0[3].name = "camera";
TM_W21qh9cNwdEes8mcgZon3lA_28[3] = &TM_W21qh9cNwdEes8mcgZon3lA_0[4];
TM_W21qh9cNwdEes8mcgZon3lA_0[4].kind = 1;
TM_W21qh9cNwdEes8mcgZon3lA_0[4].offset = offsetof(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA, cameraBond);
TM_W21qh9cNwdEes8mcgZon3lA_0[4].typ = (&NTI_T7Veu570Ns0s8v8VllCJeQ_);
TM_W21qh9cNwdEes8mcgZon3lA_0[4].name = "cameraBond";
TM_W21qh9cNwdEes8mcgZon3lA_28[4] = &TM_W21qh9cNwdEes8mcgZon3lA_0[5];
TM_W21qh9cNwdEes8mcgZon3lA_0[5].kind = 1;
TM_W21qh9cNwdEes8mcgZon3lA_0[5].offset = offsetof(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA, cameraBondOffset);
TM_W21qh9cNwdEes8mcgZon3lA_0[5].typ = (&NTI_wpFMp8IwxV6MlaM4GANJ0Q_);
TM_W21qh9cNwdEes8mcgZon3lA_0[5].name = "cameraBondOffset";
TM_W21qh9cNwdEes8mcgZon3lA_0[0].len = 5; TM_W21qh9cNwdEes8mcgZon3lA_0[0].kind = 2; TM_W21qh9cNwdEes8mcgZon3lA_0[0].sons = &TM_W21qh9cNwdEes8mcgZon3lA_28[0];
NTI_HJoCklFKysxcwmn6eT8mUA_.node = &TM_W21qh9cNwdEes8mcgZon3lA_0[0];
NTI_362BxmZEsdbfpPK9cPHeiRA_.size = sizeof(tyObject_ScenecolonObjectType__HJoCklFKysxcwmn6eT8mUA*);
NTI_362BxmZEsdbfpPK9cPHeiRA_.kind = 22;
NTI_362BxmZEsdbfpPK9cPHeiRA_.base = (&NTI_HJoCklFKysxcwmn6eT8mUA_);
NTI_362BxmZEsdbfpPK9cPHeiRA_.marker = Marker_tyRef_362BxmZEsdbfpPK9cPHeiRA;
}

