/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\Users\Alterna\Documents\nim-0.18.0\lib -o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\sdl2_nim_sdl.o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\sdl2_nim_sdl.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ tyObject_Rect_qiXweduDJk1iLE5aHysNdQ;
typedef struct tyObject_Point_O882QUBegNwSZhlvLsYQRw tyObject_Point_O882QUBegNwSZhlvLsYQRw;
typedef struct tyObject_RendererInfo_I9c5YLPHRMZZPky07Ra19asQ tyObject_RendererInfo_I9c5YLPHRMZZPky07Ra19asQ;
typedef struct tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg;
typedef struct tyObject_Color_YizDHyEvJtgQk2fn8KdZUA tyObject_Color_YizDHyEvJtgQk2fn8KdZUA;
typedef struct tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A;
typedef struct tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA;
typedef struct tyObject_JoystickGUID_uJWItJY4VFfI5KsjUEP2Gw tyObject_JoystickGUID_uJWItJY4VFfI5KsjUEP2Gw;
typedef union tyObject_Event_QLORHniUO5yE9cFPjAVIQUQ tyObject_Event_QLORHniUO5yE9cFPjAVIQUQ;
typedef union tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ;
typedef struct tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ;
typedef struct tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA;
typedef struct tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ;
typedef struct tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg;
typedef struct tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q;
typedef struct tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA;
typedef struct tyObject_CommonEventObj_U66FPCFgDSbmlcOHqT5Evg tyObject_CommonEventObj_U66FPCFgDSbmlcOHqT5Evg;
typedef struct tyObject_WindowEventObj_HBP9bGvXZ9cfsCLYB1W6CBWg tyObject_WindowEventObj_HBP9bGvXZ9cfsCLYB1W6CBWg;
typedef struct tyObject_KeyboardEventObj_Dgl9ajEnawue8OG9aYGwSYbA tyObject_KeyboardEventObj_Dgl9ajEnawue8OG9aYGwSYbA;
typedef struct tyObject_Keysym_F9bEEu9clWcmI0vvyozr9a4Tw tyObject_Keysym_F9bEEu9clWcmI0vvyozr9a4Tw;
typedef struct tyObject_TextEditingEventObj_4AU9cO5RL5ZL4hmpgH3Jyzg tyObject_TextEditingEventObj_4AU9cO5RL5ZL4hmpgH3Jyzg;
typedef struct tyObject_TextInputEventObj_S9cLtDyk9axj9aA9clgun09c5Ew tyObject_TextInputEventObj_S9cLtDyk9axj9aA9clgun09c5Ew;
typedef struct tyObject_MouseMotionEventObj_Y5AiWYph9bMQ3GmyLOmToig tyObject_MouseMotionEventObj_Y5AiWYph9bMQ3GmyLOmToig;
typedef struct tyObject_MouseButtonEventObj_oaAf9csV57uDbAJMQu9aLB4g tyObject_MouseButtonEventObj_oaAf9csV57uDbAJMQu9aLB4g;
typedef struct tyObject_MouseWheelEventObj_pHTMxw9akKBFiwZnl89aPqHA tyObject_MouseWheelEventObj_pHTMxw9akKBFiwZnl89aPqHA;
typedef struct tyObject_JoyAxisEventObj_9almo0Qaqu9aJI54QQBFQtxw tyObject_JoyAxisEventObj_9almo0Qaqu9aJI54QQBFQtxw;
typedef struct tyObject_JoyBallEventObj_RpVDnVNhcJe4TgE9b9cBTQyA tyObject_JoyBallEventObj_RpVDnVNhcJe4TgE9b9cBTQyA;
typedef struct tyObject_JoyHatEventObj_mT1NMwB9bgI2VnTkrYRUIfw tyObject_JoyHatEventObj_mT1NMwB9bgI2VnTkrYRUIfw;
typedef struct tyObject_JoyButtonEventObj_nyLCEn9bu9c9bD34sZSYrZKpA tyObject_JoyButtonEventObj_nyLCEn9bu9c9bD34sZSYrZKpA;
typedef struct tyObject_JoyDeviceEventObj_V7ZbnyDb6P6GWjH1BlzlWA tyObject_JoyDeviceEventObj_V7ZbnyDb6P6GWjH1BlzlWA;
typedef struct tyObject_ControllerAxisEventObj_HZEfvgUe1nwZN4Lfp9bSltg tyObject_ControllerAxisEventObj_HZEfvgUe1nwZN4Lfp9bSltg;
typedef struct tyObject_ControllerButtonEventObj_vFJG0ERJ9byeZvGy7hGG9cAA tyObject_ControllerButtonEventObj_vFJG0ERJ9byeZvGy7hGG9cAA;
typedef struct tyObject_ControllerDeviceEventObj_hNueoLSiKNHag4YYAV7iMw tyObject_ControllerDeviceEventObj_hNueoLSiKNHag4YYAV7iMw;
typedef struct tyObject_AudioDeviceEventObj_XI9bTqUH9cIPyHTibgkMxZrQ tyObject_AudioDeviceEventObj_XI9bTqUH9cIPyHTibgkMxZrQ;
typedef struct tyObject_QuitEventObj_b9aT3LGnCHReVoiRUmUOH6Q tyObject_QuitEventObj_b9aT3LGnCHReVoiRUmUOH6Q;
typedef struct tyObject_UserEventObj_Zjaeqi8Qb8tdMBVF5j19aBg tyObject_UserEventObj_Zjaeqi8Qb8tdMBVF5j19aBg;
typedef struct tyObject_SysWMEventObj_NVNWXaYFlMqYyeJw89cqUmw tyObject_SysWMEventObj_NVNWXaYFlMqYyeJw89cqUmw;
typedef struct tyObject_TouchFingerEventObj_a2BGLpKFgONBTuDEalsX9bg tyObject_TouchFingerEventObj_a2BGLpKFgONBTuDEalsX9bg;
typedef struct tyObject_MultiGestureEventObj_aD7Jwxj5RkeR6dZxbx4v9cQ tyObject_MultiGestureEventObj_aD7Jwxj5RkeR6dZxbx4v9cQ;
typedef struct tyObject_DollarGestureEventObj_9afGfbHjuc5BDKXR9aYAnpJg tyObject_DollarGestureEventObj_9afGfbHjuc5BDKXR9aYAnpJg;
typedef struct tyObject_DropEventObj_M4TEepExXfQepg9bRejOs1A tyObject_DropEventObj_M4TEepExXfQepg9bRejOs1A;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(void, tyProc_32w2ZypAyMWuajvi2Jt79cg) (void* texture);
typedef NI32 tyEnum_TextureAccess_poCqMuWAVlQ9auy0EWhBQuA;
typedef N_CDECL_PTR(int, tyProc_Z3C0z9blaIY9abfEJhIF9b1WQ) (void* texture, NU32* format, tyEnum_TextureAccess_poCqMuWAVlQ9auy0EWhBQuA* access, int* w, int* h);
typedef NI32 tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw;
typedef N_CDECL_PTR(void, tyProc_DusjKySyJW30WdV9bsteVxw) (tyEnum_LogCategory_ZUw9c3kmm9boZHlT9aDBS7AXw category, NCSTRING fmt, ...);
typedef N_CDECL_PTR(NCSTRING, tyProc_09bvyvHFtWbkzL5AHgf0bKw) (void);
typedef N_CDECL_PTR(int, tyProc_QGX7uxPZtIoH9bzksYUj1mg) (void* renderer, void* texture, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* srcrect, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* dstrect);
typedef NI32 tyEnum_RendererFlip_v7zeNYRvzJgcDDS9cEco6wg;
typedef N_CDECL_PTR(int, tyProc_oVfcvGczxlST8hWjhSa9aHA) (void* renderer, void* texture, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* srcrect, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* dstrect, double angle, tyObject_Point_O882QUBegNwSZhlvLsYQRw* center, tyEnum_RendererFlip_v7zeNYRvzJgcDDS9cEco6wg flip);
typedef N_CDECL_PTR(int, tyProc_wPxvXWWgPCAYBuODEXklIQ) (void* texture, NU8* r, NU8* g, NU8* b);
typedef N_CDECL_PTR(int, tyProc_zhHzw47u9aiQa6dkiW0Xt6A) (void* texture, NU8 r, NU8 g, NU8 b);
typedef N_CDECL_PTR(int, tyProc_vQpo9bldiNjTNBM8HFLFDnA) (void* texture, NU8* alpha);
typedef N_CDECL_PTR(int, tyProc_FlP63hJrVpAOGAcB9aysLWg) (void* texture, NU8 alpha);
typedef NI32 tyEnum_BlendMode_acuvsAfHtuIf9ats9aWCQoeQ;
typedef N_CDECL_PTR(int, tyProc_iHseqIAJGzwtK1AnPOzGxg) (void* texture, tyEnum_BlendMode_acuvsAfHtuIf9ats9aWCQoeQ* blendMode);
typedef N_CDECL_PTR(int, tyProc_drbIXv9cjqA4ZjQmLutUd0A) (void* texture, tyEnum_BlendMode_acuvsAfHtuIf9ats9aWCQoeQ blendMode);
typedef N_CDECL_PTR(int, tyProc_eacO1b28DxmNZ4wkv7Xz1A) (void* renderer, tyObject_RendererInfo_I9c5YLPHRMZZPky07Ra19asQ* info);
typedef N_CDECL_PTR(void, tyProc_3d8ZGFdX9cH9cDT9a42QwE9cvg) (tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette);
typedef N_CDECL_PTR(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg*, tyProc_Anj9as7d5YZdqOLVOsW9cq9bQ) (int ncolors);
typedef N_CDECL_PTR(int, tyProc_wotRTUnRZK0xNH5VjeE8Ng) (tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette, tyObject_Color_YizDHyEvJtgQk2fn8KdZUA* colors, int firstcolor, int ncolors);
typedef N_CDECL_PTR(void, tyProc_fj5zQw9asqT9cpDX9bwFTdIYQ) (tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A* surface);
struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ {
int x;
int y;
int w;
int h;
};
struct tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A {
NU32 flags;
tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q* format;
int w;
int h;
int pitch;
void* pixels;
void* userdata;
int locked;
void* lock_data;
tyObject_Rect_qiXweduDJk1iLE5aHysNdQ clip_rect;
void* map;
int refcount;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 tyArray_bN9bddWn8oiNSHn2MqEJSZQ[2];
struct tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q {
NU32 format;
tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette;
NU8 BitsPerPixel;
NU8 BytesPerPixel;
tyArray_bN9bddWn8oiNSHn2MqEJSZQ padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int refcount;
tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q* next;
};
struct tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg {
int ncolors;
tyObject_Color_YizDHyEvJtgQk2fn8KdZUA* colors;
NU32 version;
int refcount;
};
struct tyObject_Color_YizDHyEvJtgQk2fn8KdZUA {
NU8 r;
NU8 g;
NU8 b;
NU8 a;
};
typedef N_CDECL_PTR(int, tyProc_D19cH77xVwhL04Bkj8wjreA) (tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A* surface, tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette);
typedef N_CDECL_PTR(void*, tyProc_WCSbnyfpsjNzpCETKXisyQ) (void* renderer, tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A* surface);
typedef N_CDECL_PTR(void, tyProc_OMfTrA6Dqf9cACW3aIhhxEA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* area);
typedef N_CDECL_PTR(NU64, tyProc_F2KC9bitLsP5b9bCBN9b81hEg) (void);
typedef N_CDECL_PTR(tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA*, tyProc_Q4hOU9as18Fp2AN1WS9af3lw) (NCSTRING file, NCSTRING mode);
typedef NI32 tyEnum_Scancode_GQzt28Vd9bjjGKwYsdVggVg;
typedef N_CDECL_PTR(NU8*, tyProc_I9bPtzY9bF1nZwgVXz7RwbsQ) (int* numkeys);
typedef NI32 tyEnum_Keymod_oK9bp3RBwSGMiYY9bgGCZ3qw;
typedef N_CDECL_PTR(tyEnum_Keymod_oK9bp3RBwSGMiYY9bgGCZ3qw, tyProc_XdK6FMM9bpZDt8hBM8zRBmA) (void);
typedef N_CDECL_PTR(NU32, tyProc_3x6s3S5VLwHgqm89bRORIwA) (int* x, int* y);
typedef NU8 tyArray_qtqsWM5aXmcpMIVmvq3kAA[16];
struct tyObject_JoystickGUID_uJWItJY4VFfI5KsjUEP2Gw {
tyArray_qtqsWM5aXmcpMIVmvq3kAA data;
};
typedef N_CDECL_PTR(void*, tyProc_k1adoqH9aKm9azQEPzuEHntg) (int device_index);
typedef N_CDECL_PTR(tyObject_JoystickGUID_uJWItJY4VFfI5KsjUEP2Gw, tyProc_0uAo5XqgYf0g2Ezq241cwA) (void* joystick);
typedef N_CDECL_PTR(int, tyProc_fbYpjfe38x3ujjAmVRbI1Q) (void* joystick);
typedef N_CDECL_PTR(NCSTRING, tyProc_p1X2BwWx9a3wsChhykvf29aA) (void* joystick);
typedef N_CDECL_PTR(NU8, tyProc_JT315YeHbhx5wOveM5R6iw) (void* joystick, int button);
typedef N_CDECL_PTR(NI16, tyProc_4bw5UOiK6CCnYnXwMrhKVA) (void* joystick, int axis);
typedef N_CDECL_PTR(int, tyProc_7oyw4ZADV0qPTb4h9bhPG6g) (void* joystick, int ball, int* dx, int* dy);
typedef NU8 tyEnum_HatPosition_WXrdDcbfAWDwkLkWu9c0m2w;
typedef N_CDECL_PTR(tyEnum_HatPosition_WXrdDcbfAWDwkLkWu9c0m2w, tyProc_KlFjvoExkMPsa9c65P1UoYQ) (void* joystick, int hat);
typedef N_CDECL_PTR(NCSTRING, tyProc_AC9c6fqQ57iNdqiHar41S6g) (tyEnum_Scancode_GQzt28Vd9bjjGKwYsdVggVg scancode);
typedef N_CDECL_PTR(tyObject_JoystickGUID_uJWItJY4VFfI5KsjUEP2Gw, tyProc_UlKOyh2Hz7sZWP2OH9a8k2A) (NCSTRING pchGUID);
typedef N_CDECL_PTR(tyEnum_Scancode_GQzt28Vd9bjjGKwYsdVggVg, tyProc_ZH8c23vA4ARq6GxRdV149aQ) (NCSTRING name);
typedef N_CDECL_PTR(void, tyProc_sF69apV6Ddbmp8i9a0mNwE2Q) (tyObject_JoystickGUID_uJWItJY4VFfI5KsjUEP2Gw guid, NCSTRING pszGUID, int cbGUID);
typedef N_CDECL_PTR(void, tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(int, tyProc_qLs9bEMEYHZYOeFIf1LOpoQ) (NU32 flags);
typedef N_CDECL_PTR(void*, tyProc_hKarI59cLAeI0v1WuQhCZ9ag) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(void, tyProc_QlCkx80RqXe3H5HPnaH9bXw) (void* window, tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A* icon);
typedef N_CDECL_PTR(void*, tyProc_jPHHnsvDYo8Q3NQemQIGWg) (void* window, int index, NU32 flags);
typedef N_CDECL_PTR(int, tyProc_YsPh3gbdjC9aWnl5GwfE11g) (void* renderer, int w, int h);
typedef N_CDECL_PTR(NIM_BOOL, tyProc_CS9bxA1KE4RHFQ1vMCkCBmg) (NCSTRING name, NCSTRING value);
typedef N_CDECL_PTR(int, tyProc_cSn2aF8C9bc9c1Xq33CduLpA) (void* renderer, NIM_BOOL enable);
typedef N_CDECL_PTR(void, tyProc_WYY8i0I79agBofnUcEGCfig) (void* window, NCSTRING title);
typedef N_CDECL_PTR(void, tyProc_xmqN0ZWK4lw72DZ4V9b09cTw) (void* window, int* x, int* y);
typedef N_CDECL_PTR(void, tyProc_PhiNc70ll6IvDlrnhDZ1Zw) (void* window, int x, int y);
typedef N_CDECL_PTR(void, tyProc_5fEbO9c5NkY4gdhCj9ao7T1g) (void* window, NIM_BOOL bordered);
typedef N_CDECL_PTR(void, tyProc_yuYTMNVUr5YiJgeXuSByeQ) (void* renderer, float* scaleX, float* scaleY);
typedef N_CDECL_PTR(void, tyProc_5Og8Col0Fi6amjd7LeSCVg) (void* renderer, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* rect);
typedef N_CDECL_PTR(int, tyProc_yHY3uRNlpOCQI5Fck5Ny9bg) (void* renderer, tyObject_Rect_qiXweduDJk1iLE5aHysNdQ* rect);
typedef N_CDECL_PTR(int, tyProc_7bYZDaP1ASB0w4tVKW9bKew) (tyObject_Event_QLORHniUO5yE9cFPjAVIQUQ* event);
typedef N_CDECL_PTR(int, tyProc_buOIiiD42E5nxpbw32t0bA) (void* renderer, NU8 r, NU8 g, NU8 b, NU8 a);
struct tyObject_Point_O882QUBegNwSZhlvLsYQRw {
int x;
int y;
};
typedef NU32 tyArray_U0SiHM0pVagA9c71oWelQMA[16];
struct tyObject_RendererInfo_I9c5YLPHRMZZPky07Ra19asQ {
NCSTRING name;
NU32 flags;
NU32 num_texture_formats;
tyArray_U0SiHM0pVagA9c71oWelQMA texture_formats;
int max_texture_width;
int max_texture_height;
};
typedef N_CDECL_PTR(NI64, tyProc_p9adtE9afP6ObPoIZKMFxiAA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context);
typedef N_CDECL_PTR(NI64, tyProc_tpgoL9bwK9bkzBn2qq83QKag) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context, NI64 offset, int whence);
typedef N_CDECL_PTR(size_t, tyProc_vPnfrHDX45Ib7P40WFtTvg) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context, void* p, size_t size, size_t maxnum);
typedef N_CDECL_PTR(int, tyProc_pcLKO4pFPDvuTZj9c0HX5oA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context);
struct tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ {
void* fileNameRef;
void* inputStreamRef;
void* readableByteChannelRef;
void* readMethod;
void* assetFileDescriptorRef;
long position;
long size;
long offset;
int fd;
};
struct tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ {
void* data;
size_t size;
size_t left;
};
struct tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA {
NIM_BOOL append;
void* h;
tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ buffer;
};
struct tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg {
NIM_BOOL autoclose;
FILE* fp;
};
struct tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q {
NU8* base;
NU8* here;
NU8* stop;
};
struct tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA {
void* data1;
void* data2;
};
union tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ {
tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ androidio;
tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA windowsio;
tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg stdio;
tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q mem;
tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA unknown;
};
struct tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA {
tyProc_p9adtE9afP6ObPoIZKMFxiAA size;
tyProc_tpgoL9bwK9bkzBn2qq83QKag seek;
tyProc_vPnfrHDX45Ib7P40WFtTvg read;
tyProc_vPnfrHDX45Ib7P40WFtTvg write;
tyProc_pcLKO4pFPDvuTZj9c0HX5oA close;
NU32 kind;
tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ mem;
};
typedef NI32 tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA;
struct tyObject_CommonEventObj_U66FPCFgDSbmlcOHqT5Evg {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
};
typedef NU8 tyEnum_WindowEventID_4pBj089cDcviznpP9amV8ALg;
struct tyObject_WindowEventObj_HBP9bGvXZ9cfsCLYB1W6CBWg {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 windowID;
tyEnum_WindowEventID_4pBj089cDcviznpP9amV8ALg event;
NU8 padding1;
NU8 padding2;
NU8 padding3;
NI32 data1;
NI32 data2;
};
typedef NI32 tyEnum_Keycode_gca09as4xPHN0YKkZ6i0fwg;
struct tyObject_Keysym_F9bEEu9clWcmI0vvyozr9a4Tw {
tyEnum_Scancode_GQzt28Vd9bjjGKwYsdVggVg scancode;
tyEnum_Keycode_gca09as4xPHN0YKkZ6i0fwg sym;
NU16 mods;
NU32 unused;
};
struct tyObject_KeyboardEventObj_Dgl9ajEnawue8OG9aYGwSYbA {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 windowID;
NU8 state;
NU8 repeat;
NU8 padding2;
NU8 padding3;
tyObject_Keysym_F9bEEu9clWcmI0vvyozr9a4Tw keysym;
};
typedef NIM_CHAR tyArray_x9aRkN8DVcTBDUl3hEPJutg[32];
struct tyObject_TextEditingEventObj_4AU9cO5RL5ZL4hmpgH3Jyzg {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 windowID;
tyArray_x9aRkN8DVcTBDUl3hEPJutg text;
NI32 start;
NI32 length;
};
struct tyObject_TextInputEventObj_S9cLtDyk9axj9aA9clgun09c5Ew {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 windowID;
tyArray_x9aRkN8DVcTBDUl3hEPJutg text;
};
struct tyObject_MouseMotionEventObj_Y5AiWYph9bMQ3GmyLOmToig {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 windowID;
NU32 which;
NU32 state;
NI32 x;
NI32 y;
NI32 xrel;
NI32 yrel;
};
struct tyObject_MouseButtonEventObj_oaAf9csV57uDbAJMQu9aLB4g {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 windowID;
NU32 which;
NU8 button;
NU8 state;
NU8 clicks;
NU8 padding1;
NI32 x;
NI32 y;
};
typedef NI32 tyEnum_MouseWheelDirection_ZdgUQMIRg26TpKLhSp2wQw;
struct tyObject_MouseWheelEventObj_pHTMxw9akKBFiwZnl89aPqHA {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 windowID;
NU32 which;
NI32 x;
NI32 y;
tyEnum_MouseWheelDirection_ZdgUQMIRg26TpKLhSp2wQw direction;
};
struct tyObject_JoyAxisEventObj_9almo0Qaqu9aJI54QQBFQtxw {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI32 which;
NU8 axis;
NU8 padding1;
NU8 padding2;
NU8 padding3;
NI16 value;
NU16 padding4;
};
struct tyObject_JoyBallEventObj_RpVDnVNhcJe4TgE9b9cBTQyA {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI32 which;
NU8 ball;
NU8 padding1;
NU8 padding2;
NU8 padding3;
NI16 xrel;
NI16 yrel;
};
struct tyObject_JoyHatEventObj_mT1NMwB9bgI2VnTkrYRUIfw {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI32 which;
NU8 hat;
tyEnum_HatPosition_WXrdDcbfAWDwkLkWu9c0m2w value;
NU8 padding1;
NU8 padding2;
};
struct tyObject_JoyButtonEventObj_nyLCEn9bu9c9bD34sZSYrZKpA {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI32 which;
NU8 button;
NU8 state;
NU8 padding1;
NU8 padding2;
};
struct tyObject_JoyDeviceEventObj_V7ZbnyDb6P6GWjH1BlzlWA {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI32 which;
};
typedef NU8 tyEnum_GameControllerAxis_SZ9c5QxUIAU7GwhI6uAzqsA;
struct tyObject_ControllerAxisEventObj_HZEfvgUe1nwZN4Lfp9bSltg {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI32 which;
tyEnum_GameControllerAxis_SZ9c5QxUIAU7GwhI6uAzqsA axis;
NU8 padding1;
NU8 padding2;
NU8 padding3;
NI16 value;
NU16 padding4;
};
typedef NU8 tyEnum_GameControllerButton_GCZhKAmuNz63NHEW2cMy6g;
struct tyObject_ControllerButtonEventObj_vFJG0ERJ9byeZvGy7hGG9cAA {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI32 which;
tyEnum_GameControllerButton_GCZhKAmuNz63NHEW2cMy6g button;
NU8 state;
NU8 padding1;
NU8 padding2;
};
struct tyObject_ControllerDeviceEventObj_hNueoLSiKNHag4YYAV7iMw {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI32 which;
};
struct tyObject_AudioDeviceEventObj_XI9bTqUH9cIPyHTibgkMxZrQ {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 which;
NU8 iscapture;
NU8 padding1;
NU8 padding2;
NU8 padding3;
};
struct tyObject_QuitEventObj_b9aT3LGnCHReVoiRUmUOH6Q {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
};
struct tyObject_UserEventObj_Zjaeqi8Qb8tdMBVF5j19aBg {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NU32 windowID;
NI32 code;
void* data1;
void* data2;
};
struct tyObject_SysWMEventObj_NVNWXaYFlMqYyeJw89cqUmw {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
void* msg;
};
struct tyObject_TouchFingerEventObj_a2BGLpKFgONBTuDEalsX9bg {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI64 touchId;
NI64 fingerId;
float x;
float y;
float dx;
float dy;
float pressure;
};
struct tyObject_MultiGestureEventObj_aD7Jwxj5RkeR6dZxbx4v9cQ {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI64 touchId;
float dTheta;
float dDist;
float x;
float y;
NU16 numFingers;
NU16 padding;
};
struct tyObject_DollarGestureEventObj_9afGfbHjuc5BDKXR9aYAnpJg {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NI64 touchId;
NI64 gestureId;
NU32 numFingers;
float error;
float x;
float y;
};
struct tyObject_DropEventObj_M4TEepExXfQepg9bRejOs1A {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
NU32 timestamp;
NCSTRING file;
NU32 windowID;
};
typedef NU8 tyArray_sH9avbK619blGCGFZhgSDaWg[56];
union tyObject_Event_QLORHniUO5yE9cFPjAVIQUQ {
tyEnum_EventKind_9ah9bfUvCzPwX85zbhChobaA kind;
tyObject_CommonEventObj_U66FPCFgDSbmlcOHqT5Evg common;
tyObject_WindowEventObj_HBP9bGvXZ9cfsCLYB1W6CBWg window;
tyObject_KeyboardEventObj_Dgl9ajEnawue8OG9aYGwSYbA key;
tyObject_TextEditingEventObj_4AU9cO5RL5ZL4hmpgH3Jyzg edit;
tyObject_TextInputEventObj_S9cLtDyk9axj9aA9clgun09c5Ew text;
tyObject_MouseMotionEventObj_Y5AiWYph9bMQ3GmyLOmToig motion;
tyObject_MouseButtonEventObj_oaAf9csV57uDbAJMQu9aLB4g button;
tyObject_MouseWheelEventObj_pHTMxw9akKBFiwZnl89aPqHA wheel;
tyObject_JoyAxisEventObj_9almo0Qaqu9aJI54QQBFQtxw jaxis;
tyObject_JoyBallEventObj_RpVDnVNhcJe4TgE9b9cBTQyA jball;
tyObject_JoyHatEventObj_mT1NMwB9bgI2VnTkrYRUIfw jhat;
tyObject_JoyButtonEventObj_nyLCEn9bu9c9bD34sZSYrZKpA jbutton;
tyObject_JoyDeviceEventObj_V7ZbnyDb6P6GWjH1BlzlWA jdevice;
tyObject_ControllerAxisEventObj_HZEfvgUe1nwZN4Lfp9bSltg caxis;
tyObject_ControllerButtonEventObj_vFJG0ERJ9byeZvGy7hGG9cAA cbutton;
tyObject_ControllerDeviceEventObj_hNueoLSiKNHag4YYAV7iMw cdevice;
tyObject_AudioDeviceEventObj_XI9bTqUH9cIPyHTibgkMxZrQ adevice;
tyObject_QuitEventObj_b9aT3LGnCHReVoiRUmUOH6Q quit;
tyObject_UserEventObj_Zjaeqi8Qb8tdMBVF5j19aBg user;
tyObject_SysWMEventObj_NVNWXaYFlMqYyeJw89cqUmw syswm;
tyObject_TouchFingerEventObj_a2BGLpKFgONBTuDEalsX9bg tfinger;
tyObject_MultiGestureEventObj_aD7Jwxj5RkeR6dZxbx4v9cQ mgesture;
tyObject_DollarGestureEventObj_9afGfbHjuc5BDKXR9aYAnpJg dgesture;
tyObject_DropEventObj_M4TEepExXfQepg9bRejOs1A drop;
tyArray_sH9avbK619blGCGFZhgSDaWg padding;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static void* TM_T8sPUeYymAg4VnmycaqyjQ_2;
tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_155413_;
tyProc_Z3C0z9blaIY9abfEJhIF9b1WQ Dl_155149_;
tyProc_DusjKySyJW30WdV9bsteVxw Dl_154881_;
tyProc_09bvyvHFtWbkzL5AHgf0bKw Dl_147926_;
tyProc_QGX7uxPZtIoH9bzksYUj1mg Dl_155382_;
tyProc_oVfcvGczxlST8hWjhSa9aHA Dl_155390_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
tyProc_wPxvXWWgPCAYBuODEXklIQ Dl_155170_;
tyProc_zhHzw47u9aiQa6dkiW0Xt6A Dl_155160_;
tyProc_vQpo9bldiNjTNBM8HFLFDnA Dl_155187_;
tyProc_FlP63hJrVpAOGAcB9aysLWg Dl_155183_;
tyProc_iHseqIAJGzwtK1AnPOzGxg Dl_155196_;
tyProc_drbIXv9cjqA4ZjQmLutUd0A Dl_155192_;
tyProc_eacO1b28DxmNZ4wkv7Xz1A Dl_155126_;
tyProc_3d8ZGFdX9cH9cDT9a42QwE9cvg Dl_150911_;
tyProc_Anj9as7d5YZdqOLVOsW9cq9bQ Dl_150893_;
tyProc_wotRTUnRZK0xNH5VjeE8Ng Dl_150903_;
tyProc_fj5zQw9asqT9cpDX9bwFTdIYQ Dl_151078_;
TNimType NTI_p38hmQYM8dSHCxdlRSTN3A_;
extern TNimType NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_;
TNimType NTI_wU9cDPZQN8lu0JgltTtFK0Q_;
TNimType NTI_uR3LHDHYgbK2Xt6nAh5vfg_;
extern TNimType NTI_nlCscttRCss70IBTyuBqnA_;
TNimType NTI_YizDHyEvJtgQk2fn8KdZUA_;
extern TNimType NTI_k3HXouOuhqAKq0dx450lXQ_;
TNimType NTI_A4jJR6kA5b9beh4x9asVfwig_;
TNimType NTI_nEaLZFyoOc1bDWmF6Dnu8Q_;
TNimType NTI_bN9bddWn8oiNSHn2MqEJSZQ_;
TNimType NTI_2U9cJZm3OIF0hPUw4ebyArw_;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw_;
TNimType NTI_qiXweduDJk1iLE5aHysNdQ_;
TNimType NTI_upQLnkUdjbWZ8w9ag9btZFYw_;
tyProc_D19cH77xVwhL04Bkj8wjreA Dl_151081_;
tyProc_WCSbnyfpsjNzpCETKXisyQ Dl_155145_;
tyProc_OMfTrA6Dqf9cACW3aIhhxEA Dl_147327_;
tyProc_F2KC9bitLsP5b9bCBN9b81hEg Dl_156042_;
tyProc_F2KC9bitLsP5b9bCBN9b81hEg Dl_156044_;
tyProc_Q4hOU9as18Fp2AN1WS9af3lw Dl_147304_;
TNimType NTI_GQzt28Vd9bjjGKwYsdVggVg_;
tyProc_I9bPtzY9bF1nZwgVXz7RwbsQ Dl_153241_;
tyProc_XdK6FMM9bpZDt8hBM8zRBmA Dl_153259_;
tyProc_3x6s3S5VLwHgqm89bRORIwA Dl_153562_;
tyProc_3x6s3S5VLwHgqm89bRORIwA Dl_153574_;
TNimType NTI_uJWItJY4VFfI5KsjUEP2Gw_;
TNimType NTI_qtqsWM5aXmcpMIVmvq3kAA_;
tyProc_k1adoqH9aKm9azQEPzuEHntg Dl_153357_;
tyProc_0uAo5XqgYf0g2Ezq241cwA Dl_153366_;
tyProc_fbYpjfe38x3ujjAmVRbI1Q Dl_153404_;
tyProc_fbYpjfe38x3ujjAmVRbI1Q Dl_153395_;
tyProc_fbYpjfe38x3ujjAmVRbI1Q Dl_153398_;
tyProc_fbYpjfe38x3ujjAmVRbI1Q Dl_153401_;
tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_153487_;
tyProc_p1X2BwWx9a3wsChhykvf29aA Dl_153363_;
tyProc_JT315YeHbhx5wOveM5R6iw Dl_153483_;
tyProc_4bw5UOiK6CCnYnXwMrhKVA Dl_153417_;
tyProc_7oyw4ZADV0qPTb4h9bhPG6g Dl_153475_;
tyProc_KlFjvoExkMPsa9c65P1UoYQ Dl_153471_;
TNimType NTI_WXrdDcbfAWDwkLkWu9c0m2w_;
tyProc_AC9c6fqQ57iNdqiHar41S6g Dl_153270_;
tyProc_UlKOyh2Hz7sZWP2OH9a8k2A Dl_153386_;
tyProc_ZH8c23vA4ARq6GxRdV149aQ Dl_153273_;
tyProc_sF69apV6Ddbmp8i9a0mNwE2Q Dl_153381_;
tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_155416_;
tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_151711_;
tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_146832_;
tyProc_qLs9bEMEYHZYOeFIf1LOpoQ Dl_146820_;
tyProc_hKarI59cLAeI0v1WuQhCZ9ag Dl_151489_;
tyProc_QlCkx80RqXe3H5HPnaH9bXw Dl_151516_;
tyProc_jPHHnsvDYo8Q3NQemQIGWg Dl_155115_;
tyProc_YsPh3gbdjC9aWnl5GwfE11g Dl_155244_;
tyProc_CS9bxA1KE4RHFQ1vMCkCBmg Dl_154765_;
tyProc_cSn2aF8C9bc9c1Xq33CduLpA Dl_155256_;
tyProc_p1X2BwWx9a3wsChhykvf29aA Dl_151513_;
tyProc_WYY8i0I79agBofnUcEGCfig Dl_151509_;
tyProc_xmqN0ZWK4lw72DZ4V9b09cTw Dl_151534_;
tyProc_PhiNc70ll6IvDlrnhDZ1Zw Dl_151529_;
tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_151605_;
tyProc_xmqN0ZWK4lw72DZ4V9b09cTw Dl_151546_;
tyProc_PhiNc70ll6IvDlrnhDZ1Zw Dl_151541_;
tyProc_xmqN0ZWK4lw72DZ4V9b09cTw Dl_151569_;
tyProc_PhiNc70ll6IvDlrnhDZ1Zw Dl_151564_;
tyProc_xmqN0ZWK4lw72DZ4V9b09cTw Dl_151581_;
tyProc_PhiNc70ll6IvDlrnhDZ1Zw Dl_151576_;
tyProc_5fEbO9c5NkY4gdhCj9ao7T1g Dl_151588_;
tyProc_5fEbO9c5NkY4gdhCj9ao7T1g Dl_151592_;
tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_151596_;
tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_151599_;
tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_151602_;
tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_151608_;
tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_151611_;
tyProc_yuYTMNVUr5YiJgeXuSByeQ Dl_155291_;
tyProc_5Og8Col0Fi6amjd7LeSCVg Dl_155268_;
tyProc_yHY3uRNlpOCQI5Fck5Ny9bg Dl_155263_;
tyProc_DusjKySyJW30WdV9bsteVxw Dl_154877_;
tyProc_7bYZDaP1ASB0w4tVKW9bKew Dl_154239_;
tyProc_buOIiiD42E5nxpbw32t0bA Dl_155298_;
tyProc_fbYpjfe38x3ujjAmVRbI1Q Dl_155333_;
tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_155410_;
STRING_LITERAL(TM_T8sPUeYymAg4VnmycaqyjQ_4, "SDL2.dll", 8);
STRING_LITERAL(TM_T8sPUeYymAg4VnmycaqyjQ_5, "SDL2.dll", 8);

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(int, toCint_yAPwf7d9aO5za0vgIa7yl8g)(NI x) {
	int result;
	nimfr_("toCint", "stdinc.nim");
	result = (int)0;
	nimln_(85, "stdinc.nim");
	result = ((int)chckRange(x, ((int) (-2147483647 -1)), ((int) 2147483647)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, toInt_FyvsRljGYhrqFJddP0X6JQ)(NU8 x) {
	NI result;
	nimfr_("toInt", "stdinc.nim");
	result = (NI)0;
	nimln_(87, "stdinc.nim");
	result = ((NI) (x));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, sdl2_nim_sdlInit000)(void) {
	nimfr_("sdl", "sdl.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_nim_sdlDatInit000)(void) {
static TNimNode* TM_T8sPUeYymAg4VnmycaqyjQ_40[12];
static TNimNode* TM_T8sPUeYymAg4VnmycaqyjQ_41[19];
static TNimNode* TM_T8sPUeYymAg4VnmycaqyjQ_42[4];
static TNimNode* TM_T8sPUeYymAg4VnmycaqyjQ_43[4];
static TNimNode* TM_T8sPUeYymAg4VnmycaqyjQ_44[4];
static TNimNode* TM_T8sPUeYymAg4VnmycaqyjQ_57[244];
NI TM_T8sPUeYymAg4VnmycaqyjQ_59;
static char* NIM_CONST TM_T8sPUeYymAg4VnmycaqyjQ_58[244] = {
"SCANCODE_UNKNOWN", 
"SCANCODE_A", 
"SCANCODE_B", 
"SCANCODE_C", 
"SCANCODE_D", 
"SCANCODE_E", 
"SCANCODE_F", 
"SCANCODE_G", 
"SCANCODE_H", 
"SCANCODE_I", 
"SCANCODE_J", 
"SCANCODE_K", 
"SCANCODE_L", 
"SCANCODE_M", 
"SCANCODE_N", 
"SCANCODE_O", 
"SCANCODE_P", 
"SCANCODE_Q", 
"SCANCODE_R", 
"SCANCODE_S", 
"SCANCODE_T", 
"SCANCODE_U", 
"SCANCODE_V", 
"SCANCODE_W", 
"SCANCODE_X", 
"SCANCODE_Y", 
"SCANCODE_Z", 
"SCANCODE_1", 
"SCANCODE_2", 
"SCANCODE_3", 
"SCANCODE_4", 
"SCANCODE_5", 
"SCANCODE_6", 
"SCANCODE_7", 
"SCANCODE_8", 
"SCANCODE_9", 
"SCANCODE_0", 
"SCANCODE_RETURN", 
"SCANCODE_ESCAPE", 
"SCANCODE_BACKSPACE", 
"SCANCODE_TAB", 
"SCANCODE_SPACE", 
"SCANCODE_MINUS", 
"SCANCODE_EQUALS", 
"SCANCODE_LEFTBRACKET", 
"SCANCODE_RIGHTBRACKET", 
"SCANCODE_BACKSLASH", 
"SCANCODE_NONUSHASH", 
"SCANCODE_SEMICOLON", 
"SCANCODE_APOSTROPHE", 
"SCANCODE_GRAVE", 
"SCANCODE_COMMA", 
"SCANCODE_PERIOD", 
"SCANCODE_SLASH", 
"SCANCODE_CAPSLOCK", 
"SCANCODE_F1", 
"SCANCODE_F2", 
"SCANCODE_F3", 
"SCANCODE_F4", 
"SCANCODE_F5", 
"SCANCODE_F6", 
"SCANCODE_F7", 
"SCANCODE_F8", 
"SCANCODE_F9", 
"SCANCODE_F10", 
"SCANCODE_F11", 
"SCANCODE_F12", 
"SCANCODE_PRINTSCREEN", 
"SCANCODE_SCROLLLOCK", 
"SCANCODE_PAUSE", 
"SCANCODE_INSERT", 
"SCANCODE_HOME", 
"SCANCODE_PAGEUP", 
"SCANCODE_DELETE", 
"SCANCODE_END", 
"SCANCODE_PAGEDOWN", 
"SCANCODE_RIGHT", 
"SCANCODE_LEFT", 
"SCANCODE_DOWN", 
"SCANCODE_UP", 
"SCANCODE_NUMLOCKCLEAR", 
"SCANCODE_KP_DIVIDE", 
"SCANCODE_KP_MULTIPLY", 
"SCANCODE_KP_MINUS", 
"SCANCODE_KP_PLUS", 
"SCANCODE_KP_ENTER", 
"SCANCODE_KP_1", 
"SCANCODE_KP_2", 
"SCANCODE_KP_3", 
"SCANCODE_KP_4", 
"SCANCODE_KP_5", 
"SCANCODE_KP_6", 
"SCANCODE_KP_7", 
"SCANCODE_KP_8", 
"SCANCODE_KP_9", 
"SCANCODE_KP_0", 
"SCANCODE_KP_PERIOD", 
"SCANCODE_NONUSBACKSLASH", 
"SCANCODE_APPLICATION", 
"SCANCODE_POWER", 
"SCANCODE_KP_EQUALS", 
"SCANCODE_F13", 
"SCANCODE_F14", 
"SCANCODE_F15", 
"SCANCODE_F16", 
"SCANCODE_F17", 
"SCANCODE_F18", 
"SCANCODE_F19", 
"SCANCODE_F20", 
"SCANCODE_F21", 
"SCANCODE_F22", 
"SCANCODE_F23", 
"SCANCODE_F24", 
"SCANCODE_EXECUTE", 
"SCANCODE_HELP", 
"SCANCODE_MENU", 
"SCANCODE_SELECT", 
"SCANCODE_STOP", 
"SCANCODE_AGAIN", 
"SCANCODE_UNDO", 
"SCANCODE_CUT", 
"SCANCODE_COPY", 
"SCANCODE_PASTE", 
"SCANCODE_FIND", 
"SCANCODE_MUTE", 
"SCANCODE_VOLUMEUP", 
"SCANCODE_VOLUMEDOWN", 
"SCANCODE_KP_COMMA", 
"SCANCODE_KP_EQUALSAS400", 
"SCANCODE_INTERNATIONAL1", 
"SCANCODE_INTERNATIONAL2", 
"SCANCODE_INTERNATIONAL3", 
"SCANCODE_INTERNATIONAL4", 
"SCANCODE_INTERNATIONAL5", 
"SCANCODE_INTERNATIONAL6", 
"SCANCODE_INTERNATIONAL7", 
"SCANCODE_INTERNATIONAL8", 
"SCANCODE_INTERNATIONAL9", 
"SCANCODE_LANG1", 
"SCANCODE_LANG2", 
"SCANCODE_LANG3", 
"SCANCODE_LANG4", 
"SCANCODE_LANG5", 
"SCANCODE_LANG6", 
"SCANCODE_LANG7", 
"SCANCODE_LANG8", 
"SCANCODE_LANG9", 
"SCANCODE_ALTERASE", 
"SCANCODE_SYSREQ", 
"SCANCODE_CANCEL", 
"SCANCODE_CLEAR", 
"SCANCODE_PRIOR", 
"SCANCODE_RETURN2", 
"SCANCODE_SEPARATOR", 
"SCANCODE_OUT", 
"SCANCODE_OPER", 
"SCANCODE_CLEARAGAIN", 
"SCANCODE_CRSEL", 
"SCANCODE_EXSEL", 
"SCANCODE_KP_00", 
"SCANCODE_KP_000", 
"SCANCODE_THOUSANDSSEPARATOR", 
"SCANCODE_DECIMALSEPARATOR", 
"SCANCODE_CURRENCYUNIT", 
"SCANCODE_CURRENCYSUBUNIT", 
"SCANCODE_KP_LEFTPAREN", 
"SCANCODE_KP_RIGHTPAREN", 
"SCANCODE_KP_LEFTBRACE", 
"SCANCODE_KP_RIGHTBRACE", 
"SCANCODE_KP_TAB", 
"SCANCODE_KP_BACKSPACE", 
"SCANCODE_KP_A", 
"SCANCODE_KP_B", 
"SCANCODE_KP_C", 
"SCANCODE_KP_D", 
"SCANCODE_KP_E", 
"SCANCODE_KP_F", 
"SCANCODE_KP_XOR", 
"SCANCODE_KP_POWER", 
"SCANCODE_KP_PERCENT", 
"SCANCODE_KP_LESS", 
"SCANCODE_KP_GREATER", 
"SCANCODE_KP_AMPERSAND", 
"SCANCODE_KP_DBLAMPERSAND", 
"SCANCODE_KP_VERTICALBAR", 
"SCANCODE_KP_DBLVERTICALBAR", 
"SCANCODE_KP_COLON", 
"SCANCODE_KP_HASH", 
"SCANCODE_KP_SPACE", 
"SCANCODE_KP_AT", 
"SCANCODE_KP_EXCLAM", 
"SCANCODE_KP_MEMSTORE", 
"SCANCODE_KP_MEMRECALL", 
"SCANCODE_KP_MEMCLEAR", 
"SCANCODE_KP_MEMADD", 
"SCANCODE_KP_MEMSUBTRACT", 
"SCANCODE_KP_MEMMULTIPLY", 
"SCANCODE_KP_MEMDIVIDE", 
"SCANCODE_KP_PLUSMINUS", 
"SCANCODE_KP_CLEAR", 
"SCANCODE_KP_CLEARENTRY", 
"SCANCODE_KP_BINARY", 
"SCANCODE_KP_OCTAL", 
"SCANCODE_KP_DECIMAL", 
"SCANCODE_KP_HEXADECIMAL", 
"SCANCODE_LCTRL", 
"SCANCODE_LSHIFT", 
"SCANCODE_LALT", 
"SCANCODE_LGUI", 
"SCANCODE_RCTRL", 
"SCANCODE_RSHIFT", 
"SCANCODE_RALT", 
"SCANCODE_RGUI", 
"SCANCODE_MODE", 
"SCANCODE_AUDIONEXT", 
"SCANCODE_AUDIOPREV", 
"SCANCODE_AUDIOSTOP", 
"SCANCODE_AUDIOPLAY", 
"SCANCODE_AUDIOMUTE", 
"SCANCODE_MEDIASELECT", 
"SCANCODE_WWW", 
"SCANCODE_MAIL", 
"SCANCODE_CALCULATOR", 
"SCANCODE_COMPUTER", 
"SCANCODE_AC_SEARCH", 
"SCANCODE_AC_HOME", 
"SCANCODE_AC_BACK", 
"SCANCODE_AC_FORWARD", 
"SCANCODE_AC_STOP", 
"SCANCODE_AC_REFRESH", 
"SCANCODE_AC_BOOKMARKS", 
"SCANCODE_BRIGHTNESSDOWN", 
"SCANCODE_BRIGHTNESSUP", 
"SCANCODE_DISPLAYSWITCH", 
"SCANCODE_KBDILLUMTOGGLE", 
"SCANCODE_KBDILLUMDOWN", 
"SCANCODE_KBDILLUMUP", 
"SCANCODE_EJECT", 
"SCANCODE_SLEEP", 
"SCANCODE_APP1", 
"SCANCODE_APP2", 
"SCANCODE_AUDIOREWIND", 
"SCANCODE_AUDIOFASTFORWARD", 
"NUM_SCANCODES"};
static TNimNode* TM_T8sPUeYymAg4VnmycaqyjQ_92[9];
NI TM_T8sPUeYymAg4VnmycaqyjQ_94;
static char* NIM_CONST TM_T8sPUeYymAg4VnmycaqyjQ_93[9] = {
"HAT_CENTERED", 
"HAT_UP", 
"HAT_RIGHT", 
"HAT_RIGHTUP", 
"HAT_DOWN", 
"HAT_RIGHTDOWN", 
"HAT_LEFT", 
"HAT_LEFTUP", 
"HAT_LEFTDOWN"};
static TNimNode TM_T8sPUeYymAg4VnmycaqyjQ_0[304];
NTI_p38hmQYM8dSHCxdlRSTN3A_.size = sizeof(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A);
NTI_p38hmQYM8dSHCxdlRSTN3A_.kind = 18;
NTI_p38hmQYM8dSHCxdlRSTN3A_.base = 0;
NTI_p38hmQYM8dSHCxdlRSTN3A_.flags = 3;
TM_T8sPUeYymAg4VnmycaqyjQ_40[0] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[1];
TM_T8sPUeYymAg4VnmycaqyjQ_0[1].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[1].offset = offsetof(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A, flags);
TM_T8sPUeYymAg4VnmycaqyjQ_0[1].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[1].name = "flags";
TM_T8sPUeYymAg4VnmycaqyjQ_40[1] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[2];
NTI_wU9cDPZQN8lu0JgltTtFK0Q_.size = sizeof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q);
NTI_wU9cDPZQN8lu0JgltTtFK0Q_.kind = 18;
NTI_wU9cDPZQN8lu0JgltTtFK0Q_.base = 0;
NTI_wU9cDPZQN8lu0JgltTtFK0Q_.flags = 3;
TM_T8sPUeYymAg4VnmycaqyjQ_41[0] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[4];
TM_T8sPUeYymAg4VnmycaqyjQ_0[4].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[4].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, format);
TM_T8sPUeYymAg4VnmycaqyjQ_0[4].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[4].name = "format";
TM_T8sPUeYymAg4VnmycaqyjQ_41[1] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[5];
NTI_uR3LHDHYgbK2Xt6nAh5vfg_.size = sizeof(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg);
NTI_uR3LHDHYgbK2Xt6nAh5vfg_.kind = 18;
NTI_uR3LHDHYgbK2Xt6nAh5vfg_.base = 0;
NTI_uR3LHDHYgbK2Xt6nAh5vfg_.flags = 3;
TM_T8sPUeYymAg4VnmycaqyjQ_42[0] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[7];
TM_T8sPUeYymAg4VnmycaqyjQ_0[7].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[7].offset = offsetof(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg, ncolors);
TM_T8sPUeYymAg4VnmycaqyjQ_0[7].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[7].name = "ncolors";
TM_T8sPUeYymAg4VnmycaqyjQ_42[1] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[8];
NTI_YizDHyEvJtgQk2fn8KdZUA_.size = sizeof(tyObject_Color_YizDHyEvJtgQk2fn8KdZUA);
NTI_YizDHyEvJtgQk2fn8KdZUA_.kind = 18;
NTI_YizDHyEvJtgQk2fn8KdZUA_.base = 0;
NTI_YizDHyEvJtgQk2fn8KdZUA_.flags = 3;
TM_T8sPUeYymAg4VnmycaqyjQ_43[0] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[10];
TM_T8sPUeYymAg4VnmycaqyjQ_0[10].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[10].offset = offsetof(tyObject_Color_YizDHyEvJtgQk2fn8KdZUA, r);
TM_T8sPUeYymAg4VnmycaqyjQ_0[10].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[10].name = "r";
TM_T8sPUeYymAg4VnmycaqyjQ_43[1] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[11];
TM_T8sPUeYymAg4VnmycaqyjQ_0[11].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[11].offset = offsetof(tyObject_Color_YizDHyEvJtgQk2fn8KdZUA, g);
TM_T8sPUeYymAg4VnmycaqyjQ_0[11].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[11].name = "g";
TM_T8sPUeYymAg4VnmycaqyjQ_43[2] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[12];
TM_T8sPUeYymAg4VnmycaqyjQ_0[12].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[12].offset = offsetof(tyObject_Color_YizDHyEvJtgQk2fn8KdZUA, b);
TM_T8sPUeYymAg4VnmycaqyjQ_0[12].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[12].name = "b";
TM_T8sPUeYymAg4VnmycaqyjQ_43[3] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[13];
TM_T8sPUeYymAg4VnmycaqyjQ_0[13].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[13].offset = offsetof(tyObject_Color_YizDHyEvJtgQk2fn8KdZUA, a);
TM_T8sPUeYymAg4VnmycaqyjQ_0[13].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[13].name = "a";
TM_T8sPUeYymAg4VnmycaqyjQ_0[9].len = 4; TM_T8sPUeYymAg4VnmycaqyjQ_0[9].kind = 2; TM_T8sPUeYymAg4VnmycaqyjQ_0[9].sons = &TM_T8sPUeYymAg4VnmycaqyjQ_43[0];
NTI_YizDHyEvJtgQk2fn8KdZUA_.node = &TM_T8sPUeYymAg4VnmycaqyjQ_0[9];
NTI_A4jJR6kA5b9beh4x9asVfwig_.size = sizeof(tyObject_Color_YizDHyEvJtgQk2fn8KdZUA*);
NTI_A4jJR6kA5b9beh4x9asVfwig_.kind = 21;
NTI_A4jJR6kA5b9beh4x9asVfwig_.base = (&NTI_YizDHyEvJtgQk2fn8KdZUA_);
NTI_A4jJR6kA5b9beh4x9asVfwig_.flags = 3;
TM_T8sPUeYymAg4VnmycaqyjQ_0[8].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[8].offset = offsetof(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg, colors);
TM_T8sPUeYymAg4VnmycaqyjQ_0[8].typ = (&NTI_A4jJR6kA5b9beh4x9asVfwig_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[8].name = "colors";
TM_T8sPUeYymAg4VnmycaqyjQ_42[2] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[14];
TM_T8sPUeYymAg4VnmycaqyjQ_0[14].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[14].offset = offsetof(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg, version);
TM_T8sPUeYymAg4VnmycaqyjQ_0[14].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[14].name = "version";
TM_T8sPUeYymAg4VnmycaqyjQ_42[3] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[15];
TM_T8sPUeYymAg4VnmycaqyjQ_0[15].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[15].offset = offsetof(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg, refcount);
TM_T8sPUeYymAg4VnmycaqyjQ_0[15].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[15].name = "refcount";
TM_T8sPUeYymAg4VnmycaqyjQ_0[6].len = 4; TM_T8sPUeYymAg4VnmycaqyjQ_0[6].kind = 2; TM_T8sPUeYymAg4VnmycaqyjQ_0[6].sons = &TM_T8sPUeYymAg4VnmycaqyjQ_42[0];
NTI_uR3LHDHYgbK2Xt6nAh5vfg_.node = &TM_T8sPUeYymAg4VnmycaqyjQ_0[6];
NTI_nEaLZFyoOc1bDWmF6Dnu8Q_.size = sizeof(tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg*);
NTI_nEaLZFyoOc1bDWmF6Dnu8Q_.kind = 21;
NTI_nEaLZFyoOc1bDWmF6Dnu8Q_.base = (&NTI_uR3LHDHYgbK2Xt6nAh5vfg_);
NTI_nEaLZFyoOc1bDWmF6Dnu8Q_.flags = 3;
TM_T8sPUeYymAg4VnmycaqyjQ_0[5].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[5].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, palette);
TM_T8sPUeYymAg4VnmycaqyjQ_0[5].typ = (&NTI_nEaLZFyoOc1bDWmF6Dnu8Q_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[5].name = "palette";
TM_T8sPUeYymAg4VnmycaqyjQ_41[2] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[16];
TM_T8sPUeYymAg4VnmycaqyjQ_0[16].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[16].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, BitsPerPixel);
TM_T8sPUeYymAg4VnmycaqyjQ_0[16].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[16].name = "BitsPerPixel";
TM_T8sPUeYymAg4VnmycaqyjQ_41[3] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[17];
TM_T8sPUeYymAg4VnmycaqyjQ_0[17].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[17].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, BytesPerPixel);
TM_T8sPUeYymAg4VnmycaqyjQ_0[17].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[17].name = "BytesPerPixel";
TM_T8sPUeYymAg4VnmycaqyjQ_41[4] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[18];
NTI_bN9bddWn8oiNSHn2MqEJSZQ_.size = sizeof(tyArray_bN9bddWn8oiNSHn2MqEJSZQ);
NTI_bN9bddWn8oiNSHn2MqEJSZQ_.kind = 16;
NTI_bN9bddWn8oiNSHn2MqEJSZQ_.base = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
NTI_bN9bddWn8oiNSHn2MqEJSZQ_.flags = 3;
TM_T8sPUeYymAg4VnmycaqyjQ_0[18].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[18].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, padding);
TM_T8sPUeYymAg4VnmycaqyjQ_0[18].typ = (&NTI_bN9bddWn8oiNSHn2MqEJSZQ_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[18].name = "padding";
TM_T8sPUeYymAg4VnmycaqyjQ_41[5] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[19];
TM_T8sPUeYymAg4VnmycaqyjQ_0[19].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[19].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, Rmask);
TM_T8sPUeYymAg4VnmycaqyjQ_0[19].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[19].name = "Rmask";
TM_T8sPUeYymAg4VnmycaqyjQ_41[6] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[20];
TM_T8sPUeYymAg4VnmycaqyjQ_0[20].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[20].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, Gmask);
TM_T8sPUeYymAg4VnmycaqyjQ_0[20].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[20].name = "Gmask";
TM_T8sPUeYymAg4VnmycaqyjQ_41[7] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[21];
TM_T8sPUeYymAg4VnmycaqyjQ_0[21].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[21].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, Bmask);
TM_T8sPUeYymAg4VnmycaqyjQ_0[21].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[21].name = "Bmask";
TM_T8sPUeYymAg4VnmycaqyjQ_41[8] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[22];
TM_T8sPUeYymAg4VnmycaqyjQ_0[22].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[22].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, Amask);
TM_T8sPUeYymAg4VnmycaqyjQ_0[22].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[22].name = "Amask";
TM_T8sPUeYymAg4VnmycaqyjQ_41[9] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[23];
TM_T8sPUeYymAg4VnmycaqyjQ_0[23].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[23].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, Rloss);
TM_T8sPUeYymAg4VnmycaqyjQ_0[23].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[23].name = "Rloss";
TM_T8sPUeYymAg4VnmycaqyjQ_41[10] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[24];
TM_T8sPUeYymAg4VnmycaqyjQ_0[24].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[24].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, Gloss);
TM_T8sPUeYymAg4VnmycaqyjQ_0[24].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[24].name = "Gloss";
TM_T8sPUeYymAg4VnmycaqyjQ_41[11] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[25];
TM_T8sPUeYymAg4VnmycaqyjQ_0[25].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[25].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, Bloss);
TM_T8sPUeYymAg4VnmycaqyjQ_0[25].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[25].name = "Bloss";
TM_T8sPUeYymAg4VnmycaqyjQ_41[12] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[26];
TM_T8sPUeYymAg4VnmycaqyjQ_0[26].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[26].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, Aloss);
TM_T8sPUeYymAg4VnmycaqyjQ_0[26].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[26].name = "Aloss";
TM_T8sPUeYymAg4VnmycaqyjQ_41[13] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[27];
TM_T8sPUeYymAg4VnmycaqyjQ_0[27].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[27].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, Rshift);
TM_T8sPUeYymAg4VnmycaqyjQ_0[27].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[27].name = "Rshift";
TM_T8sPUeYymAg4VnmycaqyjQ_41[14] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[28];
TM_T8sPUeYymAg4VnmycaqyjQ_0[28].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[28].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, Gshift);
TM_T8sPUeYymAg4VnmycaqyjQ_0[28].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[28].name = "Gshift";
TM_T8sPUeYymAg4VnmycaqyjQ_41[15] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[29];
TM_T8sPUeYymAg4VnmycaqyjQ_0[29].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[29].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, Bshift);
TM_T8sPUeYymAg4VnmycaqyjQ_0[29].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[29].name = "Bshift";
TM_T8sPUeYymAg4VnmycaqyjQ_41[16] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[30];
TM_T8sPUeYymAg4VnmycaqyjQ_0[30].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[30].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, Ashift);
TM_T8sPUeYymAg4VnmycaqyjQ_0[30].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[30].name = "Ashift";
TM_T8sPUeYymAg4VnmycaqyjQ_41[17] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[31];
TM_T8sPUeYymAg4VnmycaqyjQ_0[31].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[31].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, refcount);
TM_T8sPUeYymAg4VnmycaqyjQ_0[31].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[31].name = "refcount";
TM_T8sPUeYymAg4VnmycaqyjQ_41[18] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[32];
TM_T8sPUeYymAg4VnmycaqyjQ_0[32].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[32].offset = offsetof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q, next);
TM_T8sPUeYymAg4VnmycaqyjQ_0[32].typ = (&NTI_2U9cJZm3OIF0hPUw4ebyArw_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[32].name = "next";
TM_T8sPUeYymAg4VnmycaqyjQ_0[3].len = 19; TM_T8sPUeYymAg4VnmycaqyjQ_0[3].kind = 2; TM_T8sPUeYymAg4VnmycaqyjQ_0[3].sons = &TM_T8sPUeYymAg4VnmycaqyjQ_41[0];
NTI_wU9cDPZQN8lu0JgltTtFK0Q_.node = &TM_T8sPUeYymAg4VnmycaqyjQ_0[3];
NTI_2U9cJZm3OIF0hPUw4ebyArw_.size = sizeof(tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q*);
NTI_2U9cJZm3OIF0hPUw4ebyArw_.kind = 21;
NTI_2U9cJZm3OIF0hPUw4ebyArw_.base = (&NTI_wU9cDPZQN8lu0JgltTtFK0Q_);
NTI_2U9cJZm3OIF0hPUw4ebyArw_.flags = 3;
TM_T8sPUeYymAg4VnmycaqyjQ_0[2].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[2].offset = offsetof(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A, format);
TM_T8sPUeYymAg4VnmycaqyjQ_0[2].typ = (&NTI_2U9cJZm3OIF0hPUw4ebyArw_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[2].name = "format";
TM_T8sPUeYymAg4VnmycaqyjQ_40[2] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[33];
TM_T8sPUeYymAg4VnmycaqyjQ_0[33].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[33].offset = offsetof(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A, w);
TM_T8sPUeYymAg4VnmycaqyjQ_0[33].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[33].name = "w";
TM_T8sPUeYymAg4VnmycaqyjQ_40[3] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[34];
TM_T8sPUeYymAg4VnmycaqyjQ_0[34].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[34].offset = offsetof(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A, h);
TM_T8sPUeYymAg4VnmycaqyjQ_0[34].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[34].name = "h";
TM_T8sPUeYymAg4VnmycaqyjQ_40[4] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[35];
TM_T8sPUeYymAg4VnmycaqyjQ_0[35].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[35].offset = offsetof(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A, pitch);
TM_T8sPUeYymAg4VnmycaqyjQ_0[35].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[35].name = "pitch";
TM_T8sPUeYymAg4VnmycaqyjQ_40[5] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[36];
TM_T8sPUeYymAg4VnmycaqyjQ_0[36].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[36].offset = offsetof(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A, pixels);
TM_T8sPUeYymAg4VnmycaqyjQ_0[36].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[36].name = "pixels";
TM_T8sPUeYymAg4VnmycaqyjQ_40[6] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[37];
TM_T8sPUeYymAg4VnmycaqyjQ_0[37].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[37].offset = offsetof(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A, userdata);
TM_T8sPUeYymAg4VnmycaqyjQ_0[37].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[37].name = "userdata";
TM_T8sPUeYymAg4VnmycaqyjQ_40[7] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[38];
TM_T8sPUeYymAg4VnmycaqyjQ_0[38].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[38].offset = offsetof(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A, locked);
TM_T8sPUeYymAg4VnmycaqyjQ_0[38].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[38].name = "locked";
TM_T8sPUeYymAg4VnmycaqyjQ_40[8] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[39];
TM_T8sPUeYymAg4VnmycaqyjQ_0[39].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[39].offset = offsetof(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A, lock_data);
TM_T8sPUeYymAg4VnmycaqyjQ_0[39].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[39].name = "lock_data";
TM_T8sPUeYymAg4VnmycaqyjQ_40[9] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[40];
NTI_qiXweduDJk1iLE5aHysNdQ_.size = sizeof(tyObject_Rect_qiXweduDJk1iLE5aHysNdQ);
NTI_qiXweduDJk1iLE5aHysNdQ_.kind = 18;
NTI_qiXweduDJk1iLE5aHysNdQ_.base = 0;
NTI_qiXweduDJk1iLE5aHysNdQ_.flags = 3;
TM_T8sPUeYymAg4VnmycaqyjQ_44[0] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[42];
TM_T8sPUeYymAg4VnmycaqyjQ_0[42].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[42].offset = offsetof(tyObject_Rect_qiXweduDJk1iLE5aHysNdQ, x);
TM_T8sPUeYymAg4VnmycaqyjQ_0[42].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[42].name = "x";
TM_T8sPUeYymAg4VnmycaqyjQ_44[1] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[43];
TM_T8sPUeYymAg4VnmycaqyjQ_0[43].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[43].offset = offsetof(tyObject_Rect_qiXweduDJk1iLE5aHysNdQ, y);
TM_T8sPUeYymAg4VnmycaqyjQ_0[43].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[43].name = "y";
TM_T8sPUeYymAg4VnmycaqyjQ_44[2] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[44];
TM_T8sPUeYymAg4VnmycaqyjQ_0[44].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[44].offset = offsetof(tyObject_Rect_qiXweduDJk1iLE5aHysNdQ, w);
TM_T8sPUeYymAg4VnmycaqyjQ_0[44].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[44].name = "w";
TM_T8sPUeYymAg4VnmycaqyjQ_44[3] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[45];
TM_T8sPUeYymAg4VnmycaqyjQ_0[45].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[45].offset = offsetof(tyObject_Rect_qiXweduDJk1iLE5aHysNdQ, h);
TM_T8sPUeYymAg4VnmycaqyjQ_0[45].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[45].name = "h";
TM_T8sPUeYymAg4VnmycaqyjQ_0[41].len = 4; TM_T8sPUeYymAg4VnmycaqyjQ_0[41].kind = 2; TM_T8sPUeYymAg4VnmycaqyjQ_0[41].sons = &TM_T8sPUeYymAg4VnmycaqyjQ_44[0];
NTI_qiXweduDJk1iLE5aHysNdQ_.node = &TM_T8sPUeYymAg4VnmycaqyjQ_0[41];
TM_T8sPUeYymAg4VnmycaqyjQ_0[40].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[40].offset = offsetof(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A, clip_rect);
TM_T8sPUeYymAg4VnmycaqyjQ_0[40].typ = (&NTI_qiXweduDJk1iLE5aHysNdQ_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[40].name = "clip_rect";
TM_T8sPUeYymAg4VnmycaqyjQ_40[10] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[46];
TM_T8sPUeYymAg4VnmycaqyjQ_0[46].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[46].offset = offsetof(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A, map);
TM_T8sPUeYymAg4VnmycaqyjQ_0[46].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[46].name = "map";
TM_T8sPUeYymAg4VnmycaqyjQ_40[11] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[47];
TM_T8sPUeYymAg4VnmycaqyjQ_0[47].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[47].offset = offsetof(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A, refcount);
TM_T8sPUeYymAg4VnmycaqyjQ_0[47].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[47].name = "refcount";
TM_T8sPUeYymAg4VnmycaqyjQ_0[0].len = 12; TM_T8sPUeYymAg4VnmycaqyjQ_0[0].kind = 2; TM_T8sPUeYymAg4VnmycaqyjQ_0[0].sons = &TM_T8sPUeYymAg4VnmycaqyjQ_40[0];
NTI_p38hmQYM8dSHCxdlRSTN3A_.node = &TM_T8sPUeYymAg4VnmycaqyjQ_0[0];
NTI_upQLnkUdjbWZ8w9ag9btZFYw_.size = sizeof(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A*);
NTI_upQLnkUdjbWZ8w9ag9btZFYw_.kind = 21;
NTI_upQLnkUdjbWZ8w9ag9btZFYw_.base = (&NTI_p38hmQYM8dSHCxdlRSTN3A_);
NTI_upQLnkUdjbWZ8w9ag9btZFYw_.flags = 3;
NTI_GQzt28Vd9bjjGKwYsdVggVg_.size = sizeof(tyEnum_Scancode_GQzt28Vd9bjjGKwYsdVggVg);
NTI_GQzt28Vd9bjjGKwYsdVggVg_.kind = 14;
NTI_GQzt28Vd9bjjGKwYsdVggVg_.base = 0;
NTI_GQzt28Vd9bjjGKwYsdVggVg_.flags = 3;
for (TM_T8sPUeYymAg4VnmycaqyjQ_59 = 0; TM_T8sPUeYymAg4VnmycaqyjQ_59 < 244; TM_T8sPUeYymAg4VnmycaqyjQ_59++) {
TM_T8sPUeYymAg4VnmycaqyjQ_0[TM_T8sPUeYymAg4VnmycaqyjQ_59+48].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[TM_T8sPUeYymAg4VnmycaqyjQ_59+48].offset = TM_T8sPUeYymAg4VnmycaqyjQ_59;
TM_T8sPUeYymAg4VnmycaqyjQ_0[TM_T8sPUeYymAg4VnmycaqyjQ_59+48].name = TM_T8sPUeYymAg4VnmycaqyjQ_58[TM_T8sPUeYymAg4VnmycaqyjQ_59];
TM_T8sPUeYymAg4VnmycaqyjQ_57[TM_T8sPUeYymAg4VnmycaqyjQ_59] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[TM_T8sPUeYymAg4VnmycaqyjQ_59+48];
}
TM_T8sPUeYymAg4VnmycaqyjQ_0[48].offset = 0;
TM_T8sPUeYymAg4VnmycaqyjQ_0[49].offset = 4;
TM_T8sPUeYymAg4VnmycaqyjQ_0[50].offset = 5;
TM_T8sPUeYymAg4VnmycaqyjQ_0[51].offset = 6;
TM_T8sPUeYymAg4VnmycaqyjQ_0[52].offset = 7;
TM_T8sPUeYymAg4VnmycaqyjQ_0[53].offset = 8;
TM_T8sPUeYymAg4VnmycaqyjQ_0[54].offset = 9;
TM_T8sPUeYymAg4VnmycaqyjQ_0[55].offset = 10;
TM_T8sPUeYymAg4VnmycaqyjQ_0[56].offset = 11;
TM_T8sPUeYymAg4VnmycaqyjQ_0[57].offset = 12;
TM_T8sPUeYymAg4VnmycaqyjQ_0[58].offset = 13;
TM_T8sPUeYymAg4VnmycaqyjQ_0[59].offset = 14;
TM_T8sPUeYymAg4VnmycaqyjQ_0[60].offset = 15;
TM_T8sPUeYymAg4VnmycaqyjQ_0[61].offset = 16;
TM_T8sPUeYymAg4VnmycaqyjQ_0[62].offset = 17;
TM_T8sPUeYymAg4VnmycaqyjQ_0[63].offset = 18;
TM_T8sPUeYymAg4VnmycaqyjQ_0[64].offset = 19;
TM_T8sPUeYymAg4VnmycaqyjQ_0[65].offset = 20;
TM_T8sPUeYymAg4VnmycaqyjQ_0[66].offset = 21;
TM_T8sPUeYymAg4VnmycaqyjQ_0[67].offset = 22;
TM_T8sPUeYymAg4VnmycaqyjQ_0[68].offset = 23;
TM_T8sPUeYymAg4VnmycaqyjQ_0[69].offset = 24;
TM_T8sPUeYymAg4VnmycaqyjQ_0[70].offset = 25;
TM_T8sPUeYymAg4VnmycaqyjQ_0[71].offset = 26;
TM_T8sPUeYymAg4VnmycaqyjQ_0[72].offset = 27;
TM_T8sPUeYymAg4VnmycaqyjQ_0[73].offset = 28;
TM_T8sPUeYymAg4VnmycaqyjQ_0[74].offset = 29;
TM_T8sPUeYymAg4VnmycaqyjQ_0[75].offset = 30;
TM_T8sPUeYymAg4VnmycaqyjQ_0[76].offset = 31;
TM_T8sPUeYymAg4VnmycaqyjQ_0[77].offset = 32;
TM_T8sPUeYymAg4VnmycaqyjQ_0[78].offset = 33;
TM_T8sPUeYymAg4VnmycaqyjQ_0[79].offset = 34;
TM_T8sPUeYymAg4VnmycaqyjQ_0[80].offset = 35;
TM_T8sPUeYymAg4VnmycaqyjQ_0[81].offset = 36;
TM_T8sPUeYymAg4VnmycaqyjQ_0[82].offset = 37;
TM_T8sPUeYymAg4VnmycaqyjQ_0[83].offset = 38;
TM_T8sPUeYymAg4VnmycaqyjQ_0[84].offset = 39;
TM_T8sPUeYymAg4VnmycaqyjQ_0[85].offset = 40;
TM_T8sPUeYymAg4VnmycaqyjQ_0[86].offset = 41;
TM_T8sPUeYymAg4VnmycaqyjQ_0[87].offset = 42;
TM_T8sPUeYymAg4VnmycaqyjQ_0[88].offset = 43;
TM_T8sPUeYymAg4VnmycaqyjQ_0[89].offset = 44;
TM_T8sPUeYymAg4VnmycaqyjQ_0[90].offset = 45;
TM_T8sPUeYymAg4VnmycaqyjQ_0[91].offset = 46;
TM_T8sPUeYymAg4VnmycaqyjQ_0[92].offset = 47;
TM_T8sPUeYymAg4VnmycaqyjQ_0[93].offset = 48;
TM_T8sPUeYymAg4VnmycaqyjQ_0[94].offset = 49;
TM_T8sPUeYymAg4VnmycaqyjQ_0[95].offset = 50;
TM_T8sPUeYymAg4VnmycaqyjQ_0[96].offset = 51;
TM_T8sPUeYymAg4VnmycaqyjQ_0[97].offset = 52;
TM_T8sPUeYymAg4VnmycaqyjQ_0[98].offset = 53;
TM_T8sPUeYymAg4VnmycaqyjQ_0[99].offset = 54;
TM_T8sPUeYymAg4VnmycaqyjQ_0[100].offset = 55;
TM_T8sPUeYymAg4VnmycaqyjQ_0[101].offset = 56;
TM_T8sPUeYymAg4VnmycaqyjQ_0[102].offset = 57;
TM_T8sPUeYymAg4VnmycaqyjQ_0[103].offset = 58;
TM_T8sPUeYymAg4VnmycaqyjQ_0[104].offset = 59;
TM_T8sPUeYymAg4VnmycaqyjQ_0[105].offset = 60;
TM_T8sPUeYymAg4VnmycaqyjQ_0[106].offset = 61;
TM_T8sPUeYymAg4VnmycaqyjQ_0[107].offset = 62;
TM_T8sPUeYymAg4VnmycaqyjQ_0[108].offset = 63;
TM_T8sPUeYymAg4VnmycaqyjQ_0[109].offset = 64;
TM_T8sPUeYymAg4VnmycaqyjQ_0[110].offset = 65;
TM_T8sPUeYymAg4VnmycaqyjQ_0[111].offset = 66;
TM_T8sPUeYymAg4VnmycaqyjQ_0[112].offset = 67;
TM_T8sPUeYymAg4VnmycaqyjQ_0[113].offset = 68;
TM_T8sPUeYymAg4VnmycaqyjQ_0[114].offset = 69;
TM_T8sPUeYymAg4VnmycaqyjQ_0[115].offset = 70;
TM_T8sPUeYymAg4VnmycaqyjQ_0[116].offset = 71;
TM_T8sPUeYymAg4VnmycaqyjQ_0[117].offset = 72;
TM_T8sPUeYymAg4VnmycaqyjQ_0[118].offset = 73;
TM_T8sPUeYymAg4VnmycaqyjQ_0[119].offset = 74;
TM_T8sPUeYymAg4VnmycaqyjQ_0[120].offset = 75;
TM_T8sPUeYymAg4VnmycaqyjQ_0[121].offset = 76;
TM_T8sPUeYymAg4VnmycaqyjQ_0[122].offset = 77;
TM_T8sPUeYymAg4VnmycaqyjQ_0[123].offset = 78;
TM_T8sPUeYymAg4VnmycaqyjQ_0[124].offset = 79;
TM_T8sPUeYymAg4VnmycaqyjQ_0[125].offset = 80;
TM_T8sPUeYymAg4VnmycaqyjQ_0[126].offset = 81;
TM_T8sPUeYymAg4VnmycaqyjQ_0[127].offset = 82;
TM_T8sPUeYymAg4VnmycaqyjQ_0[128].offset = 83;
TM_T8sPUeYymAg4VnmycaqyjQ_0[129].offset = 84;
TM_T8sPUeYymAg4VnmycaqyjQ_0[130].offset = 85;
TM_T8sPUeYymAg4VnmycaqyjQ_0[131].offset = 86;
TM_T8sPUeYymAg4VnmycaqyjQ_0[132].offset = 87;
TM_T8sPUeYymAg4VnmycaqyjQ_0[133].offset = 88;
TM_T8sPUeYymAg4VnmycaqyjQ_0[134].offset = 89;
TM_T8sPUeYymAg4VnmycaqyjQ_0[135].offset = 90;
TM_T8sPUeYymAg4VnmycaqyjQ_0[136].offset = 91;
TM_T8sPUeYymAg4VnmycaqyjQ_0[137].offset = 92;
TM_T8sPUeYymAg4VnmycaqyjQ_0[138].offset = 93;
TM_T8sPUeYymAg4VnmycaqyjQ_0[139].offset = 94;
TM_T8sPUeYymAg4VnmycaqyjQ_0[140].offset = 95;
TM_T8sPUeYymAg4VnmycaqyjQ_0[141].offset = 96;
TM_T8sPUeYymAg4VnmycaqyjQ_0[142].offset = 97;
TM_T8sPUeYymAg4VnmycaqyjQ_0[143].offset = 98;
TM_T8sPUeYymAg4VnmycaqyjQ_0[144].offset = 99;
TM_T8sPUeYymAg4VnmycaqyjQ_0[145].offset = 100;
TM_T8sPUeYymAg4VnmycaqyjQ_0[146].offset = 101;
TM_T8sPUeYymAg4VnmycaqyjQ_0[147].offset = 102;
TM_T8sPUeYymAg4VnmycaqyjQ_0[148].offset = 103;
TM_T8sPUeYymAg4VnmycaqyjQ_0[149].offset = 104;
TM_T8sPUeYymAg4VnmycaqyjQ_0[150].offset = 105;
TM_T8sPUeYymAg4VnmycaqyjQ_0[151].offset = 106;
TM_T8sPUeYymAg4VnmycaqyjQ_0[152].offset = 107;
TM_T8sPUeYymAg4VnmycaqyjQ_0[153].offset = 108;
TM_T8sPUeYymAg4VnmycaqyjQ_0[154].offset = 109;
TM_T8sPUeYymAg4VnmycaqyjQ_0[155].offset = 110;
TM_T8sPUeYymAg4VnmycaqyjQ_0[156].offset = 111;
TM_T8sPUeYymAg4VnmycaqyjQ_0[157].offset = 112;
TM_T8sPUeYymAg4VnmycaqyjQ_0[158].offset = 113;
TM_T8sPUeYymAg4VnmycaqyjQ_0[159].offset = 114;
TM_T8sPUeYymAg4VnmycaqyjQ_0[160].offset = 115;
TM_T8sPUeYymAg4VnmycaqyjQ_0[161].offset = 116;
TM_T8sPUeYymAg4VnmycaqyjQ_0[162].offset = 117;
TM_T8sPUeYymAg4VnmycaqyjQ_0[163].offset = 118;
TM_T8sPUeYymAg4VnmycaqyjQ_0[164].offset = 119;
TM_T8sPUeYymAg4VnmycaqyjQ_0[165].offset = 120;
TM_T8sPUeYymAg4VnmycaqyjQ_0[166].offset = 121;
TM_T8sPUeYymAg4VnmycaqyjQ_0[167].offset = 122;
TM_T8sPUeYymAg4VnmycaqyjQ_0[168].offset = 123;
TM_T8sPUeYymAg4VnmycaqyjQ_0[169].offset = 124;
TM_T8sPUeYymAg4VnmycaqyjQ_0[170].offset = 125;
TM_T8sPUeYymAg4VnmycaqyjQ_0[171].offset = 126;
TM_T8sPUeYymAg4VnmycaqyjQ_0[172].offset = 127;
TM_T8sPUeYymAg4VnmycaqyjQ_0[173].offset = 128;
TM_T8sPUeYymAg4VnmycaqyjQ_0[174].offset = 129;
TM_T8sPUeYymAg4VnmycaqyjQ_0[175].offset = 133;
TM_T8sPUeYymAg4VnmycaqyjQ_0[176].offset = 134;
TM_T8sPUeYymAg4VnmycaqyjQ_0[177].offset = 135;
TM_T8sPUeYymAg4VnmycaqyjQ_0[178].offset = 136;
TM_T8sPUeYymAg4VnmycaqyjQ_0[179].offset = 137;
TM_T8sPUeYymAg4VnmycaqyjQ_0[180].offset = 138;
TM_T8sPUeYymAg4VnmycaqyjQ_0[181].offset = 139;
TM_T8sPUeYymAg4VnmycaqyjQ_0[182].offset = 140;
TM_T8sPUeYymAg4VnmycaqyjQ_0[183].offset = 141;
TM_T8sPUeYymAg4VnmycaqyjQ_0[184].offset = 142;
TM_T8sPUeYymAg4VnmycaqyjQ_0[185].offset = 143;
TM_T8sPUeYymAg4VnmycaqyjQ_0[186].offset = 144;
TM_T8sPUeYymAg4VnmycaqyjQ_0[187].offset = 145;
TM_T8sPUeYymAg4VnmycaqyjQ_0[188].offset = 146;
TM_T8sPUeYymAg4VnmycaqyjQ_0[189].offset = 147;
TM_T8sPUeYymAg4VnmycaqyjQ_0[190].offset = 148;
TM_T8sPUeYymAg4VnmycaqyjQ_0[191].offset = 149;
TM_T8sPUeYymAg4VnmycaqyjQ_0[192].offset = 150;
TM_T8sPUeYymAg4VnmycaqyjQ_0[193].offset = 151;
TM_T8sPUeYymAg4VnmycaqyjQ_0[194].offset = 152;
TM_T8sPUeYymAg4VnmycaqyjQ_0[195].offset = 153;
TM_T8sPUeYymAg4VnmycaqyjQ_0[196].offset = 154;
TM_T8sPUeYymAg4VnmycaqyjQ_0[197].offset = 155;
TM_T8sPUeYymAg4VnmycaqyjQ_0[198].offset = 156;
TM_T8sPUeYymAg4VnmycaqyjQ_0[199].offset = 157;
TM_T8sPUeYymAg4VnmycaqyjQ_0[200].offset = 158;
TM_T8sPUeYymAg4VnmycaqyjQ_0[201].offset = 159;
TM_T8sPUeYymAg4VnmycaqyjQ_0[202].offset = 160;
TM_T8sPUeYymAg4VnmycaqyjQ_0[203].offset = 161;
TM_T8sPUeYymAg4VnmycaqyjQ_0[204].offset = 162;
TM_T8sPUeYymAg4VnmycaqyjQ_0[205].offset = 163;
TM_T8sPUeYymAg4VnmycaqyjQ_0[206].offset = 164;
TM_T8sPUeYymAg4VnmycaqyjQ_0[207].offset = 176;
TM_T8sPUeYymAg4VnmycaqyjQ_0[208].offset = 177;
TM_T8sPUeYymAg4VnmycaqyjQ_0[209].offset = 178;
TM_T8sPUeYymAg4VnmycaqyjQ_0[210].offset = 179;
TM_T8sPUeYymAg4VnmycaqyjQ_0[211].offset = 180;
TM_T8sPUeYymAg4VnmycaqyjQ_0[212].offset = 181;
TM_T8sPUeYymAg4VnmycaqyjQ_0[213].offset = 182;
TM_T8sPUeYymAg4VnmycaqyjQ_0[214].offset = 183;
TM_T8sPUeYymAg4VnmycaqyjQ_0[215].offset = 184;
TM_T8sPUeYymAg4VnmycaqyjQ_0[216].offset = 185;
TM_T8sPUeYymAg4VnmycaqyjQ_0[217].offset = 186;
TM_T8sPUeYymAg4VnmycaqyjQ_0[218].offset = 187;
TM_T8sPUeYymAg4VnmycaqyjQ_0[219].offset = 188;
TM_T8sPUeYymAg4VnmycaqyjQ_0[220].offset = 189;
TM_T8sPUeYymAg4VnmycaqyjQ_0[221].offset = 190;
TM_T8sPUeYymAg4VnmycaqyjQ_0[222].offset = 191;
TM_T8sPUeYymAg4VnmycaqyjQ_0[223].offset = 192;
TM_T8sPUeYymAg4VnmycaqyjQ_0[224].offset = 193;
TM_T8sPUeYymAg4VnmycaqyjQ_0[225].offset = 194;
TM_T8sPUeYymAg4VnmycaqyjQ_0[226].offset = 195;
TM_T8sPUeYymAg4VnmycaqyjQ_0[227].offset = 196;
TM_T8sPUeYymAg4VnmycaqyjQ_0[228].offset = 197;
TM_T8sPUeYymAg4VnmycaqyjQ_0[229].offset = 198;
TM_T8sPUeYymAg4VnmycaqyjQ_0[230].offset = 199;
TM_T8sPUeYymAg4VnmycaqyjQ_0[231].offset = 200;
TM_T8sPUeYymAg4VnmycaqyjQ_0[232].offset = 201;
TM_T8sPUeYymAg4VnmycaqyjQ_0[233].offset = 202;
TM_T8sPUeYymAg4VnmycaqyjQ_0[234].offset = 203;
TM_T8sPUeYymAg4VnmycaqyjQ_0[235].offset = 204;
TM_T8sPUeYymAg4VnmycaqyjQ_0[236].offset = 205;
TM_T8sPUeYymAg4VnmycaqyjQ_0[237].offset = 206;
TM_T8sPUeYymAg4VnmycaqyjQ_0[238].offset = 207;
TM_T8sPUeYymAg4VnmycaqyjQ_0[239].offset = 208;
TM_T8sPUeYymAg4VnmycaqyjQ_0[240].offset = 209;
TM_T8sPUeYymAg4VnmycaqyjQ_0[241].offset = 210;
TM_T8sPUeYymAg4VnmycaqyjQ_0[242].offset = 211;
TM_T8sPUeYymAg4VnmycaqyjQ_0[243].offset = 212;
TM_T8sPUeYymAg4VnmycaqyjQ_0[244].offset = 213;
TM_T8sPUeYymAg4VnmycaqyjQ_0[245].offset = 214;
TM_T8sPUeYymAg4VnmycaqyjQ_0[246].offset = 215;
TM_T8sPUeYymAg4VnmycaqyjQ_0[247].offset = 216;
TM_T8sPUeYymAg4VnmycaqyjQ_0[248].offset = 217;
TM_T8sPUeYymAg4VnmycaqyjQ_0[249].offset = 218;
TM_T8sPUeYymAg4VnmycaqyjQ_0[250].offset = 219;
TM_T8sPUeYymAg4VnmycaqyjQ_0[251].offset = 220;
TM_T8sPUeYymAg4VnmycaqyjQ_0[252].offset = 221;
TM_T8sPUeYymAg4VnmycaqyjQ_0[253].offset = 224;
TM_T8sPUeYymAg4VnmycaqyjQ_0[254].offset = 225;
TM_T8sPUeYymAg4VnmycaqyjQ_0[255].offset = 226;
TM_T8sPUeYymAg4VnmycaqyjQ_0[256].offset = 227;
TM_T8sPUeYymAg4VnmycaqyjQ_0[257].offset = 228;
TM_T8sPUeYymAg4VnmycaqyjQ_0[258].offset = 229;
TM_T8sPUeYymAg4VnmycaqyjQ_0[259].offset = 230;
TM_T8sPUeYymAg4VnmycaqyjQ_0[260].offset = 231;
TM_T8sPUeYymAg4VnmycaqyjQ_0[261].offset = 257;
TM_T8sPUeYymAg4VnmycaqyjQ_0[262].offset = 258;
TM_T8sPUeYymAg4VnmycaqyjQ_0[263].offset = 259;
TM_T8sPUeYymAg4VnmycaqyjQ_0[264].offset = 260;
TM_T8sPUeYymAg4VnmycaqyjQ_0[265].offset = 261;
TM_T8sPUeYymAg4VnmycaqyjQ_0[266].offset = 262;
TM_T8sPUeYymAg4VnmycaqyjQ_0[267].offset = 263;
TM_T8sPUeYymAg4VnmycaqyjQ_0[268].offset = 264;
TM_T8sPUeYymAg4VnmycaqyjQ_0[269].offset = 265;
TM_T8sPUeYymAg4VnmycaqyjQ_0[270].offset = 266;
TM_T8sPUeYymAg4VnmycaqyjQ_0[271].offset = 267;
TM_T8sPUeYymAg4VnmycaqyjQ_0[272].offset = 268;
TM_T8sPUeYymAg4VnmycaqyjQ_0[273].offset = 269;
TM_T8sPUeYymAg4VnmycaqyjQ_0[274].offset = 270;
TM_T8sPUeYymAg4VnmycaqyjQ_0[275].offset = 271;
TM_T8sPUeYymAg4VnmycaqyjQ_0[276].offset = 272;
TM_T8sPUeYymAg4VnmycaqyjQ_0[277].offset = 273;
TM_T8sPUeYymAg4VnmycaqyjQ_0[278].offset = 274;
TM_T8sPUeYymAg4VnmycaqyjQ_0[279].offset = 275;
TM_T8sPUeYymAg4VnmycaqyjQ_0[280].offset = 276;
TM_T8sPUeYymAg4VnmycaqyjQ_0[281].offset = 277;
TM_T8sPUeYymAg4VnmycaqyjQ_0[282].offset = 278;
TM_T8sPUeYymAg4VnmycaqyjQ_0[283].offset = 279;
TM_T8sPUeYymAg4VnmycaqyjQ_0[284].offset = 280;
TM_T8sPUeYymAg4VnmycaqyjQ_0[285].offset = 281;
TM_T8sPUeYymAg4VnmycaqyjQ_0[286].offset = 282;
TM_T8sPUeYymAg4VnmycaqyjQ_0[287].offset = 283;
TM_T8sPUeYymAg4VnmycaqyjQ_0[288].offset = 284;
TM_T8sPUeYymAg4VnmycaqyjQ_0[289].offset = 285;
TM_T8sPUeYymAg4VnmycaqyjQ_0[290].offset = 286;
TM_T8sPUeYymAg4VnmycaqyjQ_0[291].offset = 512;
TM_T8sPUeYymAg4VnmycaqyjQ_0[292].len = 244; TM_T8sPUeYymAg4VnmycaqyjQ_0[292].kind = 2; TM_T8sPUeYymAg4VnmycaqyjQ_0[292].sons = &TM_T8sPUeYymAg4VnmycaqyjQ_57[0];
NTI_GQzt28Vd9bjjGKwYsdVggVg_.node = &TM_T8sPUeYymAg4VnmycaqyjQ_0[292];
NTI_GQzt28Vd9bjjGKwYsdVggVg_.flags = 1<<2;
NTI_uJWItJY4VFfI5KsjUEP2Gw_.size = sizeof(tyObject_JoystickGUID_uJWItJY4VFfI5KsjUEP2Gw);
NTI_uJWItJY4VFfI5KsjUEP2Gw_.kind = 18;
NTI_uJWItJY4VFfI5KsjUEP2Gw_.base = 0;
NTI_uJWItJY4VFfI5KsjUEP2Gw_.flags = 3;
NTI_qtqsWM5aXmcpMIVmvq3kAA_.size = sizeof(tyArray_qtqsWM5aXmcpMIVmvq3kAA);
NTI_qtqsWM5aXmcpMIVmvq3kAA_.kind = 16;
NTI_qtqsWM5aXmcpMIVmvq3kAA_.base = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
NTI_qtqsWM5aXmcpMIVmvq3kAA_.flags = 3;
TM_T8sPUeYymAg4VnmycaqyjQ_0[293].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[293].offset = offsetof(tyObject_JoystickGUID_uJWItJY4VFfI5KsjUEP2Gw, data);
TM_T8sPUeYymAg4VnmycaqyjQ_0[293].typ = (&NTI_qtqsWM5aXmcpMIVmvq3kAA_);
TM_T8sPUeYymAg4VnmycaqyjQ_0[293].name = "data";
NTI_uJWItJY4VFfI5KsjUEP2Gw_.node = &TM_T8sPUeYymAg4VnmycaqyjQ_0[293];
NTI_WXrdDcbfAWDwkLkWu9c0m2w_.size = sizeof(tyEnum_HatPosition_WXrdDcbfAWDwkLkWu9c0m2w);
NTI_WXrdDcbfAWDwkLkWu9c0m2w_.kind = 14;
NTI_WXrdDcbfAWDwkLkWu9c0m2w_.base = 0;
NTI_WXrdDcbfAWDwkLkWu9c0m2w_.flags = 3;
for (TM_T8sPUeYymAg4VnmycaqyjQ_94 = 0; TM_T8sPUeYymAg4VnmycaqyjQ_94 < 9; TM_T8sPUeYymAg4VnmycaqyjQ_94++) {
TM_T8sPUeYymAg4VnmycaqyjQ_0[TM_T8sPUeYymAg4VnmycaqyjQ_94+294].kind = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[TM_T8sPUeYymAg4VnmycaqyjQ_94+294].offset = TM_T8sPUeYymAg4VnmycaqyjQ_94;
TM_T8sPUeYymAg4VnmycaqyjQ_0[TM_T8sPUeYymAg4VnmycaqyjQ_94+294].name = TM_T8sPUeYymAg4VnmycaqyjQ_93[TM_T8sPUeYymAg4VnmycaqyjQ_94];
TM_T8sPUeYymAg4VnmycaqyjQ_92[TM_T8sPUeYymAg4VnmycaqyjQ_94] = &TM_T8sPUeYymAg4VnmycaqyjQ_0[TM_T8sPUeYymAg4VnmycaqyjQ_94+294];
}
TM_T8sPUeYymAg4VnmycaqyjQ_0[294].offset = 0;
TM_T8sPUeYymAg4VnmycaqyjQ_0[295].offset = 1;
TM_T8sPUeYymAg4VnmycaqyjQ_0[296].offset = 2;
TM_T8sPUeYymAg4VnmycaqyjQ_0[297].offset = 3;
TM_T8sPUeYymAg4VnmycaqyjQ_0[298].offset = 4;
TM_T8sPUeYymAg4VnmycaqyjQ_0[299].offset = 6;
TM_T8sPUeYymAg4VnmycaqyjQ_0[300].offset = 8;
TM_T8sPUeYymAg4VnmycaqyjQ_0[301].offset = 9;
TM_T8sPUeYymAg4VnmycaqyjQ_0[302].offset = 12;
TM_T8sPUeYymAg4VnmycaqyjQ_0[303].len = 9; TM_T8sPUeYymAg4VnmycaqyjQ_0[303].kind = 2; TM_T8sPUeYymAg4VnmycaqyjQ_0[303].sons = &TM_T8sPUeYymAg4VnmycaqyjQ_92[0];
NTI_WXrdDcbfAWDwkLkWu9c0m2w_.node = &TM_T8sPUeYymAg4VnmycaqyjQ_0[303];
NTI_WXrdDcbfAWDwkLkWu9c0m2w_.flags = 1<<2;
if (!((TM_T8sPUeYymAg4VnmycaqyjQ_2 = nimLoadLibrary((NimStringDesc*) &TM_T8sPUeYymAg4VnmycaqyjQ_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_T8sPUeYymAg4VnmycaqyjQ_5);
	Dl_155413_ = (tyProc_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_DestroyTexture");
	Dl_155149_ = (tyProc_Z3C0z9blaIY9abfEJhIF9b1WQ) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_QueryTexture");
	Dl_154881_ = (tyProc_DusjKySyJW30WdV9bsteVxw) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_LogCritical");
	Dl_147926_ = (tyProc_09bvyvHFtWbkzL5AHgf0bKw) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetError");
	Dl_155382_ = (tyProc_QGX7uxPZtIoH9bzksYUj1mg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_RenderCopy");
	Dl_155390_ = (tyProc_oVfcvGczxlST8hWjhSa9aHA) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_RenderCopyEx");
	Dl_155170_ = (tyProc_wPxvXWWgPCAYBuODEXklIQ) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetTextureColorMod");
	Dl_155160_ = (tyProc_zhHzw47u9aiQa6dkiW0Xt6A) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_SetTextureColorMod");
	Dl_155187_ = (tyProc_vQpo9bldiNjTNBM8HFLFDnA) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetTextureAlphaMod");
	Dl_155183_ = (tyProc_FlP63hJrVpAOGAcB9aysLWg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_SetTextureAlphaMod");
	Dl_155196_ = (tyProc_iHseqIAJGzwtK1AnPOzGxg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetTextureBlendMode");
	Dl_155192_ = (tyProc_drbIXv9cjqA4ZjQmLutUd0A) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_SetTextureBlendMode");
	Dl_155126_ = (tyProc_eacO1b28DxmNZ4wkv7Xz1A) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetRendererInfo");
	Dl_150911_ = (tyProc_3d8ZGFdX9cH9cDT9a42QwE9cvg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_FreePalette");
	Dl_150893_ = (tyProc_Anj9as7d5YZdqOLVOsW9cq9bQ) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_AllocPalette");
	Dl_150903_ = (tyProc_wotRTUnRZK0xNH5VjeE8Ng) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_SetPaletteColors");
	Dl_151078_ = (tyProc_fj5zQw9asqT9cpDX9bwFTdIYQ) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_FreeSurface");
	Dl_151081_ = (tyProc_D19cH77xVwhL04Bkj8wjreA) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_SetSurfacePalette");
	Dl_155145_ = (tyProc_WCSbnyfpsjNzpCETKXisyQ) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_CreateTextureFromSurface");
	Dl_147327_ = (tyProc_OMfTrA6Dqf9cACW3aIhhxEA) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_FreeRW");
	Dl_156042_ = (tyProc_F2KC9bitLsP5b9bCBN9b81hEg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetPerformanceCounter");
	Dl_156044_ = (tyProc_F2KC9bitLsP5b9bCBN9b81hEg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetPerformanceFrequency");
	Dl_147304_ = (tyProc_Q4hOU9as18Fp2AN1WS9af3lw) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_RWFromFile");
	Dl_153241_ = (tyProc_I9bPtzY9bF1nZwgVXz7RwbsQ) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetKeyboardState");
	Dl_153259_ = (tyProc_XdK6FMM9bpZDt8hBM8zRBmA) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetModState");
	Dl_153562_ = (tyProc_3x6s3S5VLwHgqm89bRORIwA) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetMouseState");
	Dl_153574_ = (tyProc_3x6s3S5VLwHgqm89bRORIwA) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetRelativeMouseState");
	Dl_153357_ = (tyProc_k1adoqH9aKm9azQEPzuEHntg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_JoystickOpen");
	Dl_153366_ = (tyProc_0uAo5XqgYf0g2Ezq241cwA) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_JoystickGetGUID");
	Dl_153404_ = (tyProc_fbYpjfe38x3ujjAmVRbI1Q) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_JoystickNumButtons");
	Dl_153395_ = (tyProc_fbYpjfe38x3ujjAmVRbI1Q) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_JoystickNumAxes");
	Dl_153398_ = (tyProc_fbYpjfe38x3ujjAmVRbI1Q) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_JoystickNumBalls");
	Dl_153401_ = (tyProc_fbYpjfe38x3ujjAmVRbI1Q) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_JoystickNumHats");
	Dl_153487_ = (tyProc_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_JoystickClose");
	Dl_153363_ = (tyProc_p1X2BwWx9a3wsChhykvf29aA) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_JoystickName");
	Dl_153483_ = (tyProc_JT315YeHbhx5wOveM5R6iw) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_JoystickGetButton");
	Dl_153417_ = (tyProc_4bw5UOiK6CCnYnXwMrhKVA) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_JoystickGetAxis");
	Dl_153475_ = (tyProc_7oyw4ZADV0qPTb4h9bhPG6g) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_JoystickGetBall");
	Dl_153471_ = (tyProc_KlFjvoExkMPsa9c65P1UoYQ) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_JoystickGetHat");
	Dl_153270_ = (tyProc_AC9c6fqQ57iNdqiHar41S6g) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetScancodeName");
	Dl_153386_ = (tyProc_UlKOyh2Hz7sZWP2OH9a8k2A) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_JoystickGetGUIDFromString");
	Dl_153273_ = (tyProc_ZH8c23vA4ARq6GxRdV149aQ) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetScancodeFromName");
	Dl_153381_ = (tyProc_sF69apV6Ddbmp8i9a0mNwE2Q) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_JoystickGetGUIDString");
	Dl_155416_ = (tyProc_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_DestroyRenderer");
	Dl_151711_ = (tyProc_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_DestroyWindow");
	Dl_146832_ = (tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_Quit");
	Dl_146820_ = (tyProc_qLs9bEMEYHZYOeFIf1LOpoQ) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_Init");
	Dl_151489_ = (tyProc_hKarI59cLAeI0v1WuQhCZ9ag) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_CreateWindow");
	Dl_151516_ = (tyProc_QlCkx80RqXe3H5HPnaH9bXw) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_SetWindowIcon");
	Dl_155115_ = (tyProc_jPHHnsvDYo8Q3NQemQIGWg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_CreateRenderer");
	Dl_155244_ = (tyProc_YsPh3gbdjC9aWnl5GwfE11g) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_RenderSetLogicalSize");
	Dl_154765_ = (tyProc_CS9bxA1KE4RHFQ1vMCkCBmg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_SetHint");
	Dl_155256_ = (tyProc_cSn2aF8C9bc9c1Xq33CduLpA) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_RenderSetIntegerScale");
	Dl_151513_ = (tyProc_p1X2BwWx9a3wsChhykvf29aA) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetWindowTitle");
	Dl_151509_ = (tyProc_WYY8i0I79agBofnUcEGCfig) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_SetWindowTitle");
	Dl_151534_ = (tyProc_xmqN0ZWK4lw72DZ4V9b09cTw) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetWindowPosition");
	Dl_151529_ = (tyProc_PhiNc70ll6IvDlrnhDZ1Zw) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_SetWindowPosition");
	Dl_151605_ = (tyProc_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_MaximizeWindow");
	Dl_151546_ = (tyProc_xmqN0ZWK4lw72DZ4V9b09cTw) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetWindowSize");
	Dl_151541_ = (tyProc_PhiNc70ll6IvDlrnhDZ1Zw) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_SetWindowSize");
	Dl_151569_ = (tyProc_xmqN0ZWK4lw72DZ4V9b09cTw) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetWindowMinimumSize");
	Dl_151564_ = (tyProc_PhiNc70ll6IvDlrnhDZ1Zw) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_SetWindowMinimumSize");
	Dl_151581_ = (tyProc_xmqN0ZWK4lw72DZ4V9b09cTw) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_GetWindowMaximumSize");
	Dl_151576_ = (tyProc_PhiNc70ll6IvDlrnhDZ1Zw) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_SetWindowMaximumSize");
	Dl_151588_ = (tyProc_5fEbO9c5NkY4gdhCj9ao7T1g) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_SetWindowBordered");
	Dl_151592_ = (tyProc_5fEbO9c5NkY4gdhCj9ao7T1g) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_SetWindowResizable");
	Dl_151596_ = (tyProc_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_ShowWindow");
	Dl_151599_ = (tyProc_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_HideWindow");
	Dl_151602_ = (tyProc_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_RaiseWindow");
	Dl_151608_ = (tyProc_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_MinimizeWindow");
	Dl_151611_ = (tyProc_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_RestoreWindow");
	Dl_155291_ = (tyProc_yuYTMNVUr5YiJgeXuSByeQ) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_RenderGetScale");
	Dl_155268_ = (tyProc_5Og8Col0Fi6amjd7LeSCVg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_RenderGetViewport");
	Dl_155263_ = (tyProc_yHY3uRNlpOCQI5Fck5Ny9bg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_RenderSetViewport");
	Dl_154877_ = (tyProc_DusjKySyJW30WdV9bsteVxw) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_LogError");
	Dl_154239_ = (tyProc_7bYZDaP1ASB0w4tVKW9bKew) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_PollEvent");
	Dl_155298_ = (tyProc_buOIiiD42E5nxpbw32t0bA) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_SetRenderDrawColor");
	Dl_155333_ = (tyProc_fbYpjfe38x3ujjAmVRbI1Q) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_RenderClear");
	Dl_155410_ = (tyProc_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_T8sPUeYymAg4VnmycaqyjQ_2, "SDL_RenderPresent");
}

