/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\Users\Alterna\Documents\nim-0.18.0\lib -o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\sdl2_nim_sdl_gfx_primitives.o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\sdl2_nim_sdl_gfx_primitives.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A;
typedef struct tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q;
typedef struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ tyObject_Rect_qiXweduDJk1iLE5aHysNdQ;
typedef struct tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg;
typedef struct tyObject_Color_YizDHyEvJtgQk2fn8KdZUA tyObject_Color_YizDHyEvJtgQk2fn8KdZUA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(int, tyProc_SSqw9cNo8Mf6MmIJEdLFGSQ) (void* renderer, NI16 x, NI16 y, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_rQIZx4wC6REw9aHmOegjvHg) (void* renderer, NI16 x1, NI16 x2, NI16 y, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_XKGgUlQDoYOavZdP09bvlvg) (void* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_TvDqUpQevFbLv23LGWgPvQ) (void* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 rad, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_qAUKUGou1ENFEIQWwibH1w) (void* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU8 width, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_qPqBS49ckVYghHaRhDe9bhzA) (void* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 x3, NI16 y3, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_sCoe4tIqEGTlfV3L9coWeoQ) (void* renderer, NI16* vx, NI16* vy, int n, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_iWZxubK6MtZbJP55ce9c9cZQ) (void* renderer, NI16* vx, NI16* vy, int n, tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A* texture, int texture_dx, int texture_dy);
typedef N_CDECL_PTR(int, tyProc_bG9aqvmV8xt5SjWK9cQ9aZM5g) (void* renderer, NI16* vx, NI16* vy, int n, int s, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(void, tyProc_rpU67nzC5WaSfXPDEajeiA) (void* fontdata, NU32 cw, NU32 ch);
typedef N_CDECL_PTR(int, tyProc_ElHqXU4YrZEvKm7wPSDkYA) (void* renderer, NI16 x, NI16 y, NIM_CHAR c, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, tyProc_qtym4k1a9bIJYHCEaSHkiyg) (void* renderer, NI16 x, NI16 y, NCSTRING s, NU8 r, NU8 g, NU8 b, NU8 a);
struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ {
int x;
int y;
int w;
int h;
};
struct tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A {
NU32 flags;
tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q* format;
int w;
int h;
int pitch;
void* pixels;
void* userdata;
int locked;
void* lock_data;
tyObject_Rect_qiXweduDJk1iLE5aHysNdQ clip_rect;
void* map;
int refcount;
};
typedef NU8 tyArray_bN9bddWn8oiNSHn2MqEJSZQ[2];
struct tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q {
NU32 format;
tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette;
NU8 BitsPerPixel;
NU8 BytesPerPixel;
tyArray_bN9bddWn8oiNSHn2MqEJSZQ padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int refcount;
tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q* next;
};
struct tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg {
int ncolors;
tyObject_Color_YizDHyEvJtgQk2fn8KdZUA* colors;
NU32 version;
int refcount;
};
struct tyObject_Color_YizDHyEvJtgQk2fn8KdZUA {
NU8 r;
NU8 g;
NU8 b;
NU8 a;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static void* TM_g5o5WEqRGC1LPWvqxdE8Kg_2;
tyProc_SSqw9cNo8Mf6MmIJEdLFGSQ Dl_177012_;
tyProc_rQIZx4wC6REw9aHmOegjvHg Dl_177028_;
tyProc_rQIZx4wC6REw9aHmOegjvHg Dl_177045_;
tyProc_XKGgUlQDoYOavZdP09bvlvg Dl_177063_;
tyProc_TvDqUpQevFbLv23LGWgPvQ Dl_177083_;
tyProc_XKGgUlQDoYOavZdP09bvlvg Dl_177103_;
tyProc_TvDqUpQevFbLv23LGWgPvQ Dl_177123_;
tyProc_XKGgUlQDoYOavZdP09bvlvg Dl_177143_;
tyProc_XKGgUlQDoYOavZdP09bvlvg Dl_177162_;
tyProc_qAUKUGou1ENFEIQWwibH1w Dl_177182_;
tyProc_rQIZx4wC6REw9aHmOegjvHg Dl_177201_;
tyProc_rQIZx4wC6REw9aHmOegjvHg Dl_177239_;
tyProc_rQIZx4wC6REw9aHmOegjvHg Dl_177256_;
tyProc_TvDqUpQevFbLv23LGWgPvQ Dl_177220_;
tyProc_XKGgUlQDoYOavZdP09bvlvg Dl_177274_;
tyProc_XKGgUlQDoYOavZdP09bvlvg Dl_177293_;
tyProc_XKGgUlQDoYOavZdP09bvlvg Dl_177312_;
tyProc_TvDqUpQevFbLv23LGWgPvQ Dl_177332_;
tyProc_TvDqUpQevFbLv23LGWgPvQ Dl_177353_;
tyProc_qPqBS49ckVYghHaRhDe9bhzA Dl_177375_;
tyProc_qPqBS49ckVYghHaRhDe9bhzA Dl_177398_;
tyProc_qPqBS49ckVYghHaRhDe9bhzA Dl_177421_;
tyProc_sCoe4tIqEGTlfV3L9coWeoQ Dl_177443_;
tyProc_sCoe4tIqEGTlfV3L9coWeoQ Dl_177464_;
tyProc_sCoe4tIqEGTlfV3L9coWeoQ Dl_177485_;
tyProc_iWZxubK6MtZbJP55ce9c9cZQ Dl_177497_;
tyProc_bG9aqvmV8xt5SjWK9cQ9aZM5g Dl_177518_;
tyProc_rpU67nzC5WaSfXPDEajeiA Dl_177531_;
tyProc_ElHqXU4YrZEvKm7wPSDkYA Dl_177546_;
tyProc_qtym4k1a9bIJYHCEaSHkiyg Dl_177563_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_g5o5WEqRGC1LPWvqxdE8Kg_4, "SDL2_gfx.dll", 12);
STRING_LITERAL(TM_g5o5WEqRGC1LPWvqxdE8Kg_5, "SDL2_gfx.dll", 12);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, sdl2_nim_sdl_gfx_primitivesInit000)(void) {
	nimfr_("sdl_gfx_primitives", "sdl_gfx_primitives.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_nim_sdl_gfx_primitivesDatInit000)(void) {
if (!((TM_g5o5WEqRGC1LPWvqxdE8Kg_2 = nimLoadLibrary((NimStringDesc*) &TM_g5o5WEqRGC1LPWvqxdE8Kg_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_g5o5WEqRGC1LPWvqxdE8Kg_5);
	Dl_177012_ = (tyProc_SSqw9cNo8Mf6MmIJEdLFGSQ) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "pixelRGBA");
	Dl_177028_ = (tyProc_rQIZx4wC6REw9aHmOegjvHg) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "hlineRGBA");
	Dl_177045_ = (tyProc_rQIZx4wC6REw9aHmOegjvHg) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "vlineRGBA");
	Dl_177063_ = (tyProc_XKGgUlQDoYOavZdP09bvlvg) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "rectangleRGBA");
	Dl_177083_ = (tyProc_TvDqUpQevFbLv23LGWgPvQ) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "roundedRectangleRGBA");
	Dl_177103_ = (tyProc_XKGgUlQDoYOavZdP09bvlvg) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "boxRGBA");
	Dl_177123_ = (tyProc_TvDqUpQevFbLv23LGWgPvQ) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "roundedBoxRGBA");
	Dl_177143_ = (tyProc_XKGgUlQDoYOavZdP09bvlvg) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "lineRGBA");
	Dl_177162_ = (tyProc_XKGgUlQDoYOavZdP09bvlvg) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "aalineRGBA");
	Dl_177182_ = (tyProc_qAUKUGou1ENFEIQWwibH1w) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "thickLineRGBA");
	Dl_177201_ = (tyProc_rQIZx4wC6REw9aHmOegjvHg) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "circleRGBA");
	Dl_177239_ = (tyProc_rQIZx4wC6REw9aHmOegjvHg) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "aacircleRGBA");
	Dl_177256_ = (tyProc_rQIZx4wC6REw9aHmOegjvHg) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "filledCircleRGBA");
	Dl_177220_ = (tyProc_TvDqUpQevFbLv23LGWgPvQ) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "arcRGBA");
	Dl_177274_ = (tyProc_XKGgUlQDoYOavZdP09bvlvg) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "ellipseRGBA");
	Dl_177293_ = (tyProc_XKGgUlQDoYOavZdP09bvlvg) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "aaellipseRGBA");
	Dl_177312_ = (tyProc_XKGgUlQDoYOavZdP09bvlvg) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "filledEllipseRGBA");
	Dl_177332_ = (tyProc_TvDqUpQevFbLv23LGWgPvQ) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "pieRGBA");
	Dl_177353_ = (tyProc_TvDqUpQevFbLv23LGWgPvQ) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "filledPieRGBA");
	Dl_177375_ = (tyProc_qPqBS49ckVYghHaRhDe9bhzA) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "trigonRGBA");
	Dl_177398_ = (tyProc_qPqBS49ckVYghHaRhDe9bhzA) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "aatrigonRGBA");
	Dl_177421_ = (tyProc_qPqBS49ckVYghHaRhDe9bhzA) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "filledTrigonRGBA");
	Dl_177443_ = (tyProc_sCoe4tIqEGTlfV3L9coWeoQ) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "polygonRGBA");
	Dl_177464_ = (tyProc_sCoe4tIqEGTlfV3L9coWeoQ) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "aapolygonRGBA");
	Dl_177485_ = (tyProc_sCoe4tIqEGTlfV3L9coWeoQ) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "filledPolygonRGBA");
	Dl_177497_ = (tyProc_iWZxubK6MtZbJP55ce9c9cZQ) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "texturedPolygon");
	Dl_177518_ = (tyProc_bG9aqvmV8xt5SjWK9cQ9aZM5g) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "bezierRGBA");
	Dl_177531_ = (tyProc_rpU67nzC5WaSfXPDEajeiA) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "gfxPrimitivesSetFont");
	Dl_177546_ = (tyProc_ElHqXU4YrZEvKm7wPSDkYA) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "characterRGBA");
	Dl_177563_ = (tyProc_qtym4k1a9bIJYHCEaSHkiyg) nimGetProcAddr(TM_g5o5WEqRGC1LPWvqxdE8Kg_2, "stringRGBA");
}

