/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\Users\Alterna\Documents\nim-0.18.0\lib -o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\sdl2_nim_sdl_mixer.o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\sdl2_nim_sdl_mixer.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA;
typedef struct tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef union tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ;
typedef struct tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ;
typedef struct tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA;
typedef struct tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ;
typedef struct tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg;
typedef struct tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q;
typedef struct tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(int, tyProc_4hSZquf3VZZvlELaYshEWg) (int channel);
typedef N_CDECL_PTR(void, tyProc_br1oh11YVvfM9avejTxxNpQ) (tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA* chunk);
typedef N_CDECL_PTR(tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA*, tyProc_aBWCOlwWWonQvhPQizx8Ug) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, int freesrc);
struct tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA {
int allocated;
NU8* abuf;
NU32 alen;
NU8 volume;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(int, tyProc_yyBtDTXzQO2Lna7JemGx2g) (int channel, tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA* chunk, int loops, int ticks);
typedef N_CDECL_PTR(void, tyProc_NuisSWKwsQg36a0Egqo6Qw) (int channel);
typedef N_CDECL_PTR(int, tyProc_MGiOj2b5S2DqV5jgE4sbMw) (tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA* chunk, int volume);
typedef N_CDECL_PTR(int, tyProc_7VGp0OOrDVpzpiikBAb50A) (int channel, NU8 distance);
typedef N_CDECL_PTR(int, tyProc_IQYjW9c4S3CibO23lDxXOxw) (int channel, NU8 left, NU8 right);
typedef N_CDECL_PTR(int, tyProc_7p9b9aTX47z9coV9cdAsiN46aQ) (int channel, NI16 angle, NU8 distance);
typedef N_CDECL_PTR(int, tyProc_6DzmQdLg31OmeFUXpotB2g) (int channel, int volume);
typedef N_CDECL_PTR(void, tyProc_32w2ZypAyMWuajvi2Jt79cg) (void* music);
typedef N_CDECL_PTR(void*, tyProc_YDKrw1adv61oVQkQhbYyaA) (NCSTRING file);
typedef N_CDECL_PTR(void*, tyProc_TH669aE9aoWAsrXM41jGg5rw) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, int freesrc);
typedef N_CDECL_PTR(int, tyProc_AbsnR49cK1X9a2Wblez5VQWQ) (void* music, int loops);
typedef N_CDECL_PTR(int, tyProc_cez8YhJI0vaCUcjGg6z4zA) (void);
typedef N_CDECL_PTR(void, tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(int, tyProc_zHmgYCIVwMsNhQMzkHVoMQ) (double position);
typedef N_CDECL_PTR(void, tyProc_DB9cnq6SiUb8XjfAfm1BAtA) (tyProc_ln4kdL5W9bbX4a1xl8nnVXQ music_finished);
typedef N_CDECL_PTR(int, tyProc_5e9a7cuXSscTqirykAS9c4GA) (int* frequency, NU16* format, int* channels);
typedef N_CDECL_PTR(int, tyProc_QfSTmsZTaEEiWuexopQsmQ) (int frequency, NU16 format, int channels, int chunksize);
typedef N_CDECL_PTR(NI64, tyProc_p9adtE9afP6ObPoIZKMFxiAA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context);
typedef N_CDECL_PTR(NI64, tyProc_tpgoL9bwK9bkzBn2qq83QKag) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context, NI64 offset, int whence);
typedef N_CDECL_PTR(size_t, tyProc_vPnfrHDX45Ib7P40WFtTvg) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context, void* p, size_t size, size_t maxnum);
typedef N_CDECL_PTR(int, tyProc_pcLKO4pFPDvuTZj9c0HX5oA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context);
struct tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ {
void* fileNameRef;
void* inputStreamRef;
void* readableByteChannelRef;
void* readMethod;
void* assetFileDescriptorRef;
long position;
long size;
long offset;
int fd;
};
struct tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ {
void* data;
size_t size;
size_t left;
};
struct tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA {
NIM_BOOL append;
void* h;
tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ buffer;
};
struct tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg {
NIM_BOOL autoclose;
FILE* fp;
};
struct tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q {
NU8* base;
NU8* here;
NU8* stop;
};
struct tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA {
void* data1;
void* data2;
};
union tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ {
tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ androidio;
tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA windowsio;
tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg stdio;
tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q mem;
tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA unknown;
};
struct tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA {
tyProc_p9adtE9afP6ObPoIZKMFxiAA size;
tyProc_tpgoL9bwK9bkzBn2qq83QKag seek;
tyProc_vPnfrHDX45Ib7P40WFtTvg read;
tyProc_vPnfrHDX45Ib7P40WFtTvg write;
tyProc_pcLKO4pFPDvuTZj9c0HX5oA close;
NU32 kind;
tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ mem;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static void* TM_W11iaJ8UI2yznGBy183z7w_2;
tyProc_4hSZquf3VZZvlELaYshEWg Dl_159929_;
tyProc_4hSZquf3VZZvlELaYshEWg Dl_159881_;
tyProc_br1oh11YVvfM9avejTxxNpQ Dl_159511_;
tyProc_aBWCOlwWWonQvhPQizx8Ug Dl_159459_;
TNimType NTI_p4ND3OiqZKVy2rXdSQvwGA_;
extern TNimType NTI_nlCscttRCss70IBTyuBqnA_;
extern TNimType NTI_cG1a2XAxsP28AUq2q9aXnNg_;
extern TNimType NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_;
extern TNimType NTI_k3HXouOuhqAKq0dx450lXQ_;
TNimType NTI_fk5c7FchYduFB24e7g9aUsA_;
tyProc_yyBtDTXzQO2Lna7JemGx2g Dl_159829_;
tyProc_4hSZquf3VZZvlELaYshEWg Dl_159915_;
tyProc_NuisSWKwsQg36a0Egqo6Qw Dl_159909_;
tyProc_NuisSWKwsQg36a0Egqo6Qw Dl_159912_;
tyProc_MGiOj2b5S2DqV5jgE4sbMw Dl_159874_;
tyProc_7VGp0OOrDVpzpiikBAb50A Dl_159613_;
tyProc_IQYjW9c4S3CibO23lDxXOxw Dl_159603_;
tyProc_7p9b9aTX47z9coV9cdAsiN46aQ Dl_159608_;
tyProc_6DzmQdLg31OmeFUXpotB2g Dl_159870_;
tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_159514_;
tyProc_YDKrw1adv61oVQkQhbYyaA Dl_159475_;
tyProc_TH669aE9aoWAsrXM41jGg5rw Dl_159478_;
tyProc_AbsnR49cK1X9a2Wblez5VQWQ Dl_159841_;
tyProc_cez8YhJI0vaCUcjGg6z4zA Dl_159924_;
tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_159918_;
tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_159920_;
tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_159922_;
tyProc_cez8YhJI0vaCUcjGg6z4zA Dl_159932_;
tyProc_cez8YhJI0vaCUcjGg6z4zA Dl_159887_;
tyProc_zHmgYCIVwMsNhQMzkHVoMQ Dl_159926_;
tyProc_DB9cnq6SiUb8XjfAfm1BAtA Dl_159553_;
tyProc_4hSZquf3VZZvlELaYshEWg Dl_159026_;
tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_159029_;
tyProc_5e9a7cuXSscTqirykAS9c4GA Dl_159451_;
tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_159958_;
tyProc_QfSTmsZTaEEiWuexopQsmQ Dl_159434_;
tyProc_4hSZquf3VZZvlELaYshEWg Dl_159448_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_W11iaJ8UI2yznGBy183z7w_4, "SDL2_mixer.dll", 14);
STRING_LITERAL(TM_W11iaJ8UI2yznGBy183z7w_5, "SDL2_mixer.dll", 14);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, sdl2_nim_sdl_mixerInit000)(void) {
	nimfr_("sdl_mixer", "sdl_mixer.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_nim_sdl_mixerDatInit000)(void) {
static TNimNode* TM_W11iaJ8UI2yznGBy183z7w_14[4];
static TNimNode TM_W11iaJ8UI2yznGBy183z7w_0[5];
NTI_p4ND3OiqZKVy2rXdSQvwGA_.size = sizeof(tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA);
NTI_p4ND3OiqZKVy2rXdSQvwGA_.kind = 18;
NTI_p4ND3OiqZKVy2rXdSQvwGA_.base = 0;
NTI_p4ND3OiqZKVy2rXdSQvwGA_.flags = 3;
TM_W11iaJ8UI2yznGBy183z7w_14[0] = &TM_W11iaJ8UI2yznGBy183z7w_0[1];
TM_W11iaJ8UI2yznGBy183z7w_0[1].kind = 1;
TM_W11iaJ8UI2yznGBy183z7w_0[1].offset = offsetof(tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA, allocated);
TM_W11iaJ8UI2yznGBy183z7w_0[1].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_W11iaJ8UI2yznGBy183z7w_0[1].name = "allocated";
TM_W11iaJ8UI2yznGBy183z7w_14[1] = &TM_W11iaJ8UI2yznGBy183z7w_0[2];
TM_W11iaJ8UI2yznGBy183z7w_0[2].kind = 1;
TM_W11iaJ8UI2yznGBy183z7w_0[2].offset = offsetof(tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA, abuf);
TM_W11iaJ8UI2yznGBy183z7w_0[2].typ = (&NTI_cG1a2XAxsP28AUq2q9aXnNg_);
TM_W11iaJ8UI2yznGBy183z7w_0[2].name = "abuf";
TM_W11iaJ8UI2yznGBy183z7w_14[2] = &TM_W11iaJ8UI2yznGBy183z7w_0[3];
TM_W11iaJ8UI2yznGBy183z7w_0[3].kind = 1;
TM_W11iaJ8UI2yznGBy183z7w_0[3].offset = offsetof(tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA, alen);
TM_W11iaJ8UI2yznGBy183z7w_0[3].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_W11iaJ8UI2yznGBy183z7w_0[3].name = "alen";
TM_W11iaJ8UI2yznGBy183z7w_14[3] = &TM_W11iaJ8UI2yznGBy183z7w_0[4];
TM_W11iaJ8UI2yznGBy183z7w_0[4].kind = 1;
TM_W11iaJ8UI2yznGBy183z7w_0[4].offset = offsetof(tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA, volume);
TM_W11iaJ8UI2yznGBy183z7w_0[4].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
TM_W11iaJ8UI2yznGBy183z7w_0[4].name = "volume";
TM_W11iaJ8UI2yznGBy183z7w_0[0].len = 4; TM_W11iaJ8UI2yznGBy183z7w_0[0].kind = 2; TM_W11iaJ8UI2yznGBy183z7w_0[0].sons = &TM_W11iaJ8UI2yznGBy183z7w_14[0];
NTI_p4ND3OiqZKVy2rXdSQvwGA_.node = &TM_W11iaJ8UI2yznGBy183z7w_0[0];
NTI_fk5c7FchYduFB24e7g9aUsA_.size = sizeof(tyObject_ChunkObj_p4ND3OiqZKVy2rXdSQvwGA*);
NTI_fk5c7FchYduFB24e7g9aUsA_.kind = 21;
NTI_fk5c7FchYduFB24e7g9aUsA_.base = (&NTI_p4ND3OiqZKVy2rXdSQvwGA_);
NTI_fk5c7FchYduFB24e7g9aUsA_.flags = 3;
if (!((TM_W11iaJ8UI2yznGBy183z7w_2 = nimLoadLibrary((NimStringDesc*) &TM_W11iaJ8UI2yznGBy183z7w_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_W11iaJ8UI2yznGBy183z7w_5);
	Dl_159929_ = (tyProc_4hSZquf3VZZvlELaYshEWg) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_Playing");
	Dl_159881_ = (tyProc_4hSZquf3VZZvlELaYshEWg) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_HaltChannel");
	Dl_159511_ = (tyProc_br1oh11YVvfM9avejTxxNpQ) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_FreeChunk");
	Dl_159459_ = (tyProc_aBWCOlwWWonQvhPQizx8Ug) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_LoadWAV_RW");
	Dl_159829_ = (tyProc_yyBtDTXzQO2Lna7JemGx2g) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_PlayChannelTimed");
	Dl_159915_ = (tyProc_4hSZquf3VZZvlELaYshEWg) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_Paused");
	Dl_159909_ = (tyProc_NuisSWKwsQg36a0Egqo6Qw) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_Pause");
	Dl_159912_ = (tyProc_NuisSWKwsQg36a0Egqo6Qw) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_Resume");
	Dl_159874_ = (tyProc_MGiOj2b5S2DqV5jgE4sbMw) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_VolumeChunk");
	Dl_159613_ = (tyProc_7VGp0OOrDVpzpiikBAb50A) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_SetDistance");
	Dl_159603_ = (tyProc_IQYjW9c4S3CibO23lDxXOxw) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_SetPanning");
	Dl_159608_ = (tyProc_7p9b9aTX47z9coV9cdAsiN46aQ) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_SetPosition");
	Dl_159870_ = (tyProc_6DzmQdLg31OmeFUXpotB2g) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_Volume");
	Dl_159514_ = (tyProc_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_FreeMusic");
	Dl_159475_ = (tyProc_YDKrw1adv61oVQkQhbYyaA) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_LoadMUS");
	Dl_159478_ = (tyProc_TH669aE9aoWAsrXM41jGg5rw) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_LoadMUS_RW");
	Dl_159841_ = (tyProc_AbsnR49cK1X9a2Wblez5VQWQ) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_PlayMusic");
	Dl_159924_ = (tyProc_cez8YhJI0vaCUcjGg6z4zA) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_PausedMusic");
	Dl_159918_ = (tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_PauseMusic");
	Dl_159920_ = (tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_ResumeMusic");
	Dl_159922_ = (tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_RewindMusic");
	Dl_159932_ = (tyProc_cez8YhJI0vaCUcjGg6z4zA) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_PlayingMusic");
	Dl_159887_ = (tyProc_cez8YhJI0vaCUcjGg6z4zA) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_HaltMusic");
	Dl_159926_ = (tyProc_zHmgYCIVwMsNhQMzkHVoMQ) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_SetMusicPosition");
	Dl_159553_ = (tyProc_DB9cnq6SiUb8XjfAfm1BAtA) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_HookMusicFinished");
	Dl_159026_ = (tyProc_4hSZquf3VZZvlELaYshEWg) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_Init");
	Dl_159029_ = (tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_Quit");
	Dl_159451_ = (tyProc_5e9a7cuXSscTqirykAS9c4GA) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_QuerySpec");
	Dl_159958_ = (tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_CloseAudio");
	Dl_159434_ = (tyProc_QfSTmsZTaEEiWuexopQsmQ) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_OpenAudio");
	Dl_159448_ = (tyProc_4hSZquf3VZZvlELaYshEWg) nimGetProcAddr(TM_W11iaJ8UI2yznGBy183z7w_2, "Mix_AllocateChannels");
}

