/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   C:\mingw64\bin\gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\Users\Alterna\Documents\nim-0.18.0\lib -o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\sdl2_nim_sdl_image.o c:\Users\Alterna\gits\nimgame2\nimgame2\nimcache\sdl2_nim_sdl_image.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA;
typedef struct tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A;
typedef union tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ;
typedef struct tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ;
typedef struct tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA;
typedef struct tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ;
typedef struct tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg;
typedef struct tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q;
typedef struct tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA;
typedef struct tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q;
typedef struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ tyObject_Rect_qiXweduDJk1iLE5aHysNdQ;
typedef struct tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg;
typedef struct tyObject_Color_YizDHyEvJtgQk2fn8KdZUA tyObject_Color_YizDHyEvJtgQk2fn8KdZUA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(void**, tyProc_1LIoIPgxf1fnU6YXXXDfCA) (void* renderer, NCSTRING file);
typedef N_CDECL_PTR(void*, tyProc_VQBltFKZwH39aVWDIW09ctKw) (void* renderer, tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, int freesrc);
typedef N_CDECL_PTR(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A*, tyProc_oTI7Gk9b9bgxQuZMQRpglP1w) (NCSTRING file);
typedef N_CDECL_PTR(tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A*, tyProc_ov47cSW7te2Rk6vJnziJZA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* src, int freesrc);
typedef N_CDECL_PTR(void, tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(int, tyProc_4hSZquf3VZZvlELaYshEWg) (int flags);
typedef N_CDECL_PTR(NI64, tyProc_p9adtE9afP6ObPoIZKMFxiAA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context);
typedef N_CDECL_PTR(NI64, tyProc_tpgoL9bwK9bkzBn2qq83QKag) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context, NI64 offset, int whence);
typedef N_CDECL_PTR(size_t, tyProc_vPnfrHDX45Ib7P40WFtTvg) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context, void* p, size_t size, size_t maxnum);
typedef N_CDECL_PTR(int, tyProc_pcLKO4pFPDvuTZj9c0HX5oA) (tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA* context);
struct tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ {
void* fileNameRef;
void* inputStreamRef;
void* readableByteChannelRef;
void* readMethod;
void* assetFileDescriptorRef;
long position;
long size;
long offset;
int fd;
};
struct tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ {
void* data;
size_t size;
size_t left;
};
struct tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA {
NIM_BOOL append;
void* h;
tyObject_RWopsWindowsioBuffer_szd2VVBRm6mbSNMdL8LkKQ buffer;
};
struct tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg {
NIM_BOOL autoclose;
FILE* fp;
};
struct tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q {
NU8* base;
NU8* here;
NU8* stop;
};
struct tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA {
void* data1;
void* data2;
};
union tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ {
tyObject_RWopsAndroidio_9bmucCZftzIUfLB0AYNuuMQ androidio;
tyObject_RWopsWindowsio_MbwOJIFSPqDwSbRWn1ygSA windowsio;
tyObject_RWopsStdio_R4gEF6TLygfCBTS9cRm1fYg stdio;
tyObject_RWopsMemio_p9aMmhyg8NTeSTHMEwEBG7Q mem;
tyObject_RWopsUnknownio_xAX1nygcCVgIHhbOn0eDSA unknown;
};
struct tyObject_RWops_eDjAEsZ0dMPUbPNzsgqbqA {
tyProc_p9adtE9afP6ObPoIZKMFxiAA size;
tyProc_tpgoL9bwK9bkzBn2qq83QKag seek;
tyProc_vPnfrHDX45Ib7P40WFtTvg read;
tyProc_vPnfrHDX45Ib7P40WFtTvg write;
tyProc_pcLKO4pFPDvuTZj9c0HX5oA close;
NU32 kind;
tyObject_RWopsKind_B9bGTbwHI302xDKkFwe5RZQ mem;
};
struct tyObject_Rect_qiXweduDJk1iLE5aHysNdQ {
int x;
int y;
int w;
int h;
};
struct tyObject_SurfaceObj_p38hmQYM8dSHCxdlRSTN3A {
NU32 flags;
tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q* format;
int w;
int h;
int pitch;
void* pixels;
void* userdata;
int locked;
void* lock_data;
tyObject_Rect_qiXweduDJk1iLE5aHysNdQ clip_rect;
void* map;
int refcount;
};
typedef NU8 tyArray_bN9bddWn8oiNSHn2MqEJSZQ[2];
struct tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q {
NU32 format;
tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg* palette;
NU8 BitsPerPixel;
NU8 BytesPerPixel;
tyArray_bN9bddWn8oiNSHn2MqEJSZQ padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int refcount;
tyObject_PixelFormat_wU9cDPZQN8lu0JgltTtFK0Q* next;
};
struct tyObject_Palette_uR3LHDHYgbK2Xt6nAh5vfg {
int ncolors;
tyObject_Color_YizDHyEvJtgQk2fn8KdZUA* colors;
NU32 version;
int refcount;
};
struct tyObject_Color_YizDHyEvJtgQk2fn8KdZUA {
NU8 r;
NU8 g;
NU8 b;
NU8 a;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static void* TM_KBqytsBOSVgv4K9bnF5oGYQ_2;
tyProc_1LIoIPgxf1fnU6YXXXDfCA Dl_157060_;
tyProc_VQBltFKZwH39aVWDIW09ctKw Dl_157065_;
tyProc_oTI7Gk9b9bgxQuZMQRpglP1w Dl_157041_;
tyProc_ov47cSW7te2Rk6vJnziJZA Dl_157044_;
tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_157026_;
tyProc_4hSZquf3VZZvlELaYshEWg Dl_157023_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_KBqytsBOSVgv4K9bnF5oGYQ_4, "SDL2_image.dll", 14);
STRING_LITERAL(TM_KBqytsBOSVgv4K9bnF5oGYQ_5, "SDL2_image.dll", 14);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, sdl2_nim_sdl_imageInit000)(void) {
	nimfr_("sdl_image", "sdl_image.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_nim_sdl_imageDatInit000)(void) {
if (!((TM_KBqytsBOSVgv4K9bnF5oGYQ_2 = nimLoadLibrary((NimStringDesc*) &TM_KBqytsBOSVgv4K9bnF5oGYQ_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_KBqytsBOSVgv4K9bnF5oGYQ_5);
	Dl_157060_ = (tyProc_1LIoIPgxf1fnU6YXXXDfCA) nimGetProcAddr(TM_KBqytsBOSVgv4K9bnF5oGYQ_2, "IMG_LoadTexture");
	Dl_157065_ = (tyProc_VQBltFKZwH39aVWDIW09ctKw) nimGetProcAddr(TM_KBqytsBOSVgv4K9bnF5oGYQ_2, "IMG_LoadTexture_RW");
	Dl_157041_ = (tyProc_oTI7Gk9b9bgxQuZMQRpglP1w) nimGetProcAddr(TM_KBqytsBOSVgv4K9bnF5oGYQ_2, "IMG_Load");
	Dl_157044_ = (tyProc_ov47cSW7te2Rk6vJnziJZA) nimGetProcAddr(TM_KBqytsBOSVgv4K9bnF5oGYQ_2, "IMG_Load_RW");
	Dl_157026_ = (tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_KBqytsBOSVgv4K9bnF5oGYQ_2, "IMG_Quit");
	Dl_157023_ = (tyProc_4hSZquf3VZZvlELaYshEWg) nimGetProcAddr(TM_KBqytsBOSVgv4K9bnF5oGYQ_2, "IMG_Init");
}

